(()=>{
'use strict';

const TESTNET_INFO='https://api.hyperliquid-testnet.xyz/info';
const SESSION_KEY='rwa_wallet_link_v1';
const CLAIM_AMOUNT=1000;
let pollTimer=null,modalReady=false,busy=false;
const byId=id=>document.getElementById(id);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const short=a=>a?`${a.slice(0,6)}…${a.slice(-4)}`:'—';
const money=n=>`$${Number(n||0).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const isTestnet=()=>byId('testnetToggle')?.checked!==false;
const provider=()=>window.RWAProviderRuntime?.provider?.()||window.RWAProvider||window.ethereum||null;

function sessionWallet(){try{const row=JSON.parse(localStorage.getItem(SESSION_KEY)||'null'),w=String(row?.wallet||'').toLowerCase();return /^0x[a-f0-9]{40}$/.test(w)?w:''}catch{return''}}
async function currentWallet(){const stored=sessionWallet();if(stored)return stored;try{const p=provider(),a=await p?.request?.({method:'eth_accounts'}),w=String(a?.[0]||'').toLowerCase();return /^0x[a-f0-9]{40}$/.test(w)?w:''}catch{return''}}
async function execution(){for(let i=0;i<80;i++){if(window.RWAExecutionAPI?.version==='2.0.0')return window.RWAExecutionAPI;await sleep(100)}throw Error('RWA execution engine is not ready')}
async function testInfo(payload){const r=await fetch(TESTNET_INFO,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),cache:'no-store'}),text=await r.text();let body=text;try{body=text?JSON.parse(text):null}catch{}if(!r.ok)throw Error(String(typeof body==='string'?body:(body?.error||body?.message||`HTTP ${r.status}`)));if(body?.error)throw Error(String(body.error));if(body?.status&&String(body.status).toLowerCase()==='err')throw Error(String(body.message||'Request rejected'));return body}
async function equity(user,testnet=isTestnet()){if(!user)return 0;if(testnet){const s=await testInfo({type:'clearinghouseState',user});return Number(s?.marginSummary?.accountValue||0)||0}const api=await execution(),s=await api.account.state(false);return Number(s?.marginSummary?.accountValue||0)||0}

function cleanPrimaryBrand(){
  const subtitle=document.querySelector('.brand small');if(subtitle)subtitle.textContent='RWA execution network';
  const fund=byId('fundBtn');if(fund)fund.textContent=isTestnet()?'Get test balance':'Deposit USDC';
  const micro=document.querySelector('.microcopy');if(micro)micro.textContent='If TP/SL is provided, RWA submits protection together with the entry.';
  const meta=document.querySelector('meta[name="description"]');if(meta)meta.setAttribute('content','Secure non-custodial trading interface for RWA Markets.');
}
function ensureModal(){
  if(modalReady)return;modalReady=true;
  const root=document.createElement('div');root.id='fundModal';root.className='fund-modal';root.hidden=true;root.innerHTML=`<div class="fund-modal-backdrop" data-fund-close></div><section class="fund-modal-panel" role="dialog" aria-modal="true" aria-labelledby="fundModalTitle"><header class="fund-modal-head"><div><small id="fundEnvLabel">RWA TRADE · TESTNET</small><h2 id="fundModalTitle">Get test balance</h2></div><button class="fund-icon-btn" type="button" data-fund-close aria-label="Close funding panel">×</button></header><div class="fund-status-row"><div><small>Wallet</small><b id="fundWallet">—</b></div><div><small id="fundBalanceLabel">TESTNET balance</small><b id="fundEquity">Checking…</b></div><div><small>Status</small><b id="fundStatus">Checking</b></div></div><div class="fund-native-card"><div class="fund-native-mark">R</div><div><small id="fundCardEyebrow">RWA TEST BALANCE</small><h3 id="fundNativeTitle">Checking your balance…</h3><p id="fundNativeText">RWA checks your account while keeping you inside this application.</p></div></div><div id="fundMainnetInput" class="fund-mainnet-input" hidden><label><span>Deposit amount · native Arbitrum USDC</span><input id="fundAmount" type="number" min="5" step="1" value="25" inputmode="decimal"></label><small>Minimum 5 USDC. Your wallet needs native USDC and a small amount of ETH on Arbitrum for gas.</small></div><div class="fund-note" id="fundNote"><b>TESTNET only.</b> Test balance has no real monetary value. Eligibility is controlled by the TESTNET network.</div><footer class="fund-modal-actions"><span id="fundHint">Checking balance…</span><div><button id="fundClaimBtn" class="button primary" type="button" disabled>Get 1,000 test USDC</button><button id="fundCheckBtn" class="button ghost" type="button">Check balance</button><button id="fundContinueBtn" class="button secondary" type="button" disabled>Continue trading</button></div></footer></section>`;document.body.appendChild(root);
  const st=document.createElement('style');st.textContent='.fund-mainnet-input{padding:12px;border:1px solid #232c38;border-radius:10px;background:#0b1118;margin:10px 0}.fund-mainnet-input label{display:grid;gap:5px}.fund-mainnet-input label span,.fund-mainnet-input>small{font-size:9px;color:#8895a4}.fund-mainnet-input input{width:100%;box-sizing:border-box;margin-top:4px;padding:11px;border:1px solid #2a3542;border-radius:8px;background:#080d13;color:#f2f5f8;font:800 12px system-ui}.fund-mainnet-input>small{display:block;margin-top:7px;line-height:1.45}';document.head.appendChild(st);
  root.querySelectorAll('[data-fund-close]').forEach(x=>x.addEventListener('click',closeFunding));byId('fundClaimBtn').addEventListener('click',primaryAction);byId('fundCheckBtn').addEventListener('click',()=>refreshFunding(true));byId('fundContinueBtn').addEventListener('click',closeFunding);
}
function setBusy(v,label){busy=!!v;const b=byId('fundClaimBtn');if(!b)return;if(v){b.dataset.base=b.textContent;b.textContent=label||'Working…';b.disabled=true}else b.textContent=b.dataset.base||(isTestnet()?'Get 1,000 test USDC':'Deposit USDC')}
function configureMode(){ensureModal();const t=isTestnet();byId('fundEnvLabel').textContent=t?'RWA TRADE · TESTNET':'RWA TRADE · MAINNET';byId('fundModalTitle').textContent=t?'Get test balance':'Deposit collateral';byId('fundBalanceLabel').textContent=t?'TESTNET balance':'MAINNET equity';byId('fundCardEyebrow').textContent=t?'RWA TEST BALANCE':'RWA MAINNET FUNDING';byId('fundMainnetInput').hidden=t;byId('fundNote').innerHTML=t?'<b>TESTNET only.</b> Test balance has no real monetary value. Eligibility is controlled by the TESTNET network.':'<b>Real funds.</b> RWA sends native Arbitrum USDC from your connected master wallet to the configured production bridge only after the machine launch gate is READY and you confirm in your wallet.';byId('fundClaimBtn').textContent=t?'Get 1,000 test USDC':'Deposit USDC';byId('fundClaimBtn').dataset.base=byId('fundClaimBtn').textContent;cleanPrimaryBrand()}
function renderFunded(v){byId('fundStatus').textContent='READY';byId('fundNativeTitle').textContent=isTestnet()?'Test balance detected':'Mainnet collateral detected';byId('fundNativeText').textContent=`Your ${isTestnet()?'TESTNET':'MAINNET'} account has ${money(v)} equity.`;byId('fundHint').textContent='Balance detected. You can continue trading.';byId('fundClaimBtn').disabled=isTestnet();byId('fundContinueBtn').disabled=false;window.dispatchEvent(new CustomEvent('rwa:funding-changed',{detail:{equity:v,testnet:isTestnet()}}))}
function renderZero(){const t=isTestnet();byId('fundStatus').textContent=t?'TEST BALANCE REQUIRED':'COLLATERAL REQUIRED';byId('fundNativeTitle').textContent=t?'Test balance is ready to request':'Deposit native Arbitrum USDC';byId('fundNativeText').textContent=t?'Request the standard TESTNET allocation directly from RWA.':'Deposit real USDC only after the production gate has unlocked MAINNET for this verified wallet.';byId('fundHint').textContent=t?'Request TESTNET allocation, then RWA verifies it automatically.':'Enter at least 5 USDC. RWA verifies the production gate again before any wallet transaction.';byId('fundClaimBtn').disabled=busy;byId('fundContinueBtn').disabled=true}
async function refreshFunding(manual=false){configureMode();try{const user=await currentWallet();byId('fundWallet').textContent=short(user);if(!user){byId('fundEquity').textContent='—';byId('fundStatus').textContent='CONNECT WALLET';byId('fundNativeTitle').textContent='Connect your wallet first';byId('fundNativeText').textContent='RWA needs the connected master wallet before checking collateral.';byId('fundClaimBtn').disabled=true;byId('fundContinueBtn').disabled=true;return 0}if(!isTestnet()){const gate=await window.RWATradeLaunchGate?.refresh?.();if(!gate?.ready){byId('fundEquity').textContent='—';byId('fundStatus').textContent='MAINNET LOCKED';byId('fundNativeTitle').textContent='Production gate is not ready';byId('fundNativeText').textContent=gate?.reason||'MAINNET remains locked by machine policy.';byId('fundHint').textContent='No real-fund transaction can be submitted while the machine gate is locked.';byId('fundClaimBtn').disabled=true;byId('fundContinueBtn').disabled=true;return 0}}
    const v=await equity(user,isTestnet());byId('fundEquity').textContent=money(v);if(v>0)renderFunded(v);else renderZero();if(manual&&v<=0)byId('fundHint').textContent=isTestnet()?'Balance is still $0.00. Request TESTNET balance above.':'Mainnet equity is still $0.00. Deposit native Arbitrum USDC above.';return v
  }catch(e){byId('fundStatus').textContent='CHECK FAILED';byId('fundNativeTitle').textContent='Balance check unavailable';byId('fundNativeText').textContent='No funding transaction was submitted.';if(manual)byId('fundHint').textContent=String(e?.message||e);return 0}}
async function claimTestnet(user){setBusy(true,'Requesting…');try{byId('fundStatus').textContent='REQUESTING';await testInfo({type:'claimDrip',user:String(user).toLowerCase()});byId('fundStatus').textContent='VERIFYING';for(let i=0;i<20;i++){await sleep(i?1500:1000);if(await refreshFunding(false)>0)return}byId('fundStatus').textContent='PENDING';byId('fundHint').textContent='Request sent. Check again in a moment.'}catch(e){byId('fundStatus').textContent='NOT AVAILABLE';byId('fundHint').textContent=String(e?.message||e).slice(0,180)}finally{setBusy(false);if(Number(String(byId('fundEquity')?.textContent||'').replace(/[^0-9.-]/g,''))<=0)byId('fundClaimBtn').disabled=false}}
async function depositMainnet(){const amount=Number(byId('fundAmount')?.value||0);if(!(amount>=5))throw Error('Minimum mainnet deposit is 5 USDC');if(!confirm(`Deposit ${amount} USDC from your master wallet on Arbitrum?`))return;const phrase=prompt('For security, type exactly: DEPOSIT');if(phrase==null)return;setBusy(true,'Confirm in wallet…');try{const api=await execution();byId('fundStatus').textContent='WALLET CONFIRMATION';const out=await api.funds.depositMainnet({amount,confirmText:phrase});byId('fundStatus').textContent='DEPOSIT SUBMITTED';byId('fundHint').textContent=`Transaction ${short(out?.hash||'')} submitted. Waiting for venue credit…`;for(let i=0;i<30;i++){await sleep(i?2000:1500);if(await refreshFunding(false)>0)return}byId('fundHint').textContent='Deposit transaction was submitted. Venue credit can take a short time; use Check balance.'}finally{setBusy(false)}}
async function primaryAction(){if(busy)return;const user=await currentWallet();if(!user){byId('fundHint').textContent='Connect your wallet first.';return}try{if(isTestnet())await claimTestnet(user);else await depositMainnet()}catch(e){byId('fundStatus').textContent='BLOCKED';byId('fundHint').textContent=String(e?.message||e).slice(0,200);setBusy(false)}}
async function openFunding(){ensureModal();configureMode();const m=byId('fundModal');m.hidden=false;document.documentElement.classList.add('funding-open');clearInterval(pollTimer);pollTimer=setInterval(()=>refreshFunding(false),5000);await refreshFunding(false)}
function closeFunding(){const m=byId('fundModal');if(!m)return;m.hidden=true;document.documentElement.classList.remove('funding-open');clearInterval(pollTimer);pollTimer=null;window.dispatchEvent(new CustomEvent('rwa:funding-changed'));byId('refreshBtn')?.click()}
document.addEventListener('click',e=>{const b=e.target?.closest?.('#fundBtn');if(!b)return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();openFunding().catch(err=>{ensureModal();byId('fundModal').hidden=false;byId('fundStatus').textContent='ERROR';byId('fundHint').textContent=String(err?.message||err)})},true);
document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!byId('fundModal')?.hidden)closeFunding()});byId('testnetToggle')?.addEventListener('change',()=>{cleanPrimaryBrand();if(!byId('fundModal')?.hidden)refreshFunding(false)});window.addEventListener('rwa:trade-launch-gate',cleanPrimaryBrand);
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',cleanPrimaryBrand,{once:true});else cleanPrimaryBrand();setTimeout(cleanPrimaryBrand,1200);
window.RWAFundingPanel={version:'2.0.0',open:openFunding,close:closeFunding,refresh:refreshFunding,claim:primaryAction};
})();
