const KEY='rwa_trade_margin_mode_v1';
const $=id=>document.getElementById(id);
const mode=()=>localStorage.getItem(KEY)==='cross'?'cross':'isolated';
function save(v){localStorage.setItem(KEY,v==='cross'?'cross':'isolated');render();window.dispatchEvent(new CustomEvent('rwa:margin-mode',{detail:{mode:mode()}}))}
function render(){const v=mode();document.querySelectorAll('[data-margin-mode]').forEach(b=>b.classList.toggle('active',b.dataset.marginMode===v));const s=$('marginModeStatus');if(s)s.textContent=v==='isolated'?'ISOLATED · position-contained':'CROSS · shared collateral'}
function inject(){if($('marginModeControl'))return true;const lev=document.querySelector('.leverage-wrap');if(!lev)return false;const box=document.createElement('div');box.id='marginModeControl';box.className='margin-mode-control';box.innerHTML='<div class="margin-mode-head"><span>Margin mode</span><small id="marginModeStatus">ISOLATED · position-contained</small></div><div class="trade-segment margin"><button type="button" data-margin-mode="isolated">ISOLATED</button><button type="button" data-margin-mode="cross">CROSS</button></div><p class="microcopy margin-copy">Isolated is the default. Margin mode is applied by the same delegated execution API before a new risk-increasing order.</p>';lev.insertAdjacentElement('afterend',box);if(!document.getElementById('margin-runtime-style')){const st=document.createElement('style');st.id='margin-runtime-style';st.textContent='.margin-mode-control{margin:10px 0}.margin-mode-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:6px}.margin-mode-head span{font-size:11px;font-weight:800}.margin-mode-head small{font-size:9px;color:#7f8a99}.trade-segment.margin{grid-template-columns:1fr 1fr}.trade-segment.margin button.active{border-color:#4770ff;background:#14214a;color:#dce5ff}.margin-copy{margin:6px 0 0}@media(max-width:680px){.margin-mode-head{align-items:flex-start;flex-direction:column;gap:3px}}';document.head.appendChild(st)}box.querySelectorAll('[data-margin-mode]').forEach(b=>b.addEventListener('click',()=>save(b.dataset.marginMode)));render();return true}
function patch(){const api=window.RWAExecutionAPI;if(!api?.orders||api.__rwaMarginModePatched)return false;for(const name of ['limit','market','bracket']){const original=api.orders[name];if(typeof original!=='function')continue;api.orders[name]=async function(args={}){const a={...args};if(!a.reduceOnly&&Number(a.leverage)>0){await api.risk.setLeverage({coin:a.coin,leverage:Number(a.leverage),isCross:mode()==='cross',testnet:!!a.testnet,preferAgent:a.preferAgent!==false});a.leverage=null}return original.call(api.orders,a)};api.orders[name].__rwaMarginMode='single-owner-wrapper-v1'}Object.defineProperty(api,'marginMode',{configurable:true,enumerable:true,get:()=>mode()});api.__rwaMarginModePatched=true;window.dispatchEvent(new CustomEvent('rwa:margin-runtime-ready',{detail:{mode:mode()}}));return true}
function boot(){inject();patch();const mo=new MutationObserver(()=>{inject();patch()});mo.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('rwa:execution-api-ready',patch)}
window.RWAMarginRuntime={version:'1.0.0',mode,set:save,patch};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
