const $=id=>document.getElementById(id);
const num=v=>Number.isFinite(Number(v))?Number(v):0;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const testnet=()=>$('testnetToggle')?.checked!==false;
const wallet=()=>{try{const w=String(window.RWAExecutionAPI?.auth?.master?.()||JSON.parse(localStorage.getItem('rwa_wallet_link_v1')||'{}')?.wallet||'').toLowerCase();return /^0x[a-f0-9]{40}$/.test(w)?w:''}catch{return''}};
const riskKey=()=>`rwa_risk_v2:${wallet()||'anon'}`;
function toast(m,t=''){const e=$('toast');if(!e)return;e.textContent=String(m);e.className=`toast show ${t}`;clearTimeout(toast.t);toast.t=setTimeout(()=>e.className='toast',5200)}
function fire(e){if(!e)return;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))}
function setKill(value=true){let r={};try{r=JSON.parse(localStorage.getItem(riskKey())||'{}')||{}}catch{}r.kill=!!value;localStorage.setItem(riskKey(),JSON.stringify(r));return r}
function positions(raw){return(raw?.assetPositions||[]).map(x=>x?.position||x).filter(p=>num(p?.szi)!==0)}
async function emergencyExit(btn){const api=window.RWAExecutionAPI;if(!api)return toast('Execution API unavailable','error');const env=testnet()?'TESTNET':'MAINNET';if(!confirm(`EMERGENCY EXIT ${env}: block new entries, cancel every open order, then submit one reduce-only market close for each open position?`))return;const phrase=prompt('Type EXIT to confirm emergency risk reduction');if(phrase!=='EXIT')return toast('Emergency exit cancelled','error');const old=btn.textContent;btn.disabled=true;btn.textContent='Exiting…';setKill(true);window.dispatchEvent(new CustomEvent('rwa:risk-changed',{detail:{kill:true,source:'emergency-exit'}}));let cancels=0,closes=0,errors=[];try{try{const out=await api.orders.cancelAll({testnet:testnet(),preferAgent:true});cancels=Array.isArray(out)?out.length:0}catch(e){errors.push(`cancel: ${e.message||e}`)}let raw;try{raw=await api.account.state(testnet())}catch(e){errors.push(`state: ${e.message||e}`)}for(const p of positions(raw)){try{await api.orders.market({coin:String(p.coin||'').toUpperCase(),side:num(p.szi)>0?'SELL':'BUY',size:Math.abs(num(p.szi)),reduceOnly:true,leverage:1,testnet:testnet(),preferAgent:true});closes++}catch(e){errors.push(`${p.coin}: ${e.message||e}`)}}await sleep(1200);let leftP=[],leftO=[];try{leftP=positions(await api.account.state(testnet()))}catch{}try{leftO=await api.orders.open(testnet())||[]}catch{}$('refreshBtn')?.click();const residual=`${leftP.length} position(s), ${leftO.length} order(s) remain`;if(!leftP.length&&!leftO.length)toast(`Emergency exit complete · ${cancels} cancelled · ${closes} close(s) · account flat`,'success');else toast(`Emergency exit submitted · ${residual}${errors.length?' · review errors':''}`,'error');if(errors.length)console.warn('RWA emergency exit',errors)}finally{btn.disabled=false;btn.textContent=old}}
function installEmergency(){if($('emergencyExitBtn'))return;const row=document.querySelector('.account .actions-row');if(!row)return;const b=document.createElement('button');b.id='emergencyExitBtn';b.type='button';b.className='button danger-outline';b.textContent='Emergency exit';b.title='Kill switch + cancel all + reduce-only close all positions';b.onclick=()=>emergencyExit(b);row.appendChild(b)}
function installShare(){if($('sharePositionBtn'))return;const actions=$('addProtectionBtn')?.closest('.manage-actions');if(!actions)return;const b=document.createElement('button');b.id='sharePositionBtn';b.type='button';b.className='button ghost';b.textContent='Copy position';b.onclick=async()=>{const coin=$('manageCoin')?.textContent||'Position',side=$('manageSide')?.textContent||'',size=$('manageSize')?.textContent||'',entry=$('manageEntry')?.textContent||'',pnl=$('managePnl')?.textContent||'';const text=`RWA Trade · ${coin}\n${side} · size ${size}\nEntry ${entry} · P&L ${pnl}`;try{await navigator.clipboard.writeText(text);toast('Position summary copied','success')}catch{toast('Clipboard unavailable','error')}};actions.appendChild(b)}
function installFunds(){if($('mainnetDepositBtn'))return;const row=document.querySelector('.account .actions-row');if(!row)return;const b=document.createElement('button');b.id='mainnetDepositBtn';b.type='button';b.className='button ghost';b.textContent='Deposit · mainnet only';b.disabled=true;b.onclick=()=>window.RWAFundingPanel?.open?.();row.insertBefore(b,$('withdrawBtn')||row.firstChild);syncFunds()}
function syncWithdraw(){const b=$('withdrawBtn');if(!b)return;const ready=window.RWATradeLaunchGate?.canMainnet?.()===true&&!testnet();if(!ready){b.disabled=true;b.title='Withdrawals stay master-wallet-only and remain disabled until MAINNET is machine-unlocked.';b.textContent='Withdraw · mainnet only'}else{b.disabled=false;b.title='Master-wallet-only withdrawal. A fresh wallet signature and typed confirmation are required.';b.textContent='Withdraw USDC'}}
function syncFunds(){const d=$('mainnetDepositBtn'),ready=window.RWATradeLaunchGate?.canMainnet?.()===true&&!testnet();if(d){d.disabled=!ready;d.textContent=ready?'Deposit USDC':'Deposit · mainnet only';d.title=ready?'Deposit native Arbitrum USDC using the connected master wallet.':'Available only after the production machine gate unlocks MAINNET.'}syncWithdraw()}
function deepLink(){const q=new URLSearchParams(location.search),coin=String(q.get('coin')||q.get('market')||'').toUpperCase().replace(/[-_/ ]?(USDT|USDC|PERP)$/,'');if(coin){let tries=0;const t=setInterval(()=>{const e=$('coin');if(e&&[...e.options].some(o=>String(o.value).toUpperCase()===coin)){clearInterval(t);e.value=coin;fire(e)}else if(++tries>80)clearInterval(t)},125)}const side=String(q.get('side')||'').toUpperCase();if(side==='BUY'||side==='LONG')setTimeout(()=>document.querySelector('[data-side-btn="BUY"]')?.click(),200);if(side==='SELL'||side==='SHORT')setTimeout(()=>document.querySelector('[data-side-btn="SELL"]')?.click(),200);const type=String(q.get('type')||'').toUpperCase();if(type==='MARKET'||type==='LIMIT')setTimeout(()=>document.querySelector(`[data-type-btn="${type}"]`)?.click(),220);for(const [param,id,min,max] of [['usd','orderUsd',1,1000],['leverage','leverage',1,5],['tp','tp',0,Infinity],['sl','sl',0,Infinity],['price','limitPrice',0,Infinity]]){const v=num(q.get(param));if(v>=min&&v<=max)setTimeout(()=>{const e=$(id);if(e){e.value=String(v);fire(e)}},250)}}
function syncGate(){const b=$('networkBadge'),ready=window.RWATradeLaunchGate?.canMainnet?.()===true;if(b&&ready&&testnet())b.title='Production launch gate is READY; switch remains explicitly opt-in.';syncFunds()}
function boot(){installEmergency();installShare();installFunds();syncFunds();deepLink();window.addEventListener('rwa:trade-launch-gate',syncGate);window.addEventListener('rwa:risk-changed',()=>window.RWATradePro?.risk?.());$('testnetToggle')?.addEventListener('change',syncFunds);const mo=new MutationObserver(()=>{installEmergency();installShare();installFunds()});mo.observe(document.body,{childList:true,subtree:true});window.RWATradeReleaseRuntime={version:'1.1.0',emergencyExit:()=>emergencyExit($('emergencyExitBtn')),setKill,deepLink,syncFunds}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
