import { CONFIG } from './config.js';

const $=id=>document.getElementById(id);
const FAV='rwa_trade_favorites_v1',INT='rwa_trade_interval_v1';
const S={coin:'BTC',interval:localStorage.getItem(INT)||'15m',candles:[],info:null,sdk:null,lastPx:0,lastPxAt:0,position:null,modal:null,chartSeq:0,metricSeq:0};
const IMS={'1m':60000,'5m':300000,'15m':900000,'1h':3600000,'4h':14400000,'1d':86400000};
const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const money=(v,d=2)=>Number.isFinite(Number(v))?`$${Number(v).toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:Math.abs(Number(v))<1?6:d})}`:'—';
const compact=v=>Number.isFinite(Number(v))?new Intl.NumberFormat('en-US',{notation:'compact',maximumFractionDigits:2}).format(Number(v)):'—';
const pct=(v,d=2)=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}${Number(v).toFixed(d)}%`:'—';
const testnet=()=>$('testnetToggle')?.checked!==false;
function wallet(){try{const w=String(window.RWAExecutionAPI?.auth?.master?.()||'').toLowerCase();if(/^0x[a-f0-9]{40}$/.test(w))return w}catch{}try{const w=String(JSON.parse(localStorage.getItem('rwa_wallet_link_v1')||'{}')?.wallet||'').toLowerCase();return /^0x[a-f0-9]{40}$/.test(w)?w:''}catch{return''}}
function toast(m,t=''){const e=$('toast');if(!e)return;e.textContent=String(m);e.className=`toast show ${t}`;clearTimeout(toast.t);toast.t=setTimeout(()=>e.className='toast',4500)}
function fire(e){if(!e)return;e.dispatchEvent(new Event('input',{bubbles:true}));e.dispatchEvent(new Event('change',{bubbles:true}))}
function busy(e,on,label='Working…'){if(!e)return;if(!e.dataset.proBase)e.dataset.proBase=e.textContent;e.disabled=!!on;e.textContent=on?label:e.dataset.proBase}
async function info(){if(S.info)return S.info;if(!S.sdk)S.sdk=await import(CONFIG.sdkUrl);S.info=new S.sdk.InfoClient({transport:new S.sdk.HttpTransport({isTestnet:testnet(),timeout:CONFIG.exchangeTimeoutMs})});return S.info}
function resetInfo(){S.info=null}
function syncCoin(){S.coin=String($('coin')?.value||'BTC').toUpperCase();if($('marketPickerLabel'))$('marketPickerLabel').textContent=`${S.coin}-PERP`}
function favs(){try{const a=JSON.parse(localStorage.getItem(FAV)||'[]');return Array.isArray(a)?a.map(x=>String(x).toUpperCase()):[]}catch{return[]}}
function saveFavs(a){localStorage.setItem(FAV,JSON.stringify([...new Set(a)].slice(0,30)))}
function nativeMarkets(){return [...($('coin')?.options||[])].map(o=>{const text=String(o.textContent||o.value);return{coin:String(o.value||'').toUpperCase(),lev:num((text.match(/max\s+(\d+)x/i)||[])[1])}}).filter(x=>x.coin)}
function openModal(id){const e=$(id);if(!e)return;if(S.modal&&S.modal!==id)closeModal(S.modal);e.hidden=false;document.body.classList.add('modal-open');S.modal=id;requestAnimationFrame(()=>e.classList.add('open'))}
function closeModal(id=S.modal){const e=$(id);if(!e)return;e.classList.remove('open');setTimeout(()=>e.hidden=true,120);document.body.classList.remove('modal-open');if(S.modal===id)S.modal=null}
function renderMarkets(q=''){const root=$('marketList');if(!root)return;const query=String(q).trim().toUpperCase(),f=favs();const rows=nativeMarkets().filter(x=>!query||x.coin.includes(query)).sort((a,b)=>(f.includes(b.coin)?1:0)-(f.includes(a.coin)?1:0)||a.coin.localeCompare(b.coin)).slice(0,150);root.innerHTML=rows.map(x=>`<button class="market-row ${x.coin===S.coin?'active':''}" data-market="${esc(x.coin)}"><span class="market-star" data-star="${esc(x.coin)}">${f.includes(x.coin)?'★':'☆'}</span><strong>${esc(x.coin)}-PERP</strong><small>max ${x.lev||'—'}x</small></button>`).join('')||'<div class="picker-empty">No markets found.</div>';root.querySelectorAll('[data-star]').forEach(e=>e.onclick=ev=>{ev.preventDefault();ev.stopPropagation();const a=favs(),i=a.indexOf(e.dataset.star);i>=0?a.splice(i,1):a.unshift(e.dataset.star);saveFavs(a);renderMarkets($('marketSearch')?.value||'')});root.querySelectorAll('[data-market]').forEach(e=>e.onclick=()=>selectMarket(e.dataset.market))}
function selectMarket(c){const e=$('coin');if(!e||![...e.options].some(o=>o.value===c))return;e.value=c;fire(e);syncCoin();closeModal('marketPickerModal');loadMarket().catch(()=>{})}
async function metrics(){const seq=++S.metricSeq;try{const i=await info(),raw=await i.metaAndAssetCtxs();if(seq!==S.metricSeq)return;const meta=raw?.[0]||raw?.meta||{},ctxs=raw?.[1]||raw?.assetCtxs||[],idx=(meta.universe||[]).findIndex(x=>String(x?.name||'').toUpperCase()===S.coin),c=ctxs[idx]||{},mark=num(c.markPx,S.lastPx),prev=num(c.prevDayPx),ch=prev>0&&mark>0?(mark/prev-1)*100:NaN;if($('metricChange')){$('metricChange').textContent=pct(ch);$('metricChange').className=`metric-value ${ch>=0?'positive':'negative'}`}if($('metricVolume'))$('metricVolume').textContent=`$${compact(num(c.dayNtlVlm))}`;if($('metricOI'))$('metricOI').textContent=`$${compact(num(c.openInterest)*mark)}`;if($('metricFunding'))$('metricFunding').textContent=pct(num(c.funding)*100,4);if(mark>0)S.lastPx=mark;previewRisk()}catch(e){console.warn('metrics',e)}}
async function chart(){const seq=++S.chartSeq,status=$('chartStatus');if(status)status.textContent='Loading…';try{const i=await info(),ms=IMS[S.interval]||IMS['15m'],end=Date.now(),start=end-ms*220,rows=await i.candleSnapshot({coin:S.coin,interval:S.interval,startTime:start,endTime:end});if(seq!==S.chartSeq)return;S.candles=(Array.isArray(rows)?rows:[]).map(c=>({t:num(c.t),o:num(c.o),h:num(c.h),l:num(c.l),c:num(c.c),v:num(c.v)})).filter(c=>c.t&&c.o>0&&c.h>0&&c.l>0&&c.c>0).slice(-180);if(S.candles.length)S.lastPx=S.candles.at(-1).c;draw();if(status)status.textContent=`${S.candles.length} candles · live`}catch(e){console.warn('chart',e);if(status)status.textContent='Chart retrying'}}
function draw(){const cv=$('priceChart');if(!cv)return;const r=cv.getBoundingClientRect(),d=Math.max(1,Math.min(2,devicePixelRatio||1)),w=Math.max(300,Math.floor(r.width)),h=Math.max(250,Math.floor(r.height));cv.width=w*d;cv.height=h*d;const x=cv.getContext('2d');x.setTransform(d,0,0,d,0,0);x.clearRect(0,0,w,h);const a=S.candles.slice(-120);if(!a.length){x.fillStyle='#778196';x.font='12px system-ui';x.fillText('Waiting for chart data…',16,28);return}const p={l:12,r:72,t:18,b:38},vh=48,ph=h-p.t-p.b-vh;let lo=Math.min(...a.map(c=>c.l)),hi=Math.max(...a.map(c=>c.h)),span=Math.max(hi-lo,hi*.002);lo-=span*.08;hi+=span*.08;const step=(w-p.l-p.r)/a.length,Y=v=>p.t+(hi-v)/(hi-lo)*ph,X=i=>p.l+(i+.5)*step;x.strokeStyle='rgba(255,255,255,.055)';x.fillStyle='#778196';x.font='10px system-ui';for(let k=0;k<=4;k++){const y=p.t+ph*k/4;x.beginPath();x.moveTo(p.l,y);x.lineTo(w-p.r,y);x.stroke();x.fillText(money(hi-(hi-lo)*k/4),w-p.r+7,y+3)}const maxV=Math.max(1,...a.map(c=>c.v));a.forEach((c,i)=>{const up=c.c>=c.o,col=up?'#30d790':'#ff6378',xx=X(i),bw=Math.max(2,Math.min(9,step*.62));x.strokeStyle=col;x.fillStyle=col;x.beginPath();x.moveTo(xx,Y(c.h));x.lineTo(xx,Y(c.l));x.stroke();const y1=Y(Math.max(c.o,c.c)),y2=Y(Math.min(c.o,c.c));x.fillRect(xx-bw/2,y1,bw,Math.max(1,y2-y1));const vol=c.v/maxV*vh*.85;x.globalAlpha=.28;x.fillRect(xx-bw/2,h-p.b-vol,bw,vol);x.globalAlpha=1});const last=a.at(-1).c,yy=Y(last);x.setLineDash([4,4]);x.strokeStyle='#8caef8';x.beginPath();x.moveTo(p.l,yy);x.lineTo(w-p.r,yy);x.stroke();x.setLineDash([]);x.fillStyle='#8caef8';x.fillText(money(last),w-p.r+7,yy+3)}
function setIntervalValue(v){if(!IMS[v])return;S.interval=v;localStorage.setItem(INT,v);document.querySelectorAll('[data-interval]').forEach(b=>b.classList.toggle('active',b.dataset.interval===v));chart()}
function setSide(v){const e=$('side');if(!e)return;e.value=v==='SELL'?'SELL':'BUY';fire(e);document.querySelectorAll('[data-side-btn]').forEach(b=>b.classList.toggle('active',b.dataset.sideBtn===e.value));previewRisk()}
function setType(v){const e=$('orderType');if(!e)return;e.value=v==='LIMIT'?'LIMIT':'MARKET';fire(e);document.querySelectorAll('[data-type-btn]').forEach(b=>b.classList.toggle('active',b.dataset.typeBtn===e.value));previewRisk()}
function setUsd(v){const e=$('orderUsd');if(!e)return;e.value=String(Math.max(1,Math.round(num(v))));fire(e);previewRisk()}
function equity(){return num(String($('equity')?.textContent||'').replace(/[^0-9.-]/g,''))}
function setEquity(fr){const e=equity();if(e>0)setUsd(Math.min(CONFIG.maxOrderUsd,e*fr))}
function basePx(){if($('orderType')?.value==='LIMIT'){const p=num($('limitPrice')?.value);if(p>0)return p}return S.lastPx||num(String($('marketPrice')?.textContent||'').replace(/[^0-9.-]/g,''))}
function protect(kind,percent){const p=basePx();if(!(p>0))return toast('Live price is not ready','error');const buy=$('side')?.value!=='SELL',up=kind==='tp'?buy:!buy,val=p*(up?1+percent/100:1-percent/100),e=$(kind);e.value=String(Number(val.toPrecision(6)));fire(e);previewRisk()}
function validateOrder(){const buy=$('side')?.value!=='SELL',p=basePx(),tpv=num($('tp')?.value),slv=num($('sl')?.value),type=$('orderType')?.value;if(type==='LIMIT'&&!(p>0))return'Enter a valid limit price';if(!(num($('orderUsd')?.value)>0))return'Order amount must be positive';if(tpv>0&&p>0&&((buy&&tpv<=p)||(!buy&&tpv>=p)))return buy?'Take profit must be above entry':'Take profit must be below entry';if(slv>0&&p>0&&((buy&&slv>=p)||(!buy&&slv<=p)))return buy?'Stop loss must be below entry':'Stop loss must be above entry';return''}
function previewRisk(){const p=basePx(),usd=num($('orderUsd')?.value),lev=Math.max(1,num($('leverage')?.value,1)),tpv=num($('tp')?.value),slv=num($('sl')?.value),risk=slv>0&&p>0?usd*Math.abs(slv-p)/p:0,reward=tpv>0&&p>0?usd*Math.abs(tpv-p)/p:0;if($('riskMargin'))$('riskMargin').textContent=usd>0?money(usd/lev):'—';if($('riskLoss'))$('riskLoss').textContent=risk>0?money(risk):'—';if($('riskReward'))$('riskReward').textContent=reward>0?money(reward):'—';if($('riskRR'))$('riskRR').textContent=risk>0&&reward>0?`1:${(reward/risk).toFixed(2)}`:'—';if($('riskSlippage'))$('riskSlippage').textContent=`${CONFIG.marketSlippageBps} bps`;const err=validateOrder(),v=$('orderValidation');if(v){v.textContent=err||((tpv||slv)?'Protection ready':'Protection optional');v.classList.toggle('bad',!!err)}}
function riskKey(){return`rwa_risk_v2:${wallet()||'anon'}`}
function risk(){let r={};try{r=JSON.parse(localStorage.getItem(riskKey())||'{}')||{}}catch{}return{dailyLoss:Math.min(CONFIG.dailyLossUsd,Math.max(1,num(r.dailyLoss,CONFIG.dailyLossUsd))),maxLeverage:Math.min(CONFIG.maxLeverage,Math.max(1,num(r.maxLeverage,CONFIG.maxLeverage))),maxExposure:Math.min(CONFIG.maxExposureUsd,Math.max(1,num(r.maxExposure,CONFIG.maxExposureUsd))),perAsset:Math.min(CONFIG.maxPerAssetUsd,Math.max(1,num(r.perAsset,CONFIG.maxPerAssetUsd))),kill:!!r.kill}}
function renderRisk(){const r=risk();if($('riskSummary'))$('riskSummary').textContent=`${r.maxLeverage}x · $${compact(r.perAsset)}`;const b=$('killSwitchBtn');if(b){b.classList.toggle('kill-on',r.kill);b.textContent=r.kill?'KILL SWITCH ON — entries blocked':'Kill switch'}}
function openRisk(){const r=risk();$('riskDailyLoss').value=r.dailyLoss;$('riskMaxLeverage').value=r.maxLeverage;$('riskMaxExposure').value=r.maxExposure;$('riskPerAsset').value=r.perAsset;$('riskKill').checked=r.kill;openModal('riskModal')}
function saveRisk(){const r={dailyLoss:Math.min(CONFIG.dailyLossUsd,Math.max(1,num($('riskDailyLoss').value))),maxLeverage:Math.min(CONFIG.maxLeverage,Math.max(1,num($('riskMaxLeverage').value))),maxExposure:Math.min(CONFIG.maxExposureUsd,Math.max(1,num($('riskMaxExposure').value))),perAsset:Math.min(CONFIG.maxPerAssetUsd,Math.max(1,num($('riskPerAsset').value))),kill:!!$('riskKill').checked};localStorage.setItem(riskKey(),JSON.stringify(r));renderRisk();closeModal('riskModal');toast('Risk limits saved','success')}
function toggleKill(){const r=risk();r.kill=!r.kill;localStorage.setItem(riskKey(),JSON.stringify(r));renderRisk();toast(r.kill?'Kill switch enabled — new entries blocked':'Kill switch disabled',r.kill?'error':'success')}
async function livePositions(){const api=window.RWAExecutionAPI;if(!api)throw Error('Execution API unavailable');const raw=await api.account.state(testnet()),rows=(raw?.assetPositions||[]).map(x=>x?.position||x).filter(p=>num(p?.szi)!==0);return rows}
async function managePosition(coin){try{const p=(await livePositions()).find(x=>String(x.coin||'').toUpperCase()===String(coin).toUpperCase());if(!p)return toast('Position is no longer open','error');S.position=p;$('manageCoin').textContent=`${p.coin} position`;$('manageSide').textContent=num(p.szi)>0?'LONG':'SHORT';$('manageSize').textContent=String(Math.abs(num(p.szi)));$('manageEntry').textContent=money(p.entryPx);$('managePnl').textContent=money(p.unrealizedPnl);if($('manageNetwork'))$('manageNetwork').textContent=testnet()?'TESTNET':'MAINNET';$('manageTp').value='';$('manageSl').value='';openModal('positionModal')}catch(e){toast(e.message||e,'error')}}
async function partialClose(fr,b){const p=S.position,api=window.RWAExecutionAPI;if(!p||!api)return;try{busy(b,true,'Closing…');await api.orders.market({coin:String(p.coin).toUpperCase(),side:num(p.szi)>0?'SELL':'BUY',size:Math.abs(num(p.szi))*fr,reduceOnly:true,leverage:1,testnet:testnet(),preferAgent:true});toast(`${p.coin} ${Math.round(fr*100)}% close submitted`,'success');closeModal('positionModal');setTimeout(()=>$('refreshBtn')?.click(),700)}catch(e){toast(e.message||e,'error')}finally{busy(b,false)}}
async function addProtection(b){const p=S.position,api=window.RWAExecutionAPI;if(!p||!api)return;const tpv=num($('manageTp').value),slv=num($('manageSl').value),entry=num(p.entryPx),long=num(p.szi)>0;if(!tpv&&!slv)return toast('Enter TP and/or SL price','error');if(tpv&&((long&&tpv<=entry)||(!long&&tpv>=entry)))return toast('TP is on the wrong side of entry','error');if(slv&&((long&&slv>=entry)||(!long&&slv<=entry)))return toast('SL is on the wrong side of entry','error');try{busy(b,true,'Adding…');const side=long?'SELL':'BUY',size=Math.abs(num(p.szi));if(tpv)await api.orders.trigger({coin:p.coin,side,size,triggerPx:tpv,tpsl:'tp',testnet:testnet(),preferAgent:true});if(slv)await api.orders.trigger({coin:p.coin,side,size,triggerPx:slv,tpsl:'sl',testnet:testnet(),preferAgent:true});toast(`${p.coin} protection added`,'success');closeModal('positionModal');setTimeout(()=>$('refreshBtn')?.click(),700)}catch(e){toast(e.message||e,'error')}finally{busy(b,false)}}
async function cancelTriggers(b){const p=S.position,api=window.RWAExecutionAPI;if(!p||!api)return;try{busy(b,true,'Cancelling…');const rows=await api.orders.open(testnet()),coin=String(p.coin).toUpperCase(),tr=(Array.isArray(rows)?rows:[]).filter(o=>String(o?.coin||'').toUpperCase()===coin&&(o?.isTrigger===true||/trigger|take profit|stop/i.test(JSON.stringify(o))));for(const o of tr)await api.orders.cancel({coin,oid:o.oid,testnet:testnet(),preferAgent:true});toast(tr.length?`${tr.length} protection order(s) cancelled`:'No trigger orders found','success');setTimeout(()=>$('refreshBtn')?.click(),500)}catch(e){toast(e.message||e,'error')}finally{busy(b,false)}}
function breakEven(){if(!S.position)return;$('manageSl').value=String(S.position.entryPx||'');toast('Break-even SL filled — review then add protection','success')}
async function modifyRow(row,b){const c=row.querySelector('[data-cancel]'),api=window.RWAExecutionAPI;if(!c||!api)return;try{const rows=await api.orders.open(testnet()),oid=num(c.dataset.cancel),o=(Array.isArray(rows)?rows:[]).find(x=>num(x?.oid)===oid);if(!o)return toast('Order is no longer open','error');if(o?.isTrigger===true||/trigger/i.test(JSON.stringify(o)))return toast('Use Position manager for TP/SL','error');const old=num(o.limitPx||o.px),next=prompt(`New ${o.coin||c.dataset.coin} limit price`,String(old||''));if(next==null)return;const price=num(next);if(!(price>0))return toast('Enter a valid limit price','error');const raw=String(o.side||row.cells?.[1]?.textContent||'').toUpperCase(),side=['B','BUY','LONG'].includes(raw)?'BUY':'SELL';busy(b,true,'…');await api.orders.modify({coin:String(o.coin||c.dataset.coin).toUpperCase(),oid,side,price,size:num(o.sz),reduceOnly:!!o.reduceOnly,testnet:testnet(),preferAgent:true});toast('Order modified','success');setTimeout(()=>$('refreshBtn')?.click(),600)}catch(e){toast(e.message||e,'error')}finally{busy(b,false)}}
function augment(){document.querySelectorAll('#positionsBody tr').forEach(r=>{const c=r.querySelector('[data-close]');if(!c||r.querySelector('[data-pro-manage]'))return;const b=document.createElement('button');b.className='mini pro-manage';b.dataset.proManage=c.dataset.close;b.textContent='Manage';b.onclick=()=>managePosition(c.dataset.close);c.parentElement?.prepend(b)});document.querySelectorAll('#ordersBody tr').forEach(r=>{const c=r.querySelector('[data-cancel]');if(!c||r.querySelector('[data-pro-modify]'))return;const b=document.createElement('button');b.className='mini pro-modify';b.dataset.proModify=c.dataset.cancel;b.textContent='Modify';b.onclick=()=>modifyRow(r,b);c.parentElement?.prepend(b)})}
function watchPrice(){const e=$('marketPrice');if(!e)return;const u=()=>{const p=num(String(e.textContent||'').replace(/[^0-9.-]/g,''));if(p>0){S.lastPx=p;S.lastPxAt=Date.now();$('liveDot')?.classList.add('online');if($('liveText'))$('liveText').textContent='LIVE';previewRisk()}};new MutationObserver(u).observe(e,{childList:true,characterData:true,subtree:true});u();setInterval(()=>{const stale=!S.lastPxAt||Date.now()-S.lastPxAt>20000;$('liveDot')?.classList.toggle('online',!stale);if($('liveText'))$('liveText').textContent=stale?'RECONNECTING':'LIVE'},5000)}
async function loadMarket(){syncCoin();resetInfo();await Promise.allSettled([metrics(),chart()])}
function bind(){
 $('marketPickerBtn')?.addEventListener('click',()=>{renderMarkets();$('marketSearch').value='';openModal('marketPickerModal');setTimeout(()=>$('marketSearch')?.focus(),40)});$('marketSearch')?.addEventListener('input',e=>renderMarkets(e.target.value));document.querySelectorAll('[data-close-modal]').forEach(b=>b.onclick=()=>closeModal(b.dataset.closeModal));document.querySelectorAll('.modal-backdrop').forEach(b=>b.onclick=()=>closeModal(b.closest('.modal-layer')?.id));document.querySelectorAll('[data-interval]').forEach(b=>b.onclick=()=>setIntervalValue(b.dataset.interval));document.querySelectorAll('[data-side-btn]').forEach(b=>b.onclick=()=>setSide(b.dataset.sideBtn));document.querySelectorAll('[data-type-btn]').forEach(b=>b.onclick=()=>setType(b.dataset.typeBtn));document.querySelectorAll('[data-usd-preset]').forEach(b=>b.onclick=()=>setUsd(b.dataset.usdPreset));document.querySelectorAll('[data-equity-preset]').forEach(b=>b.onclick=()=>setEquity(num(b.dataset.equityPreset)));document.querySelectorAll('[data-tp-pct]').forEach(b=>b.onclick=()=>protect('tp',num(b.dataset.tpPct)));document.querySelectorAll('[data-sl-pct]').forEach(b=>b.onclick=()=>protect('sl',num(b.dataset.slPct)));$('riskSettingsBtn')?.addEventListener('click',openRisk);$('saveRiskBtn')?.addEventListener('click',saveRisk);$('killSwitchBtn')?.addEventListener('click',toggleKill);document.querySelectorAll('[data-close-fraction]').forEach(b=>b.onclick=()=>partialClose(num(b.dataset.closeFraction),b));$('addProtectionBtn')?.addEventListener('click',e=>addProtection(e.currentTarget));$('cancelTriggersBtn')?.addEventListener('click',e=>cancelTriggers(e.currentTarget));$('breakEvenBtn')?.addEventListener('click',breakEven);
 ['orderUsd','leverage','limitPrice','tp','sl','side','orderType'].forEach(id=>$(id)?.addEventListener('input',previewRisk));$('coin')?.addEventListener('change',()=>{syncCoin();loadMarket().catch(()=>{})});$('testnetToggle')?.addEventListener('change',()=>{resetInfo();loadMarket().catch(()=>{})});const l=$('leverage'),r=$('leverageRange');if(l&&r){r.max=String(CONFIG.maxLeverage);r.value=l.value;r.oninput=()=>{l.value=r.value;fire(l);previewRisk()};l.oninput=()=>r.value=String(Math.max(1,Math.min(CONFIG.maxLeverage,num(l.value,1))))}
 [$('positionsBody'),$('ordersBody')].filter(Boolean).forEach(e=>new MutationObserver(augment).observe(e,{childList:true,subtree:true}));augment();const cv=$('priceChart');if(cv)new ResizeObserver(draw).observe(cv);window.addEventListener('keydown',e=>{const typing=/input|textarea|select/i.test(document.activeElement?.tagName||'');if(e.key==='Escape'&&S.modal)return closeModal();if(typing)return;if(e.key==='/'){e.preventDefault();$('marketPickerBtn')?.click()}if(e.key.toLowerCase()==='b')setSide('BUY');if(e.key.toLowerCase()==='s')setSide('SELL');if(e.key.toLowerCase()==='m')setType('MARKET');if(e.key.toLowerCase()==='l')setType('LIMIT')});$('mobileBuy')?.addEventListener('click',()=>{setSide('BUY');document.querySelector('.order')?.scrollIntoView({behavior:'smooth',block:'start'})});$('mobileSell')?.addEventListener('click',()=>{setSide('SELL');document.querySelector('.order')?.scrollIntoView({behavior:'smooth',block:'start'})});
 const trade=$('tradeBtn');trade?.addEventListener('click',e=>{const err=validateOrder();if(err){e.preventDefault();e.stopImmediatePropagation();toast(err,'error')}},true);
}
async function boot(){syncCoin();bind();watchPrice();renderRisk();document.querySelectorAll('[data-interval]').forEach(b=>b.classList.toggle('active',b.dataset.interval===S.interval));setSide($('side')?.value||'BUY');setType($('orderType')?.value||'MARKET');previewRisk();setTimeout(()=>loadMarket().catch(()=>{}),800);setInterval(()=>{metrics().catch(()=>{});chart().catch(()=>{})},30000);window.RWATradePro={version:'1.0.0',selectMarket,managePosition,chart,metrics,risk};window.dispatchEvent(new CustomEvent('rwa:trade-pro-ready'))}
boot().catch(e=>console.warn('RWA Trade Pro unavailable',e));
