const API=['https://data-api.binance.vision','https://api.binance.com'];
const RWA=new Set(['ONDO','PENDLE','POLYX','LINK','TRU','RSR','MKR','SKY','AAVE','COMP','SNX','ENA','CFG','OM','XDC','ALGO','HBAR']);
const S={pairs:[],map:new Map(),selected:'BTCUSDT',filter:'all',query:'',interval:'60',marketWS:null,detailWS:null,buyVol:0,sellVol:0,trades:0,recentTrades:[],klines:[],book:{bids:[],asks:[]},rawBook:{bids:[],asks:[]},bookLastUpdateId:0,bookStep:.1,bookLevels:9,bookTimer:null,tvTimer:null};
const $=id=>document.getElementById(id);const esc=s=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
function toast(t){const e=$('toast');e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function num(v){const n=Number(v);return Number.isFinite(n)?n:null}function price(v){const n=num(v);if(n==null)return'—';let d=n>=1000?2:n>=1?4:n>=.01?5:7;return '$'+n.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:d})}function compact(v){const n=num(v);if(n==null)return'—';return '$'+Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:2}).format(n)}function pct(v){const n=num(v);if(n==null)return'—';return(n>=0?'+':'')+n.toFixed(2)+'%'}
async function get(path){let err;for(const base of API){try{const r=await fetch(base+path,{cache:'no-store'});if(r.ok)return await r.json();err=new Error(r.status)}catch(e){err=e}}throw err||new Error('market data unavailable')}
async function loadMarkets(){try{const [info,tickers]=await Promise.all([get('/api/v3/exchangeInfo'),get('/api/v3/ticker/24hr')]);const tm=new Map(tickers.map(x=>[x.symbol,x]));S.pairs=info.symbols.filter(x=>x.status==='TRADING'&&x.quoteAsset==='USDT'&&x.isSpotTradingAllowed!==false).map(x=>{const t=tm.get(x.symbol)||{};return{symbol:x.symbol,base:x.baseAsset,quote:x.quoteAsset,price:num(t.lastPrice),open:num(t.openPrice),change:num(t.priceChangePercent),high:num(t.highPrice),low:num(t.lowPrice),vol:num(t.quoteVolume),rwa:RWA.has(x.baseAsset)}}).sort((a,b)=>(b.vol||0)-(a.vol||0));S.map=new Map(S.pairs.map(x=>[x.symbol,x]));$('pairCount').textContent=S.pairs.length+' live USDT pairs · click any market';if(!S.map.has(S.selected)&&S.pairs[0])S.selected=S.pairs[0].symbol;renderPairs();renderMovers();selectPair(S.selected,false);connectAllTicker();setLive(true,'LIVE · hundreds of markets')}catch(e){$('pairCount').textContent='Exchange list unavailable · retrying';$('pairList').innerHTML='<div class="empty">Could not load exchange markets. Retrying automatically…</div>';setLive(false,'RECONNECTING');setTimeout(loadMarkets,5000)}}
function filtered(){let a=S.pairs;const q=S.query.trim().toUpperCase();if(q)a=a.filter(x=>x.symbol.includes(q)||x.base.includes(q));if(S.filter==='rwa')a=a.filter(x=>x.rwa);if(S.filter==='crypto')a=a.filter(x=>!x.rwa);if(S.filter==='gainers')a=[...a].filter(x=>(x.change||0)>0).sort((x,y)=>(y.change||0)-(x.change||0));if(S.filter==='losers')a=[...a].filter(x=>(x.change||0)<0).sort((x,y)=>(x.change||0)-(y.change||0));return a}
function renderPairs(){const all=filtered(),limit=innerWidth<681?70:140,a=all.slice(0,limit);if($('pairCount'))$('pairCount').textContent=S.pairs.length+' live USDT pairs · showing '+a.length+' of '+all.length;const frag=document.createDocumentFragment();a.forEach(x=>{const d=document.createElement('div');d.className='pairrow'+(x.symbol===S.selected?' active':'');d.dataset.sym=x.symbol;d.innerHTML=`<div class="pairname"><div class="tokenicon">${esc(x.base.slice(0,2))}</div><div class="pairmeta"><b>${esc(x.base)} / USDT</b><small>${x.rwa?'RWA · ':''}Spot</small></div></div><div class="pairprice"><b data-p="${x.symbol}">${price(x.price)}</b><div data-c="${x.symbol}" class="chg ${(x.change||0)>=0?'up':'down'}">${pct(x.change)}</div></div>`;d.onclick=()=>selectPair(x.symbol,true);frag.appendChild(d)});$('pairList').replaceChildren(frag);if(!a.length)$('pairList').innerHTML='<div class="empty">No markets match this filter.</div>'}
function setLive(ok,text){const d=$('liveDot'),t=$('liveText');if(d)d.className='dot'+(ok?' live':'');if(t)t.textContent=text}
function connectAllTicker(){if(S.marketWS)try{S.marketWS.close()}catch(_){};const ws=new WebSocket('wss://data-stream.binance.vision/ws/!miniTicker@arr');S.marketWS=ws;ws.onopen=()=>setLive(true,'LIVE · '+S.pairs.length+' markets');ws.onmessage=e=>{try{const arr=JSON.parse(e.data);for(const t of arr){const x=S.map.get(t.s);if(!x)continue;const old=x.price;x.price=num(t.c);x.open=num(t.o);x.high=num(t.h);x.low=num(t.l);x.vol=num(t.q);if(x.open)x.change=(x.price-x.open)/x.open*100;updatePairDOM(x,old);if(t.s===S.selected)renderHeader(x)}renderMoversThrottled()}catch(_){}};ws.onclose=()=>{setLive(false,'RECONNECTING');setTimeout(connectAllTicker,1800)};ws.onerror=()=>{}}
function updatePairDOM(x,old){const p=document.querySelector(`[data-p="${x.symbol}"]`),c=document.querySelector(`[data-c="${x.symbol}"]`);if(p){p.textContent=price(x.price);if(old!=null&&x.price!==old){p.style.color=x.price>old?'var(--green)':'var(--red)';setTimeout(()=>p.style.color='',260)}}if(c){c.textContent=pct(x.change);c.className='chg '+((x.change||0)>=0?'up':'down')}}
let moverTimer;function renderMoversThrottled(){if(moverTimer)return;moverTimer=setTimeout(()=>{renderMovers();moverTimer=null},1800)}function renderMovers(){const top=[...S.pairs].filter(x=>x.change!=null).sort((a,b)=>Math.abs(b.change)-Math.abs(a.change)).slice(0,8);$('movers').innerHTML=top.map(x=>`<div class="mover" data-ms="${x.symbol}"><div><b>${esc(x.base)} / USDT</b><br><span>${price(x.price)}</span></div><span class="${x.change>=0?'up':'down'}">${pct(x.change)}</span></div>`).join('');document.querySelectorAll('[data-ms]').forEach(e=>e.onclick=()=>selectPair(e.dataset.ms,true))}
function renderMidPrice(value,spreadText){
 const el=$('midPrice');if(!el)return;const v=num(value);el.innerHTML='<strong>'+price(v)+'</strong><span>'+(spreadText?'Spread '+esc(spreadText):'Live mid')+'</span>'
}
function renderHeader(x){$('selIcon').textContent=x.base.slice(0,2);$('selName').textContent=x.base+' / USDT';$('selLabel').textContent=(x.rwa?'RWA-linked · ':'')+'Binance Spot';$('statPrice').textContent=price(x.price);$('statChange').textContent=pct(x.change);$('statChange').className=(x.change||0)>=0?'up':'down';$('statHigh').textContent=price(x.high);$('statLow').textContent=price(x.low);$('statVol').textContent=compact(x.vol);if(!S.rawBook.bids.length||!S.rawBook.asks.length)renderMidPrice(x.price,null)}
async function selectPair(sym,scroll){if(!S.map.has(sym))return;if(S.bookTimer){clearTimeout(S.bookTimer);S.bookTimer=null}S.selected=sym;S.buyVol=0;S.sellVol=0;S.trades=0;S.recentTrades=[];S.book={bids:[],asks:[]};S.rawBook={bids:[],asks:[]};S.rawBook={bids:[],asks:[]};S.bookLastUpdateId=0;renderHeader(S.map.get(sym));document.querySelectorAll('.pairrow.active').forEach(e=>e.classList.remove('active'));document.querySelector(`.pairrow[data-sym="${sym}"]`)?.classList.add('active');$('tradeTape').innerHTML='<div class="empty">Connecting live trade stream…</div>';$('activity').innerHTML='<div class="empty">Waiting for market activity…</div>';$('bids').innerHTML='';$('asks').innerHTML='';renderPulse();loadBookSnapshot();connectDetail();loadKlines();loadTradingView();if(scroll&&innerWidth<681)$('terminal').scrollIntoView({behavior:'smooth',block:'start'})}
async function loadBookSnapshot(){
 try{
  const snap=await get('/api/v3/depth?symbol='+encodeURIComponent(S.selected)+'&limit=100');
  if(!snap||!Array.isArray(snap.bids)||!Array.isArray(snap.asks))throw Error('invalid order book snapshot');
  S.bookLastUpdateId=Number(snap.lastUpdateId||0);
  S.rawBook={bids:snap.bids.map(x=>[String(x[0]),String(x[1])]),asks:snap.asks.map(x=>[String(x[0]),String(x[1])])};
  renderBook();
 }catch(_){}
}
function mergeDepthSide(current,updates,desc){
 const m=new Map((current||[]).map(x=>[String(x[0]),String(x[1])]));
 for(const row of updates||[]){const p=String(row[0]),q=Number(row[1]);if(!(Number(p)>0))continue;if(q===0)m.delete(p);else m.set(p,String(row[1]))}
 return [...m.entries()].sort((a,b)=>desc?Number(b[0])-Number(a[0]):Number(a[0])-Number(b[0])).slice(0,120);
}
function applyBookDelta(ev){
 const U=Number(ev.U||0),u=Number(ev.u||0),last=Number(S.bookLastUpdateId||0);
 if(last&&u<=last)return;
 if(last&&U>last+1){S.bookLastUpdateId=0;loadBookSnapshot();return}
 if(last&&u>=last+1&&U<=last+1){
  S.rawBook={bids:mergeDepthSide(S.rawBook.bids,ev.b,true),asks:mergeDepthSide(S.rawBook.asks,ev.a,false)};
  S.bookLastUpdateId=u;renderBook();
 }
}
async function loadBookDepth(){const sym=S.selected;if(S.bookTimer){clearTimeout(S.bookTimer);S.bookTimer=null}try{const d=await get('/api/v3/depth?symbol='+encodeURIComponent(sym)+'&limit=100');if(sym===S.selected&&Array.isArray(d.bids)&&Array.isArray(d.asks))renderBook(d.bids,d.asks)}catch(_){}finally{if(sym===S.selected)S.bookTimer=setTimeout(loadBookDepth,1500)}}
function connectDetail(){if(S.detailWS)try{S.detailWS.close()}catch(_){};const l=S.selected.toLowerCase();const url=`wss://data-stream.binance.vision/stream?streams=${l}@ticker/${l}@bookTicker/${l}@depth@100ms/${l}@aggTrade`;const ws=new WebSocket(url);S.detailWS=ws;ws.onmessage=e=>{try{const m=JSON.parse(e.data).data||{};if(m.e==='24hrTicker'){const x=S.map.get(m.s);if(x){x.price=num(m.c);x.change=num(m.P);x.high=num(m.h);x.low=num(m.l);x.vol=num(m.q);renderHeader(x)}}else if(m.e==='aggTrade'){addTrade(m)}else if(m.e==='depthUpdate'&&m.b&&m.a){applyBookDelta(m)}else if(m.s&&m.b&&m.a){$('bestBid').textContent=price(m.b);$('bestAsk').textContent=price(m.a);const b=num(m.b),a=num(m.a);$('spread').textContent=b&&a?(((a-b)/((a+b)/2))*100).toFixed(4)+'%':'—'}}catch(_){}};ws.onclose=()=>{if(S.detailWS===ws)setTimeout(connectDetail,1200)};ws.onerror=()=>{}}
function groupBook(arr,side){
 const step=Math.max(.00000001,Number(S.bookStep)||.1),m=new Map(),clean=[];
 for(const row of arr||[]){const p=Number(row[0]),q=Number(row[1]);if(!(p>0)||!(q>0))continue;clean.push([p,q]);const k=(side==='ask'?Math.ceil(p/step):Math.floor(p/step))*step,key=Number(k.toFixed(8));m.set(key,(m.get(key)||0)+q)}
 const grouped=[...m.entries()].sort((a,b)=>side==='ask'?a[0]-b[0]:b[0]-a[0]);
 if(grouped.length>=S.bookLevels)return grouped.slice(0,S.bookLevels);
 return clean.sort((a,b)=>side==='ask'?a[0]-b[0]:b[0]-a[0]).slice(0,S.bookLevels)
}
function bookPrice(v){const step=Number(S.bookStep)||.1,d=step>=1?0:Math.min(8,Math.max(1,Math.ceil(-Math.log10(step))));return '$'+Number(v).toLocaleString(undefined,{minimumFractionDigits:d,maximumFractionDigits:d})}
function renderBook(bids,asks){
 if(Array.isArray(bids)&&Array.isArray(asks))S.rawBook={bids:bids.map(x=>[String(x[0]),String(x[1])]),asks:asks.map(x=>[String(x[0]),String(x[1])])};
 const gb=groupBook(S.rawBook.bids,'bid'),ga=groupBook(S.rawBook.asks,'ask');S.book={bids:gb,asks:ga};
 const rs=(arr,side)=>arr.slice(0,S.bookLevels).map(([p,q])=>'<div class="bookrow"><span class="'+side+'">'+bookPrice(p)+'</span><span>'+Number(q).toFixed(4)+'</span><span>'+compact(Number(p)*Number(q))+'</span></div>').join('');
 $('asks').innerHTML=rs([...ga].reverse(),'down');$('bids').innerHTML=rs(gb,'up');
 const rb=S.rawBook.bids[0],ra=S.rawBook.asks[0];if(rb)$('bestBid').textContent=price(rb[0]);if(ra)$('bestAsk').textContent=price(ra[0]);if(rb&&ra){const b=+rb[0],a=+ra[0],sp=(((a-b)/((a+b)/2))*100).toFixed(4)+'%';$('spread').textContent=sp;renderMidPrice(S.map.get(S.selected)?.price||((a+b)/2),sp)}
}
function setBookLevels(levels){
 const next=Number(levels)===10?10:5;S.bookLevels=next;renderBook();
 const m=$('bookMenu');if(m)m.setAttribute('aria-label','Order book depth '+next+' levels');
 return next
}
function bindBookControls(){
 const p=$('bookPrecision'),m=$('bookMenu');
 if(p&&!p.dataset.rwaBookBound){p.dataset.rwaBookBound='1';p.onclick=()=>{const steps=[.01,.1,1],i=steps.findIndex(x=>x===S.bookStep);S.bookStep=steps[(i+1)%steps.length];p.textContent=String(S.bookStep)+'⌄';renderBook()}}
 if(m&&!m.dataset.rwaBookBound){m.dataset.rwaBookBound='1';m.title='Toggle 5 / 10 visible price levels';m.setAttribute('aria-label','Order book depth '+S.bookLevels+' levels');m.onclick=()=>setBookLevels(S.bookLevels===10?5:10)}
}
function addTrade(t){const buy=!t.m,p=Number(t.p),q=Number(t.q),value=p*q,time=Number(t.T||Date.now());buy?S.buyVol+=value:S.sellVol+=value;S.trades++;S.recentTrades.unshift({buy,p,q,value,time});if(S.recentTrades.length>50)S.recentTrades.length=50;const tape=$('tradeTape');if(tape.querySelector('.empty'))tape.innerHTML='';const d=document.createElement('div');d.className='trade';d.innerHTML=`<span class="${buy?'up':'down'}">${price(p)}</span><span>${q.toFixed(q<1?5:3)}</span><span>${new Date(t.T||Date.now()).toLocaleTimeString()}</span>`;tape.prepend(d);while(tape.children.length>40)tape.lastChild.remove();$('lastTick').textContent=new Date().toLocaleTimeString();if(S.trades%6===0)addActivity(buy,p,q);renderPulse()}
function renderPulse(){const total=S.buyVol+S.sellVol;if(!total){$('buyPct').textContent='—';$('pulseBar').style.width='0%';$('tradeCount').textContent=S.trades.toLocaleString()+' trades';return}const b=S.buyVol/total*100;$('buyPct').textContent=b.toFixed(0)+'%';$('pulseBar').style.width=b+'%';$('tradeCount').textContent=S.trades.toLocaleString()+' trades'}
function addActivity(buy,p,q){const a=$('activity');if(a.querySelector('.empty'))a.innerHTML='';const d=document.createElement('div');d.className='activity-item';d.innerHTML=`<div class="activity-avatar">${buy?'B':'S'}</div><div><b>${buy?'Buy-side':'Sell-side'} trade</b><small>${S.selected} · ${q.toFixed(q<1?5:3)} units</small></div><span class="${buy?'up':'down'}">${price(p)}</span>`;a.prepend(d);while(a.children.length>8)a.lastChild.remove()}
function intervalParam(){return({'1':'1m','5':'5m','15':'15m','60':'1h','240':'4h','D':'1d'})[S.interval]||'15m'}
async function loadKlines(){try{const data=await get(`/api/v3/klines?symbol=${S.selected}&interval=${intervalParam()}&limit=180`);S.klines=data.map(k=>({t:k[0],o:+k[1],h:+k[2],l:+k[3],c:+k[4],v:+k[5]}));drawFallback()}catch(_){S.klines=[];drawFallback()}}
function drawFallback(){const c=$('fallbackChart'),ctx=c.getContext('2d'),rect=c.getBoundingClientRect(),dpr=devicePixelRatio||1;c.width=Math.max(1,rect.width*dpr);c.height=Math.max(1,rect.height*dpr);ctx.setTransform(dpr,0,0,dpr,0,0);const w=rect.width,h=rect.height;ctx.fillStyle='#09090d';ctx.fillRect(0,0,w,h);const a=S.klines;if(!a.length){ctx.strokeStyle='#18181f';ctx.lineWidth=1;for(let i=1;i<6;i++){const y=h*i/6;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}for(let i=1;i<8;i++){const x=w*i/8;ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,h);ctx.stroke()}return}const pad={l:10,r:58,t:18,b:28},cw=w-pad.l-pad.r,ch=h-pad.t-pad.b,min=Math.min(...a.map(x=>x.l)),max=Math.max(...a.map(x=>x.h)),range=max-min||1;ctx.strokeStyle='#18181f';ctx.lineWidth=1;ctx.fillStyle='#5d5c68';ctx.font='10px system-ui';ctx.textAlign='left';for(let i=0;i<5;i++){const y=pad.t+ch*i/4;ctx.beginPath();ctx.moveTo(pad.l,y);ctx.lineTo(w-pad.r,y);ctx.stroke();const val=max-range*i/4;ctx.fillText(val.toFixed(val>=100?2:4),w-pad.r+5,y+3)}const step=cw/a.length,body=Math.max(1,step*.62);for(let i=0;i<a.length;i++){const x=pad.l+i*step+step/2,k=a[i],up=k.c>=k.o,col=up?'#38d996':'#ff6677',yy=v=>pad.t+(max-v)/range*ch;ctx.strokeStyle=col;ctx.fillStyle=col;ctx.beginPath();ctx.moveTo(x,yy(k.h));ctx.lineTo(x,yy(k.l));ctx.stroke();const y1=yy(Math.max(k.o,k.c)),y2=yy(Math.min(k.o,k.c));ctx.fillRect(x-body/2,y1,body,Math.max(1,y2-y1))}}
function loadTradingView(){const host=$('tvHost');host.innerHTML='';host.style.pointerEvents='auto';clearTimeout(S.tvTimer);const box=document.createElement('div');box.className='tradingview-widget-container';box.style.height='100%';box.style.width='100%';const widget=document.createElement('div');widget.className='tradingview-widget-container__widget';widget.style.height='100%';widget.style.width='100%';box.appendChild(widget);const sc=document.createElement('script');sc.type='text/javascript';sc.src='https://s3.tradingview.com/external-embedding/embed-widget-advanced-chart.js';sc.async=true;sc.text=JSON.stringify({autosize:true,symbol:'BINANCE:'+S.selected,interval:S.interval,timezone:'Asia/Jakarta',theme:'dark',style:'1',locale:'en',backgroundColor:'rgba(9,9,13,1)',gridColor:'rgba(36,36,46,.55)',hide_top_toolbar:false,hide_legend:false,allow_symbol_change:false,save_image:false,calendar:false,support_host:'https://www.tradingview.com'});box.appendChild(sc);host.appendChild(box);S.tvTimer=setTimeout(()=>{if(!host.querySelector('iframe')){host.style.pointerEvents='none';toast('TradingView unavailable — live fallback candlestick chart remains active')}else host.style.pointerEvents='auto'},7000)}
function reloadChart(){loadKlines();loadTradingView();toast('Chart reloaded')}
bindBookControls();
const watchAdd=$('watchAdd'),watchMenu=$('watchMenu');
if(watchAdd)watchAdd.onclick=()=>{document.body.classList.toggle('rwa-watch-search-open');if(document.body.classList.contains('rwa-watch-search-open'))setTimeout(()=>$('search')?.focus(),0)};
if(watchMenu)watchMenu.onclick=()=>{const on=document.body.classList.toggle('rwa-watch-comfortable');watchMenu.setAttribute('aria-pressed',String(on));watchMenu.title=on?'Use compact watchlist':'Use comfortable watchlist'};
document.querySelectorAll('.filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.filter=b.dataset.filter;renderPairs()});$('search').oninput=e=>{S.query=e.target.value;renderPairs()};document.querySelectorAll('#timeframes button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#timeframes button').forEach(x=>x.classList.remove('active'));b.classList.add('active');S.interval=b.dataset.iv;loadKlines();loadTradingView()});addEventListener('resize',()=>drawFallback());document.addEventListener('visibilitychange',()=>{if(!document.hidden){if(!S.marketWS||S.marketWS.readyState>1)connectAllTicker();if(!S.detailWS||S.detailWS.readyState>1)connectDetail();if(!S.bookTimer)loadBookDepth()}});setTimeout(loadMarkets,0);
window.RWAMarketRuntime={version:'1.4.3',state:()=>({selected:S.selected,interval:S.interval,bookStep:S.bookStep,bookLevels:S.bookLevels,pairs:S.pairs.map(x=>({...x})),book:{bids:S.book.bids.map(x=>[...x]),asks:S.book.asks.map(x=>[...x])},buyVol:S.buyVol,sellVol:S.sellVol,trades:S.trades,recentTrades:S.recentTrades.map(x=>({...x})),klines:S.klines.map(x=>({...x}))}),selectPair:(sym,scroll=false)=>selectPair(sym,scroll),setBookLevels,setInterval:iv=>{S.interval=String(iv);loadKlines();loadTradingView();return S.interval},reload:()=>{loadKlines();loadTradingView()},format:{price,compact,pct}};
