(()=>{
'use strict';
if(window.RWAExchangeActions)return;
const $=id=>document.getElementById(id);const toast=t=>typeof window.toast==='function'?window.toast(t):console.log(t);
function addFunding(){const p=$('exPreflight');if(!p||$('exTestnetFaucet'))return false;const b=document.createElement('button');b.id='exTestnetFaucet';b.textContent='Get Testnet USDC';b.title='Official Hyperliquid testnet faucet';b.onclick=()=>window.open('https://app.hyperliquid-testnet.xyz/drip','_blank','noopener,noreferrer');p.parentElement?.appendChild(b);return true}
function decorateOrders(){document.querySelectorAll('#exRows .rwa-ex-row').forEach(row=>{const cancel=row.querySelector('[data-ex-cancel]');if(!cancel||row.querySelector('[data-ex-modify]'))return;const m=document.createElement('button');m.dataset.exModify=cancel.dataset.exCancel;m.dataset.coin=cancel.dataset.coin;m.textContent='Modify';m.style.marginRight='3px';cancel.before(m)})}
async function modify(btn){const c=window.RWAExchangeCore,s=window.RWAExchangeCore?.state?.();if(!c)throw Error('Exchange core unavailable');const oid=Number(btn.dataset.exModify),coin=String(btn.dataset.coin||'');const order=(s?.orders||[]).find(o=>Number(o.oid)===oid);if(!order)throw Error('Open order not found');const oldPx=order.limitPx||order.px||'',oldSz=order.sz||order.origSz||'';const price=prompt(`New ${coin} limit price`,String(oldPx));if(price==null)return;const size=prompt(`New ${coin} size`,String(oldSz));if(size==null)return;const p=Number(price),z=Number(size);if(!(p>0)||!(z>0))throw Error('Price and size must be greater than zero');const side=order.side||((order.isBuy||order.b)?'BUY':'SELL');await c.modify({coin,oid,side,price:p,size:z,reduceOnly:!!order.reduceOnly});toast('Order modified');await c.refresh({silent:true})}
document.addEventListener('click',e=>{const b=e.target.closest?.('[data-ex-modify]');if(!b)return;e.preventDefault();e.stopPropagation();modify(b).catch(err=>toast(err.message||'Modify failed'))},true);
const observer=new MutationObserver(()=>{addFunding();decorateOrders()});observer.observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('rwa:exchange-state',()=>{addFunding();decorateOrders()});
window.RWAExchangeActions={modify,decorateOrders,addFunding};let n=0;const t=setInterval(()=>{n++;addFunding();decorateOrders();if($('rwaExchange')||n>100)clearInterval(t)},50);
})();
