(()=>{
'use strict';
if(window.RWAExecutionUI)return;
const $=id=>document.getElementById(id);
const short=a=>a?`${a.slice(0,6)}…${a.slice(-4)}`:'—';
const toast=t=>typeof window.toast==='function'?window.toast(t):console.log(t);
function inject(){const panel=document.querySelector('[data-suite-panel="trade"] .suite-card');if(!panel||$('executionEngine'))return false;const head=panel.querySelector('.suite-card-head');if(!head)return false;head.insertAdjacentHTML('afterend',`<div id="executionEngine" class="execution-engine"><div class="execution-engine-top"><div><small>RWA EXECUTION API</small><b>Wallet master + delegated API wallet</b></div><span id="execApiStatus" class="suite-status">Checking…</span></div><div class="execution-engine-grid"><div><small>MASTER WALLET</small><b id="execMaster">Not logged in</b></div><div><small>API WALLET</small><b id="execAgent">Not authorized</b></div><div><small>EXECUTION MODE</small><b id="execMode">MASTER SIGN</b></div><div><small>VENUE</small><b>HYPERLIQUID</b></div></div><div class="suite-actions execution-engine-actions"><button id="authorizeApiWallet" class="suite-primary">Enable Fast API Wallet</button><button id="revokeApiWallet" class="suite-secondary">Revoke API Wallet</button><button id="approveBuilderFee" class="suite-secondary" style="display:none">Approve RWA Trading Fee</button><button id="refreshExecutionApi">Refresh</button></div><p class="suite-muted">Master wallet is your login. The optional API/agent wallet can sign trading actions after one authorization; it cannot withdraw or transfer funds. Its key is generated client-side and stored encrypted in this browser.</p></div>`);
 const form=panel.querySelector('.suite-form.two');if(form&&!$('execOrderType')){form.insertAdjacentHTML('afterbegin','<div class="suite-field"><label>ORDER TYPE</label><select id="execOrderType"><option value="LIMIT">LIMIT</option><option value="MARKET">MARKET</option></select></div>')}
 if(!document.getElementById('execution-engine-style')){const st=document.createElement('style');st.id='execution-engine-style';st.textContent='.execution-engine{border:1px solid #263141;background:#0b1118;border-radius:12px;padding:11px;margin:8px 0 12px}.execution-engine-top{display:flex;justify-content:space-between;gap:10px;align-items:center}.execution-engine-top small,.execution-engine-grid small{display:block;color:#687685;font-size:6px;letter-spacing:.08em}.execution-engine-top b{font-size:10px}.execution-engine-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:6px;margin-top:9px}.execution-engine-grid>div{padding:8px;border:1px solid #202a36;border-radius:8px;background:#0e151d;min-width:0}.execution-engine-grid b{display:block;font-size:8px;margin-top:3px;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.execution-engine-actions{margin-top:9px;flex-wrap:wrap}@media(max-width:680px){.execution-engine-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.execution-engine-actions button{flex:1 1 45%}}';document.head.appendChild(st)}
 $('execOrderType')?.addEventListener('change',syncOrderType);syncOrderType();return true}
function isTestnet(){return !!$('tradeTestnet')?.checked}
function syncOrderType(){const market=$('execOrderType')?.value==='MARKET',px=$('tradePrice');if(px){px.disabled=market;px.placeholder=market?'Market price determined by venue':'Limit price';if(market)px.value=''}}
async function refresh(){if(!inject())return;const api=window.RWAExecutionAPI;if(!api){$('execApiStatus').textContent='API loading';return}try{const t=isTestnet(),h=await api.health(t),a=api.agent.status(t);$('execMaster').textContent=h.master?short(h.master):'Not logged in';$('execAgent').textContent=a?short(a.address):'Not authorized';$('execMode').textContent=a?'FAST API WALLET':'MASTER SIGN';$('execApiStatus').textContent=h.api==='ok'?'READY':'DEGRADED';$('execApiStatus').className='suite-status '+(h.api==='ok'?'ok':'warn');$('authorizeApiWallet').style.display=a?'none':'inline-flex';$('revokeApiWallet').style.display=a?'inline-flex':'none';const b=h.builder||{};$('approveBuilderFee').style.display=b.enabled?'inline-flex':'none';if(b.enabled)$('approveBuilderFee').textContent=`Approve fee · ${b.maxFeeRate||''}`.trim()}catch(e){$('execApiStatus').textContent='ERROR';$('execApiStatus').className='suite-status bad';console.warn(e)}}
async function authorize(){try{if(!window.RWAWalletAuth?.isLoggedIn?.())throw Error('Login with wallet first');$('execApiStatus').textContent='Wallet approval…';const r=await window.RWAExecutionAPI.agent.authorize(isTestnet());toast(`API wallet authorized ${short(r.address)}`);refresh()}catch(e){toast(e.message||'API wallet approval failed');refresh()}}
async function revoke(){try{$('execApiStatus').textContent='Revoking…';await window.RWAExecutionAPI.agent.revoke(isTestnet());toast('API wallet revoked');refresh()}catch(e){toast(e.message||'Revoke failed');refresh()}}
async function approveBuilder(){try{$('execApiStatus').textContent='Fee approval…';await window.RWAExecutionAPI.builder.approve(isTestnet());toast('RWA builder fee approved');refresh()}catch(e){toast(e.message||'Builder approval failed');refresh()}}
document.addEventListener('click',e=>{if(e.target.closest('#authorizeApiWallet')){e.preventDefault();authorize()}if(e.target.closest('#revokeApiWallet')){e.preventDefault();revoke()}if(e.target.closest('#approveBuilderFee')){e.preventDefault();approveBuilder()}if(e.target.closest('#refreshExecutionApi')){e.preventDefault();refresh()}if(e.target.closest('[data-suite-tab="trade"]'))setTimeout(refresh,30)});
window.addEventListener('rwa:agent-changed',refresh);window.addEventListener('rwa:execution-api-ready',refresh);new MutationObserver(()=>{if(inject())refresh()}).observe(document.documentElement,{childList:true,subtree:true});
window.RWAExecutionUI={refresh};inject();setTimeout(refresh,0);
})();
