(()=>{
'use strict';
if(window.RWALaunchStatus)return;
const $=id=>document.getElementById(id);let state={readiness:null,worker:null,reviewers:0,assets:0,e2e:0,beta:null,error:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#039;'}[m]));
async function json(url){const r=await fetch(url+(url.includes('?')?'&':'?')+'t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(`${url} HTTP ${r.status}`);return r.json()}
function inject(){const panel=document.querySelector('[data-suite-panel="rwa"]');if(!panel||$('rwaLaunchStatus'))return false;const box=document.createElement('section');box.id='rwaLaunchStatus';box.className='suite-card';box.style.marginBottom='10px';box.innerHTML='<div class="suite-card-head"><div><small>PRODUCTION LAUNCH GATE</small><h3>RWA System Readiness</h3></div><span id="rwaLaunchBadge" class="suite-status">CHECKING</span></div><div id="rwaLaunchRows" class="rwa-preflight"></div><div class="suite-actions"><button id="rwaLaunchRefresh" class="suite-secondary">Refresh Launch Gate</button></div>';panel.prepend(box);$('rwaLaunchRefresh').onclick=refresh;render();return true}
function render(){if(!inject())return;const r=state.readiness,b=$('rwaLaunchBadge'),rows=$('rwaLaunchRows');if(!b||!rows)return;if(!r){b.textContent=state.error?'CHECK FAILED':'CHECKING';b.className='suite-status '+(state.error?'bad':'');rows.innerHTML=`<div class="rwa-check bad"><span>Launch state</span><b>${esc(state.error||'Loading…')}</b></div>`;return}b.textContent=r.status||'BLOCKED';b.className='suite-status '+(r.mainnet_ready?'ok':r.engineering_ready?'warn':'bad');const labels={browser_single_write:'Execution Agent',browser_global_mainnet_lock:'Global mainnet lock',worker_single_write:'24/7 single write',worker_idempotency:'24/7 duplicate protection',worker_no_fund_methods:'Worker fund isolation',e2e_verifier_pipeline:'E2E proof verifier',rwa_verifier_pipeline:'RWA verifier pipeline',beta_verifier_pipeline:'Beta proof verifier',security_ci_pipeline:'Security CI',watchdog_pipeline:'Worker watchdog',real_wallet_e2e:'Real-wallet E2E',reviewer_registry:'RWA reviewer',verified_rwa_asset:'Verified RWA asset',worker_configured:'24/7 endpoint',worker_live:'24/7 health',worker_control:'24/7 production control',beta_internal:'Internal beta',beta_closed:'Closed beta',beta_public:'Public beta',mainnet_control:'Mainnet control',revenue_deferred:'Revenue deferred'};rows.innerHTML=Object.entries(r.checks||{}).map(([k,x])=>`<div class="rwa-check ${x.ok?'ok':'bad'}"><span>${esc(labels[k]||k)}</span><b>${x.ok?'PASS':'BLOCKED'} · ${esc(x.detail||'')}</b></div>`).join('')+`<div class="rwa-check ${r.engineering_ready?'ok':'bad'}"><span>ENGINEERING PACKAGE</span><b>${r.engineering_ready?'COMPLETE':'INCOMPLETE'}</b></div><div class="rwa-check ${r.beta_ready?'ok':'bad'}"><span>BETA ENTRY</span><b>${r.beta_ready?'READY':'LOCKED'}</b></div><div class="rwa-check ${r.beta_passed?'ok':'bad'}"><span>BETA PROGRAM</span><b>${r.beta_passed?'PASS':'INCOMPLETE'}</b></div><div class="rwa-check ${r.mainnet_ready?'ok':'bad'}"><span>MAINNET PUBLIC LAUNCH</span><b>${r.mainnet_ready?'READY':'LOCKED'}</b></div>`}
async function refresh(){try{const [r,rv,a,e,beta,wc,ctl]=await Promise.all([json('launch/readiness.json'),json('rwa-reviewers.json'),json('rwa-assets.json'),json('launch/e2e-registry.json'),json('launch/beta-registry.json'),json('agent-worker/public-config.json'),json('agent-worker/control.json')]);state.readiness=r;state.reviewers=(rv.reviewers||[]).length;state.assets=(a.verified||[]).length;state.e2e=(e.wallets||[]).length;state.beta=beta;state.worker={config:wc,control:ctl};state.error='';if(wc.enabled&&/^https:\/\//i.test(String(wc.base_url||'')))try{const [h,ready]=await Promise.all([json(String(wc.base_url).replace(/\/$/,'')+'/healthz'),json(String(wc.base_url).replace(/\/$/,'')+'/readyz')]);state.worker.health=h;state.worker.ready=ready}catch(err){state.worker.health={ok:false,error:String(err.message||err)}}}catch(e){state.error=String(e.message||e)}render();return state}
new MutationObserver(()=>inject()).observe(document.documentElement,{childList:true,subtree:true});window.addEventListener('rwa:wallet-login',refresh);window.RWALaunchStatus={version:'2.1.0',refresh,state:()=>JSON.parse(JSON.stringify(state))};refresh();inject();
})();