(()=>{
'use strict';
if(window.RWAMonitorClient)return;
let last=0;
const jget=(k,d)=>{try{return JSON.parse(localStorage.getItem(k))??d}catch{return d}};
const jset=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const toastSafe=t=>{if(typeof toast==='function')toast(t)};
const wallet=()=>{try{return JSON.parse(localStorage.getItem('rwa_wallet_link_v1')||'null')?.wallet?.toLowerCase()||''}catch{return''}};
const risk=()=>jget(`rwa_risk_v2:${wallet()||'anon'}`,{kill:false});
function importCopy(s){const cfg=jget('rwa_copy_v1',{}),r=risk();if(r.kill){window.RWAAudit?.log?.('copy.24x7.blocked',{reason:'kill-switch'});return 0}const q=jget('rwa_copy_queue_v1',[]),ids=new Set(q.map(x=>String(x.id))),allocation=Math.max(0,Math.min(100,Number(cfg.allocation??10))),maxNotional=Math.max(0,Number(cfg.maxNotional||0));let added=0;for(const f of s.copy_signals||[]){const id=`24x7-${f.event_id||f.tid||f.time}-${f.coin}`;if(ids.has(id))continue;const px=Number(f.px),sourceSize=Number(f.sz),raw=sourceSize*(allocation/100),cap=maxNotional>0&&px>0?maxNotional/px:Infinity,size=Math.min(raw,cap);if(!(size>0))continue;q.unshift({id,coin:f.coin,side:f.side,px,sourceSize,size,time:f.time,target:f.target,source:'24x7-monitor'});ids.add(id);added++;window.RWAAudit?.log?.('copy.signal.24x7',{id,coin:f.coin,side:f.side,sourceSize,size,allocation,maxNotional,target:f.target})}if(added)jset('rwa_copy_queue_v1',q.slice(0,100));return added}
function importAlerts(s){const seen=jget('rwa_24x7_alert_seen_v2',[]),set=new Set(seen),fresh=[];for(const a of s.alerts||[]){const id=String(a.event_id||`${a.id}-${a.triggered_at}`);if(set.has(id))continue;set.add(id);fresh.push(a);toastSafe(`24/7 alert: ${a.symbol} ${String(a.type||'').replaceAll('_',' ')}`);window.RWAAudit?.log?.('alert.24x7',{eventId:id,symbol:a.symbol,type:a.type,threshold:a.threshold,price:a.price,provider:a.provider})}jset('rwa_24x7_alert_seen_v2',[...set].slice(-300));return fresh.length}
async function sync(){try{const r=await fetch(`monitor/status.json?t=${Date.now()}`,{cache:'no-store'});if(!r.ok)return;const s=await r.json();window.RWA24x7Status=s;if(Number(s.updated_at)>last){last=Number(s.updated_at);const copies=importCopy(s),alerts=importAlerts(s);if(copies)toastSafe(`${copies} new 24/7 copy signal${copies>1?'s':''} ready for review`)}const box=document.getElementById('providerRows');if(box&&document.querySelector('[data-ops-panel="system"].active')){let e=document.getElementById('scheduledMonitorRow');if(!e){e=document.createElement('div');e.id='scheduledMonitorRow';e.className='ops-row';box.appendChild(e)}const age=s.updated_at?Math.max(0,Math.round((Date.now()-Number(s.updated_at))/60000)):null,ok=age!=null&&age<15;e.innerHTML=`<div><b>GitHub 24/7 monitor</b><small>${s.market_data_provider||'provider auto'}</small></div><span class="${ok?'up':'down'}">${age==null?'WAITING':age+'m ago'}</span>`}}catch(e){window.RWAAudit?.log?.('monitor.sync.error',{message:String(e.message||e)})}}
setInterval(sync,60000);sync();window.RWAMonitorClient={sync,status:()=>window.RWA24x7Status||null};
})();