(()=>{
'use strict';
if(window.RWAOps)return;
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const LS={risk:'rwa_risk_v2',audit:'rwa_audit_v2',verify:'rwa_verify_v1',mute:'rwa_social_mute_v1',report:'rwa_social_report_v1',wc:'rwa_wc_project_v1'};
const toast=t=>typeof window.toast==='function'?window.toast(t):console.log(t);
const session=()=>{try{return JSON.parse(localStorage.getItem('rwa_wallet_link_v1')||'null')}catch{return null}};
const wallet=()=>session()?.wallet?.toLowerCase()||'';
const key=k=>`${k}:${wallet()||'anon'}`;
const get=(k,d)=>{try{return JSON.parse(localStorage.getItem(key(k))||'null')??d}catch{return d}};
const set=(k,v)=>localStorage.setItem(key(k),JSON.stringify(v));
const money=n=>Number.isFinite(Number(n))?'$'+Number(n).toLocaleString(undefined,{maximumFractionDigits:2}):'—';
const pct=n=>Number.isFinite(Number(n))?(Number(n)>=0?'+':'')+Number(n).toFixed(2)+'%':'—';
function log(type,details={}){const a=get(LS.audit,[]);a.unshift({ts:Date.now(),type,wallet:wallet(),details});set(LS.audit,a.slice(0,1000));renderAudit()}
window.RWAAudit={log,export:()=>new Blob([JSON.stringify(get(LS.audit,[]),null,2)],{type:'application/json'})};
function inject(){
 const tabs=document.querySelector('.suite-tabs'), body=document.querySelector('.suite-body'); if(!tabs||!body||$('opsOrders'))return;
 for(const [id,label] of [['orders','Orders'],['risk','Risk'],['audit','Audit'],['verify','Verify'],['safety','Safety'],['system','System']]){const b=document.createElement('button');b.dataset.opsTab=id;b.textContent=label;tabs.appendChild(b)}
 body.insertAdjacentHTML('beforeend',`
 <section class="suite-panel" data-ops-panel="orders"><div class="suite-grid"><div class="suite-card span-12" id="opsOrders"><div class="suite-card-head"><div><small>WALLET-SIGNED</small><h3>Order management</h3></div><div><label class="checkline"><input id="opsTestnet" type="checkbox"> Testnet</label><button id="refreshOrders">Refresh</button></div></div><div class="ops-kpis"><div><small>OPEN</small><b id="opsOpenCount">—</b></div><div><small>HISTORY</small><b id="opsHistCount">—</b></div><div><small>ENV</small><b id="opsEnv">MAINNET</b></div></div><div id="openOrderRows" class="ops-list"><div class="suite-empty">Connect wallet, then refresh.</div></div><div class="suite-card-head"><div><small>POSITION PROTECTION</small><h3>TP / SL trigger orders</h3></div></div><div class="suite-form two"><div class="suite-field"><label>COIN</label><input id="protectCoin" placeholder="BTC"></div><div class="suite-field"><label>POSITION SIZE</label><input id="protectSize" type="number" step="any"></div><div class="suite-field"><label>TP TRIGGER</label><input id="protectTp" type="number" step="any"></div><div class="suite-field"><label>SL TRIGGER</label><input id="protectSl" type="number" step="any"></div></div><div class="suite-actions"><button id="loadPositionProtect">Load position</button><button class="suite-primary" id="submitProtection">Sign TP/SL</button></div><div class="suite-card-head"><div><small>RECENT</small><h3>Order history</h3></div></div><div id="historyOrderRows" class="ops-list"></div></div></div></section>
 <section class="suite-panel" data-ops-panel="risk"><div class="suite-grid"><div class="suite-card span-6"><div class="suite-card-head"><div><small>GLOBAL GUARD</small><h3>Risk engine</h3></div><span id="riskState" class="suite-status">ACTIVE</span></div><div class="suite-form two"><div class="suite-field"><label>DAILY MAX LOSS USD</label><input id="riskDaily" type="number" value="250"></div><div class="suite-field"><label>MAX LEVERAGE</label><input id="riskLev" type="number" value="5"></div><div class="suite-field"><label>TOTAL EXPOSURE USD</label><input id="riskExposure" type="number" value="5000"></div><div class="suite-field"><label>PER-ASSET USD</label><input id="riskAsset" type="number" value="2000"></div></div><label class="checkline"><input id="riskKill" type="checkbox"> Emergency KILL SWITCH — block every new order and copy signal</label><div class="suite-actions"><button class="suite-primary" id="saveRisk">Save risk limits</button><button id="cancelAll">Kill + cancel open orders</button></div></div><div class="suite-card span-6"><div class="suite-card-head"><div><small>LIVE ACCOUNT</small><h3>Risk monitor</h3></div><button id="refreshRisk">Refresh</button></div><div class="ops-kpis"><div><small>DAY P&L</small><b id="riskDayPnl">—</b></div><div><small>EXPOSURE</small><b id="riskLiveExp">—</b></div><div><small>MAX LEV</small><b id="riskLiveLev">—</b></div><div><small>POSITIONS</small><b id="riskPos">—</b></div></div><div id="riskMessage" class="suite-muted">Risk checks run before wallet signing.</div></div></div></section>
 <section class="suite-panel" data-ops-panel="audit"><div class="suite-card span-12"><div class="suite-card-head"><div><small>WALLET-SCOPED</small><h3>Activity & audit log</h3></div><div><button id="exportAudit">Export JSON</button><button id="clearAudit">Clear</button></div></div><div id="auditRows" class="ops-list"></div></div></section>
 <section class="suite-panel" data-ops-panel="verify"><div class="suite-grid"><div class="suite-card span-6"><div class="suite-card-head"><div><small>LEGAL GATE</small><h3>RWA verification</h3></div><span id="verifyStatus" class="suite-status">DRAFT</span></div><div class="suite-form"><div class="suite-field"><label>ASSET / DRAFT ID</label><input id="verifyAsset" placeholder="Asset name or ID"></div><div class="suite-field"><label>ISSUER / SPV</label><input id="verifyIssuer"></div><div class="suite-field"><label>OWNERSHIP EVIDENCE URL</label><input id="verifyOwnership"></div><div class="suite-field"><label>APPRAISAL / NAV URL</label><input id="verifyAppraisal"></div><div class="suite-field"><label>LEGAL DOCUMENT URL</label><input id="verifyLegal"></div></div><div class="verify-checks"><label><input type="checkbox" data-vcheck="issuer"> Issuer/SPV verified</label><label><input type="checkbox" data-vcheck="ownership"> Ownership verified</label><label><input type="checkbox" data-vcheck="appraisal"> Independent NAV/appraisal</label><label><input type="checkbox" data-vcheck="legal"> Legal documents reviewed</label><label><input type="checkbox" data-vcheck="kyb"> KYB/AML complete</label><label><input type="checkbox" data-vcheck="disclosure"> Risk disclosure complete</label></div><div class="suite-actions"><button class="suite-primary" id="saveVerification">Save verification package</button></div><p class="suite-muted">Completing this checklist does not self-approve an asset. Public VERIFIED status still requires an authorized reviewer and registry publication.</p></div><div class="suite-card span-6"><div class="suite-card-head"><div><small>NAV HISTORY</small><h3>Valuation ledger</h3></div></div><div class="suite-form two"><div class="suite-field"><label>DATE</label><input id="navDate" type="date"></div><div class="suite-field"><label>NAV USD</label><input id="navValue" type="number"></div></div><div class="suite-actions"><button id="addNavHistory">Add NAV</button></div><div id="navHistoryRows" class="ops-list"></div></div></div></section>
 <section class="suite-panel" data-ops-panel="safety"><div class="suite-grid"><div class="suite-card span-6"><div class="suite-card-head"><div><small>SOCIAL SAFETY</small><h3>Mute & block</h3></div></div><div class="suite-form"><div class="suite-field"><label>PUBKEY / WALLET / KEYWORD</label><input id="muteValue" placeholder="pubkey, 0x wallet, or keyword"></div></div><div class="suite-actions"><button id="addMute">Mute</button></div><div id="muteRows" class="ops-list"></div></div><div class="suite-card span-6"><div class="suite-card-head"><div><small>REPORTS</small><h3>Moderation queue</h3></div></div><div class="suite-form"><div class="suite-field"><label>EVENT / USER</label><input id="reportTarget"></div><div class="suite-field"><label>REASON</label><select id="reportReason"><option>spam</option><option>impersonation</option><option>scam</option><option>harassment</option><option>illegal</option></select></div></div><div class="suite-actions"><button id="addReport">Report</button></div><div id="reportRows" class="ops-list"></div></div></div></section>
 <section class="suite-panel" data-ops-panel="system"><div class="suite-grid"><div class="suite-card span-6"><div class="suite-card-head"><div><small>MOBILE WALLET</small><h3>WalletConnect / Reown</h3></div></div><div class="suite-field"><label>FREE REOWN PROJECT ID</label><input id="wcProjectId" placeholder="Paste public Project ID"></div><div class="suite-actions"><button id="saveWcProject">Save</button><button id="openWalletConnect">Connect mobile wallet</button></div><p class="suite-muted">Reown requires a free public Project ID. It is not a secret and is stored only in this browser.</p></div><div class="suite-card span-6"><div class="suite-card-head"><div><small>PROVIDERS</small><h3>Failover & 24/7 monitor</h3></div><button id="refreshProviders">Refresh</button></div><div id="providerRows" class="ops-list"></div><div class="ops-kpis"><div><small>24/7 MODE</small><b>MONITOR + QUEUE</b></div><div><small>AUTO EXECUTION</small><b>WALLET SIGN ONLY</b></div></div><p class="suite-muted">GitHub Actions can monitor public conditions for free on a schedule. It never stores a trading private key; queued copy signals require your signature when you return.</p></div></div></section>`);
}
function activate(tab){document.querySelectorAll('.suite-panel').forEach(p=>p.classList.remove('active'));document.querySelectorAll('[data-suite-tab],[data-ops-tab]').forEach(b=>b.classList.remove('active'));const p=document.querySelector(`[data-ops-panel="${tab}"]`),b=document.querySelector(`[data-ops-tab="${tab}"]`);if(p)p.classList.add('active');if(b)b.classList.add('active'); if(tab==='orders')refreshOrders(); if(tab==='risk')refreshRisk(); if(tab==='audit')renderAudit(); if(tab==='verify')renderVerify(); if(tab==='safety')renderSafety(); if(tab==='system')renderSystem()}
async function hl(type,data={},testnet=false){const u=testnet?'https://api.hyperliquid-testnet.xyz/info':'https://api.hyperliquid.xyz/info';const r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,...data})});if(!r.ok)throw Error(`Hyperliquid ${r.status}`);return r.json()}
function api(){if(!window.RWAExecutionAPI)throw Error('RWA Execution API is loading');return window.RWAExecutionAPI}
async function refreshOrders(){const w=wallet(),t=!!$('opsTestnet')?.checked;if(!w)return;try{const [open,hist]=await Promise.all([hl('frontendOpenOrders',{user:w},t),hl('historicalOrders',{user:w},t)]);$('opsOpenCount').textContent=open.length;$('opsHistCount').textContent=hist.length;$('opsEnv').textContent=t?'TESTNET':'MAINNET';$('openOrderRows').innerHTML=open.length?open.map(o=>`<div class="ops-row"><div><b>${esc(o.coin)} ${o.side==='B'?'BUY':'SELL'}</b><small>#${o.oid} · ${esc(o.orderType||'Order')} ${o.isTrigger?'· trigger':''}</small></div><div><b>${money(o.limitPx)}</b><small>${esc(o.sz)} / ${esc(o.origSz)}</small></div><div class="ops-actions"><button data-cancel-oid="${o.oid}" data-coin="${esc(o.coin)}">Cancel</button><button data-modify-oid="${o.oid}" data-coin="${esc(o.coin)}" data-side="${o.side}" data-size="${esc(o.sz)}">Modify</button></div></div>`).join(''):'<div class="suite-empty">No open orders.</div>';$('historyOrderRows').innerHTML=(hist||[]).slice(0,30).map(x=>{const o=x.order||x;return`<div class="ops-row"><div><b>${esc(o.coin||'—')} ${o.side==='B'?'BUY':'SELL'}</b><small>${new Date(o.timestamp||x.timestamp||Date.now()).toLocaleString()}</small></div><div><b>${money(o.limitPx||o.px)}</b><small>${esc(x.status||o.status||'historical')}</small></div></div>`}).join('');log('orders.refresh',{testnet:t,open:open.length})}catch(e){toast(e.message)}}
async function cancelOrder(btn){const t=!!$('opsTestnet')?.checked;await api().orders.cancel({coin:btn.dataset.coin,oid:btn.dataset.cancelOid,testnet:t,preferAgent:true});log('order.cancel',{coin:btn.dataset.coin,oid:btn.dataset.cancelOid,testnet:t,path:'RWAExecutionAPI'});toast('Order canceled');refreshOrders()}
async function modifyOrder(btn){const t=!!$('opsTestnet')?.checked,price=prompt('New limit price');if(!price)return;const size=prompt('New size',btn.dataset.size);if(!size)return;await api().orders.modify({coin:btn.dataset.coin,oid:btn.dataset.modifyOid,side:btn.dataset.side,price:Number(price),size:Number(size),testnet:t,preferAgent:true});log('order.modify',{coin:btn.dataset.coin,oid:btn.dataset.modifyOid,price,size,testnet:t,path:'RWAExecutionAPI'});toast('Order modified');refreshOrders()}
async function loadPosition(){const w=wallet(),t=!!$('opsTestnet')?.checked;if(!w)return;const ch=await hl('clearinghouseState',{user:w},t),p=(ch.assetPositions||[]).map(x=>x.position||x).find(x=>Number(x.szi)!==0);if(!p)return toast('No open position');$('protectCoin').value=p.coin;$('protectSize').value=Math.abs(Number(p.szi));toast(`Loaded ${p.coin} position`)}
async function protect(){const t=!!$('opsTestnet')?.checked,coin=$('protectCoin').value.trim().toUpperCase(),requestedSize=Math.abs(Number($('protectSize').value)),tp=Number($('protectTp').value),sl=Number($('protectSl').value);if(!coin||!(requestedSize>0)||(!tp&&!sl))throw Error('Enter coin, size and TP or SL');const ch=await api().account.state(t),pos=(ch.assetPositions||[]).map(x=>x.position||x).find(x=>x.coin===coin&&Number(x.szi)!==0);if(!pos)throw Error('Position not found');const signed=Number(pos.szi),side=signed>0?'SELL':'BUY',size=Math.min(requestedSize,Math.abs(signed)),out=[];if(tp>0)out.push(await api().orders.trigger({coin,side,size,triggerPx:tp,tpsl:'tp',testnet:t,preferAgent:true}));if(sl>0)out.push(await api().orders.trigger({coin,side,size,triggerPx:sl,tpsl:'sl',testnet:t,preferAgent:true}));log('order.protection',{coin,size,tp,sl,testnet:t,path:'RWAExecutionAPI'});toast(`TP/SL submitted · ${out.length} trigger order(s)`);refreshOrders()}
function riskCfg(){return get(LS.risk,{dailyLoss:250,maxLeverage:5,maxExposure:5000,perAsset:2000,kill:false})}
function renderRiskCfg(){const r=riskCfg();for(const [id,v] of [['riskDaily',r.dailyLoss],['riskLev',r.maxLeverage],['riskExposure',r.maxExposure],['riskAsset',r.perAsset]])if($(id))$(id).value=v;if($('riskKill'))$('riskKill').checked=!!r.kill;if($('riskState')){$('riskState').textContent=r.kill?'KILLED':'ACTIVE';$('riskState').className='suite-status '+(r.kill?'bad':'ok')}}
async function refreshRisk(){renderRiskCfg();const w=wallet(),t=!!$('opsTestnet')?.checked;if(!w)return;try{const [ch,pf]=await Promise.all([hl('clearinghouseState',{user:w},t),hl('portfolio',{user:w},t)]),pos=(ch.assetPositions||[]).map(x=>x.position||x),exp=pos.reduce((s,p)=>s+Math.abs(Number(p.positionValue||0)),0),lev=Math.max(0,...pos.map(p=>Number(p.leverage?.value||p.leverage||0))),day=(pf||[]).find(x=>x[0]==='day')?.[1],pnl=Number(day?.pnlHistory?.at(-1)?.[1]||0);$('riskDayPnl').textContent=money(pnl);$('riskLiveExp').textContent=money(exp);$('riskLiveLev').textContent=lev.toFixed(1)+'x';$('riskPos').textContent=pos.length;$('riskMessage').textContent=(riskCfg().kill?'KILL SWITCH active — all new orders blocked.':'Pre-signature risk guard active.')+` · ${t?'TESTNET':'MAINNET'}`;window.__rwaRiskLive={pnl,exp,lev,pos,testnet:t}}catch(e){$('riskMessage').textContent=e.message}}
function saveRisk(){const r={dailyLoss:Math.abs(Number($('riskDaily').value||0)),maxLeverage:Number($('riskLev').value||0),maxExposure:Number($('riskExposure').value||0),perAsset:Number($('riskAsset').value||0),kill:!!$('riskKill').checked};set(LS.risk,r);try{const c=JSON.parse(localStorage.getItem('rwa_copy_v1')||'{}');if(r.kill){c.enabled=false;localStorage.setItem('rwa_copy_v1',JSON.stringify(c))}}catch{};log('risk.update',r);renderRiskCfg();toast('Risk limits saved')}
async function checkRisk({coin,price,size,leverage=1,reduceOnly=false}){const r=riskCfg();if(r.kill)throw Error('KILL SWITCH is active');const live=window.__rwaRiskLive||{};if(r.dailyLoss>0&&Number(live.pnl)<-r.dailyLoss)throw Error('Daily max loss reached');if(r.maxLeverage>0&&Number(leverage)>r.maxLeverage)throw Error(`Max leverage ${r.maxLeverage}x exceeded`);if(!reduceOnly){const notional=Math.abs(Number(price)*Number(size));if(r.perAsset>0&&notional>r.perAsset)throw Error(`Per-asset limit exceeded (${money(r.perAsset)})`);if(r.maxExposure>0&&Number(live.exp||0)+notional>r.maxExposure)throw Error(`Total exposure limit exceeded (${money(r.maxExposure)})`)}return true}
window.RWARisk={check:checkRisk,cfg:riskCfg,refresh:refreshRisk};
async function cancelAll(){const t=!!$('opsTestnet')?.checked;if(!confirm(`Activate KILL SWITCH and cancel every open ${t?'TESTNET':'MAINNET'} order?`))return;const r=riskCfg();r.kill=true;set(LS.risk,r);renderRiskCfg();const out=await api().orders.cancelAll({testnet:t,preferAgent:true});log('risk.kill',{cancelled:out.length,testnet:t,path:'RWAExecutionAPI'});toast(`Kill switch active; ${out.length} open order(s) canceled`);refreshOrders()}
function renderAudit(){const box=$('auditRows');if(!box)return;const a=get(LS.audit,[]);box.innerHTML=a.length?a.slice(0,100).map(x=>`<div class="ops-row"><div><b>${esc(x.type)}</b><small>${new Date(x.ts).toLocaleString()}</small></div><code>${esc(JSON.stringify(x.details))}</code></div>`).join(''):'<div class="suite-empty">No wallet-scoped activity yet.</div>'}
function exportAudit(){const blob=new Blob([JSON.stringify(get(LS.audit,[]),null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rwa-audit-${wallet()||'anon'}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),500);log('audit.export')}
function verifyPkg(){return get(LS.verify,{asset:'',issuer:'',ownership:'',appraisal:'',legal:'',checks:{},nav:[]})}
function renderVerify(){const v=verifyPkg();for(const [id,k] of [['verifyAsset','asset'],['verifyIssuer','issuer'],['verifyOwnership','ownership'],['verifyAppraisal','appraisal'],['verifyLegal','legal']])if($(id))$(id).value=v[k]||'';document.querySelectorAll('[data-vcheck]').forEach(c=>c.checked=!!v.checks?.[c.dataset.vcheck]);const n=Object.values(v.checks||{}).filter(Boolean).length;if($('verifyStatus')){$('verifyStatus').textContent=n===6?'READY FOR REVIEW':`${n}/6 CHECKS`;$('verifyStatus').className='suite-status '+(n===6?'ok':'warn')}$('navHistoryRows').innerHTML=(v.nav||[]).map(x=>`<div class="ops-row"><div><b>${esc(x.date)}</b><small>NAV snapshot</small></div><b>${money(x.value)}</b></div>`).join('')}
function saveVerify(){const checks={};document.querySelectorAll('[data-vcheck]').forEach(c=>checks[c.dataset.vcheck]=c.checked);const old=verifyPkg(),v={asset:$('verifyAsset').value.trim(),issuer:$('verifyIssuer').value.trim(),ownership:$('verifyOwnership').value.trim(),appraisal:$('verifyAppraisal').value.trim(),legal:$('verifyLegal').value.trim(),checks,nav:old.nav||[]};set(LS.verify,v);log('rwa.verification.update',{asset:v.asset,checks});renderVerify();toast('Verification package saved')}
function addNav(){const v=verifyPkg(),date=$('navDate').value,value=Number($('navValue').value);if(!date||!Number.isFinite(value))return;v.nav=v.nav||[];v.nav.unshift({date,value,ts:Date.now()});set(LS.verify,v);log('rwa.nav',{date,value});renderVerify()}
function renderSafety(){const m=get(LS.mute,[]),r=get(LS.report,[]);$('muteRows').innerHTML=m.map(x=>`<div class="ops-row"><b>${esc(x)}</b><button data-unmute="${esc(x)}">×</button></div>`).join('')||'<div class="suite-empty">Nothing muted.</div>';$('reportRows').innerHTML=r.map(x=>`<div class="ops-row"><div><b>${esc(x.target)}</b><small>${esc(x.reason)} · ${new Date(x.ts).toLocaleString()}</small></div></div>`).join('')||'<div class="suite-empty">No reports.</div>'}
function addMute(){const v=$('muteValue').value.trim().toLowerCase();if(!v)return;const m=get(LS.mute,[]);if(!m.includes(v))m.unshift(v);set(LS.mute,m.slice(0,200));log('social.mute',{value:v});$('muteValue').value='';renderSafety();applySocialSafety()}
function addReport(){const target=$('reportTarget').value.trim(),reason=$('reportReason').value;if(!target)return;const r=get(LS.report,[]);r.unshift({target,reason,ts:Date.now()});set(LS.report,r.slice(0,200));log('social.report',{target,reason});$('reportTarget').value='';renderSafety()}
function applySocialSafety(){const m=get(LS.mute,[]);document.querySelectorAll('.network-post,.social-post').forEach(p=>{const txt=(p.textContent||'').toLowerCase();p.style.display=m.some(x=>txt.includes(x))?'none':''})}
function renderSystem(){if($('wcProjectId'))$('wcProjectId').value=localStorage.getItem(LS.wc)||'';renderProviders()}
async function renderProviders(){const box=$('providerRows');if(!box)return;box.innerHTML='<div class="suite-empty">Checking providers…</div>';const rows=[];for(const [name,url,body] of [['Hyperliquid','https://api.hyperliquid.xyz/info',{type:'allMids'}],['Binance Vision','https://data-api.binance.vision/api/v3/time',null],['Binance','https://api.binance.com/api/v3/time',null]]){const t=performance.now();try{const r=await fetch(url,body?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{});rows.push({name,ok:r.ok,ms:Math.round(performance.now()-t)})}catch{rows.push({name,ok:false,ms:0})}}box.innerHTML=rows.map(x=>`<div class="ops-row"><b>${esc(x.name)}</b><span class="${x.ok?'up':'down'}">${x.ok?'ONLINE '+x.ms+'ms':'OFFLINE'}</span></div>`).join('');window.RWAProviderHealth=rows}
function saveWc(){localStorage.setItem(LS.wc,$('wcProjectId').value.trim());log('walletconnect.config',{configured:!!$('wcProjectId').value.trim()});toast('WalletConnect Project ID saved')}
async function openWc(){const id=localStorage.getItem(LS.wc)||'';if(!id)return toast('Add your free Reown Project ID first');if(!window.RWAWalletConnect)throw Error('WalletConnect module is loading');await window.RWAWalletConnect.connect(id)}
document.addEventListener('click',async e=>{try{const t=e.target.closest('[data-ops-tab]');if(t){e.preventDefault();activate(t.dataset.opsTab);return}if(e.target.closest('#refreshOrders'))return refreshOrders();const c=e.target.closest('[data-cancel-oid]');if(c)return cancelOrder(c);const m=e.target.closest('[data-modify-oid]');if(m)return modifyOrder(m);if(e.target.closest('#loadPositionProtect'))return loadPosition();if(e.target.closest('#submitProtection'))return protect();if(e.target.closest('#saveRisk'))return saveRisk();if(e.target.closest('#refreshRisk'))return refreshRisk();if(e.target.closest('#cancelAll'))return cancelAll();if(e.target.closest('#exportAudit'))return exportAudit();if(e.target.closest('#clearAudit')){set(LS.audit,[]);return renderAudit()}if(e.target.closest('#saveVerification'))return saveVerify();if(e.target.closest('#addNavHistory'))return addNav();if(e.target.closest('#addMute'))return addMute();const u=e.target.closest('[data-unmute]');if(u){set(LS.mute,get(LS.mute,[]).filter(x=>x!==u.dataset.unmute));return renderSafety()}if(e.target.closest('#addReport'))return addReport();if(e.target.closest('#saveWcProject'))return saveWc();if(e.target.closest('#openWalletConnect'))return openWc();if(e.target.closest('#refreshProviders'))return renderProviders()}catch(err){log('error',{message:err.message});toast(err.message||'Action failed')}},true);
const obs=new MutationObserver(applySocialSafety);obs.observe(document.body,{childList:true,subtree:true});
inject();renderRiskCfg();setInterval(()=>{if(wallet())refreshRisk().catch(()=>{})},15000);window.RWAOps={activate,log,refreshOrders,refreshRisk};
})();
