(()=>{
'use strict';
if(window.RWAProductOS)return;
const $=id=>document.getElementById(id),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const isTrade=/\/trade\/?$/.test(location.pathname),rootUrl=isTrade?'../':'./';
const toastSafe=t=>typeof window.toast==='function'?window.toast(t):console.log(t);
const selectedBase=()=>{try{const t=$('selName')?.textContent||$('marketName')?.textContent||'BTC';return t.split(/[\s\/-]/)[0].toUpperCase()}catch{return'BTC'}};
function openSuite(tab){if(isTrade){location.href=`../#${tab}`;return}if(window.RWASuite?.open)return RWASuite.open(tab);window.RWAQuickActions?.loadSuite?.().then(s=>s?.open?.(tab)).catch(e=>toastSafe(e.message||'Workspace unavailable'))}
function hideModes(){document.body.classList.remove('rwa-home-open','social-open','market-drawer-open','suite-open');const suite=$('suite');if(suite&&innerWidth<=680)suite.style.display='none'}
function openMarkets(){if(isTrade){location.href='../#markets';return}hideModes();document.body.classList.remove('rwa-home-open');$('terminal')?.scrollIntoView({behavior:'auto',block:'start'});setActive('markets')}
function openHome(){if(isTrade){location.href='../#home';return}hideModes();document.body.classList.add('rwa-home-open');renderHome();scrollTo({top:0,behavior:'auto'});setActive('home')}
function openSocial(){if(isTrade){location.href='../#social';return}hideModes();openSuite('feed');setActive('social')}
function openTrade(base=selectedBase()){location.href=`${rootUrl}trade/?coin=${encodeURIComponent(base||'BTC')}`}
function openAsset(base=selectedBase()){location.href=`${rootUrl}asset/?symbol=${encodeURIComponent(base||'BTC')}`}
function openTrader(wallet){location.href=`${rootUrl}trader/?wallet=${encodeURIComponent(wallet||'')}`}
function setActive(name){qa('[data-rwa-route]').forEach(x=>x.classList.toggle('active',x.dataset.rwaRoute===name));qa('[data-mobile-nav]').forEach(x=>x.classList.toggle('active',x.dataset.mobileNav===name))}
function normalizeDesktopNav(){
  if(isTrade){const n=document.querySelector('.product-nav');if(n)n.innerHTML=`<a href="../#home">Home</a><a href="../#markets">Markets</a><a class="active" href="./">Trade</a><a href="../#social">Social</a><a href="../#rwa">RWA Assets</a><a href="../#intel">Intelligence</a><a href="../backtest/">Backtest</a><a href="../renko/">Renko</a>`;return}
  const n=document.querySelector('.topnav');if(!n)return;n.innerHTML=`<button data-rwa-route="home">Home</button><button data-rwa-route="markets">Markets</button><button data-rwa-route="trade">Trade</button><button data-rwa-route="social">Social</button><button data-rwa-route="rwa">RWA Assets</button><button data-rwa-route="intel">Intelligence</button>`;
}
function normalizeMobileNav(){if(isTrade)return;const nav=document.querySelector('.mobile-tabs');if(!nav)return;nav.innerHTML=`<a href="#home" data-mobile-nav="home"><span>⌂</span><small>Home</small></a><a href="#markets" data-mobile-nav="markets"><span>⌕</span><small>Markets</small></a><a href="trade/" data-mobile-nav="trade"><span>↗</span><small>Trade</small></a><a href="#social" data-mobile-nav="social"><span>◎</span><small>Social</small></a><a href="#portfolio" data-mobile-nav="portfolio"><span>▣</span><small>Portfolio</small></a>`}
function installCommandButton(){const host=document.querySelector('.top-actions');if(!host||host.querySelector('.rwa-command-button'))return;const b=document.createElement('button');b.type='button';b.className='rwa-command-button';b.innerHTML='<span>⌕</span><span class="label">Search / Command</span><kbd>⌘K</kbd>';b.onclick=()=>openCommand();host.insertBefore(b,host.querySelector('.signin,.status-pill,.button.primary')||host.lastElementChild)}
function installCommandLayer(){if($('rwaCommandLayer'))return;const layer=document.createElement('div');layer.id='rwaCommandLayer';layer.className='rwa-command-layer';layer.hidden=true;layer.innerHTML=`<section class="rwa-command-card" role="dialog" aria-modal="true" aria-label="RWA command center"><div class="rwa-command-head"><span>⌕</span><input id="rwaCommandInput" autocomplete="off" placeholder="BTC, trader wallet, portfolio, backtest GOLD, trade ETH…"><button class="rwa-command-close" type="button" aria-label="Close">×</button></div><div class="rwa-command-help">Search markets and traders or use natural commands. Execution commands only open the protected trade flow; they never bypass wallet approval, Risk Engine checks or the mainnet gate.</div><div id="rwaCommandResults" class="rwa-command-results"></div></section>`;document.body.appendChild(layer);layer.addEventListener('click',e=>{if(e.target===layer||e.target.closest('.rwa-command-close'))closeCommand()});$('rwaCommandInput').addEventListener('input',renderCommand);$('rwaCommandInput').addEventListener('keydown',e=>{if(e.key==='Enter')$('rwaCommandResults')?.querySelector('.rwa-command-item')?.click();if(e.key==='Escape')closeCommand()})}
function openCommand(seed=''){installCommandLayer();const l=$('rwaCommandLayer');l.hidden=false;const i=$('rwaCommandInput');i.value=seed;renderCommand();setTimeout(()=>i.focus(),20)}function closeCommand(){const l=$('rwaCommandLayer');if(l)l.hidden=true}
function marketCandidates(q){if(isTrade)return[];try{return (S?.pairs||[]).filter(x=>!q||x.symbol.includes(q)||x.base.includes(q)).slice(0,8).map(x=>({title:`${x.base} / USDT`,desc:`${x.rwa?'RWA-linked · ':''}Live market`,tag:'MARKET',run:()=>{closeCommand();selectPair?.(x.symbol,false);openMarkets()}}))}catch{return[]}}
function commandCandidates(raw){const text=String(raw||'').trim(),q=text.toUpperCase(),out=[];const wallet=(text.match(/0x[a-fA-F0-9]{40}/)||[])[0];if(wallet)out.push({title:'Open verified trader profile',desc:wallet,tag:'TRADER',run:()=>openTrader(wallet)});
  const symbol=(q.match(/\b[A-Z0-9]{2,12}\b/g)||[]).find(x=>!['TRADE','BACKTEST','RENKO','ASSET','MARKET','OPEN','SHOW','COPY','PORTFOLIO','SOCIAL','HOME','INTELLIGENCE','RWA','LEADERBOARD','DEFAULT','TERMINAL'].includes(x));
  if(/DEFAULT HOME/.test(q))out.push({title:'Set Home as default',desc:'Open Home on future visits',tag:'SETTING',run:()=>{localStorage.setItem('rwa_default_landing_v3','home');closeCommand();openHome();toastSafe('Default landing set to Home')}});
  if(/DEFAULT TERMINAL|DEFAULT MARKET/.test(q))out.push({title:'Set Markets as default',desc:'Open the live terminal on future visits',tag:'SETTING',run:()=>{localStorage.setItem('rwa_default_landing_v3','markets');closeCommand();openMarkets();toastSafe('Default landing set to Markets')}});
  if(/\bHOME\b/.test(q))out.push({title:'Open Home',desc:'Portfolio, trends and quick actions',tag:'HOME',run:openHome});
  if(/MARKET/.test(q))out.push({title:'Open Markets',desc:'Live market terminal',tag:'MARKETS',run:openMarkets});
  if(/LEADERBOARD|TOP TRADER/.test(q))out.push({title:'Open Trader Leaderboard',desc:'Signed identities + venue performance',tag:'TRADERS',run:()=>openSuite('leaderboard')});
  if(/\bCOPY\b/.test(q)&&!wallet)out.push({title:'Open Copy Trading',desc:'Non-custodial copy controls and max-loss',tag:'COPY',run:()=>openSuite('copy')});
  if(/PORTFOLIO|PNL|POSITION/.test(q))out.push({title:'Open Portfolio',desc:'Verified Hyperliquid account data',tag:'PORTFOLIO',run:()=>openSuite('portfolio')});
  if(/SOCIAL|FEED|THESIS/.test(q))out.push({title:'Open Social',desc:'Trader feed and signed profiles',tag:'SOCIAL',run:openSocial});
  if(/INTEL|INTELLIGENCE/.test(q))out.push({title:'Open Intelligence',desc:'Breadth, momentum and flow',tag:'INTEL',run:()=>openSuite('intel')});
  if(/RWA|ASSET/.test(q))out.push({title:'Open RWA Assets',desc:'Verified assets and onboarding',tag:'RWA',run:()=>openSuite('rwa')});
  if(/BACKTEST/.test(q))out.push({title:`Backtest ${symbol||selectedBase()}`,desc:'Open the backtest workspace',tag:'BACKTEST',run:()=>{location.href=`${rootUrl}backtest/?symbol=${encodeURIComponent(symbol||selectedBase())}`}});
  if(/RENKO/.test(q))out.push({title:`Renko ${symbol||selectedBase()}`,desc:'Open the Renko workspace',tag:'RENKO',run:()=>{location.href=`${rootUrl}renko/?symbol=${encodeURIComponent(symbol||selectedBase())}`}});
  if(/TRADE|BUY|SELL|CLOSE|TP|SL/.test(q))out.push({title:`Trade ${symbol||selectedBase()}`,desc:'Protected order ticket · Risk Engine → preview → approval',tag:'TRADE',run:()=>openTrade(symbol||selectedBase())});
  if(symbol&&!/BACKTEST|RENKO|TRADE|BUY|SELL|CLOSE|TP|SL/.test(q))out.push({title:`Open ${symbol} asset page`,desc:'Chart, market data, social context and tools',tag:'ASSET',run:()=>openAsset(symbol)});
  return out}
function renderCommand(){const box=$('rwaCommandResults');if(!box)return;const text=$('rwaCommandInput')?.value||'',q=text.trim().toUpperCase();let rows=[...commandCandidates(text),...marketCandidates(q)];if(!text.trim())rows=[{title:'Home',desc:'Portfolio, trends and recent activity',tag:'GO',run:openHome},{title:'Markets',desc:'Live market discovery',tag:'GO',run:openMarkets},{title:'Trade',desc:'Protected Hyperliquid execution',tag:'GO',run:()=>openTrade()},{title:'Portfolio',desc:'Verified account data',tag:'GO',run:()=>openSuite('portfolio')},{title:'Trader leaderboard',desc:'Discover public venue-backed performance',tag:'GO',run:()=>openSuite('leaderboard')},{title:'RWA Assets',desc:'Physical-asset registry and verification',tag:'GO',run:()=>openSuite('rwa')},{title:'Backtest',desc:'Historical strategy analysis',tag:'GO',run:()=>location.href=`${rootUrl}backtest/`}];rows=rows.slice(0,10);box.replaceChildren(...rows.map(r=>{const b=document.createElement('button');b.className='rwa-command-item';b.type='button';b.innerHTML=`<div><b>${r.title}</b><small>${r.desc}</small></div><span>${r.tag}</span>`;b.onclick=r.run;return b}))}
function installHome(){if(isTrade||$('rwaHomeDashboard'))return;const h=document.createElement('section');h.id='rwaHomeDashboard';h.className='rwa-home-dashboard';h.innerHTML=`<div class="rwa-home-hero"><div><small>RWA NETWORK</small><h1>Your market operating system</h1><p>Discover markets, trade through protected execution, follow verified traders and inspect real-world assets from one interface.</p></div><div class="rwa-home-actions"><button class="primary" data-home-action="trade">Trade now</button><button data-home-action="command">Ask / Search</button><button data-home-action="portfolio">Portfolio</button></div></div><div class="rwa-home-grid"><article class="rwa-home-card"><small>LIVE MARKETS</small><strong id="homeMarketCount">—</strong><div class="rwa-home-note">Public exchange feeds</div></article><article class="rwa-home-card"><small>GAINERS</small><strong id="homeGainers">—</strong><div class="rwa-home-note">Positive 24h markets</div></article><article class="rwa-home-card"><small>RWA-LINKED</small><strong id="homeRwaCount">—</strong><div class="rwa-home-note">Tracked RWA-linked pairs</div></article><article class="rwa-home-card"><small>EXECUTION</small><strong>Protected</strong><div class="rwa-home-note">Wallet → Risk → RWA API → venue</div></article><article class="rwa-home-card wide"><h3>Trending markets</h3><div id="homeTrending" class="rwa-home-list"><div class="rwa-home-note">Loading live markets…</div></div></article><article class="rwa-home-card wide"><h3>Quick workspaces</h3><div class="rwa-home-list"><button class="rwa-command-item" data-home-action="social"><div><b>Social & traders</b><small>Feed, leaderboard, copy</small></div><span>OPEN</span></button><button class="rwa-command-item" data-home-action="rwa"><div><b>RWA Assets</b><small>Registry, evidence, verification</small></div><span>OPEN</span></button><button class="rwa-command-item" data-home-action="backtest"><div><b>Backtest</b><small>Historical strategy analysis</small></div><span>OPEN</span></button><button class="rwa-command-item" data-home-action="renko"><div><b>Renko</b><small>Traditional fixed-box history</small></div><span>OPEN</span></button></div></article></div>`;const app=document.querySelector('.app');app?.insertBefore(h,document.querySelector('.credibility-strip'));h.addEventListener('click',e=>{const a=e.target.closest('[data-home-action]')?.dataset.homeAction;if(!a)return;if(a==='trade')openTrade();if(a==='command')openCommand();if(a==='portfolio')openSuite('portfolio');if(a==='social')openSocial();if(a==='rwa')openSuite('rwa');if(a==='backtest')location.href='backtest/';if(a==='renko')location.href='renko/'});setInterval(renderHome,2500)}
function renderHome(){if(isTrade)return;try{const pairs=S?.pairs||[];if($('homeMarketCount'))$('homeMarketCount').textContent=pairs.length?pairs.length.toLocaleString():'—';if($('homeGainers'))$('homeGainers').textContent=pairs.filter(x=>(x.change||0)>0).length.toLocaleString();if($('homeRwaCount'))$('homeRwaCount').textContent=pairs.filter(x=>x.rwa).length.toLocaleString();const top=[...pairs].filter(x=>Number.isFinite(x.change)&&Number.isFinite(x.price)).sort((a,b)=>Math.abs(b.change)-Math.abs(a.change)).slice(0,6);const box=$('homeTrending');if(box&&top.length){box.replaceChildren(...top.map(x=>{const b=document.createElement('button');b.className='rwa-command-item rwa-home-row';b.innerHTML=`<div><b>${x.base} / USDT</b><small>${Number(x.price).toLocaleString(undefined,{maximumFractionDigits:x.price>=1?4:7})}</small></div><span class="${x.change>=0?'up':'down'}">${x.change>=0?'+':''}${Number(x.change).toFixed(2)}%</span>`;b.onclick=()=>{selectPair?.(x.symbol,false);openMarkets()};return b}))}}catch{}}
function bindRoutes(){document.addEventListener('click',e=>{const d=e.target.closest('[data-rwa-route]');if(d){e.preventDefault();const r=d.dataset.rwaRoute;if(r==='home')openHome();if(r==='markets')openMarkets();if(r==='trade')openTrade();if(r==='social')openSocial();if(r==='rwa')openSuite('rwa');if(r==='intel')openSuite('intel');return}const m=e.target.closest('[data-mobile-nav]');if(m){const r=m.dataset.mobileNav;if(r==='home'){e.preventDefault();openHome()}else if(r==='markets'){e.preventDefault();openMarkets()}else if(r==='trade'){e.preventDefault();openTrade()}else if(r==='social'){e.preventDefault();openSocial()}else if(r==='portfolio'){e.preventDefault();openSuite('portfolio')}}});addEventListener('keydown',e=>{if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openCommand()}else if(e.key==='Escape')closeCommand()})}
function deepLink(){if(isTrade)return;const h=location.hash.replace('#','').toLowerCase();if(h==='home')openHome();else if(h==='social')openSocial();else if(h==='portfolio')openSuite('portfolio');else if(h==='copy')openSuite('copy');else if(h==='leaderboard')openSuite('leaderboard');else if(h==='watch')openSuite('watch');else if(h==='rwa')openSuite('rwa');else if(h==='intel')openSuite('intel');else if(h==='markets')openMarkets();else{const d=localStorage.getItem('rwa_default_landing_v3')||'home';d==='markets'?openMarkets():openHome()}}
function init(){normalizeDesktopNav();normalizeMobileNav();installCommandLayer();installCommandButton();installHome();bindRoutes();deepLink();renderHome();addEventListener('hashchange',deepLink);window.dispatchEvent(new CustomEvent('rwa:product-os-ready'))}
window.RWAProductOS={version:'3.1.0',openHome,openMarkets,openTrade,openSocial,openSuite,openCommand,openTrader,openAsset,setDefaultLanding:v=>localStorage.setItem('rwa_default_landing_v3',v==='markets'?'markets':'home')};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
