(()=>{
'use strict';
if(window.RWAQuickActions)return;
let suitePromise=null;
const $=id=>document.getElementById(id);
function toastSafe(t){if(typeof window.toast==='function')window.toast(t);else console.log(t)}
function loadScript(src){return new Promise((resolve,reject)=>{const base=src.split('?')[0],old=[...document.scripts].find(s=>(s.getAttribute('src')||'').split('?')[0]===base);if(old){if(window.RWASuite?.version==='2.0.0'||old.dataset.rwaQuickReady==='1')return resolve();old.addEventListener('load',resolve,{once:true});old.addEventListener('error',reject,{once:true});return}const s=document.createElement('script');s.src=src;s.async=false;s.onload=()=>{s.dataset.rwaQuickReady='1';resolve()};s.onerror=reject;document.body.appendChild(s)})}
async function loadSuite(){if(window.RWASuite?.version==='2.0.0')return window.RWASuite;if(suitePromise)return suitePromise;suitePromise=(async()=>{if(!document.querySelector('link[href^="suite.css"]')){const l=document.createElement('link');l.rel='stylesheet';l.href='suite.css?v=1';document.head.appendChild(l)}await loadScript('suite-ui.js?v=1');await loadScript('suite.js?v=1');await loadScript('suite-nav.js?v=1');for(let i=0;i<80;i++){if(window.RWASuite?.open)return window.RWASuite;await new Promise(r=>setTimeout(r,50))}throw Error('RWA Hub did not become ready')})().catch(e=>{suitePromise=null;throw e});return suitePromise}
function pair(){const raw=String($('selName')?.textContent||'BTC / USDT').toUpperCase(),base=raw.split('/')[0].trim().replace(/[^A-Z0-9]/g,'');return{base:base||'BTC',label:raw}}
async function openTab(tab){const s=await loadSuite();s.open(tab);return s}
async function watch(){try{await openTab('watch');setTimeout(()=>$('addWatch')?.click(),80)}catch(e){toastSafe(e.message||'Watchlist unavailable')}}
async function alertAction(){try{await openTab('watch');setTimeout(()=>{const el=$('alertThreshold');el?.focus();el?.scrollIntoView({behavior:'smooth',block:'center'})},100)}catch(e){toastSafe(e.message||'Alerts unavailable')}}
async function institutional(){try{await openTab('rwa')}catch(e){toastSafe(e.message||'RWA workspace unavailable')}}
async function share(){const p=pair(),u=new URL(location.href);u.hash='terminal';u.searchParams.set('market',p.base);const text=`RWA Markets · ${p.label}`;try{if(navigator.share){await navigator.share({title:text,text,url:u.toString()});return}await navigator.clipboard.writeText(u.toString());toastSafe('Market link copied')}catch(e){if(e?.name!=='AbortError')toastSafe('Could not share this market')}}
function trade(){const p=pair(),u=new URL('trade/',location.href);u.searchParams.set('coin',p.base);location.href=u.toString()}
function injectTrade(){const actions=document.querySelector('.instrument-actions');if(actions&&!actions.querySelector('[data-rwa-trade-now]')){const b=document.createElement('button');b.type='button';b.dataset.rwaTradeNow='1';b.textContent='↗ Trade Perps';b.onclick=trade;actions.prepend(b)}if(!document.getElementById('rwaQuickStyle')){const st=document.createElement('style');st.id='rwaQuickStyle';st.textContent='[data-rwa-trade-now]{border-color:#355bff!important;color:#cdd7ff!important}@media(max-width:680px){.terminal-header{position:relative}.instrument-actions{display:flex!important;width:100%;grid-column:1/-1;gap:6px;overflow:auto;padding-top:4px}.instrument-actions button{white-space:nowrap;flex:0 0 auto}}';document.head.appendChild(st)}}
function bind(){injectTrade();document.addEventListener('click',e=>{const b=e.target.closest('.instrument-actions button,.institutional-card button,.institutional');if(!b)return;const t=(b.textContent||'').toLowerCase();if(b.matches('[data-rwa-trade-now]'))return;if(t.includes('watch')){e.preventDefault();e.stopImmediatePropagation();watch();return}if(t.includes('alert')){e.preventDefault();e.stopImmediatePropagation();alertAction();return}if(t.includes('share')){e.preventDefault();e.stopImmediatePropagation();share();return}if(b.matches('.institutional-card button,.institutional')){e.preventDefault();e.stopImmediatePropagation();institutional()}},true);new MutationObserver(injectTrade).observe(document.documentElement,{childList:true,subtree:true})}
window.RWAQuickActions={version:'1.0.0',watch,alert:alertAction,share,trade,institutional,loadSuite};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
})();
