import * as OS from './rwa-os-core.mjs?v=14';
const $=id=>document.getElementById(id),fmt=n=>Number(n||0).toLocaleString(),fixture=new URLSearchParams(location.search).get('fixture')==='1';
const state={series:null,terms:null,ledger:[],tx:null,calc:null,snapshot:null,allocation:null,distribution:null,audit:null};
function options(el,rows){el.innerHTML=rows.map(x=>`<option value="${x}">${x.replaceAll('_',' ')}</option>`).join('')}
options($('seriesType'),OS.seriesTypes());options($('basis'),OS.distributionBases());options($('frequency'),OS.frequencies());options($('snapshot'),OS.snapshotPolicies());$('seriesType').value='HOTEL';$('basis').value='NET_PROFIT';$('frequency').value='QUARTERLY';$('snapshot').value='RECORD_DATE';
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));document.querySelectorAll('[data-panel]').forEach(x=>x.classList.toggle('active',x.dataset.panel===b.dataset.tab))});
function evidence(){return fixture?{ownership:'https://fixture.invalid/ownership',legal:'https://fixture.invalid/legal',valuation:'https://fixture.invalid/valuation',issuer:'https://fixture.invalid/issuer',disclosure:'https://fixture.invalid/disclosure'}:{}}
function buildSeries(){state.series=OS.validateSeries({id:$('seriesId').value,type:$('seriesType').value,title:$('seriesTitle').value,issuer:$('seriesIssuer').value,jurisdiction:$('seriesJurisdiction').value,currency:$('currency').value||'IDR',totalUnits:Number($('seriesUnits').value),evidence:evidence(),economic:{basis:$('basis').value,investorAllocationBps:Math.round(Number($('allocationPct').value)*100),reserveBps:Math.round(Number($('reservePct').value)*100),frequency:$('frequency').value,snapshotPolicy:$('snapshot').value,payoutAsset:$('payoutAsset').value,minimumPayoutMinor:0,noticeSeconds:86400}});return OS.termsManifest(state.series).then(x=>{state.terms=x;$('termsOut').classList.remove('empty');$('termsOut').textContent=JSON.stringify(x,null,2);update()})}
$('seriesForm').onsubmit=e=>{e.preventDefault();buildSeries().catch(err=>$('termsOut').textContent=`ERROR: ${err.message}`)};
$('loadBlueprint').onclick=()=>{$('seriesType').value='HOTEL';$('basis').value='NET_PROFIT';$('allocationPct').value='40';$('reservePct').value='10';$('frequency').value='QUARTERLY';$('snapshot').value='RECORD_DATE';buildSeries()};

const C39={0:'nnnwwnwnn',1:'wnnwnnnnw',2:'nnwwnnnnw',3:'wnwwnnnnn',4:'nnnwwnnnw',5:'wnnwwnnnn',6:'nnwwwnnnn',7:'nnnwnnwnw',8:'wnnwnnwnn',9:'nnwwnnwnn',A:'wnnnnwnnw',B:'nnwnnwnnw',C:'wnwnnwnnn',D:'nnnnwwnnw',E:'wnnnwwnnn',F:'nnwnwwnnn',G:'nnnnnwwnw',H:'wnnnnwwnn',I:'nnwnnwwnn',J:'nnnnwwwnn',K:'wnnnnnnww',L:'nnwnnnnww',M:'wnwnnnnwn',N:'nnnnwnnww',O:'wnnnwnnwn',P:'nnwnwnnwn',Q:'nnnnnnwww',R:'wnnnnnwwn',S:'nnwnnnwwn',T:'nnnnwnwwn',U:'wwnnnnnnw',V:'nwwnnnnnw',W:'wwwnnnnnn',X:'nwnnwnnnw',Y:'wwnnwnnnn',Z:'nwwnwnnnn','-':'nwnnnnwnw','.':'wwnnnnwnn',' ':'nwwnnnwnn','*':'nwnnwnwnn'};
function drawBarcode(text){const svg=$('barcode'),s=`*${String(text).toUpperCase().replace(/[^0-9A-Z .-]/g,'-')}*`;let x=15,parts=[];for(const ch of s){const p=C39[ch]||C39['-'];for(let i=0;i<p.length;i++){const w=p[i]==='w'?5:2;if(i%2===0)parts.push(`<rect x="${x}" y="20" width="${w}" height="125"/>`);x+=w}x+=3}const scale=Math.min(1,690/x);svg.innerHTML=`<g transform="scale(${scale},1)">${parts.join('')}</g><text x="360" y="174" text-anchor="middle" font-size="18" font-family="monospace">${text}</text>`}
async function createTx(){if(!state.series)await buildSeries();const seed=`${state.series.id}-${Date.now()}-${state.ledger.length}`;state.tx=OS.transaction({id:`tx-${(await OS.sha256Hex(seed)).slice(0,24)}`,seriesId:state.series.id,merchantId:$('merchant').value,locationId:$('location').value,terminalId:$('terminal').value,productId:$('product').value,amountMinor:Number($('amountMinor').value),currency:$('currency').value,externalRef:`ext-${(await OS.sha256Hex(seed+'external')).slice(0,20)}`,occurredAt:Date.now()});state.ledger.push(state.tx);const code=await OS.transactionCode(state.tx);$('barcodeRef').textContent=code.reference;drawBarcode(code.reference);renderTx();update()}
$('txForm').onsubmit=e=>{e.preventDefault();createTx().catch(err=>$('txState').textContent=err.message)};
function txTransition(next){if(!state.tx)return;const updated=OS.transitionTransaction(state.tx,next,{at:Date.now(),providerRef:fixture?'FIXTURE-PROVIDER':'MANUAL-UNVERIFIED'});state.ledger[state.ledger.findIndex(x=>x.id===state.tx.id)]=updated;state.tx=updated;renderTx();update()}
$('markPaid').onclick=()=>txTransition('PAID');$('markSettled').onclick=()=>txTransition('SETTLED');$('markRefunded').onclick=()=>txTransition('REFUNDED');
function renderTx(){$('txState').textContent=state.tx?.state||'—';renderLedger()}
function renderLedger(){const s=OS.ledgerSummary(state.ledger);$('rCount').textContent=s.count;$('rSettled').textContent=s.settled;$('rRefunded').textContent=s.refunded;$('rEligible').textContent=fmt(s.eligibleRevenueMinor);$('ledgerRows').classList.toggle('empty',!state.ledger.length);$('ledgerRows').innerHTML=state.ledger.length?state.ledger.map(x=>`<div class="row"><b>${x.id.slice(0,16)}</b><small>${x.productId||'—'}</small><span>${fmt(x.amountMinor)} ${x.currency}</span><b>${x.state}</b></div>`).join(''):'No real transactions loaded.'}
function recalc(){if(!state.terms)return;state.calc=OS.calculateDistribution({terms:state.terms,ledger:state.ledger,expensesMinor:Number($('expenses').value||0),deductionsMinor:Number($('deductions').value||0)});$('calcOut').classList.remove('empty');$('calcOut').textContent=JSON.stringify(state.calc,null,2);update()}
$('recalcRevenue').onclick=recalc;$('expenses').onchange=recalc;$('deductions').onchange=recalc;
async function buildDistribution(){if(!state.terms)await buildSeries();recalc();let checkpoints;try{checkpoints=JSON.parse($('holderInput').value)}catch{throw Error('holder_checkpoint_json_invalid')}const now=Date.now();state.snapshot=OS.holderSnapshot({checkpoints,policy:state.terms.governed.snapshotPolicy,recordAt:now,periodStart:now-30*86400000,periodEnd:now});state.allocation=OS.allocateEntitlements(state.calc.poolMinor,state.snapshot,{minimumPayoutMinor:state.terms.governed.minimumPayoutMinor});state.distribution=await OS.distributionManifest({seriesId:state.series.id,periodId:'CURRENT',calculation:state.calc,snapshot:state.snapshot,allocation:state.allocation,evidenceUrls:fixture?['https://fixture.invalid/settlement-ledger']:[]});$('distributionOut').classList.remove('empty');$('distributionOut').textContent=JSON.stringify(state.distribution,null,2);update()}
$('buildDistribution').onclick=()=>buildDistribution().catch(e=>$('distributionOut').textContent=`ERROR: ${e.message}`);
$('findInvestor').onclick=()=>{const w=$('investorWallet').value.trim().toLowerCase(),row=state.distribution?.entitlements?.find(x=>x.wallet===w);$('investorOut').classList.toggle('empty',!row);$('investorOut').innerHTML=row?`<div class="row"><b>${w}</b><span>Weight ${row.weight}</span><span>${fmt(row.amountMinor)} minor</span><b>${state.distribution.payoutAsset}</b></div>`:'No entitlement found in the current manifest.'};
async function runAudit(){if(!state.series)await buildSeries();const dist=state.distribution?{...state.distribution,poolMinor:state.calc?.poolMinor??state.distribution.poolMinor}:null;state.audit=await OS.auditOperatingSystem({series:state.series,ledger:state.ledger,distribution:dist});$('auditOut').classList.remove('empty');$('auditOut').textContent=JSON.stringify(state.audit,null,2);update()}
$('runAudit').onclick=()=>runAudit().catch(e=>$('auditOut').textContent=`ERROR: ${e.message}`);
function update(){const l=OS.ledgerSummary(state.ledger);$('kSeries').textContent=state.series?1:0;$('kRevenue').textContent=fmt(l.eligibleRevenueMinor);$('kPool').textContent=fmt(state.calc?.poolMinor||0);$('kAudit').textContent=state.audit?(state.audit.ok?'PASS':'BLOCKED'):'WAITING';renderLedger()}
async function loadFixture(){document.body.dataset.fixture='1';$('mode').textContent='BROWSER TEST FIXTURE';$('mode').style.borderColor='#8a642b';await buildSeries();const now=Date.now(),holderA='0x1111111111111111111111111111111111111111',holderB='0x2222222222222222222222222222222222222222';$('holderInput').value=JSON.stringify([{wallet:holderA,balance:60,ts:now-86400000},{wallet:holderB,balance:40,ts:now-86400000}],null,2);$('investorWallet').value=holderA;await createTx();txTransition('PAID');txTransition('SETTLED');await createTx();txTransition('PAID');txTransition('REFUNDED');$('expenses').value='5000000';$('deductions').value='1000000';recalc();await buildDistribution();await runAudit()}
update();if(fixture)loadFixture().catch(e=>{document.body.dataset.fixtureError=e.message;console.error(e)});
window.RWAOS={version:OS.RWA_OS_VERSION,state,buildSeries,createTx,buildDistribution,runAudit};
