(()=>{
if(document.getElementById('rwa-suite-ui'))return;
const root=document.createElement('section');root.id='suite';root.className='suite-screen';root.style.display='none';root.setAttribute('aria-label','RWA Network product suite');
root.innerHTML=`
<div class="suite-head"><div><small>RWA NETWORK</small><h2>Trading & asset suite</h2></div><div class="suite-head-actions"><span id="nostrStatus" class="suite-status">Social offline</span><span id="walletStatus" class="suite-status">Wallet offline</span><button class="suite-close" data-suite-close aria-label="Close">×</button></div></div>
<div class="suite-tabs">
<button class="active" data-suite-tab="profile">Profile</button><button data-suite-tab="leaderboard">Leaderboard</button><button data-suite-tab="copy">Copy</button><button data-suite-tab="watch">Watch & Alerts</button><button data-suite-tab="portfolio">Portfolio</button><button data-suite-tab="feed">Feed</button><button data-suite-tab="intel">Intelligence</button><button data-suite-tab="rwa">RWA Assets</button><button data-suite-tab="trade">Trade</button>
</div>
<div class="suite-body">
<section class="suite-panel active" data-suite-panel="profile"><div class="suite-grid">
<div class="suite-card span-6"><div class="suite-card-head"><div><small>IDENTITY</small><h3>Trader profile</h3></div><span id="pnlVerifyStatus" class="suite-status">UNVERIFIED</span></div><div class="identity-strip"><div><small>SOCIAL ID</small><b id="profileIdentity">Local profile</b></div><div><small>TRADING WALLET</small><b id="profileWallet">Not linked</b></div></div><div class="suite-form"><div class="suite-field"><label>DISPLAY NAME</label><input id="profileName" placeholder="Trader name"></div><div class="suite-field"><label>BIO</label><textarea id="profileBio" placeholder="Strategy, markets, risk style"></textarea></div><div class="suite-field"><label>AVATAR URL</label><input id="profileAvatar" placeholder="https://..."></div></div><div class="suite-actions"><button class="suite-secondary" id="connectNostr">Connect Social ID</button><button class="suite-secondary" id="connectWallet">Connect Trading Wallet</button><button class="suite-primary" id="saveProfile">Save profile</button></div></div>
<div class="suite-card span-6"><div class="suite-card-head"><div><small>VENUE-DERIVED</small><h3>Verified performance</h3></div></div><div class="metric-grid"><div class="metric"><small>ROI ALL</small><b id="profileRoi">—</b></div><div class="metric"><small>WIN RATE</small><b id="profileWin">—</b></div><div class="metric"><small>MAX DD</small><b id="profileDd">—</b></div><div class="metric"><small>OPEN POS.</small><b id="profileOpen">—</b></div></div><div class="metric-grid" style="margin-top:6px"><div class="metric"><small>FOLLOWERS</small><b id="profileFollowers">—</b></div><div class="metric"><small>FOLLOWING</small><b id="profileFollowing">—</b></div></div><p class="suite-muted">P&L is marked verified only after a wallet signature and venue-derived Hyperliquid history.</p></div>
</div></section>
<section class="suite-panel" data-suite-panel="leaderboard"><div class="suite-card span-12"><div class="suite-card-head"><div><small>SIGNED IDENTITIES + VENUE DATA</small><h3>Verified trader leaderboard</h3></div></div><div class="leader-periods"><button class="active" data-leader-period="day">Daily</button><button data-leader-period="week">Weekly</button><button data-leader-period="month">Monthly</button><button data-leader-period="allTime">All time</button></div><div id="leaderRows"><div class="suite-empty">Open this tab to load verified traders.</div></div></div></section>
<section class="suite-panel" data-suite-panel="copy"><div class="suite-grid"><div class="suite-card span-6"><div class="suite-card-head"><div><small>NON-CUSTODIAL</small><h3>Copy-trade controls</h3></div><span id="copyStatus" class="suite-status">Paused</span></div><div class="suite-form two"><div class="suite-field"><label>TRADER WALLET</label><input id="copyTarget" placeholder="0x..."></div><div class="suite-field"><label>SIZE COPY %</label><input id="copyAllocation" type="number" value="10" min="0" max="100"></div><div class="suite-field"><label>MAX LOSS USD</label><input id="copyMaxLoss" type="number" value="100"></div><div class="suite-field"><label>MAX NOTIONAL USD</label><input id="copyMaxNotional" type="number" value="250"></div></div><label class="checkline"><input id="copyEnabled" type="checkbox"> Watch source fills while this page is open</label><div class="suite-actions"><button class="suite-primary" id="saveCopy">Save & apply</button></div><p class="suite-muted">Signals enter a review queue. No order is sent until your wallet signs it.</p></div><div class="suite-card span-6"><div class="suite-card-head"><div><small>REVIEW FIRST</small><h3>Copy signal queue</h3></div></div><div id="copyQueue"><div class="suite-empty">No signals yet.</div></div></div></div></section>
<section class="suite-panel" data-suite-panel="watch"><div class="suite-grid"><div class="suite-card span-6"><div class="suite-card-head"><div><small>LOCAL-FIRST</small><h3>Watchlist</h3></div><button id="addWatch">+ Current market</button></div><div id="watchRows"></div></div><div class="suite-card span-6"><div class="suite-card-head"><div><small>BROWSER NOTIFICATIONS</small><h3>Alert engine</h3></div></div><div class="suite-form two"><div class="suite-field"><label>TYPE</label><select id="alertType"><option value="price_above">Price above</option><option value="price_below">Price below</option><option value="change_abs">24H move ≥ %</option><option value="volume_min">24H volume ≥ USD</option><option value="breakout">Break 24H high</option></select></div><div class="suite-field"><label>THRESHOLD</label><input id="alertThreshold" type="number" placeholder="Value"></div></div><div class="suite-actions"><button class="suite-primary" id="addAlert">Create alert</button></div><div id="alertRows"></div></div></div></section>
<section class="suite-panel" data-suite-panel="portfolio"><div class="suite-grid"><div class="suite-card span-12"><div class="suite-card-head"><div><small>HYPERLIQUID WALLET</small><h3>Portfolio</h3></div><div><button id="portfolioConnect">Connect</button><button id="refreshPortfolio">Refresh</button></div></div><div class="identity-strip"><div><small>WALLET</small><b id="portfolioWallet">Not connected</b></div><div><small>SOURCE</small><b>Hyperliquid public account data</b></div></div><div class="metric-grid"><div class="metric"><small>ACCOUNT VALUE</small><b id="portfolioValue">—</b></div><div class="metric"><small>WITHDRAWABLE</small><b id="portfolioWithdraw">—</b></div><div class="metric"><small>DAY ROI</small><b id="portfolioDay">—</b></div><div class="metric"><small>WEEK ROI</small><b id="portfolioWeek">—</b></div><div class="metric"><small>MONTH ROI</small><b id="portfolioMonth">—</b></div></div><div class="suite-card-head" style="margin-top:10px"><div><small>LIVE</small><h3>Open positions</h3></div></div><div id="positionRows"><div class="suite-empty">Connect a wallet to load positions.</div></div></div></div></section>
<section class="suite-panel" data-suite-panel="feed"><div class="suite-grid"><div class="suite-card span-12"><div class="suite-card-head"><div><small>SIGNED SOCIAL NETWORK</small><h3>Trading feed</h3></div><button id="connectNostr">Connect Social ID</button></div><div class="network-composer"><textarea id="networkPostText" maxlength="500" placeholder="Post a thesis, setup, catalyst or risk view..."></textarea><footer><select id="networkPostSide"><option>THESIS</option><option>LONG</option><option>SHORT</option><option>RWA</option></select><button id="publishNetworkPost">Publish signed post</button></footer></div><div id="networkFeed"><div class="suite-empty">Connect social identity to publish. Public signed posts load without an account.</div></div></div></div></section>
<section class="suite-panel" data-suite-panel="intel"><div class="suite-card span-12"><div class="suite-card-head"><div><small>LIVE MARKET ENGINE</small><h3>Market intelligence</h3></div></div><div class="intel-cards"><div><small>MARKET BREADTH</small><b id="intelBreadth">—</b></div><div><small>SELECTED MOMENTUM</small><b id="intelMomentum">—</b></div><div><small>VOLUME SPIKE</small><b id="intelVolSpike">—</b></div><div><small>ORDER FLOW</small><b id="intelSentiment">—</b></div></div><div id="intelTrending" class="intel-trending"></div><p class="suite-muted">Signals are descriptive market analytics, not guaranteed predictions.</p></div></section>
<section class="suite-panel" data-suite-panel="rwa"><div class="suite-grid"><div class="suite-card span-6"><div class="suite-card-head"><div><small>PUBLIC REGISTRY</small><h3>RWA Marketplace</h3></div></div><div class="asset-toolbar"><div><small>VERIFIED</small><b id="rwaVerifiedCount">0</b></div><div><small>LOCAL DRAFTS</small><b id="rwaDraftCount">0</b></div></div><div id="rwaAssetRows"></div></div><div class="suite-card span-6"><div class="suite-card-head"><div><small>ONBOARDING</small><h3>Add asset draft</h3></div></div><div class="suite-form two"><div class="suite-field"><label>ASSET NAME</label><input id="rwaName" placeholder="Warehouse A-01"></div><div class="suite-field"><label>TYPE</label><input id="rwaType" placeholder="Warehouse / Property"></div><div class="suite-field"><label>NAV USD</label><input id="rwaNav" type="number"></div><div class="suite-field"><label>YIELD %</label><input id="rwaYield" type="number"></div><div class="suite-field"><label>LOCATION</label><input id="rwaLocation"></div><div class="suite-field"><label>DOCUMENT URL</label><input id="rwaDoc" placeholder="https://..."></div></div><div class="suite-actions"><button class="suite-primary" id="addRwaDraft">Save UNVERIFIED draft</button></div><p class="suite-muted">Drafts never become “verified” automatically. Verified assets must be reviewed and added to the public registry.</p></div></div></section>
<section class="suite-panel" data-suite-panel="trade"><div class="trade-layout"><div class="suite-card span-12"><div class="suite-card-head"><div><small>WALLET-SIGNED</small><h3>Execution</h3></div><div><span id="tradeStatus" class="suite-status">Idle</span><button id="tradeConnect">Connect wallet</button></div></div><div class="identity-strip"><div><small>WALLET</small><b id="tradeWallet">Not connected</b></div><div><small>DEFAULT</small><b>Testnet + limit order</b></div></div><div class="suite-form two"><div class="suite-field"><label>COIN</label><input id="tradeCoin" placeholder="BTC"></div><div class="suite-field"><label>SIDE</label><select id="tradeSide"><option>BUY</option><option>SELL</option></select></div><div class="suite-field"><label>LIMIT PRICE</label><input id="tradePrice" type="number" step="any"></div><div class="suite-field"><label>SIZE</label><input id="tradeSize" type="number" step="any"></div><div class="suite-field"><label>MAX NOTIONAL USD</label><input id="tradeMaxNotional" type="number" value="1000"></div></div><label class="checkline"><input id="tradeReduceOnly" type="checkbox"> Reduce-only</label><label class="checkline"><input id="tradeTestnet" type="checkbox" checked> Use Hyperliquid testnet</label><label class="checkline"><input id="tradeMainnetConfirm" type="checkbox"> I explicitly authorize a MAINNET order when testnet is disabled</label><div class="suite-actions"><button class="suite-secondary" id="previewTrade">Preview & risk check</button><button class="suite-primary" id="executeTrade">Sign & submit</button></div><div id="tradePreview" class="trade-preview" style="margin-top:8px"></div><pre id="tradeResult" class="trade-result">No order submitted.</pre></div></div></section>
</div>`;
const marker=document.querySelector('.credibility-strip')||document.querySelector('.mobile-tabs')||document.body.lastElementChild;marker.parentNode.insertBefore(root,marker);
root.dataset.ready='1';root.id='suite';
const meta=document.createElement('meta');meta.id='rwa-suite-ui';document.head.appendChild(meta);
})();