(()=>{
'use strict';
if(window.RWASuite?.version==='2.0.0')return;
const $=id=>document.getElementById(id),qa=(s,r=document)=>[...r.querySelectorAll(s)];
const LS={profile:'rwa_profile_local_v2',socialWallet:'rwa_social_wallet_link_v2',watch:'rwa_watchlist_v2',alerts:'rwa_alerts_v2',copy:'rwa_copy_v2',copyActivity:'rwa_copy_activity_v2',copyLedger:'rwa_copy_ledger_v2',bookmarks:'rwa_bookmarks_v2',rwaDrafts:'rwa_asset_drafts_v2',suiteTab:'rwa_suite_tab_v2'};
const RELAYS=['wss://relay.damus.io','wss://nos.lol','wss://relay.primal.net'];
const state={nostrPub:'',wallet:'',walletVerified:false,profile:null,hl:null,leaderPeriod:'day',leaderRows:[],feedEvents:[],networkProfiles:new Map(),verifiedAssets:[],copyTimer:null,copyBusy:false,alertTimer:null,tradeWindow:[],revenue:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const jget=(k,d)=>{try{const v=JSON.parse(localStorage.getItem(k));return v??d}catch{return d}};
const jset=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}};
const money=v=>{const n=Number(v);return Number.isFinite(n)?'$'+n.toLocaleString(undefined,{maximumFractionDigits:2}):'—'};
const compact=v=>{const n=Number(v);return Number.isFinite(n)?'$'+Intl.NumberFormat('en',{notation:'compact',maximumFractionDigits:2}).format(n):'—'};
const pct=v=>{const n=Number(v);return Number.isFinite(n)?(n>=0?'+':'')+n.toFixed(2)+'%':'—'};
const short=a=>a?`${a.slice(0,6)}…${a.slice(-4)}`:'—';
const toastSafe=t=>typeof toast==='function'?toast(t):console.log(t);
const selected=()=>typeof S!=='undefined'&&S.map?S.map.get(S.selected):null;
const auth=()=>window.RWAWalletAuth,api=()=>window.RWAExecutionAPI;
function status(id,text,kind=''){const el=$(id);if(!el)return;el.textContent=text;el.className='suite-status'+(kind?' '+kind:'')}
function openSuite(tab='profile'){if(innerWidth<=680){document.body.classList.remove('market-drawer-open','social-open');document.body.classList.add('suite-open')}const s=$('suite');if(s){s.style.display='block';s.scrollTop=0}setSuiteTab(tab);qa('[data-mobile-nav]').forEach(a=>a.classList.toggle('active',a.dataset.mobileNav==='hub'||(tab==='portfolio'&&a.dataset.mobileNav==='portfolio')))}
function closeSuite(){document.body.classList.remove('suite-open');if(innerWidth<=680){const s=$('suite');if(s)s.style.display='none'}}
function setSuiteTab(tab){jset(LS.suiteTab,tab);qa('[data-suite-tab]').forEach(b=>b.classList.toggle('active',b.dataset.suiteTab===tab));qa('.suite-panel').forEach(p=>p.classList.toggle('active',p.dataset.suitePanel===tab));if(tab==='profile')renderProfile();if(tab==='leaderboard')loadLeaderboard();if(tab==='copy')renderCopy();if(tab==='watch')renderWatch();if(tab==='portfolio')renderPortfolio();if(tab==='feed')loadNetworkFeed();if(tab==='intel')renderIntel();if(tab==='rwa')renderRwa()}
function relayQuery(filters,timeout=2600){return new Promise(resolve=>{const out=new Map(),socks=[];let done=0,settled=false;const finish=()=>{if(settled)return;settled=true;for(const ws of socks)try{ws.close()}catch{};resolve([...out.values()].sort((a,b)=>(b.created_at||0)-(a.created_at||0)))};const timer=setTimeout(finish,timeout);RELAYS.forEach((url,i)=>{try{const ws=new WebSocket(url);socks.push(ws);const sub='rwa'+Date.now()+i;ws.onopen=()=>ws.send(JSON.stringify(['REQ',sub,...filters]));ws.onmessage=e=>{try{const m=JSON.parse(e.data);if(m[0]==='EVENT'&&m[2]?.id)out.set(m[2].id,m[2]);if(m[0]==='EOSE'){done++;if(done===RELAYS.length){clearTimeout(timer);finish()}}}catch{}};ws.onerror=()=>{done++;if(done===RELAYS.length){clearTimeout(timer);finish()}}}catch{done++}})})}
function relayPublish(ev){for(const url of RELAYS){try{const ws=new WebSocket(url);ws.onopen=()=>{try{ws.send(JSON.stringify(['EVENT',ev]))}finally{setTimeout(()=>ws.close(),900)}}}catch{}}}
async function nostrSign(kind,content,tags=[]){if(!window.nostr)throw Error('Nostr signer not available');return window.nostr.signEvent({kind,created_at:Math.floor(Date.now()/1000),tags,content})}
async function connectNostr(){if(!window.nostr){status('nostrStatus','Signer needed','warn');toastSafe('Use a NIP-07/NIP-46 Nostr signer to enable network identity');return}try{state.nostrPub=await window.nostr.getPublicKey();status('nostrStatus',short(state.nostrPub),'ok');await loadOwnProfile();await loadFollowStats();renderProfile();if(state.wallet)await publishSocialWalletLink()}catch(e){status('nostrStatus','Connection failed','bad');toastSafe(e.message||'Nostr connection failed')}}
async function loadOwnProfile(){if(!state.nostrPub)return;const evs=await relayQuery([{kinds:[0],authors:[state.nostrPub],limit:1}],1800);if(evs[0])try{state.profile=JSON.parse(evs[0].content||'{}')}catch{};if(!state.profile)state.profile=jget(LS.profile,{name:'',about:'',picture:''})}
async function saveProfile(){const p={name:$('profileName')?.value.trim()||'',about:$('profileBio')?.value.trim()||'',picture:$('profileAvatar')?.value.trim()||''};jset(LS.profile,p);state.profile=p;if(!state.nostrPub){toastSafe('Profile saved locally. Connect Social ID to publish it.');renderProfile();return}try{const ev=await nostrSign(0,JSON.stringify(p),[['t','rwa-trader']]);relayPublish(ev);toastSafe('Profile signed and published');renderProfile()}catch(e){toastSafe(e.message||'Profile publish failed')}}
async function loadFollowStats(){if(!state.nostrPub)return;const [mine,followers]=await Promise.all([relayQuery([{kinds:[3],authors:[state.nostrPub],limit:1}],1700),relayQuery([{kinds:[3],'#p':[state.nostrPub],limit:500}],2000)]);if($('profileFollowing'))$('profileFollowing').textContent=String(mine[0]?.tags?.filter(t=>t[0]==='p').length||0);if($('profileFollowers'))$('profileFollowers').textContent=String(new Set(followers.map(e=>e.pubkey)).size)}
async function followPubkey(pub){if(!state.nostrPub)return toastSafe('Connect Social ID first');const mine=await relayQuery([{kinds:[3],authors:[state.nostrPub],limit:1}],1600);const tags=(mine[0]?.tags||[]).filter(t=>t[0]==='p');if(!tags.some(t=>t[1]===pub))tags.push(['p',pub]);relayPublish(await nostrSign(3,'',tags));toastSafe('Trader followed');loadFollowStats()}
function activeWallet(){return String(auth()?.session?.()?.wallet||'').toLowerCase()}
async function publishSocialWalletLink(){if(!state.nostrPub||!state.wallet)return;const old=jget(LS.socialWallet,null);if(old?.wallet===state.wallet&&old?.pubkey===state.nostrPub&&old?.signature)return;const p=auth()?.provider?.()||window.RWAProvider||window.ethereum;if(!p)return;const msg=`RWA Social Wallet Link\nDomain: ${location.host}\nNostr: ${state.nostrPub}\nWallet: ${state.wallet}\nIssued At: ${new Date().toISOString()}`;const hex='0x'+[...new TextEncoder().encode(msg)].map(b=>b.toString(16).padStart(2,'0')).join('');let sig;try{sig=await p.request({method:'personal_sign',params:[hex,state.wallet]})}catch{sig=await p.request({method:'personal_sign',params:[state.wallet,hex]})}if(!sig)return;const row={wallet:state.wallet,pubkey:state.nostrPub,message:msg,signature:sig,ts:Date.now()};jset(LS.socialWallet,row);const ev=await nostrSign(30078,JSON.stringify(row),[['d','rwa-wallet-link-v2'],['wallet',state.wallet],['t','rwa-trader']]);relayPublish(ev)}
async function connectWallet(){try{if(!auth())throw Error('Wallet module is loading');const row=await auth().login();const addr=String(row?.wallet||activeWallet()).toLowerCase();if(!/^0x[a-f0-9]{40}$/.test(addr))throw Error('Wallet address unavailable');state.wallet=addr;state.walletVerified=!!auth().isLoggedIn?.();status('walletStatus',short(addr),state.walletVerified?'ok':'');if(state.nostrPub)await publishSocialWalletLink();await loadHyperliquid(addr);toastSafe('Wallet connected · venue P&L verified')}catch(e){status('walletStatus','Connection failed','bad');toastSafe(e.message||'Wallet connection failed')}}
function syncWallet(){const w=activeWallet();state.wallet=w;state.walletVerified=!!(w&&auth()?.isLoggedIn?.());status('walletStatus',w?short(w):'Wallet offline',state.walletVerified?'ok':'');if(!w){state.hl=null;renderProfile();renderPortfolio()}}
async function hlInfo(type,data={},testnet=false){if(api()?.info)return api().info(type,data,testnet);const url=testnet?'https://api.hyperliquid-testnet.xyz/info':'https://api.hyperliquid.xyz/info';const r=await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,...data}),cache:'no-store'});if(!r.ok)throw Error(`Hyperliquid ${r.status}`);return r.json()}
function maxDrawdown(history){let peak=-Infinity,dd=0;for(const row of history||[]){const v=Number(row[1]);if(!Number.isFinite(v))continue;if(v>peak)peak=v;if(peak>0)dd=Math.max(dd,(peak-v)/peak*100)}return dd}
function periodMetric(portfolio,key){const row=(portfolio||[]).find(x=>x[0]===key)?.[1];if(!row)return{roi:null,pnl:null,history:[]};const h=row.accountValueHistory||[],p=row.pnlHistory||[],a0=Number(h[0]?.[1]),pnl=Number(p.at(-1)?.[1]??0);return{roi:Number.isFinite(a0)&&a0!==0&&Number.isFinite(pnl)?pnl/Math.abs(a0)*100:null,pnl:Number.isFinite(pnl)?pnl:null,history:h}}
function fillStats(fills){const groups=new Map();let realized=0,volume=0;for(const f of fills||[]){const pnl=Number(f.closedPnl||0);if(Number.isFinite(pnl))realized+=pnl;const px=Number(f.px),sz=Number(f.sz);if(Number.isFinite(px)&&Number.isFinite(sz))volume+=Math.abs(px*sz);if(pnl!==0){const k=String(f.oid??f.hash??f.tid??f.time);groups.set(k,(groups.get(k)||0)+pnl)}}const closed=[...groups.values()].filter(Number.isFinite),wins=closed.filter(x=>x>0).length;return{realized,volume,trades:closed.length,winRate:closed.length?wins/closed.length*100:null}}
async function traderMetrics(addr,{full=true,testnet=false}={}){const req=[hlInfo('clearinghouseState',{user:addr},testnet),hlInfo('portfolio',{user:addr},testnet)];if(full)req.push(hlInfo('userFills',{user:addr,aggregateByTime:true},testnet));const [ch,portfolio,fills=[]]=await Promise.all(req);const positions=(ch.assetPositions||[]).map(x=>x.position||x).filter(p=>Math.abs(Number(p?.szi||0))>0),all=periodMetric(portfolio,'allTime'),day=periodMetric(portfolio,'day'),week=periodMetric(portfolio,'week'),month=periodMetric(portfolio,'month'),fs=fillStats(fills),unrealized=positions.reduce((s,p)=>s+Number(p.unrealizedPnl||0),0);return{addr,ch,portfolio,fills,positions,accountValue:Number(ch.marginSummary?.accountValue||0),withdrawable:Number(ch.withdrawable||0),unrealized,...fs,maxDd:maxDrawdown(all.history),roiAll:all.roi,day,week,month,all}}
async function loadHyperliquid(addr=state.wallet){if(!addr)return;status('pnlVerifyStatus','Loading venue data…','');try{state.hl=await traderMetrics(addr,{full:true,testnet:false});status('pnlVerifyStatus',state.walletVerified&&addr===state.wallet?'VERIFIED BY HYPERLIQUID':'PUBLIC WALLET DATA',state.walletVerified&&addr===state.wallet?'ok':'');renderProfile();renderPortfolio()}catch(e){status('pnlVerifyStatus','Venue unavailable','bad');toastSafe(e.message||'Could not load Hyperliquid data')}}
function renderProfile(){const p=state.profile||jget(LS.profile,{name:'',about:'',picture:''}),m=state.hl;if($('profileName')&&document.activeElement!==$('profileName'))$('profileName').value=p.name||'';if($('profileBio')&&document.activeElement!==$('profileBio'))$('profileBio').value=p.about||'';if($('profileAvatar')&&document.activeElement!==$('profileAvatar'))$('profileAvatar').value=p.picture||'';if($('profileIdentity'))$('profileIdentity').textContent=state.nostrPub?short(state.nostrPub):'Local profile';if($('profileWallet'))$('profileWallet').textContent=state.wallet?short(state.wallet):'Not linked';for(const [id,v] of [['profileRoi',m?pct(m.roiAll):'—'],['profileWin',m&&m.winRate!=null?pct(m.winRate):'—'],['profileDd',m?pct(-m.maxDd):'—'],['profileRealized',m?money(m.realized):'—'],['profileUnrealized',m?money(m.unrealized):'—'],['profileTrades',m?String(m.trades):'—']])if($(id))$(id).textContent=v}
async function verifyWalletLink(ev){try{const d=JSON.parse(ev.content||'{}');if(!d.wallet||!d.signature||!d.message)return null;const {verifyMessage}=await import('https://esm.sh/ethers@6.15.0');const recovered=String(verifyMessage(d.message,d.signature)||'').toLowerCase();if(recovered!==String(d.wallet).toLowerCase()||!d.message.includes(`Nostr: ${ev.pubkey}`))return null;return{pubkey:ev.pubkey,wallet:String(d.wallet).toLowerCase(),event:ev}}catch{return null}}
async function fetchProfiles(pubkeys){if(!pubkeys.length)return new Map();const evs=await relayQuery([{kinds:[0],authors:pubkeys.slice(0,100),limit:100}],2200),map=new Map();for(const e of evs)if(!map.has(e.pubkey))try{map.set(e.pubkey,JSON.parse(e.content||'{}'))}catch{};return map}
async function loadLeaderboard(){const box=$('leaderRows');if(!box)return;box.innerHTML='<div class="suite-empty">Finding signed trader wallets…</div>';try{const links=await relayQuery([{kinds:[30078],'#d':['rwa-wallet-link-v2','rwa-wallet-link'],limit:80}],2800),unique=new Map();for(const ev of links){if(unique.has(ev.pubkey))continue;const v=await verifyWalletLink(ev);if(v)unique.set(ev.pubkey,v);if(unique.size>=16)break}if(!unique.size){box.innerHTML='<div class="suite-empty">No signed RWA Network traders found yet. You can still inspect any public Hyperliquid wallet above.</div>';return}const profiles=await fetchProfiles([...unique.keys()]),period=state.leaderPeriod;const rows=(await Promise.all([...unique.values()].map(async v=>{try{const portfolio=await hlInfo('portfolio',{user:v.wallet}),m=periodMetric(portfolio,period);return{...v,profile:profiles.get(v.pubkey)||{},roi:m.roi,pnl:m.pnl}}catch{return null}}))).filter(Boolean).sort((a,b)=>(b.roi??-1e99)-(a.roi??-1e99));state.leaderRows=rows;box.innerHTML=rows.map((r,i)=>`<div class="leader-row"><span class="leader-rank">${i+1}</span><div class="leader-user"><b>${esc(r.profile.name||short(r.wallet))}</b><small>${esc(short(r.wallet))} · wallet verified</small></div><div><b class="${(r.roi||0)>=0?'up':'down'}">${esc(pct(r.roi))}</b><small>${esc(money(r.pnl))}</small></div><button data-view-trader="${esc(r.wallet)}" data-pub="${esc(r.pubkey)}">View</button><button data-copy-wallet="${esc(r.wallet)}">Copy</button></div>`).join('')}catch{box.innerHTML='<div class="suite-empty">Leaderboard relays unavailable. Public wallet inspection still works.</div>'}}
async function inspectTrader(){const w=($('leaderWalletSearch')?.value||'').trim().toLowerCase();if(!/^0x[a-f0-9]{40}$/.test(w))return toastSafe('Enter a valid 0x wallet');viewTrader(w,'')}
async function viewTrader(wallet,pub=''){const box=$('leaderDetail');if(!box)return;box.style.display='block';box.innerHTML='<div class="suite-empty">Loading verified venue history…</div>';try{const m=await traderMetrics(wallet,{full:true}),row=state.leaderRows.find(x=>x.wallet===wallet),name=row?.profile?.name||short(wallet),pos=m.positions.slice(0,6).map(p=>`${esc(p.coin)} ${Number(p.szi)>0?'LONG':'SHORT'} ${esc(String(Math.abs(Number(p.szi))))}`).join(' · ')||'No open positions';box.innerHTML=`<div class="trader-detail-head"><div><small>PUBLIC HYPERLIQUID PROFILE</small><h3>${esc(name)}</h3><span>${esc(wallet)}</span></div><div class="suite-actions">${pub?`<button data-follow-pub="${esc(pub)}">Follow</button>`:''}<button class="suite-primary" data-copy-wallet="${esc(wallet)}">Copy</button></div></div><div class="metric-grid"><div class="metric"><small>EQUITY</small><b>${esc(money(m.accountValue))}</b></div><div class="metric"><small>ALL ROI</small><b>${esc(pct(m.roiAll))}</b></div><div class="metric"><small>WIN RATE</small><b>${esc(m.winRate!=null?pct(m.winRate):'—')}</b></div><div class="metric"><small>MAX DD</small><b>${esc(pct(-m.maxDd))}</b></div><div class="metric"><small>REALIZED</small><b>${esc(money(m.realized))}</b></div><div class="metric"><small>UNREALIZED</small><b>${esc(money(m.unrealized))}</b></div><div class="metric"><small>CLOSED TRADES</small><b>${m.trades}</b></div><div class="metric"><small>OPEN POSITIONS</small><b>${m.positions.length}</b></div></div><p class="suite-muted">${pos}</p>`}catch(e){box.innerHTML=`<div class="suite-empty">Could not load wallet: ${esc(e.message||e)}</div>`}}
function copyCfg(){return jget(LS.copy,{target:'',capital:250,maxLoss:50,enabled:false,lastTime:0,baselinePnl:0,lastPnl:0,testnet:true,scale:0})}
function copyLedger(){return jget(LS.copyLedger,{positions:{},prices:{}})}
function copyUsed(){const l=copyLedger();return Object.entries(l.positions||{}).reduce((s,[coin,sz])=>s+Math.abs(Number(sz||0)*Number(l.prices?.[coin]||0)),0)}
function addCopyActivity(row){const a=jget(LS.copyActivity,[]);a.unshift({ts:Date.now(),...row});jset(LS.copyActivity,a.slice(0,80));renderCopyActivity()}
function renderCopyActivity(){const box=$('copyQueue');if(!box)return;const a=jget(LS.copyActivity,[]);box.innerHTML=a.length?a.map(x=>`<div class="copy-signal"><div><b>${esc(x.status||'INFO')} ${esc(x.coin||'')}</b><small>${esc(new Date(x.ts).toLocaleTimeString())} · ${esc(x.message||'')}</small></div><div><b>${x.size?esc(String(Number(x.size).toFixed(6))):'—'}</b><small>${x.px?esc(money(x.px)):''}</small></div><span class="${x.status==='EXECUTED'?'up':x.status==='BLOCKED'?'down':''}">${esc(x.side||'')}</span></div>`).join(''):'<div class="suite-empty">No copy activity yet.</div>'}
function renderCopy(){const c=copyCfg();if($('copyTarget')&&document.activeElement!==$('copyTarget'))$('copyTarget').value=c.target||'';if($('copyCapital')&&document.activeElement!==$('copyCapital'))$('copyCapital').value=c.capital??250;if($('copyMaxLoss')&&document.activeElement!==$('copyMaxLoss'))$('copyMaxLoss').value=c.maxLoss??50;status('copyStatus',c.enabled?'COPY ACTIVE':'Paused',c.enabled?'ok':'');if($('copyEnv'))$('copyEnv').textContent=c.testnet===false?'MAINNET':'TESTNET';if($('copyUsed'))$('copyUsed').textContent=money(copyUsed());const loss=Math.max(0,Number(c.baselinePnl||0)-Number(c.lastPnl??c.baselinePnl||0)),room=Math.max(0,Number(c.maxLoss||0)-loss);if($('copyLossRoom'))$('copyLossRoom').textContent=c.enabled?money(room):'—';renderCopyActivity();if(c.enabled)startCopyWatch();else stopCopyWatch()}
async function startCopy(){try{const target=($('copyTarget')?.value||'').trim().toLowerCase(),capital=Number($('copyCapital')?.value),maxLoss=Number($('copyMaxLoss')?.value);if(!/^0x[a-f0-9]{40}$/.test(target))throw Error('Trader wallet is invalid');if(!(capital>0)||!(maxLoss>0))throw Error('Capital and max loss must be greater than zero');if(!state.wallet||!state.walletVerified)await connectWallet();if(target===state.wallet)throw Error('Cannot copy your own wallet');if(!api())throw Error('Execution API is loading');const testnet=window.RWAExchangeCore?.testnet?.()!==false;if(!testnet&&!window.RWAExchangeCore?.mainnetUnlocked?.())throw Error('Mainnet is locked until real testnet E2E passes');const source=await hlInfo('clearinghouseState',{user:target},false),sourceEquity=Number(source.marginSummary?.accountValue||0);if(!(sourceEquity>0))throw Error('Source trader has no measurable Hyperliquid equity');const followerPortfolio=await hlInfo('portfolio',{user:state.wallet},testnet),baseline=periodMetric(followerPortfolio,'day').pnl||0;if(!api().agent?.status?.(testnet)){status('copyStatus','Authorize API wallet…','warn');await api().agent.authorize(testnet)}const c={target,capital,maxLoss,enabled:true,lastTime:Date.now(),baselinePnl:baseline,lastPnl:baseline,testnet,sourceEquity,scale:Math.min(1,capital/sourceEquity),startedAt:Date.now()};jset(LS.copy,c);jset(LS.copyLedger,{positions:{},prices:{}});addCopyActivity({status:'STARTED',message:`${testnet?'Testnet':'Mainnet'} · scale ${(c.scale*100).toFixed(3)}%`});renderCopy();toastSafe('Copy started · no trading form required')}catch(e){status('copyStatus','Blocked','bad');toastSafe(e.message||'Could not start copy')}}
function stopCopyWatch(){if(state.copyTimer){clearInterval(state.copyTimer);state.copyTimer=null}}
function stopCopy(reason='Stopped by user'){const c=copyCfg();c.enabled=false;jset(LS.copy,c);stopCopyWatch();addCopyActivity({status:'STOPPED',message:reason});renderCopy()}
function startCopyWatch(){if(state.copyTimer)return;state.copyTimer=setInterval(checkCopySignals,10000);setTimeout(checkCopySignals,300)}
async function checkCopySignals(){if(state.copyBusy)return;const c=copyCfg();if(!c.enabled||!c.target)return;state.copyBusy=true;try{if(!api()?.agent?.status?.(c.testnet)){stopCopy('API wallet authorization missing');return}const start=Math.max(Number(c.lastTime||Date.now())+1,Date.now()-6*3600000),fills=await hlInfo('userFillsByTime',{user:c.target,startTime:start,endTime:Date.now(),aggregateByTime:false},false),fresh=(fills||[]).filter(f=>Number(f.time)>Number(c.lastTime||0)).sort((a,b)=>Number(a.time)-Number(b.time));if(!fresh.length)return;const followerPortfolio=await hlInfo('portfolio',{user:state.wallet},c.testnet),currentPnl=periodMetric(followerPortfolio,'day').pnl||0;c.lastPnl=currentPnl;if(Number(c.baselinePnl||0)-currentPnl>=Number(c.maxLoss||0)){jset(LS.copy,c);stopCopy('Max-loss reached');return}const l=copyLedger();l.positions=l.positions||{};l.prices=l.prices||{};for(const f of fresh){const coin=String(f.coin||'').toUpperCase(),side=f.side==='B'?'BUY':'SELL',px=Number(f.px),sourceSize=Math.abs(Number(f.sz)),dir=String(f.dir||'').toLowerCase(),closing=dir.includes('close')||Number(f.closedPnl||0)!==0;let size=sourceSize*Number(c.scale||0),reduceOnly=false;if(!(px>0)||!(size>0)){addCopyActivity({status:'SKIPPED',coin,side,message:'Invalid source fill'});continue}const signed=Number(l.positions[coin]||0);if(closing){if(!signed){addCopyActivity({status:'SKIPPED',coin,side,px,message:'No copied position to reduce'});continue}if((signed>0&&side!=='SELL')||(signed<0&&side!=='BUY')){addCopyActivity({status:'SKIPPED',coin,side,px,message:'Signal does not reduce copied position'});continue}size=Math.min(size,Math.abs(signed));reduceOnly=true}else{const remaining=Math.max(0,Number(c.capital)-copyUsed());if(remaining<=0){addCopyActivity({status:'BLOCKED',coin,side,px,message:'Copy capital fully allocated'});continue}size=Math.min(size,remaining/px)}if(!(size>0))continue;try{await api().orders.market({coin,side,size,reduceOnly,testnet:!!c.testnet,preferAgent:true});const delta=(side==='BUY'?1:-1)*size,next=signed+delta;l.positions[coin]=reduceOnly&&signed!==0&&Math.sign(next)!==Math.sign(signed)?0:next;l.prices[coin]=px;jset(LS.copyLedger,l);addCopyActivity({status:'EXECUTED',coin,side,size,px,message:reduceOnly?'Copied reduction':'Copied source fill'})}catch(e){addCopyActivity({status:'BLOCKED',coin,side,size,px,message:String(e.message||e)})}}c.lastTime=Math.max(Number(c.lastTime||0),...fresh.map(f=>Number(f.time)||0));jset(LS.copy,c);renderCopy()}catch(e){addCopyActivity({status:'ERROR',message:String(e.message||e)})}finally{state.copyBusy=false}}
function watchlist(){return jget(LS.watch,[])}
function renderWatch(){const box=$('watchRows');if(!box)return;const w=watchlist();box.innerHTML=w.length?w.map(sym=>{const x=typeof S!=='undefined'?S.map.get(sym):null;return`<div class="watch-row"><div><b>${esc(x?x.base+' / USDT':sym)}</b><small>${esc(x?money(x.price):'Waiting for market')}</small></div><span class="${(x?.change||0)>=0?'up':'down'}">${esc(x?pct(x.change):'—')}</span><button data-watch-remove="${esc(sym)}">×</button></div>`}).join(''):'<div class="suite-empty">Watchlist is empty. Add the current chart market.</div>';renderAlerts()}
function addCurrentWatch(){const x=selected();if(!x)return;const w=watchlist();if(!w.includes(x.symbol))w.unshift(x.symbol);jset(LS.watch,w.slice(0,50));renderWatch();toastSafe(`${x.base} added to watchlist`)}
function alerts(){return jget(LS.alerts,[])}
async function addAlert(){const x=selected();if(!x)return;const type=$('alertType')?.value||'price_above';let threshold=Number($('alertThreshold')?.value);if(type==='breakout_high'&&!Number.isFinite(threshold))threshold=Number(x.high);if(type==='breakout_low'&&!Number.isFinite(threshold))threshold=Number(x.low);if(!Number.isFinite(threshold)||threshold<=0)return toastSafe('Enter a valid alert threshold');let positionSide='';if(type==='tp'||type==='sl'){if(state.wallet&&!state.hl)await loadHyperliquid(state.wallet);const p=state.hl?.positions?.find(p=>String(p.coin).toUpperCase()===String(x.base).toUpperCase());if(!p)return toastSafe('TP/SL alert requires an open verified position in this market');positionSide=Number(p.szi)>0?'LONG':'SHORT'}const a=alerts();a.unshift({id:Date.now(),symbol:x.symbol,type,threshold,positionSide,baselineHigh:Number(x.high),baselineLow:Number(x.low),baselineVol:Number(x.vol),created:Date.now(),triggered:false});jset(LS.alerts,a.slice(0,60));renderAlerts();startAlertWatch();toastSafe('Alert created')}
function renderAlerts(){const box=$('alertRows');if(!box)return;const a=alerts();box.innerHTML=a.length?a.map(v=>`<div class="alert-row"><div><b>${esc(v.symbol)}</b><small>${esc(v.type.replaceAll('_',' '))} · ${esc(String(v.threshold))}${v.positionSide?' · '+esc(v.positionSide):''}</small></div><span class="${v.triggered?'up':''}">${v.triggered?'TRIGGERED':'ACTIVE'}</span><button data-alert-remove="${v.id}">×</button></div>`).join(''):'<div class="suite-empty">No alerts configured.</div>'}
async function notify(title,body){try{if('Notification'in window){if(Notification.permission==='default')await Notification.requestPermission();if(Notification.permission==='granted')new Notification(title,{body})}}catch{}}
function fireAlert(v,x,detail=''){v.triggered=true;v.triggeredAt=Date.now();notify(`RWA Alert · ${x?.base||v.symbol}`,detail||`${v.type.replaceAll('_',' ')} triggered`);toastSafe(`Alert: ${x?.base||v.symbol} ${v.type.replaceAll('_',' ')}`)}
function startAlertWatch(){if(state.alertTimer)return;state.alertTimer=setInterval(checkAlerts,2500)}
function checkAlerts(){if(typeof S==='undefined')return;const a=alerts();let changed=false;for(const v of a){if(v.triggered||v.type==='whale')continue;const x=S.map.get(v.symbol);if(!x)continue;let hit=false;if(v.type==='price_above')hit=x.price>=v.threshold;if(v.type==='price_below')hit=x.price<=v.threshold;if(v.type==='change_abs')hit=Math.abs(x.change||0)>=v.threshold;if(v.type==='volume_spike')hit=Number(v.baselineVol)>0&&Number(x.vol)>=Number(v.baselineVol)*v.threshold;if(v.type==='breakout_high')hit=Number(x.price)>Number(v.baselineHigh||v.threshold);if(v.type==='breakout_low')hit=Number(x.price)<Number(v.baselineLow||v.threshold);if(v.type==='tp')hit=v.positionSide==='LONG'?x.price>=v.threshold:x.price<=v.threshold;if(v.type==='sl')hit=v.positionSide==='LONG'?x.price<=v.threshold:x.price>=v.threshold;if(hit){fireAlert(v,x,`${v.type.replaceAll('_',' ')} at ${money(x.price)}`);changed=true}}if(changed){jset(LS.alerts,a);renderAlerts()}}
function installTradeProbe(){if(typeof window.addTrade!=='function'||window.addTrade.__rwaProbe)return false;const base=window.addTrade;function wrapped(t){try{const p=Number(t.p),q=Number(t.q),notional=Math.abs(p*q),row={symbol:typeof S!=='undefined'?S.selected:'',side:t.m?'SELL':'BUY',price:p,qty:q,notional,time:Number(t.T||Date.now())};state.tradeWindow.push(row);state.tradeWindow=state.tradeWindow.filter(x=>Date.now()-x.time<10*60*1000).slice(-400);window.dispatchEvent(new CustomEvent('rwa:market-trade',{detail:row}))}catch{}return base(t)}wrapped.__rwaProbe=true;window.addTrade=wrapped;return true}
window.addEventListener('rwa:market-trade',e=>{const t=e.detail||{},a=alerts();let changed=false;for(const v of a){if(v.triggered||v.type!=='whale'||v.symbol!==t.symbol)continue;if(Number(t.notional)>=Number(v.threshold)){const x=typeof S!=='undefined'?S.map.get(v.symbol):null;fireAlert(v,x,`${t.side} whale trade ${money(t.notional)} at ${money(t.price)}`);changed=true}}if(changed){jset(LS.alerts,a);renderAlerts()}renderIntel()});
function renderPortfolio(){const m=state.hl;if($('portfolioWallet'))$('portfolioWallet').textContent=state.wallet?short(state.wallet):'Connect wallet';const vals=[['portfolioValue',m?money(m.accountValue):'—'],['portfolioWithdraw',m?money(m.withdrawable):'—'],['portfolioRealized',m?money(m.realized):'—'],['portfolioUnrealized',m?money(m.unrealized):'—'],['portfolioDay',m?pct(m.day.roi):'—'],['portfolioWeek',m?pct(m.week.roi):'—'],['portfolioMonth',m?pct(m.month.roi):'—'],['portfolioAll',m?pct(m.roiAll):'—'],['portfolioWin',m&&m.winRate!=null?pct(m.winRate):'—'],['portfolioDd',m?pct(-m.maxDd):'—'],['portfolioTrades',m?String(m.trades):'—'],['portfolioVolume',m?compact(m.volume):'—']];for(const [id,v] of vals)if($(id))$(id).textContent=v;const box=$('positionRows');if(box)box.innerHTML=m&&m.positions.length?m.positions.map(p=>`<div class="position-row"><div><b>${esc(p.coin)}</b><small>${Number(p.szi)>=0?'LONG':'SHORT'} · ${esc(String(p.leverage?.value||p.leverage||'—'))}x</small></div><div><b>${esc(String(p.szi))}</b><small>Entry ${esc(money(p.entryPx))}</small></div><div><b class="${Number(p.unrealizedPnl)>=0?'up':'down'}">${esc(money(p.unrealizedPnl))}</b><small>ROE ${esc(pct(Number(p.returnOnEquity||0)*100))}</small></div></div>`).join(''):'<div class="suite-empty">No open Hyperliquid positions.</div>'}
async function publishNetworkPost(){const input=$('networkPostText'),text=input?.value.trim();if(!text)return;if(!state.nostrPub)return toastSafe('Connect Social ID first');const x=selected(),side=$('networkPostSide')?.value||'THESIS';try{const tags=[['t','rwa-trading'],['side',side]];if(x)tags.push(['pair',x.symbol]);relayPublish(await nostrSign(1,text,tags));if(input)input.value='';toastSafe('Post signed and published');setTimeout(loadNetworkFeed,800)}catch(e){toastSafe(e.message||'Publish failed')}}
async function socialWallets(pubkeys){if(!pubkeys.length)return new Map();const links=await relayQuery([{kinds:[30078],authors:pubkeys.slice(0,40),'#d':['rwa-wallet-link-v2','rwa-wallet-link'],limit:80}],2200),out=new Map();for(const ev of links){if(out.has(ev.pubkey))continue;const v=await verifyWalletLink(ev);if(v)out.set(ev.pubkey,v)}return out}
async function loadNetworkFeed(){const box=$('networkFeed');if(!box)return;box.innerHTML='<div class="suite-empty">Loading signed social feed…</div>';try{const all=await relayQuery([{kinds:[1],'#t':['rwa-trading'],limit:70}],2700),roots=all.filter(e=>!e.tags?.some(t=>t[0]==='e'&&t[3]==='reply')).slice(0,30);state.feedEvents=all;if(!roots.length){box.innerHTML='<div class="suite-empty">No signed posts found yet. Publish the first thesis.</div>';return}const pubkeys=[...new Set(roots.map(e=>e.pubkey))],profiles=await fetchProfiles(pubkeys),wallets=await socialWallets(pubkeys),ids=roots.map(e=>e.id),interactions=await relayQuery([{kinds:[1,6,7],'#e':ids,limit:500}],2200),counts=new Map(ids.map(id=>[id,{reply:0,like:0,repost:0}]));for(const e of interactions){const id=e.tags?.find(t=>t[0]==='e')?.[1],c=counts.get(id);if(!c)continue;if(e.kind===7)c.like++;else if(e.kind===6)c.repost++;else if(e.kind===1)c.reply++}const posMap=new Map();await Promise.all([...wallets.values()].slice(0,12).map(async v=>{try{const ch=await hlInfo('clearinghouseState',{user:v.wallet}),pos=(ch.assetPositions||[]).map(x=>x.position||x).filter(p=>Math.abs(Number(p.szi||0))>0);posMap.set(v.pubkey,pos)}catch{}}));state.networkProfiles=profiles;box.innerHTML=roots.map(e=>{const p=profiles.get(e.pubkey)||{},side=e.tags?.find(t=>t[0]==='side')?.[1]||'THESIS',pair=e.tags?.find(t=>t[0]==='pair')?.[1]||'MARKET',w=wallets.get(e.pubkey),pos=posMap.get(e.pubkey)||[],first=pos[0],verified=w?`<span class="net-verified">VERIFIED${first?' · '+esc(first.coin)+' '+(Number(first.szi)>0?'LONG':'SHORT'):''}</span>`:'',c=counts.get(e.id)||{};return`<article class="network-post" data-event="${esc(e.id)}"><header><div class="net-avatar">${esc((p.name||e.pubkey).slice(0,1).toUpperCase())}</div><div><b>${esc(p.name||short(e.pubkey))}</b><small>${esc(pair)} · ${new Date((e.created_at||0)*1000).toLocaleString()}</small>${verified}</div><span>${esc(side)}</span></header><p>${esc(e.content)}</p><footer>${e.pubkey!==state.nostrPub?`<button data-follow-pub="${esc(e.pubkey)}">Follow</button>`:''}<button data-reply="${esc(e.id)}">Reply ${c.reply||0}</button><button data-like="${esc(e.id)}">Like ${c.like||0}</button><button data-repost="${esc(e.id)}">Repost ${c.repost||0}</button><button data-bookmark="${esc(e.id)}">Bookmark</button>${w?`<button data-copy-wallet="${esc(w.wallet)}">Copy</button>`:''}</footer></article>`}).join('')}catch{box.innerHTML='<div class="suite-empty">Network relays unavailable. Portfolio and market features remain active.</div>'}}
function eventById(id){return state.feedEvents.find(e=>e.id===id)}
async function replyEvent(id){const src=eventById(id);if(!src||!state.nostrPub)return toastSafe('Connect Social ID first');const text=prompt('Reply');if(!text?.trim())return;relayPublish(await nostrSign(1,text.trim(),[['e',src.id,'','reply'],['p',src.pubkey],['t','rwa-trading']]));toastSafe('Reply published');setTimeout(loadNetworkFeed,700)}
async function likeEvent(id){const src=eventById(id);if(!src||!state.nostrPub)return toastSafe('Connect Social ID first');relayPublish(await nostrSign(7,'+',[['e',src.id],['p',src.pubkey]]));toastSafe('Reaction published');setTimeout(loadNetworkFeed,700)}
async function repostEvent(id){const src=eventById(id);if(!src||!state.nostrPub)return toastSafe('Connect Social ID first');relayPublish(await nostrSign(6,JSON.stringify(src),[['e',src.id],['p',src.pubkey]]));toastSafe('Repost published');setTimeout(loadNetworkFeed,700)}
async function bookmarkEvent(id){const list=jget(LS.bookmarks,[]);if(!list.includes(id))list.unshift(id);jset(LS.bookmarks,list.slice(0,200));if(state.nostrPub)try{relayPublish(await nostrSign(10003,'',list.map(x=>['e',x])))}catch{};toastSafe('Bookmarked')}
function renderIntel(){if(typeof S==='undefined'||!S.pairs?.length)return;const xs=S.pairs.filter(x=>Number.isFinite(x.change)&&Number.isFinite(x.vol)),gain=xs.filter(x=>x.change>0).length,loss=xs.filter(x=>x.change<0).length;if($('intelBreadth'))$('intelBreadth').textContent=`${gain} ↑ / ${loss} ↓`;const x=selected();if($('intelMomentum'))$('intelMomentum').textContent=x?pct(x.change):'—';let ratio=null;if(S.klines?.length>21){const a=S.klines,cur=Number(a.at(-1).v),avg=a.slice(-21,-1).reduce((s,k)=>s+Number(k.v||0),0)/20;ratio=avg?cur/avg:null}if($('intelVolSpike'))$('intelVolSpike').textContent=ratio?`${ratio.toFixed(2)}× 20-bar avg`:'—';const buy=Number(($('buyPct')?.textContent||'50').replace('%',''));if($('intelSentiment'))$('intelSentiment').textContent=Number.isFinite(buy)?`${buy.toFixed(0)}% buy pressure`:'—';const recent=state.tradeWindow.filter(t=>t.symbol===S.selected&&Date.now()-t.time<120000),avg=recent.length?recent.reduce((s,t)=>s+t.notional,0)/recent.length:0,cut=Math.max(10000,avg*5),large=recent.filter(t=>t.notional>=cut),lb=large.filter(t=>t.side==='BUY').reduce((s,t)=>s+t.notional,0),ls=large.filter(t=>t.side==='SELL').reduce((s,t)=>s+t.notional,0),net=lb-ls;if($('intelWhale'))$('intelWhale').textContent=large.length?`${large.length} · ${net>=0?'BUY':'SELL'} ${compact(Math.abs(net))}`:'No large trades';if($('intelSmart'))$('intelSmart').textContent=large.length?(lb+ls?`${(lb/(lb+ls)*100).toFixed(0)}% large-buy flow`:'—'):'Neutral';const top=[...xs].sort((a,b)=>(Math.abs(b.change)*Math.log10((b.vol||1)+10))-(Math.abs(a.change)*Math.log10((a.vol||1)+10))).slice(0,8),box=$('intelTrending');if(box)box.innerHTML=top.map((v,i)=>`<button data-suite-symbol="${esc(v.symbol)}"><b>#${i+1} ${esc(v.base)}</b><span class="${v.change>=0?'up':'down'}">${esc(pct(v.change))}</span><small>${esc(money(v.price))} · Vol ${esc(compact(v.vol))}</small></button>`).join('')}
async function loadVerifiedAssets(){try{const r=await fetch('rwa-assets.json?'+Date.now(),{cache:'no-store'}),j=await r.json();state.verifiedAssets=Array.isArray(j.verified)?j.verified:[]}catch{state.verifiedAssets=[]}}
async function loadRevenueStatus(){try{const r=await fetch('rwa-execution-config.json?'+Date.now(),{cache:'no-store'}),c=await r.json(),b=c.builder||{},on=!!(b.enabled&&/^0x[a-fA-F0-9]{40}$/.test(b.address||'')&&Number(b.feeTenthsBp)>0);state.revenue={on,b};status('revenueStatus',on?'Revenue ON':'Revenue OFF',on?'ok':'');if($('revenueDetail'))$('revenueDetail').textContent=on?`ON · ${short(b.address)} · fee ${b.feeTenthsBp} tenths bp`:'OFF · builder wallet not configured'}catch{status('revenueStatus','Revenue OFF','');}}
function rwaDrafts(){return jget(LS.rwaDrafts,[])}
function docLinks(a){const xs=[['Ownership',a.ownership],['Appraisal',a.appraisal],['Legal',a.legal],['Document',a.document]].filter(x=>x[1]);return xs.length?xs.map(x=>`<a href="${esc(x[1])}" target="_blank" rel="noopener">${x[0]}</a>`).join(' '):'<span>No documents</span>'}
function renderRwa(){const verified=state.verifiedAssets,drafts=rwaDrafts(),box=$('rwaAssetRows');if(!box)return;if($('rwaVerifiedCount'))$('rwaVerifiedCount').textContent=String(verified.length);if($('rwaDraftCount'))$('rwaDraftCount').textContent=String(drafts.length);const rows=[...verified.map(a=>({...a,_verified:true})),...drafts.map(a=>({...a,_verified:false}))];box.innerHTML=rows.length?rows.map(a=>`<article class="asset-card ${a._verified?'verified':''}"><header><div><small>${a._verified?'VERIFIED ASSET':'DRAFT · UNVERIFIED'}</small><h3>${esc(a.name)}</h3></div><span>${esc(a.type||'Asset')}</span></header><div class="asset-metrics"><div><small>NAV</small><b>${esc(money(a.nav))}</b></div><div><small>YIELD</small><b>${a.yield!=null?esc(pct(a.yield)):'—'}</b></div><div><small>LOCATION</small><b>${esc(a.location||'—')}</b></div></div><small>Issuer/SPV · ${esc(a.issuer||'not provided')}</small><footer><div>${docLinks(a)}</div>${a._verified?'<button>Verified</button>':`<button data-rwa-verify="${esc(String(a.id))}">Start verification</button>`}</footer></article>`).join(''):'<div class="suite-empty">No verified RWA assets yet. Drafts remain explicitly unverified until reviewer signature + registry publication.</div>'}
function addRwaDraft(){const name=$('rwaName')?.value.trim();if(!name)return toastSafe('Asset name is required');const d={id:Date.now(),name,type:$('rwaType')?.value.trim()||'Real Estate',nav:Number($('rwaNav')?.value||0),yield:Number($('rwaYield')?.value||0),location:$('rwaLocation')?.value.trim()||'',issuer:$('rwaIssuer')?.value.trim()||'',ownership:$('rwaOwnership')?.value.trim()||'',appraisal:$('rwaAppraisal')?.value.trim()||'',legal:$('rwaLegal')?.value.trim()||''};const a=rwaDrafts();a.unshift(d);jset(LS.rwaDrafts,a.slice(0,60));renderRwa();toastSafe('Saved as UNVERIFIED draft')}
function startRwaVerification(id){const d=rwaDrafts().find(x=>String(x.id)===String(id));if(!d)return;const w=state.wallet||activeWallet(),pkg={asset:String(d.id),issuer:d.issuer||'',ownership:d.ownership||'',appraisal:d.appraisal||'',legal:d.legal||'',checks:{issuer:false,ownership:false,appraisal:false,legal:false,kyb:false,disclosure:false},nav:d.nav?[{date:new Date().toISOString().slice(0,10),value:d.nav,ts:Date.now()}]:[]};localStorage.setItem(`rwa_verify_v1:${w||'anon'}`,JSON.stringify(pkg));if(window.RWAOps?.activate){window.RWAOps.activate('verify');toastSafe('Verification package opened · reviewer checks remain required')}else toastSafe('Verification package prepared. Open Verify when operations module is ready')}
async function init(){state.profile=jget(LS.profile,{name:'',about:'',picture:''});syncWallet();await Promise.all([loadVerifiedAssets(),loadRevenueStatus()]);renderRwa();renderWatch();renderCopy();renderProfile();renderPortfolio();renderIntel();startAlertWatch();let tries=0;const t=setInterval(()=>{tries++;if(installTradeProbe()||tries>60)clearInterval(t)},100);if(state.wallet)loadHyperliquid(state.wallet);const tab=jget(LS.suiteTab,'profile');setSuiteTab(['profile','leaderboard','copy','watch','portfolio','feed','intel','rwa'].includes(tab)?tab:'profile');setInterval(()=>{renderWatch();renderIntel();checkAlerts();if(state.wallet&&document.visibilityState==='visible'&&state.hl)renderPortfolio()},3500)}
document.addEventListener('click',async e=>{const st=e.target.closest('[data-suite-tab]');if(st){e.preventDefault();setSuiteTab(st.dataset.suiteTab);return}const nav=e.target.closest('[data-mobile-nav]');if(nav&&['hub','portfolio'].includes(nav.dataset.mobileNav)){e.preventDefault();openSuite(nav.dataset.mobileNav==='portfolio'?'portfolio':'profile');return}if(e.target.closest('[data-suite-close]')){e.preventDefault();closeSuite();return}if(e.target.closest('#connectNostrProfile,#connectNostrFeed'))return connectNostr();if(e.target.closest('#connectWallet,#portfolioConnect'))return connectWallet();if(e.target.closest('#saveProfile'))return saveProfile();if(e.target.closest('#refreshProfilePnl,#refreshPortfolio'))return state.wallet?loadHyperliquid(state.wallet):connectWallet();const per=e.target.closest('[data-leader-period]');if(per){state.leaderPeriod=per.dataset.leaderPeriod;qa('[data-leader-period]').forEach(b=>b.classList.toggle('active',b===per));return loadLeaderboard()}if(e.target.closest('#inspectTrader'))return inspectTrader();const vt=e.target.closest('[data-view-trader]');if(vt)return viewTrader(vt.dataset.viewTrader,vt.dataset.pub||'');const follow=e.target.closest('[data-follow-pub]');if(follow)return followPubkey(follow.dataset.followPub);const cp=e.target.closest('[data-copy-wallet]');if(cp){if($('copyTarget'))$('copyTarget').value=cp.dataset.copyWallet;openSuite('copy');return}if(e.target.closest('#startCopy'))return startCopy();if(e.target.closest('#stopCopy'))return stopCopy();if(e.target.closest('#refreshCopy'))return checkCopySignals();if(e.target.closest('#addWatch'))return addCurrentWatch();const wr=e.target.closest('[data-watch-remove]');if(wr){jset(LS.watch,watchlist().filter(x=>x!==wr.dataset.watchRemove));return renderWatch()}if(e.target.closest('#addAlert'))return addAlert();const ar=e.target.closest('[data-alert-remove]');if(ar){jset(LS.alerts,alerts().filter(x=>String(x.id)!==ar.dataset.alertRemove));return renderAlerts()}if(e.target.closest('#publishNetworkPost'))return publishNetworkPost();const re=e.target.closest('[data-reply]');if(re)return replyEvent(re.dataset.reply);const li=e.target.closest('[data-like]');if(li)return likeEvent(li.dataset.like);const rp=e.target.closest('[data-repost]');if(rp)return repostEvent(rp.dataset.repost);const bm=e.target.closest('[data-bookmark]');if(bm)return bookmarkEvent(bm.dataset.bookmark);if(e.target.closest('#refreshIntel'))return renderIntel();const sym=e.target.closest('[data-suite-symbol]');if(sym){if(typeof selectPair==='function')selectPair(sym.dataset.suiteSymbol,false);closeSuite();return}if(e.target.closest('#addRwaDraft'))return addRwaDraft();const rv=e.target.closest('[data-rwa-verify]');if(rv)return startRwaVerification(rv.dataset.rwaVerify)});
window.addEventListener('rwa:wallet-login',()=>{syncWallet();if(state.wallet)loadHyperliquid(state.wallet)});window.addEventListener('rwa:wallet-logout',syncWallet);window.addEventListener('rwa:agent-changed',renderCopy);addEventListener('resize',()=>{if(innerWidth>680){document.body.classList.remove('suite-open');const s=$('suite');if(s)s.style.display='block'}else if(!document.body.classList.contains('suite-open')){const s=$('suite');if(s)s.style.display='none'}});
window.RWASuite={version:'2.0.0',open:openSuite,connectWallet,connectNostr,loadHyperliquid,inspectTrader,viewTrader,startCopy,stopCopy,state:()=>({...state,networkProfiles:undefined})};
init();
})();