(()=>{
'use strict';
if(window.RWATestnetE2E)return;
const PREFIX='rwa_testnet_e2e_v3',MAINNET_GATE='rwa_mainnet_gate_v1',ENV_KEY='rwa_exchange_env_v1';
const names={wallet:'Wallet login',collateral:'Test collateral',agent:'API wallet authorized',entry:'Filled entry',position:'Position observed',tpsl:'Atomic TP/SL',modify:'Order modified',cancel:'Order canceled',close:'Position closed',history:'Trade history observed',pnl:'PnL observed'};
const required=['wallet','collateral','agent','entry','position','tpsl','modify','cancel','close','history','pnl'];
const wallet=()=>String(window.RWAWalletAuth?.session?.()?.wallet||'').toLowerCase(),key=()=>`${PREFIX}:${wallet()||'none'}`;
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const toast=t=>typeof window.toast==='function'?window.toast(t):console.log(t);
function load(){try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return{}}}
function save(v){localStorage.setItem(key(),JSON.stringify(v));render();return v}
function orderIds(value,out=new Set(),depth=0){if(depth>9||value==null)return out;if(Array.isArray(value)){for(const x of value)orderIds(x,out,depth+1);return out}if(typeof value!=='object')return out;for(const [k,v] of Object.entries(value)){if(/^(oid|orderId)$/i.test(k)&&(typeof v==='number'||typeof v==='string')&&String(v).trim())out.add(String(v));else orderIds(v,out,depth+1)}return out}
function venueDetail(result,fallback){const ids=[...orderIds(result)];return ids.length?`${fallback} · order ${ids.slice(0,8).join(',')}`:`${fallback} · venue accepted`}
function mark(name,detail='',source='venue'){if(!wallet()||!Object.prototype.hasOwnProperty.call(names,name))return;const v=load();v[name]={ts:Date.now(),detail:String(detail||''),source};save(v)}
function validEvidence(k,row){if(!row||!Number(row.ts))return false;return k==='wallet'?row.source==='wallet-signature':row.source==='venue'}
function proof(v=load()){const p={};for(const k of required){const r=v[k];if(r)p[k]={ts:r.ts,detail:r.detail,source:r.source}}return p}
function gate(){try{return JSON.parse(localStorage.getItem(MAINNET_GATE)||'null')}catch{return null}}
function localVerified(){const w=wallet(),g=gate();return !!(w&&g?.status==='E2E_VERIFIED'&&String(g.wallet||'').toLowerCase()===w&&Number(g.verifiedAt)>0)}
function status(){const v=load(),checks=Object.keys(names).map(k=>({key:k,name:names[k],required:required.includes(k),ok:validEvidence(k,v[k]),detail:v[k]?.detail||'',source:v[k]?.source||'',ts:v[k]?.ts||0})),w=wallet(),g=gate(),core=window.RWAExchangeCore;return{wallet:w,checks,passed:required.every(k=>validEvidence(k,v[k])),localE2EVerified:localVerified(),globalMainnetReady:!!core?.globalMainnetReady?.(),mainnetUnlocked:!!core?.mainnetUnlocked?.(),gate:g}}
function reset(){if(wallet())localStorage.removeItem(key());localStorage.removeItem(MAINNET_GATE);localStorage.setItem(ENV_KEY,'testnet');try{window.RWAExchangeCore?.setEnv?.('testnet')}catch{}render()}
function unlock(){const s=status();if(!s.passed)throw Error('Complete the real-wallet testnet E2E first');if(!s.wallet)throw Error('Wallet session missing');if(!confirm('Save this venue-backed TESTNET E2E as the wallet execution gate? This does NOT bypass the global production Launch Gate.'))return false;localStorage.setItem(MAINNET_GATE,JSON.stringify({status:'E2E_VERIFIED',wallet:s.wallet,verifiedAt:Date.now(),environment:'testnet',proof:proof()}));const core=window.RWAExchangeCore;if(core?.globalMainnetReady?.()){core.setEnv('mainnet');toast('Wallet E2E gate saved · global Launch Gate READY · MAINNET available')}else{try{core?.setEnv?.('testnet')}catch{}toast('Wallet E2E gate saved · MAINNET remains locked until the global Launch Gate is READY')}render();return true}
function observe(s){if(!s||s.env!=='testnet'||!wallet())return;if(window.RWAWalletAuth?.isLoggedIn?.())mark('wallet',wallet(),'wallet-signature');if(Number(s.account?.equity||0)>0)mark('collateral',`equity ${Number(s.account.equity).toFixed(2)}`);if((s.positions||[]).length)mark('position',`${s.positions.length} open · ${s.positions.map(p=>`${p.coin}:${p.szi}`).slice(0,4).join(' ')}`);if((s.fills||[]).length){mark('history',`${s.fills.length} fills`);if(Number.isFinite(Number(s.account?.unrealizedPnl)))mark('pnl',`PnL ${Number(s.account.unrealizedPnl||0).toFixed(4)}`)}const a=window.RWAExecutionAPI?.agent?.status?.(true);if(a)mark('agent',a.address||'authorized')}
function wrap(){const c=window.RWAExchangeCore;if(!c||c.__e2eWrappedV3)return false;c.__e2eWrappedV3=true;const submit=c.submit.bind(c),modify=c.modify.bind(c),cancel=c.cancel.bind(c),close=c.closePosition.bind(c);c.submit=async o=>{if(c.state?.().env!=='testnet')throw Error('E2E evidence can only be recorded on testnet');const r=await submit(o);mark('entry',venueDetail(r?.entry||r,`${o?.type||'MARKET'} ${o?.coin||''}`));if(r?.protection?.length)mark('tpsl',venueDetail(r.entry||r,`${r.protection.length} atomic protection order(s)`));return r};c.modify=async o=>{const r=await modify(o);if(c.state?.().env==='testnet')mark('modify',venueDetail(r,`${o?.coin||''} #${o?.oid||''}`));return r};c.cancel=async(coin,oid)=>{const r=await cancel(coin,oid);if(c.state?.().env==='testnet')mark('cancel',venueDetail(r,`${coin} #${oid}`));return r};c.closePosition=async coin=>{const r=await close(coin);if(c.state?.().env==='testnet')mark('close',venueDetail(r,coin));return r};return true}
async function waitFor(fn,timeout=12000,step=600){const end=Date.now()+timeout;let v;while(Date.now()<end){v=await fn();if(v)return v;await sleep(step)}return null}
async function autoRun(){
  const c=window.RWAExchangeCore,a=window.RWAExecutionAPI;if(!c||!a)throw Error('Execution engine is still loading');if(!confirm('Run ONE-CLICK REAL TESTNET E2E? This places a very small real Hyperliquid TESTNET position, verifies TP/SL + modify/cancel, then closes it.'))return;
  reset();if(!window.RWAWalletAuth?.isLoggedIn?.())await window.RWAWalletAuth.login();c.setEnv('testnet');await c.refresh();const w=wallet();if(!w)throw Error('Wallet login failed');mark('wallet',w,'wallet-signature');
  const ch=await a.account.state(true),equity=Number(ch?.marginSummary?.accountValue||0);if(!(equity>0))throw Error('Add Hyperliquid testnet collateral first');mark('collateral',`equity ${equity.toFixed(2)}`);
  let ag=a.agent.status(true);if(!ag){toast('Approve the testnet API Wallet once…');await a.agent.authorize(true);ag=a.agent.status(true)}const verified=await a.agent.verify(true,{force:true});if(verified.valid!==true)throw Error('API wallet was not verified by Hyperliquid');mark('agent',ag.address||'authorized');
  const mids=await a.info('allMids',{},true),coin=Number(mids.BTC)>0?'BTC':Object.keys(mids||{}).find(k=>Number(mids[k])>0);if(!coin)throw Error('No testnet market available');const mid=Number(mids[coin]),notional=Math.max(12,Math.min(25,equity*.02));
  const restPx=mid*.70,restSize=notional/restPx,rest=await a.orders.limit({coin,side:'BUY',price:restPx,size:restSize,reduceOnly:false,leverage:1,testnet:true,preferAgent:true});let oid=[...orderIds(rest)][0];if(!oid){oid=await waitFor(async()=>{const rows=await a.orders.open(true),x=(rows||[]).find(o=>String(o.coin).toUpperCase()===coin&&String(o.side||'').toUpperCase().includes('B'));return x?.oid||null},8000)}if(!oid)throw Error('Could not observe resting test order');
  const modified=await a.orders.modify({coin,oid:Number(oid),side:'BUY',price:mid*.71,size:restSize,reduceOnly:false,testnet:true,preferAgent:true});mark('modify',venueDetail(modified,`${coin} #${oid}`));const canceled=await a.orders.cancel({coin,oid:Number(oid),testnet:true,preferAgent:true});mark('cancel',venueDetail(canceled,`${coin} #${oid}`));
  const size=notional/mid,tp=mid*1.10,sl=mid*.90,entry=await c.submit({type:'MARKET',coin,side:'BUY',leverage:1,size,tp,sl});mark('entry',venueDetail(entry?.entry||entry,`MARKET ${coin}`));mark('tpsl',venueDetail(entry?.entry||entry,'atomic TP + SL'));
  const pos=await waitFor(async()=>{await c.refresh({silent:true});return c.state().positions.find(p=>String(p.coin).toUpperCase()===coin)},12000);if(!pos)throw Error('Filled position was not observed');mark('position',`${coin} ${pos.szi}`);
  const closed=await c.closePosition(coin);mark('close',venueDetail(closed,coin));try{await a.orders.cancelAll({testnet:true,preferAgent:true})}catch{}await waitFor(async()=>{await c.refresh({silent:true});return !c.state().positions.some(p=>String(p.coin).toUpperCase()===coin)},12000);
  const fills=await a.account.fills(true);if(!(fills||[]).length)throw Error('Trade history not observed');mark('history',`${fills.length} fills`);const final=await a.account.state(true);mark('pnl',`unrealized ${Number(final?.marginSummary?.totalNtlPos||0).toFixed(4)} · venue account refreshed`);render();toast('REAL TESTNET E2E PASS candidate · publish the signed proof next');
}
async function sha256(s){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(s));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function publishProof(){const s=status();if(!s.passed)throw Error('E2E must PASS before publishing proof');const evidence=proof(),verified_at=Date.now(),hash=await sha256(JSON.stringify(evidence)),message=`RWA TESTNET E2E PROOF\nWallet: ${s.wallet}\nVerified At: ${verified_at}\nEvidence Hash: ${hash}`,p=window.RWAWalletAuth?.provider?.()||window.RWAProvider||window.ethereum,hex='0x'+[...new TextEncoder().encode(message)].map(b=>b.toString(16).padStart(2,'0')).join('');let signature;try{signature=await p.request({method:'personal_sign',params:[hex,s.wallet]})}catch{signature=await p.request({method:'personal_sign',params:[s.wallet,hex]})}const pkg={schema:1,wallet:s.wallet,status:'E2E_VERIFIED',environment:'testnet',verified_at,evidence_hash:hash,evidence,message,signature};const title=`[E2E-PROOF] ${s.wallet}`,body=`Submit this issue to register a wallet-bound testnet proof.\n\nE2E_PROOF_JSON_START\n\`\`\`json\n${JSON.stringify(pkg,null,2)}\n\`\`\`\nE2E_PROOF_JSON_END`;window.open(`https://github.com/narzulalistiqlal/rwa/issues/new?title=${encodeURIComponent(title)}&body=${encodeURIComponent(body)}`,'_blank','noopener')}
function inject(){const box=document.getElementById('exPreflightRows');if(!box||document.getElementById('exE2E'))return false;const root=document.createElement('div');root.id='exE2E';root.innerHTML='<div style="margin-top:8px;border-top:1px solid #202833;padding-top:7px"><small style="color:#727c89;font:700 6px system-ui">REAL-WALLET TESTNET E2E · VENUE-BACKED</small><div id="exE2ERows" class="rwa-preflight"></div><div class="rwa-ex-actions"><button id="exE2EAuto">Run ONE-CLICK REAL E2E</button><button id="exE2EPublish">Publish E2E Proof</button><button id="exMainnetUnlock">Save Wallet E2E Gate</button><button id="exE2EReset" class="danger">Reset</button></div></div>';box.after(root);document.getElementById('exE2EAuto').onclick=()=>autoRun().catch(e=>toast(e.message));document.getElementById('exE2EPublish').onclick=()=>publishProof().catch(e=>toast(e.message));document.getElementById('exMainnetUnlock').onclick=()=>{try{unlock()}catch(e){toast(e.message)}};document.getElementById('exE2EReset').onclick=()=>{if(confirm('Reset this wallet E2E evidence and local wallet gate?'))reset()};return true}
function render(){if(!inject())return;const s=status(),box=document.getElementById('exE2ERows');if(!box)return;box.innerHTML=s.checks.filter(x=>x.required||x.ok).map(x=>`<div class="rwa-check ${x.ok?'ok':'bad'}"><span>${x.name}</span><b>${x.ok?'PASS':'PENDING'}${x.detail?' · '+x.detail:''}</b></div>`).join('')+`<div class="rwa-check ${s.passed?'ok':'bad'}"><span>REAL E2E RESULT</span><b>${s.passed?'PASS · venue-backed':'INCOMPLETE'}</b></div><div class="rwa-check ${s.localE2EVerified?'ok':'bad'}"><span>WALLET E2E GATE</span><b>${s.localE2EVerified?'SAVED':'NOT SAVED'}</b></div><div class="rwa-check ${s.globalMainnetReady?'ok':'bad'}"><span>GLOBAL LAUNCH GATE</span><b>${s.globalMainnetReady?'READY':'LOCKED'}</b></div>`;const u=document.getElementById('exMainnetUnlock'),p=document.getElementById('exE2EPublish');if(u){u.disabled=!s.passed||s.localE2EVerified;u.textContent=s.localE2EVerified?'WALLET E2E GATE SAVED':'Save Wallet E2E Gate'}if(p)p.disabled=!s.passed}
window.addEventListener('rwa:exchange-state',e=>{observe(e.detail);wrap();render()});window.addEventListener('rwa:wallet-login',()=>{if(window.RWAWalletAuth?.isLoggedIn?.())mark('wallet',wallet(),'wallet-signature');wrap();render()});window.addEventListener('rwa:agent-changed',()=>{const a=window.RWAExecutionAPI?.agent?.status?.(true);if(a)mark('agent',a.address||'authorized');render()});
window.RWATestnetE2E={version:'3.1.0',status,reset,unlock,autoRun,publishProof,required,evidence:()=>load()};let tries=0;const t=setInterval(()=>{tries++;if(wrap()&&inject()){clearInterval(t);render()}if(tries>120)clearInterval(t)},50);
})();