(()=>{
'use strict';
if(window.RWATestnetE2E)return;
function loadActions(){if(window.RWAExchangeActions||[...document.scripts].some(s=>(s.getAttribute('src')||'').startsWith('exchange-actions.js')))return;const s=document.createElement('script');s.src='exchange-actions.js?v=1';s.async=true;document.body.appendChild(s)}
loadActions();
const PREFIX='rwa_testnet_e2e_v1';const MAINNET_GATE='rwa_mainnet_gate_v1';
const names={wallet:'Wallet login',collateral:'Test collateral',agent:'API wallet authorized',entry:'Entry order',position:'Position observed',tpsl:'TP/SL submitted',modify:'Order modified',cancel:'Order canceled',close:'Position closed',history:'Trade history observed',pnl:'PnL observed'};
const required=['wallet','collateral','entry','position','tpsl','modify','cancel','close','history','pnl'];
const wallet=()=>String(window.RWAWalletAuth?.session?.()?.wallet||'').toLowerCase();
const key=()=>`${PREFIX}:${wallet()||'none'}`;
function load(){try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return{}}}
function save(v){localStorage.setItem(key(),JSON.stringify(v));render();return v}
function mark(name,detail=''){if(!wallet())return;const v=load();if(!v[name])v[name]={ts:Date.now(),detail:String(detail||'')};save(v)}
function status(){const v=load(),checks=Object.keys(names).map(k=>({key:k,name:names[k],required:required.includes(k),ok:!!v[k],detail:v[k]?.detail||'',ts:v[k]?.ts||0}));return{wallet:wallet(),checks,passed:required.every(k=>!!v[k]),mainnetUnlocked:localStorage.getItem(MAINNET_GATE)==='E2E_VERIFIED'}}
function reset(){if(wallet())localStorage.removeItem(key());localStorage.removeItem(MAINNET_GATE);render()}
function unlock(){const s=status();if(!s.passed)throw Error('Complete the real-wallet testnet E2E checklist first');if(!confirm('Testnet E2E is complete. Unlock MAINNET trading on this browser?'))return false;localStorage.setItem(MAINNET_GATE,'E2E_VERIFIED');window.RWAExchangeCore?.setEnv?.('mainnet');render();return true}
function observe(s){if(!s||s.env!=='testnet'||!wallet())return;mark('wallet',wallet());if(Number(s.account?.equity||0)>0)mark('collateral',`equity ${Number(s.account.equity).toFixed(2)}`);if((s.positions||[]).length)mark('position',`${s.positions.length} open`);if((s.fills||[]).length){mark('history',`${s.fills.length} fills`);const hasPnl=(s.fills||[]).some(f=>Number.isFinite(Number(f.closedPnl))&&Number(f.closedPnl)!==0)||Number.isFinite(Number(s.account?.unrealizedPnl));if(hasPnl)mark('pnl',`PnL ${Number(s.account?.unrealizedPnl||0).toFixed(2)}`)}const a=window.RWAExecutionAPI?.agent?.status?.(true);if(a)mark('agent',a.address||'authorized')}
function wrap(){const c=window.RWAExchangeCore;if(!c||c.__e2eWrapped)return false;c.__e2eWrapped=true;const submit=c.submit.bind(c),modify=c.modify.bind(c),cancel=c.cancel.bind(c),close=c.closePosition.bind(c);c.submit=async o=>{const r=await submit(o);mark('entry',`${o?.type||'MARKET'} ${o?.coin||''}`);if(r?.protection?.length)mark('tpsl',`${r.protection.length} protection orders`);return r};c.modify=async o=>{const r=await modify(o);mark('modify',`${o?.coin||''} #${o?.oid||''}`);return r};c.cancel=async(coin,oid)=>{const r=await cancel(coin,oid);mark('cancel',`${coin} #${oid}`);return r};c.closePosition=async coin=>{const r=await close(coin);mark('close',coin);return r};return true}
function inject(){const box=document.getElementById('exPreflightRows');if(!box||document.getElementById('exE2E'))return false;const root=document.createElement('div');root.id='exE2E';root.innerHTML='<div style="margin-top:8px;border-top:1px solid #202833;padding-top:7px"><small style="color:#727c89;font:700 6px system-ui">REAL-WALLET TESTNET E2E</small><div id="exE2ERows" class="rwa-preflight"></div><div class="rwa-ex-actions"><button id="exE2ERefresh">Refresh E2E</button><button id="exMainnetUnlock">Unlock Mainnet after PASS</button><button id="exE2EReset" class="danger">Reset E2E</button></div></div>';box.after(root);document.getElementById('exE2ERefresh').onclick=()=>{window.RWAExchangeCore?.refresh?.();render()};document.getElementById('exMainnetUnlock').onclick=()=>{try{unlock()}catch(e){if(typeof toast==='function')toast(e.message)}};document.getElementById('exE2EReset').onclick=()=>{if(confirm('Reset this wallet testnet E2E evidence?'))reset()};return true}
function render(){if(!inject())return;const s=status(),box=document.getElementById('exE2ERows');if(!box)return;box.innerHTML=s.checks.filter(x=>x.required||x.ok).map(x=>`<div class="rwa-check ${x.ok?'ok':'bad'}"><span>${x.name}${x.required?'':' · optional'}</span><b>${x.ok?'PASS':'PENDING'}${x.detail?' · '+x.detail:''}</b></div>`).join('')+`<div class="rwa-check ${s.passed?'ok':'bad'}"><span>REAL E2E RESULT</span><b>${s.passed?'PASS':'INCOMPLETE'}</b></div>`;const b=document.getElementById('exMainnetUnlock');if(b){b.disabled=!s.passed||s.mainnetUnlocked;b.textContent=s.mainnetUnlocked?'MAINNET UNLOCKED':'Unlock Mainnet after PASS'}}
window.addEventListener('rwa:exchange-state',e=>{observe(e.detail);wrap();render()});window.addEventListener('rwa:wallet-login',()=>{mark('wallet',wallet());wrap();render()});window.addEventListener('rwa:agent-changed',()=>{const a=window.RWAExecutionAPI?.agent?.status?.(true);if(a)mark('agent',a.address||'authorized');render()});
window.RWATestnetE2E={status,mark,reset,unlock,required};let tries=0;const t=setInterval(()=>{tries++;if(wrap()&&inject()){clearInterval(t);render()}if(tries>100)clearInterval(t)},50);
})();