(()=>{
'use strict';
if(window.RWATestnetE2E)return;
function loadActions(){if(window.RWAExchangeActions||[...document.scripts].some(s=>(s.getAttribute('src')||'').startsWith('exchange-actions.js')))return;const s=document.createElement('script');s.src='exchange-actions.js?v=1';s.async=true;document.body.appendChild(s)}
loadActions();
const PREFIX='rwa_testnet_e2e_v2';const MAINNET_GATE='rwa_mainnet_gate_v1';const ENV_KEY='rwa_exchange_env_v1';
const names={wallet:'Wallet login',collateral:'Test collateral',agent:'API wallet authorized',entry:'Entry order',position:'Position observed',tpsl:'TP/SL submitted',modify:'Order modified',cancel:'Order canceled',close:'Position closed',history:'Trade history observed',pnl:'PnL observed'};
const required=['wallet','collateral','entry','position','tpsl','modify','cancel','close','history','pnl'];
const wallet=()=>String(window.RWAWalletAuth?.session?.()?.wallet||'').toLowerCase();
const key=()=>`${PREFIX}:${wallet()||'none'}`;
function load(){try{return JSON.parse(localStorage.getItem(key())||'{}')}catch{return{}}}
function save(v){localStorage.setItem(key(),JSON.stringify(v));render();return v}
function orderIds(value,out=new Set(),depth=0){if(depth>8||value==null)return out;if(Array.isArray(value)){for(const x of value)orderIds(x,out,depth+1);return out}if(typeof value!=='object')return out;for(const [k,v] of Object.entries(value)){if(/^(oid|orderId)$/i.test(k)&&(typeof v==='number'||typeof v==='string')&&String(v).trim())out.add(String(v));else orderIds(v,out,depth+1)}return out}
function venueDetail(result,fallback){const ids=[...orderIds(result)];return ids.length?`${fallback} · order ${ids.slice(0,6).join(',')}`:`${fallback} · venue accepted`}
function mark(name,detail='',source='venue'){if(!wallet()||!Object.prototype.hasOwnProperty.call(names,name))return;const v=load(),next={ts:Date.now(),detail:String(detail||''),source};if(!v[name]||(!v[name].detail&&next.detail)||v[name].source==='legacy')v[name]=next;save(v)}
function validEvidence(k,row){if(!row||!Number(row.ts))return false;if(k==='wallet')return row.source==='wallet-signature';return row.source==='venue'}
function gate(){try{const g=JSON.parse(localStorage.getItem(MAINNET_GATE)||'null');return g&&typeof g==='object'?g:null}catch{return null}}
function status(){const v=load(),checks=Object.keys(names).map(k=>({key:k,name:names[k],required:required.includes(k),ok:validEvidence(k,v[k]),detail:v[k]?.detail||'',source:v[k]?.source||'',ts:v[k]?.ts||0})),w=wallet(),g=gate();return{wallet:w,checks,passed:required.every(k=>validEvidence(k,v[k])),mainnetUnlocked:!!(w&&g?.status==='E2E_VERIFIED'&&String(g.wallet||'').toLowerCase()===w),gate:g}}
function reset(){if(wallet())localStorage.removeItem(key());localStorage.removeItem(MAINNET_GATE);localStorage.setItem(ENV_KEY,'testnet');try{window.RWAExchangeCore?.setEnv?.('testnet')}catch{}render()}
function proof(v){const p={};for(const k of required){const r=v[k];p[k]={ts:r.ts,detail:r.detail,source:r.source}}return p}
function unlock(){const s=status();if(!s.passed)throw Error('Complete the real-wallet testnet E2E checklist first');if(!s.wallet)throw Error('Wallet session missing');if(!confirm('Testnet E2E is complete with venue-backed evidence. Unlock MAINNET trading for this wallet on this browser?'))return false;const v=load();localStorage.setItem(MAINNET_GATE,JSON.stringify({status:'E2E_VERIFIED',wallet:s.wallet,verifiedAt:Date.now(),environment:'testnet',proof:proof(v)}));window.RWAExchangeCore?.setEnv?.('mainnet');render();return true}
function observe(s){if(!s||s.env!=='testnet'||!wallet())return;if(window.RWAWalletAuth?.isLoggedIn?.())mark('wallet',wallet(),'wallet-signature');if(Number(s.account?.equity||0)>0)mark('collateral',`equity ${Number(s.account.equity).toFixed(2)}`,'venue');if((s.positions||[]).length)mark('position',`${s.positions.length} open · ${s.positions.map(p=>`${p.coin}:${p.szi}`).slice(0,4).join(' ')}`,'venue');if((s.fills||[]).length){mark('history',`${s.fills.length} fills`,'venue');if(Number.isFinite(Number(s.account?.unrealizedPnl)))mark('pnl',`PnL ${Number(s.account?.unrealizedPnl||0).toFixed(2)}`,'venue')}const a=window.RWAExecutionAPI?.agent?.status?.(true);if(a)mark('agent',a.address||'authorized','venue')}
function wrap(){const c=window.RWAExchangeCore;if(!c||c.__e2eWrapped)return false;c.__e2eWrapped=true;const submit=c.submit.bind(c),modify=c.modify.bind(c),cancel=c.cancel.bind(c),close=c.closePosition.bind(c);c.submit=async o=>{if(c.state?.().env!=='testnet')throw Error('Real E2E evidence can only be recorded on testnet');const r=await submit(o);mark('entry',venueDetail(r?.entry||r,`${o?.type||'MARKET'} ${o?.coin||''}`),'venue');if(r?.protection?.length)mark('tpsl',venueDetail(r.protection,`${r.protection.length} protection orders`),'venue');return r};c.modify=async o=>{if(c.state?.().env!=='testnet')return modify(o);const r=await modify(o);mark('modify',venueDetail(r,`${o?.coin||''} #${o?.oid||''}`),'venue');return r};c.cancel=async(coin,oid)=>{if(c.state?.().env!=='testnet')return cancel(coin,oid);const r=await cancel(coin,oid);mark('cancel',venueDetail(r,`${coin} #${oid}`),'venue');return r};c.closePosition=async coin=>{if(c.state?.().env!=='testnet')return close(coin);const r=await close(coin);mark('close',venueDetail(r,coin),'venue');return r};return true}
function inject(){const box=document.getElementById('exPreflightRows');if(!box||document.getElementById('exE2E'))return false;const root=document.createElement('div');root.id='exE2E';root.innerHTML='<div style="margin-top:8px;border-top:1px solid #202833;padding-top:7px"><small style="color:#727c89;font:700 6px system-ui">REAL-WALLET TESTNET E2E · VENUE-BACKED EVIDENCE</small><div id="exE2ERows" class="rwa-preflight"></div><div class="rwa-ex-actions"><button id="exE2ERefresh">Refresh E2E</button><button id="exMainnetUnlock">Unlock Mainnet after PASS</button><button id="exE2EReset" class="danger">Reset E2E</button></div></div>';box.after(root);document.getElementById('exE2ERefresh').onclick=()=>{window.RWAExchangeCore?.refresh?.();render()};document.getElementById('exMainnetUnlock').onclick=()=>{try{unlock()}catch(e){if(typeof toast==='function')toast(e.message)}};document.getElementById('exE2EReset').onclick=()=>{if(confirm('Reset this wallet testnet E2E evidence and lock mainnet?'))reset()};return true}
function render(){if(!inject())return;const s=status(),box=document.getElementById('exE2ERows');if(!box)return;box.innerHTML=s.checks.filter(x=>x.required||x.ok).map(x=>`<div class="rwa-check ${x.ok?'ok':'bad'}"><span>${x.name}${x.required?'':' · optional'}</span><b>${x.ok?'PASS':'PENDING'}${x.source?' · '+x.source:''}${x.detail?' · '+x.detail:''}</b></div>`).join('')+`<div class="rwa-check ${s.passed?'ok':'bad'}"><span>REAL E2E RESULT</span><b>${s.passed?'PASS · venue-backed':'INCOMPLETE'}</b></div>`;const b=document.getElementById('exMainnetUnlock');if(b){b.disabled=!s.passed||s.mainnetUnlocked;b.textContent=s.mainnetUnlocked?'MAINNET UNLOCKED FOR WALLET':'Unlock Mainnet after PASS'}}
window.addEventListener('rwa:exchange-state',e=>{observe(e.detail);wrap();render()});window.addEventListener('rwa:wallet-login',()=>{if(window.RWAWalletAuth?.isLoggedIn?.())mark('wallet',wallet(),'wallet-signature');wrap();render()});window.addEventListener('rwa:agent-changed',()=>{const a=window.RWAExecutionAPI?.agent?.status?.(true);if(a)mark('agent',a.address||'authorized','venue');render()});
window.RWATestnetE2E={version:'2.0.0',status,reset,unlock,required,evidence:()=>load()};let tries=0;const t=setInterval(()=>{tries++;if(wrap()&&inject()){clearInterval(t);render()}if(tries>100)clearInterval(t)},50);
})();
