"use client";
import * as React from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/app";
import { Button } from "@/components/ui";
import { assets } from "./data";
import { AssetCard, SearchBox, SectionHeader } from "./shared";
import "./discovery.css";

export function RwaDirectory(){
 const router=useRouter(); const [assetClass,setAssetClass]=React.useState("All"); const [jurisdiction,setJurisdiction]=React.useState("All Jurisdictions"); const [verified,setVerified]=React.useState(true); const [sort,setSort]=React.useState("AUM (High to Low)"); const [grid,setGrid]=React.useState(true); const [minYield,setMinYield]=React.useState(""); const [maxYield,setMaxYield]=React.useState("");
 const classes=["All","Real Estate","Private Credit","Treasury & Bonds","Commodities","Funds","Infrastructure"];
 const filtered=assets.filter(a=>(assetClass==="All"||a.className===assetClass)&&(!verified||a.verified));
 function reset(){setAssetClass("All");setJurisdiction("All Jurisdictions");setVerified(true);setSort("AUM (High to Low)");setMinYield("");setMaxYield("")}
 return <AppShell><main className="directory-layout rwa-directory page-pad"><aside className="filter-sidebar"><h3>SEARCH ASSETS</h3><SearchBox placeholder="Search assets, issuers, or tokens..." onSubmit={q=>router.push(`/search?q=${encodeURIComponent(q)}`)}/><h3>ASSET CLASS <button onClick={()=>setAssetClass("All")}>Clear</button></h3><div className="side-chip-list">{classes.map(x=><button key={x} data-active={assetClass===x?"true":undefined} onClick={()=>setAssetClass(x)}>{x}</button>)}</div><h3>JURISDICTION</h3><select value={jurisdiction} onChange={e=>setJurisdiction(e.target.value)}><option>All Jurisdictions</option><option>Singapore</option><option>United States</option><option>Germany</option><option>Switzerland</option></select><h3>YIELD RANGE (APY)</h3><div className="yield-range"><input aria-label="Minimum yield" value={minYield} onChange={e=>setMinYield(e.target.value)} placeholder="Min %"/><span>–</span><input aria-label="Maximum yield" value={maxYield} onChange={e=>setMaxYield(e.target.value)} placeholder="Max %"/></div><h3>MATURITY</h3><select onChange={()=>{}} defaultValue="All Maturity"><option>All Maturity</option><option>&lt; 1 year</option><option>1–3 years</option><option>3+ years</option></select><label className="verified-check">Verified Only <input type="checkbox" checked={verified} onChange={e=>setVerified(e.target.checked)}/></label><h3>ISSUER</h3><select onChange={()=>{}} defaultValue="All Issuers"><option>All Issuers</option><option>RWA Treasury</option><option>Harbourview Capital</option></select><h3>SORT BY</h3><select value={sort} onChange={e=>setSort(e.target.value)}><option>AUM (High to Low)</option><option>Yield (High to Low)</option><option>Newest</option></select><Button onClick={()=>router.push(`/rwa?class=${encodeURIComponent(assetClass)}&sort=${encodeURIComponent(sort)}`)}>Apply Filters</Button><Button variant="ghost" onClick={reset}>Reset</Button></aside>
 <section className="directory-main"><div className="directory-heading-row"><div><h1>RWA Directory</h1><p>Discover and explore tokenized real-world assets across global markets.</p></div><div><select value={sort} onChange={e=>setSort(e.target.value)}><option>AUM (High to Low)</option><option>Yield (High to Low)</option><option>Newest</option></select><div className="view-toggle"><button aria-pressed={grid} onClick={()=>setGrid(true)}>▦</button><button aria-pressed={!grid} onClick={()=>setGrid(false)}>☷</button></div></div></div><div className="asset-class-tabs">{classes.map((x,i)=><button key={x} data-active={assetClass===x?"true":undefined} onClick={()=>setAssetClass(x)}><span>◇</span><b>{x}</b><small>{[1248,412,286,214,156,126,54][i]}</small></button>)}</div><div className={grid?"asset-grid":"asset-grid list-view"}>{(filtered.length?filtered:assets).map(a=><AssetCard asset={a} key={a.slug}/>)}</div></section>
 <aside className="directory-side"><section className="panel"><SectionHeader title="TRENDING SECTORS" href="/rwa"/><div className="sector-list">{[["Private Credit","$5.42B AUM","+24.6%"],["Real Estate","$4.12B AUM","+18.3%"],["Infrastructure","$2.31B AUM","+15.7%"],["Treasury & Bonds","$1.86B AUM","+12.4%"],["Commodities","$678.4M AUM","+9.8%"]].map(([n,a,c])=><button key={n} onClick={()=>setAssetClass(n)}><span>◇</span><b>{n}<small>{a}</small></b><em>{c}</em></button>)}</div></section><section className="panel snapshot-list"><h2>MARKET SUMMARY <em>● Live</em></h2>{[["Total Assets","1,248","+6.42%"],["Total AUM","$14.87B","+7.83%"],["Avg. Yield (APY)","6.28%","+0.36%"],["Active Issuers","214","+5.11%"],["24H Volume","$382.6M","+12.7%"]].map(([a,b,c])=><button key={a} onClick={()=>router.push(`/search?q=${encodeURIComponent(a)}`)}><span>{a}</span><b>{b}</b><em>{c}</em></button>)}</section><section className="panel donut-panel"><SectionHeader title="AUM BY ASSET CLASS" href="/reports"/><div className="donut big">$14.87B<small>Total AUM</small></div><Button variant="secondary" onClick={()=>router.push("/reports")}>View Report →</Button></section></aside></main></AppShell>
}
