"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/app";
import { Badge, Button } from "@/components/ui";
import { AddWatchlistModal, SetAlertModal, ShareModal } from "@/components/overlays";
import { AssetIdentity, ChartShell, DetailPanel, DetailTabs, DocumentsRow, KeyValueGrid, MetricStrip, TradeCard } from "./DetailPrimitives";
import type { AssetDetailData } from "./data";
import "./details.css";

export function AssetDetail({ asset }: { asset: AssetDetailData }) {
  const router=useRouter(); const crypto=asset.variant==="crypto"; const token=asset.variant==="business-token"; const regulated=asset.variant==="regulated";
  const [tab,setTab]=React.useState("Overview"); const [watch,setWatch]=React.useState(false); const [alert,setAlert]=React.useState(false); const [share,setShare]=React.useState(false); const [notice,setNotice]=React.useState("");
  const tabs = crypto ? ["Overview","Activity","Community","Order Book","Disclosures"] : token ? ["Overview","Activity","Community","Rewards","Business","Disclosures"] : regulated ? ["Overview","Underlying Asset","Documents","Cashflows","Legal Terms","Disclosures"] : ["Overview","Underlying Asset","Cashflows","Documents","Disclosures","Activity"];
  function tabAction(next:string){
    setTab(next);
    if(next==="Overview") return;
    const issuerSlug=asset.issuer.toLowerCase().replace(/[^a-z0-9]+/g,"-");
    const routes:Record<string,string>={
      "Activity": crypto ? `/markets/${asset.slug}/activity` : `/rwa/${asset.slug}/activity`,
      "Community": `/community?asset=${asset.slug}`,
      "Order Book": `/markets/${asset.slug}/order-book`,
      "Disclosures": `/rwa/${asset.slug}/disclosures`,
      "Business": `/businesses/${issuerSlug}`,
      "Rewards": `/rewards?asset=${asset.slug}`,
      "Underlying Asset": `/rwa/${asset.slug}/underlying-asset`,
      "Documents": `/rwa/${asset.slug}/documents`,
      "Cashflows": `/rwa/${asset.slug}/cashflows`,
      "Legal Terms": `/rwa/${asset.slug}/legal`,
    };
    const href=routes[next]; if(href) router.push(href);
  }
  const headerMetrics = crypto ? [["Market Cap",asset.marketCap,asset.change],["Fully Diluted Valuation",asset.marketCap,asset.change],["Circulating Supply",asset.supply],["Max Supply","21.00M BTC"],["24H Volume",asset.volume,"+6.71%"],["Liquidity","$842.71M","+4.32%"],["24H High","$67,191.22"],["24H Low","$65,102.11"],["All-Time High","$73,737.94"],["All-Time Low","$67.81"]] as Array<[string,string,string?]> : token ? [["24H Volume",asset.volume],["Market Cap",asset.marketCap],["Fully Diluted Valuation","$482.3M"],["Circulating Supply",asset.supply],["Holders","18,642"],["Liquidity","$6.42M"]] as Array<[string,string,string?]> : [["Net Asset Value (NAV)",asset.aum||asset.marketCap,regulated?"+0.32%":"+1.32%"],["NAV per Token",asset.price,regulated?"+0.32%":"+1.32%"],[regulated?"Annualized Yield":"Net Yield (TTM)",asset.yield||"5.62%","+0.08%"],[regulated?"Token Price":"Occupancy",regulated?"$1.0221":"96.3%"],[regulated?"24H Volume":"AUM",regulated?asset.volume:asset.aum||asset.marketCap],[regulated?"Total Value Locked":"Tokens Outstanding",regulated?asset.aum||asset.marketCap:asset.supply]] as Array<[string,string,string?]>;

  return <AppShell><main className={`asset-detail-page detail-page-pad asset-detail--${asset.variant}`}><div className="asset-detail-main">
    <div className="breadcrumbs"><button type="button" onClick={()=>router.push(crypto?"/markets":"/rwa")}>{crypto?"Markets":"RWA"}</button><span>›</span><button type="button" onClick={()=>router.push(crypto?"/markets?class=crypto":"/rwa")}>{crypto?"Crypto":asset.assetClass}</button><span>›</span><b>{asset.name}</b></div>
    <section className="asset-hero"><div className={`asset-hero-image asset-hero-image--${asset.variant}`}>{crypto?"₿":token?asset.symbol:"⌂"}</div><div className="asset-hero-content"><AssetIdentity asset={asset} regulated={regulated}/><div className="issuer-strip"><span>Issued by <b>{asset.issuer} ✓</b></span><span>Jurisdiction <b>🇸🇬 {asset.country}</b></span><span>Asset Class <b>{asset.assetClass}</b></span><span>{regulated?"Regulatory Status":"Token Standard"} <b>{regulated?asset.status:asset.tokenStandard}</b></span><span>Status <b className="positive">● {asset.status}</b></span></div>{crypto && <div className="crypto-price"><strong>{asset.price.replace("$","")}</strong><em>{asset.change} (+1,186.32)</em><small>Price in USDC ⓘ</small></div>}{token && <div className="token-price-head"><strong>{asset.price}</strong><em>{asset.change} (24H)</em></div>}</div><div className="detail-hero-actions"><Button variant="secondary" onClick={()=>setWatch(true)}>☆ {watch?"Watching":"Add to Watchlist"}</Button><Button variant="secondary" onClick={()=>setAlert(true)}>♧ Set Alert</Button><Button variant="secondary" onClick={()=>setShare(true)}>↗ Share</Button></div></section>
    {!crypto&&!token && <MetricStrip items={headerMetrics}/>} {token && <MetricStrip items={headerMetrics}/>} 
    <DetailTabs tabs={tabs} value={tab} onChange={tabAction}/>
    <ChartShell asset={asset} mode={crypto||token?"candles":"line"}/>
    {crypto ? <CryptoOverview asset={asset} onNavigate={router.push}/> : token ? <TokenOverview asset={asset} onNavigate={router.push}/> : <RwaOverview asset={asset} regulated={regulated} onNavigate={router.push}/>} 
  </div><aside className="asset-detail-side"><TradeCard asset={asset} regulated={regulated||asset.variant==="rwa"}/>{crypto?<CryptoSide asset={asset} onNavigate={router.push}/>:token?<TokenSide asset={asset} onNavigate={router.push}/>:<RwaSide asset={asset} regulated={regulated} onNavigate={router.push}/>}</aside>{notice&&<div className="detail-toast" role="status">{notice}<button type="button" onClick={()=>setNotice("")}>×</button></div>}</main><AddWatchlistModal open={watch} onOpenChange={setWatch} assetName={asset.symbol} onAdd={list=>{setWatch(false);setNotice(`${asset.symbol} added to ${list}.`)}}/><SetAlertModal open={alert} onOpenChange={setAlert} pair={`${asset.symbol} / USD`} currentPrice={asset.price} onCreate={()=>{setAlert(false);setNotice(`Alert created for ${asset.symbol}.`)}}/><ShareModal open={share} onOpenChange={setShare} title={`Share ${asset.name}`} url={`https://rwa.ms/${crypto?"markets":"rwa"}/${asset.slug}`} onShare={()=>setShare(false)}/></AppShell>;
}

function RwaOverview({asset,regulated,onNavigate}:{asset:AssetDetailData;regulated:boolean;onNavigate:(href:string)=>void}){
 return <><div className="detail-three-grid"><DetailPanel title="Underlying Asset Summary"><KeyValueGrid rows={[["Property Name","Marina Bay Residences"],["Address","10 Bayfront Avenue, Singapore 018956"],["Property Type","Luxury Residential"],["Total Units",regulated?"528":"512"],["NLA","42,731 sqm"],["Year Completed","2020"],["Appraised Value (Mar 2024)","$62.40M"]]}/><button className="text-action" type="button" onClick={()=>onNavigate(`/rwa/${asset.slug}/underlying`)}>View Full Asset Details →</button></DetailPanel><DetailPanel title="Valuation Summary"><KeyValueGrid rows={[["Valuation Date","Mar 31, 2024"],["Valuer","CBRE Singapore Pte. Ltd. ✓"],["Valuation Method","Income Approach"],["Gross Market Value","$62.40M"],["Net Asset Value (NAV)","$58.72M"],["Loan-to-Value (LTV)",regulated?"21.3%":"12.1%"],["Debt Outstanding",regulated?"$12.18M":"$7.12M"]]}/><button className="text-action" type="button" onClick={()=>onNavigate(`/rwa/${asset.slug}/valuation`)}>View Valuation Report →</button></DetailPanel><DetailPanel title={regulated?"Income & Yield":"Property Performance (TTM)"}><KeyValueGrid rows={regulated?[["Annualized Yield (Current)",asset.yield||"6.25%","positive"],["Distribution Frequency","Quarterly"],["Next Distribution","Jul 15, 2024"],["Last Distribution","Apr 15, 2024"],["Distribution per Token","$0.0159"],["Dividend Coverage Ratio","1.58x"],["Historic Yield (12M Avg)","6.18%"]]:[["Gross Rental Income","$4.21M","positive"],["Net Operating Income","$3.18M","positive"],["Operating Expenses","$1.03M"],["Net Income","$2.15M","positive"],["Occupancy","96.3%","positive"],["WALE (by income)","2.8 years"]]}/><button className="text-action" type="button" onClick={()=>onNavigate(`/rwa/${asset.slug}/cashflows`)}>View Cashflow Details →</button></DetailPanel></div><DetailPanel title={regulated?"Documents & Reports":"Documents"} actionHref={`/rwa/${asset.slug}/documents`} actionLabel={regulated?"View All 17":"View All Documents"}><DocumentsRow assetSlug={asset.slug}/></DetailPanel></>;
}

function CryptoOverview({asset,onNavigate}:{asset:AssetDetailData;onNavigate:(href:string)=>void}){
 const metrics=[["Market Cap","$1.32T","+1.82%"],["Fully Diluted Valuation","$1.32T","+1.82%"],["Circulating Supply","19.81M BTC"],["Max Supply","21.00M BTC"],["24H Volume","$28.45B","+6.71%"],["Liquidity","$842.71M","+4.32%"],["24H High","$67,191.22"],["24H Low","$65,102.11"],["All-Time High","$73,737.94"],["All-Time Low","$67.81"]] as Array<[string,string,string?]>;
 return <DetailPanel title="Overview"><div className="crypto-metric-grid">{metrics.map(([a,b,c])=><button type="button" key={a} onClick={()=>onNavigate(`/markets/${asset.slug}/metrics/${a.toLowerCase().replace(/[^a-z0-9]+/g,"-")}`)}><span>{a} ⛤</span><b>{b}</b>{c&&<em>{c}</em>}</button>)}</div></DetailPanel>;
}

function TokenOverview({asset,onNavigate}:{asset:AssetDetailData;onNavigate:(href:string)=>void}){
 return <div className="token-overview-grid"><DetailPanel title="Utility & Use Cases"><div className="icon-list">{[["Ecosystem Payments","Use KOPI for purchases across Kopi Nusantara stores"],["Loyalty & Rewards","Earn and redeem rewards in KOPI"],["Governance","Vote on key proposals shaping the ecosystem"],["Partner Benefits","Exclusive partner offers and premium access"]].map(([a,b])=><button type="button" key={a} onClick={()=>onNavigate(`/businesses/kopi-nusantara/token/utility`)}><span>◇</span><span><b>{a}</b><small>{b}</small></span></button>)}</div></DetailPanel><DetailPanel title="Rewards Integration"><div className="icon-list compact">{[["Earn with KOPI","Stake, hold, and engage to earn rewards"],["Loyalty Rewards","Up to 12% APR"],["DAO Participation","Governance rewards"],["Partner Campaigns","Exclusive incentives"]].map(([a,b])=><button type="button" key={a} onClick={()=>onNavigate(`/businesses/kopi-nusantara/rewards`)}><span>◇</span><span><b>{a}</b><small>{b}</small></span></button>)}</div><Button onClick={()=>onNavigate(`/businesses/kopi-nusantara/rewards`)}>Explore Rewards ↗</Button></DetailPanel><DetailPanel title="Supply & Treasury"><div className="supply-card"><div className="donut-token">100.24M<small>Circulating</small></div><ul><li>Circulating Supply <b>100.24M (40.1%)</b></li><li>Ecosystem Treasury <b>62.50M (25.0%)</b></li><li>Team & Advisors <b>37.50M (15.0%)</b></li><li>Investors <b>25.00M (10.0%)</b></li></ul></div><button className="text-action" type="button" onClick={()=>onNavigate(`/businesses/kopi-nusantara/token/tokenomics`)}>View Full Tokenomics →</button></DetailPanel><DetailPanel title="Vesting Schedule"><KeyValueGrid rows={[["Team & Advisors","37.50M KOPI"],["Investors","25.00M KOPI"],["Ecosystem Treasury","62.50M KOPI"]]}/><button className="text-action" type="button" onClick={()=>onNavigate(`/businesses/kopi-nusantara/token/vesting`)}>View Vesting Details →</button></DetailPanel></div>;
}

function RwaSide({asset,regulated,onNavigate}:{asset:AssetDetailData;regulated:boolean;onNavigate:(href:string)=>void}){
 return <><DetailPanel title={regulated?"Issuer Profile":"Issuer"}><div className="issuer-card"><span>△</span><div><b>{asset.issuer} ✓</b><p>Licensed real asset manager focused on institutional-grade real estate.</p><small>🇸🇬 Singapore　● MAS License No. CMS100073</small></div></div><MetricStrip items={[["Track Record","$1.28B AUM"],["Investors","150+"]]}/><button className="text-action" type="button" onClick={()=>onNavigate(`/businesses/harbourview-asset-management`)}>View Issuer Profile →</button></DetailPanel>{regulated?<><div className="detail-side-split"><DetailPanel title="Legal Rights Summary"><div className="rights-list">{["Economic Rights to Cashflows","Pro Rata Distribution Rights","Right to Information","Voting Rights (Major Decisions)","Redemption at Maturity"].map(x=><span key={x}>✓ {x}</span>)}</div><button className="text-action" type="button" onClick={()=>onNavigate(`/rwa/${asset.slug}/legal`)}>View Full Legal Terms →</button></DetailPanel><DetailPanel title="Key Terms"><KeyValueGrid rows={[["Token Type","Security Token"],["Offering Type","Reg D 506(c)"],["Jurisdiction","Singapore"],["Maturity Date","May 1, 2030"],["Minimum Investment","$10,000"],["Investor Eligibility","Accredited Investors"]]}/></DetailPanel></div><div className="detail-side-split"><DetailPanel title="Investor Eligibility"><b className="positive">Accredited Investors Only</b><p className="side-copy">Access is restricted to verified accredited investors under Reg D 506(c).</p><button className="text-action" type="button" onClick={()=>onNavigate("/compliance/kyc")}>Learn about eligibility requirements →</button></DetailPanel><DetailPanel title="Regulatory Disclosures"><button className="text-action" type="button" onClick={()=>onNavigate(`/rwa/${asset.slug}/disclosures`)}>View Disclosures →</button><p className="reg-note">◇ This offering is made pursuant to Regulation D 506(c). No general solicitation.</p></DetailPanel></div></>:<DetailPanel title="Key Terms"><KeyValueGrid rows={[["Asset Type","Residential Real Estate"],["Property","Marina Bay Residences"],["Location","Marina Bay, Singapore"],["Tenure","99-year Leasehold"],["Fund Structure","SPV (Special Purpose Vehicle)"],["Distribution Frequency","Quarterly"],["Lock-up Period","90 days"],["Redemption Notice","30 days"]]}/><button className="text-action" type="button" onClick={()=>onNavigate(`/rwa/${asset.slug}/terms`)}>View Complete Terms →</button></DetailPanel>}</>;
}

function CryptoSide({asset,onNavigate}:{asset:AssetDetailData;onNavigate:(href:string)=>void}){
 return <><DetailPanel title="Community" actionHref={`/community?asset=${asset.slug}`}><div className="community-stats">{[["Holders","4.18M","+2.31%"],["Active Addresses (24H)","912K","+5.12%"],["Twitter Followers","3.1M","+1.84%"],["Reddit Members","502K","+3.22%"]].map(([a,b,c])=><button type="button" key={a} onClick={()=>onNavigate(`/community?asset=${asset.slug}`)}><span>◇ {a}</span><b>{b}</b><em>{c}</em></button>)}</div></DetailPanel><DetailPanel title="Trending Discussions" actionHref={`/community?asset=${asset.slug}`}><div className="discussion-list">{["Bitcoin breaks $66K — What's next?","ETF inflows hit 7-day high","Lightning Network hits new capacity ATH","On-chain activity surges"].map((x,i)=><button type="button" key={x} onClick={()=>onNavigate(`/community/thesis/btc-${i+1}`)}><b>{x}</b><small>{i*2+2}h ago</small></button>)}</div></DetailPanel><DetailPanel title="Recent News" actionHref="/intelligence"><div className="news-mini">{["Bitcoin holds above $66K as ETF inflows continue","Spot Bitcoin ETFs see $378M in inflows","Bitcoin network hash rate hits all-time high"].map((x,i)=><button type="button" key={x} onClick={()=>onNavigate(`/intelligence/btc-${i+1}`)}><span className="news-thumb">₿</span><span><b>{x}</b><small>{i*3+2}h ago</small></span></button>)}</div></DetailPanel></>;
}

function TokenSide({asset,onNavigate}:{asset:AssetDetailData;onNavigate:(href:string)=>void}){
 return <><DetailPanel title="Key Token Metrics"><KeyValueGrid rows={[["Price (USDC)",asset.price],["24H Change",asset.change,"positive"],["7D Change","+22.31%","positive"],["30D Change","+41.63%","positive"],["Market Cap",asset.marketCap],["Fully Diluted Valuation","$482.3M"],["Circulating Supply",asset.supply],["Total Supply","250.00M KOPI"],["24H Volume",asset.volume],["Liquidity (KOPI/USDC)","$6.42M"],["Holders","18,642"],["Transfer Tax","0%"],["Trading Fees","0.25%"]]}/></DetailPanel><DetailPanel title="Business Summary" actionHref="/businesses/kopi-nusantara" actionLabel="View Business Page"><div className="business-summary-card"><span className="business-photo"/><div><h3>Kopi Nusantara</h3><Badge tone="success">● Verified Business</Badge><p>Indonesia's leading coffee brand connecting farmers, communities, and coffee lovers.</p></div></div><MetricStrip items={[["Established","2018"],["Employees","250+"],["Followers","12.8K"]]}/></DetailPanel><DetailPanel title="Transparency & Disclosures"><div className="transparency-list">{[["Smart Contract","0x8c7a…d9f3b2"],["Contract Audited","Hacken · Mar 12, 2024"],["KYC Verified","HARBOURVIEW · Verified"],["Last Disclosure","May 13, 2024"]].map(([a,b])=><button type="button" key={a} onClick={()=>onNavigate(`/businesses/kopi-nusantara/token/disclosures`)}><span>{a}</span><b>{b}</b><em>✓</em></button>)}</div></DetailPanel></>;
}
