"use client";

import * as React from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/app";
import { Badge, Button } from "@/components/ui";
import { JoinRewardsModal, ShareModal } from "@/components/overlays";
import { DetailPanel, DetailTabs, MetricStrip } from "./DetailPrimitives";
import { getBusinessProfile } from "./data";
import "./details.css";

export function BusinessProfile({ slug }: { slug: string }) {
  const router=useRouter(); const data=getBusinessProfile(slug); const [tab,setTab]=React.useState("Overview"); const [following,setFollowing]=React.useState(false); const [rewards,setRewards]=React.useState(false); const [share,setShare]=React.useState(false);
  const tabs=["Overview","Store","Community","Rewards","Token","Updates","Transparency"];
  function tabAction(next:string){setTab(next);if(next==="Store")router.push(`/businesses/${slug}/store`);if(next==="Community")router.push("/community");if(next==="Rewards")router.push(`/businesses/${slug}/rewards`);if(next==="Token")router.push(`/businesses/${slug}/token`);if(next==="Updates")router.push(`/businesses/${slug}/updates`);if(next==="Transparency")router.push(`/businesses/${slug}/transparency`)}
  return <AppShell><main className="business-detail-page detail-page-pad"><div className="business-detail-main">
    <section className="business-hero"><div className="business-hero-cover"/><div className="business-hero-content"><div className="business-logo">{data.symbol}</div><div className="business-copy"><div><h1>{data.name} <span className="verified-dot">✓</span></h1><Badge tone="success">● Verified Business</Badge></div><p>{data.tagline}</p><div className="business-meta"><span>◎ {data.category}</span><span>🇮🇩 {data.country}</span><span>Followers <b>{data.followers}</b></span><span>★ {data.rating}</span></div></div><div className="established">Established<b>{data.established}</b></div></div><div className="business-hero-actions"><Button onClick={()=>setFollowing(v=>!v)}>{following?"✓ Following":"＋ Follow"} <small>{data.followers} Followers</small></Button><Button variant="secondary" onClick={()=>router.push(`/businesses/${slug}/token`)}>View Token　${data.symbol}</Button><Button variant="secondary" onClick={()=>setRewards(true)}>♢ Join Rewards</Button><Button variant="secondary" onClick={()=>router.push(`/businesses/${slug}/store`)}>▱ Visit Store ↗</Button><Button variant="ghost" onClick={()=>setShare(true)}>↗ Share</Button></div></section>
    <DetailTabs tabs={tabs} value={tab} onChange={tabAction}/>
    <MetricStrip items={[["Physical Stores","128","↑ 12%"],["Happy Customers","520K+","↑ 18%"],["Monthly GMV","$2.45M","↑ 16.2%"],["Token Holders",data.holders,"↑ 23.4%"],["Monthly Visits","245K","↑ 15.6%"]]}/>
    <div className="business-content-grid"><DetailPanel title="Featured Products" actionHref={`/businesses/${slug}/store`} actionLabel="View Store"><div className="product-row">{["Signature Blend","Drip Coffee","Arabica Aceh Gayo","Kopi Susu","Coffee Tumbler"].map((p,i)=><button type="button" key={p} onClick={()=>router.push(`/businesses/${slug}/store/products/${i+1}`)}><span className={`product-art product-art-${i}`}/><b>{p}</b><small>{i===0?"Whole Bean 250g":i===3?"Ready to Drink":"Kopi Nusantara"}</small><strong>${[12.9,8.9,14.9,2.5,22][i].toFixed(2)}</strong></button>)}</div></DetailPanel>
      <DetailPanel title="Recent Updates" actionHref={`/businesses/${slug}/updates`}><div className="updates-list">{[["Kopi Nusantara Opens New Flagship Store in Bali","May 20, 2024 · Store Update"],["Q1 2024 Impact Report is Live","May 14, 2024 · Company Update"],["Partnership with Petani Kopi Alliance","May 6, 2024 · Partnership"]].map(([t,d],i)=><button type="button" key={t} onClick={()=>router.push(`/businesses/${slug}/updates/${i+1}`)}><span className={`update-thumb update-${i}`}/><span><b>{t}</b><small>{d}</small></span></button>)}</div></DetailPanel>
      <DetailPanel title={`About ${data.name}`}><p className="about-copy">Founded in 2018, {data.name} is on a mission to elevate Indonesian coffee globally while creating positive impact for farmers and local communities. We source ethically, roast responsibly, and build meaningful connections—one cup at a time.</p><div className="business-values">{["Ethically Sourced","Sustainable Practices","Community First","Quality Coffee"].map(x=><span key={x}>◇ <b>{x}</b></span>)}</div><button className="text-action" type="button" onClick={()=>router.push(`/businesses/${slug}/about`)}>Read Full Story →</button></DetailPanel>
      <DetailPanel title="Rewards Program"><div className="rewards-summary"><span className="rewards-icon">◇</span><div><b>{data.symbol} Rewards</b><p>Earn ${data.symbol} for every purchase, referral, and engagement.</p><small>Your Tier</small><strong>Gold　2,450 / 5,000 XP to Platinum</strong></div><Button variant="secondary" onClick={()=>setRewards(true)}>Explore Rewards</Button></div></DetailPanel>
    </div>
  </div><aside className="business-detail-side"><DetailPanel title="Quick Actions"><div className="quick-actions">{[["Shop Online","Visit our official store",`/businesses/${slug}/store`],["Find a Store","Locate stores near you",`/businesses/${slug}/store/locations`],["Join Community","Connect with coffee lovers","/community"],["Contact Us","We're here to help",`/businesses/${slug}/contact`]].map(([a,b,h])=><button type="button" key={a} onClick={()=>router.push(h)}><span>◇</span><span><b>{a}</b><small>{b}</small></span><em>›</em></button>)}</div></DetailPanel><DetailPanel title="Token Snapshot" actionHref={`/businesses/${slug}/token`} actionLabel="View Token"><div className="token-snapshot"><div><span className="business-logo mini">{data.symbol}</span><strong>${data.symbol}</strong><em>{data.tokenChange} (24H)</em></div><MetricStrip items={[["Market Cap",data.marketCap],["Holders",data.holders],["24H Volume","100.24M KOPI"]]}/><MetricStrip items={[["Total Supply","250.00M KOPI"],["Circulating","100.24M KOPI"],["Utility","Rewards, Governance"]]}/></div></DetailPanel><DetailPanel title="Transparency Summary" actionHref={`/businesses/${slug}/transparency`} actionLabel="View Details"><div className="transparency-list">{[["Smart Contract","0x8c7a…d9f3b2"],["Contract Audited","Hacken · Mar 12, 2024"],["KYC Verified","RWA.MS · Verified"],["Last Financial Report","Q1 2024 · May 14, 2024"],["Legal Entity","PT Kopi Nusantara · Indonesia"]].map(([a,b])=><button type="button" key={a} onClick={()=>router.push(`/businesses/${slug}/transparency`)}><span>{a}</span><b>{b}</b><em>✓</em></button>)}</div></DetailPanel><section className="verified-card"><span>◇</span><div><b>Verified & Secured on RWA.MS</b><p>This business is verified and monitored to ensure transparency, security, and real-world impact.</p></div></section></aside></main><JoinRewardsModal open={rewards} onOpenChange={setRewards} businessName={data.symbol} onJoin={()=>router.push(`/businesses/${slug}/rewards`)}/><ShareModal open={share} onOpenChange={setShare} title={`Share ${data.name}`} url={`https://rwa.ms/businesses/${slug}`} onShare={()=>setShare(false)}/></AppShell>;
}
