import {DatabaseSync} from 'node:sqlite';
import {readFileSync,mkdirSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash,randomUUID} from 'node:crypto';

const HERE=dirname(fileURLToPath(import.meta.url));
const now=()=>Date.now();
export const id=(p='id')=>`${p}_${randomUUID().replaceAll('-','')}`;
export const sha256=v=>createHash('sha256').update(String(v)).digest('hex');
const normWallet=v=>String(v||'').trim().toLowerCase();
const normToken=v=>String(v||'').trim().toUpperCase();
const json=v=>JSON.stringify(v??{});
const parse=s=>{try{return JSON.parse(s||'{}')}catch{return{}}};

export class BusinessStore{
  constructor(path=process.env.RWA_BUSINESS_DB||resolve(HERE,'data/business.sqlite')){
    mkdirSync(dirname(path),{recursive:true});
    this.path=path;this.db=new DatabaseSync(path);this.db.exec(readFileSync(resolve(HERE,'schema.sql'),'utf8'));
  }
  close(){this.db.close()}
  transaction(fn){this.db.exec('BEGIN IMMEDIATE');try{const out=fn();this.db.exec('COMMIT');return out}catch(e){try{this.db.exec('ROLLBACK')}catch{}throw e}}
  audit(actor,action,type,entityId,detail={}){this.db.prepare('INSERT INTO audit_log(ts,actor,action,entity_type,entity_id,detail_json) VALUES(?,?,?,?,?,?)').run(now(),actor,action,type,entityId,json(detail))}
  auditRecent(limit=100){return this.db.prepare('SELECT * FROM audit_log ORDER BY ts DESC,id DESC LIMIT ?').all(Math.max(1,Math.min(500,Number(limit)||100))).map(x=>({...x,detail:parse(x.detail_json)}))}
  upsertBusiness(b,{actor='admin'}={}){const t=now(),idv=String(b.id||'').trim(),series=String(b.seriesId||b.series_id||'').trim();if(!idv||!series||!String(b.name||'').trim())throw Error('business_identity_required');this.db.prepare(`INSERT INTO businesses(id,series_id,name,category,jurisdiction,status,kyb_verified,evidence_hash,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET series_id=excluded.series_id,name=excluded.name,category=excluded.category,jurisdiction=excluded.jurisdiction,status=excluded.status,kyb_verified=excluded.kyb_verified,evidence_hash=excluded.evidence_hash,updated_at=excluded.updated_at`).run(idv,series,String(b.name).trim(),String(b.category||'CUSTOM').toUpperCase(),String(b.jurisdiction||''),String(b.status||'ONBOARDING').toUpperCase(),b.kybVerified?1:0,String(b.evidenceHash||''),t,t);this.db.prepare(`INSERT INTO validation_policy(business_id,min_settled_count,min_settled_cents,max_settlement_age_ms,min_reconciliation_bps,max_refund_bps,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(business_id) DO NOTHING`).run(idv,1,100,2592000000,10000,5000,t);this.audit(actor,'business.upsert','business',idv,{series_id:series});return this.business(idv)}
  business(idv){const b=this.db.prepare('SELECT * FROM businesses WHERE id=?').get(idv);if(!b)return null;return{...b,kyb_verified:!!b.kyb_verified,wallets:this.wallets(idv),stores:this.bindings(idv),policy:this.policy(idv),validation:this.latestValidation(idv)}}
  businesses(){return this.db.prepare('SELECT * FROM businesses ORDER BY name').all().map(b=>({...b,kyb_verified:!!b.kyb_verified,validation:this.latestValidation(b.id)}))}
  setBusinessStatus(idv,status,{actor='admin'}={}){const s=String(status||'').toUpperCase();if(!['ONBOARDING','ACTIVE','SUSPENDED','CLOSED'].includes(s))throw Error('invalid_business_status');this.db.prepare('UPDATE businesses SET status=?,updated_at=? WHERE id=?').run(s,now(),idv);this.audit(actor,'business.status','business',idv,{status:s});return this.business(idv)}
  bindWallet(businessId,wallet,{role='OPERATOR',identityVerified=false,actor='admin'}={}){const w=normWallet(wallet);if(!/^0x[a-f0-9]{40}$/.test(w))throw Error('invalid_evm_wallet');const t=now();this.db.prepare(`INSERT INTO business_wallets(business_id,wallet,role,identity_verified,connected_at,verified_at,active) VALUES(?,?,?,?,?,?,1) ON CONFLICT(business_id,wallet) DO UPDATE SET role=excluded.role,identity_verified=excluded.identity_verified,verified_at=excluded.verified_at,active=1`).run(businessId,w,String(role||'OPERATOR').toUpperCase(),identityVerified?1:0,t,identityVerified?t:null);this.audit(actor,'wallet.bind','business',businessId,{wallet:w,identity_verified:!!identityVerified});return this.wallets(businessId)}
  verifyWallet(businessId,wallet,{actor='admin'}={}){const w=normWallet(wallet),t=now();const r=this.db.prepare('UPDATE business_wallets SET identity_verified=1,verified_at=?,active=1 WHERE business_id=? AND wallet=?').run(t,businessId,w);if(!r.changes)throw Error('wallet_binding_not_found');this.audit(actor,'wallet.identity_verified','business',businessId,{wallet:w});return this.wallets(businessId)}
  wallets(businessId){return this.db.prepare('SELECT * FROM business_wallets WHERE business_id=? AND active=1 ORDER BY connected_at').all(businessId).map(x=>({...x,identity_verified:!!x.identity_verified,active:!!x.active}))}
  bindStore(businessId,storeToken,{locationId='',terminalPolicy='ECOMMERCE_OR_APPROVED_POS',actor='admin'}={}){const token=normToken(storeToken);if(!token)throw Error('store_token_required');const t=now();this.db.prepare(`INSERT INTO store_bindings(business_id,store_token,location_id,terminal_policy,active,created_at) VALUES(?,?,?,?,1,?) ON CONFLICT(business_id,store_token) DO UPDATE SET location_id=excluded.location_id,terminal_policy=excluded.terminal_policy,active=1`).run(businessId,token,String(locationId||''),String(terminalPolicy||'ECOMMERCE_OR_APPROVED_POS'),t);this.audit(actor,'store.bind','business',businessId,{store_token:token});return this.bindings(businessId)}
  bindings(businessId){return this.db.prepare('SELECT * FROM store_bindings WHERE business_id=? AND active=1 ORDER BY store_token').all(businessId).map(x=>({...x,active:!!x.active}))}
  bindingForStore(token){return this.db.prepare('SELECT * FROM store_bindings WHERE store_token=? AND active=1').get(normToken(token))||null}
  policy(businessId){return this.db.prepare('SELECT * FROM validation_policy WHERE business_id=?').get(businessId)||null}
  setPolicy(businessId,p,{actor='admin'}={}){const old=this.policy(businessId)||{},t=now(),v={minSettledCount:Number(p.minSettledCount??old.min_settled_count??1),minSettledCents:Number(p.minSettledCents??old.min_settled_cents??100),maxSettlementAgeMs:Number(p.maxSettlementAgeMs??old.max_settlement_age_ms??2592000000),minReconciliationBps:Number(p.minReconciliationBps??old.min_reconciliation_bps??10000),maxRefundBps:Number(p.maxRefundBps??old.max_refund_bps??5000)};if(!Number.isSafeInteger(v.minSettledCount)||v.minSettledCount<1||!Number.isSafeInteger(v.minSettledCents)||v.minSettledCents<0||!Number.isFinite(v.maxSettlementAgeMs)||v.maxSettlementAgeMs<=0||v.minReconciliationBps<0||v.minReconciliationBps>10000||v.maxRefundBps<0||v.maxRefundBps>10000)throw Error('invalid_validation_policy');this.db.prepare(`INSERT INTO validation_policy(business_id,min_settled_count,min_settled_cents,max_settlement_age_ms,min_reconciliation_bps,max_refund_bps,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(business_id) DO UPDATE SET min_settled_count=excluded.min_settled_count,min_settled_cents=excluded.min_settled_cents,max_settlement_age_ms=excluded.max_settlement_age_ms,min_reconciliation_bps=excluded.min_reconciliation_bps,max_refund_bps=excluded.max_refund_bps,updated_at=excluded.updated_at`).run(businessId,v.minSettledCount,v.minSettledCents,v.maxSettlementAgeMs,v.minReconciliationBps,v.maxRefundBps,t);this.audit(actor,'validation.policy','business',businessId,v);return this.policy(businessId)}
  upsertSettlement(s,{actor='reconciler'}={}){const t=now(),source=String(s.source||'COMMERCE').toUpperCase(),orderId=s.orderId?String(s.orderId):null,externalRef=s.externalRef?String(s.externalRef):null;if(!orderId&&!externalRef)throw Error('settlement_reference_required');const idv=String(s.id||`set_${sha256(`${source}:${orderId||externalRef}`).slice(0,32)}`),gross=Math.max(0,Math.trunc(Number(s.grossCents||0))),refund=Math.max(0,Math.trunc(Number(s.refundCents||0))),net=Math.max(0,gross-refund),status=refund>=gross&&gross>0?'REFUNDED':String(s.status||'SETTLED').toUpperCase();const existing=orderId?this.db.prepare('SELECT id FROM settlement_ledger WHERE source=? AND order_id=?').get(source,orderId):this.db.prepare('SELECT id FROM settlement_ledger WHERE source=? AND external_ref=?').get(source,externalRef);if(existing){this.db.prepare('UPDATE settlement_ledger SET gross_cents=?,refund_cents=?,net_cents=?,payment_reference=?,settlement_reference=?,settlement_at=?,evidence_url=?,status=?,observed_at=? WHERE id=?').run(gross,refund,net,String(s.paymentReference||''),String(s.settlementReference||''),Number(s.settlementAt||t),String(s.evidenceUrl||''),status,t,existing.id);return existing.id}this.db.prepare(`INSERT INTO settlement_ledger(id,business_id,order_id,external_ref,source,store_token,wallet,gross_cents,refund_cents,net_cents,currency,payment_reference,settlement_reference,settlement_at,evidence_url,status,observed_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(idv,s.businessId,orderId,externalRef,source,normToken(s.storeToken),normWallet(s.wallet||''),gross,refund,net,String(s.currency||'IDR').toUpperCase(),String(s.paymentReference||''),String(s.settlementReference||''),Number(s.settlementAt||t),String(s.evidenceUrl||''),status,t);this.audit(actor,'settlement.upsert','business',s.businessId,{settlement_id:idv,order_id:orderId,external_ref:externalRef,status,net_cents:net});return idv}
  settlements(businessId,limit=500){return this.db.prepare('SELECT * FROM settlement_ledger WHERE business_id=? ORDER BY settlement_at DESC,rowid DESC LIMIT ?').all(businessId,Math.max(1,Math.min(5000,Number(limit)||500)))}
  ledgerSummary(businessId){return this.db.prepare(`SELECT COUNT(*) settled_count,COALESCE(SUM(gross_cents),0) gross_cents,COALESCE(SUM(refund_cents),0) refund_cents,COALESCE(SUM(net_cents),0) net_cents,MAX(settlement_at) latest_settlement_at FROM settlement_ledger WHERE business_id=? AND status IN ('SETTLED','REFUNDED')`).get(businessId)}
  ingestExternal(tx,{actor='terminal'}={}){const state=String(tx.state||'CREATED').toUpperCase();if(!['CREATED','PAID'].includes(state))throw Error('terminal_may_only_create_or_mark_paid');const businessId=String(tx.businessId||''),storeToken=normToken(tx.storeToken);if(!this.bindingForStore(storeToken)||this.bindingForStore(storeToken)?.business_id!==businessId)throw Error('store_not_bound_to_business');const t=now(),idv=String(tx.id||id('tx'));this.db.prepare(`INSERT INTO external_transactions(id,business_id,store_token,terminal_id,product_service_id,amount_cents,currency,state,payment_reference,settlement_reference,external_ref,evidence_url,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(idv,businessId,storeToken,String(tx.terminalId||''),String(tx.productServiceId||''),Math.trunc(Number(tx.amountCents)),String(tx.currency||'IDR').toUpperCase(),state,String(tx.paymentReference||''),'',String(tx.externalRef||''),String(tx.evidenceUrl||''),t,t);this.audit(actor,'transaction.ingest','business',businessId,{transaction_id:idv,state,external_ref:tx.externalRef});return this.externalTransaction(idv)}
  externalTransaction(idv){return this.db.prepare('SELECT * FROM external_transactions WHERE id=?').get(idv)||null}
  settleExternal(idv,{settlementReference,evidenceUrl='',actor='admin'}={}){const tx=this.externalTransaction(idv);if(!tx)throw Error('transaction_not_found');if(!['CREATED','PAID'].includes(tx.state))throw Error('transaction_not_settleable');if(!String(settlementReference||'').trim())throw Error('settlement_reference_required');const t=now();this.db.prepare("UPDATE external_transactions SET state='SETTLED',settlement_reference=?,evidence_url=?,updated_at=? WHERE id=?").run(String(settlementReference),String(evidenceUrl||''),t,idv);this.upsertSettlement({businessId:tx.business_id,externalRef:tx.external_ref,source:'APPROVED_API',storeToken:tx.store_token,wallet:'',grossCents:tx.amount_cents,refundCents:0,currency:tx.currency,paymentReference:tx.payment_reference||tx.external_ref,settlementReference:settlementReference,settlementAt:t,evidenceUrl,status:'SETTLED'},{actor});return this.externalTransaction(idv)}
  reconciliationPut(r,{actor='reconciler'}={}){const idv=id('rec'),t=now();this.db.prepare('INSERT INTO reconciliation_runs(id,business_id,expected_net_cents,ledger_net_cents,difference_cents,reconciliation_bps,qualifying_count,refund_cents,status,detail_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(idv,r.businessId,r.expectedNetCents,r.ledgerNetCents,r.differenceCents,r.reconciliationBps,r.qualifyingCount,r.refundCents,r.status,json(r.detail||{}),t);this.audit(actor,'reconciliation.run','business',r.businessId,{id:idv,status:r.status,difference_cents:r.differenceCents});return this.latestReconciliation(r.businessId)}
  latestReconciliation(businessId){const x=this.db.prepare('SELECT * FROM reconciliation_runs WHERE business_id=? ORDER BY created_at DESC,rowid DESC LIMIT 1').get(businessId);return x?{...x,detail:parse(x.detail_json)}:null}
  validationPut(v,{actor='validator'}={}){const idv=id('val'),t=now();this.db.prepare('INSERT INTO validation_snapshots(id,business_id,state,score,reason_json,settled_count,net_settled_cents,latest_settlement_at,reconciliation_bps,refund_bps,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(idv,v.businessId,v.state,v.score,json(v.reasons||[]),v.settledCount,v.netSettledCents,v.latestSettlementAt||null,v.reconciliationBps,v.refundBps,t);this.audit(actor,'validation.snapshot','business',v.businessId,{state:v.state,score:v.score,reasons:v.reasons||[]});return this.latestValidation(v.businessId)}
  latestValidation(businessId){const x=this.db.prepare('SELECT * FROM validation_snapshots WHERE business_id=? ORDER BY created_at DESC,rowid DESC LIMIT 1').get(businessId);return x?{...x,reasons:parse(x.reason_json)}:null}
  distributionPut(m,{actor='distribution'}={}){const idv=id('dist'),t=now();this.db.prepare('INSERT INTO distribution_manifests(id,business_id,series_id,basis,eligible_revenue_cents,reserve_cents,distributable_cents,investor_allocation_bps,reserve_bps,snapshot_hash,manifest_hash,state,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(idv,m.businessId,m.seriesId,m.basis,m.eligibleRevenueCents,m.reserveCents,m.distributableCents,m.investorAllocationBps,m.reserveBps,m.snapshotHash,m.manifestHash,'AWAITING_AUTHORIZED_FUNDING',t);this.audit(actor,'distribution.preview','business',m.businessId,{manifest_id:idv,distributable_cents:m.distributableCents});return this.db.prepare('SELECT * FROM distribution_manifests WHERE id=?').get(idv)}
}
