(() => {
'use strict';
const $=id=>document.getElementById(id),ENGINE_VERSION='VF-1.0.0';let worker=null,lastResult=null,startedAt=0;
const strategyMeta={sma_cross:['Fast period','Slow period',50,1000],ema_cross:['Fast period','Slow period',50,500],rsi_mr:['RSI period','Entry level (<50)',14,30],breakout:['Lookback seconds','Exit lookback',300,60],bollinger_mr:['BB period','Deviation ×10',200,20]};
const fmt=(n,d=2)=>Number.isFinite(n)?n.toLocaleString(undefined,{maximumFractionDigits:d,minimumFractionDigits:d}):'—';const money=n=>!Number.isFinite(n)?'—':`${n>=0?'+':'-'}$${Math.abs(n).toLocaleString(undefined,{maximumFractionDigits:2})}`;const pct=n=>Number.isFinite(n)?`${n.toFixed(2)}%`:'—';
function monthRange(start,end){const a=/^(\d{4})-(\d{2})$/.exec(start),b=/^(\d{4})-(\d{2})$/.exec(end);if(!a||!b)return[];let y=+a[1],m=+a[2],ey=+b[1],em=+b[2],out=[];while(y<ey||(y===ey&&m<=em)){out.push(`${y}-${String(m).padStart(2,'0')}`);if(++m===13){m=1;y++}if(out.length>240)break}return out}
function config(){const mode=$('dataMode').value,months=monthRange($('startMonth').value,$('endMonth').value);return{engineVersion:ENGINE_VERSION,mode,months,strategy:$('strategy').value,p1:+$('p1').value,p2:+$('p2').value,initialBalance:+$('balance').value,lot:+$('lot').value,spreadPips:+$('spread').value,slippagePips:+$('slippage').value,stopLossPips:+$('sl').value,rr:+$('rr').value,commissionPerLotRT:+$('commission').value,maxTrades:+$('maxTrades').value,pipSize:.0001,pipValuePerLot:10,symbol:'EURUSD',source:'zcbmlijygrdwa/fx_EUR_USD_tick'}}
function validate(c){if(c.mode==='remote'&&(!c.months.length||c.months.length>120))return'Choose a valid range of 1–120 months.';if(c.mode==='upload'&&!$('tickFile').files[0])return'Choose a TXT/CSV tick file.';if(c.p1<2||c.p2<2)return'Strategy periods must be at least 2.';if(['sma_cross','ema_cross'].includes(c.strategy)&&c.p1>=c.p2)return'Fast period must be smaller than slow period.';if(c.initialBalance<=0||c.lot<=0||c.stopLossPips<=0||c.rr<=0)return'Execution inputs must be positive.';return''}
function setRunning(on){$('runBtn').disabled=on;$('stopBtn').disabled=!on;$('engineStatus').textContent=on?'RUNNING':'ENGINE READY'}
function resetView(){$('progressBar').style.width='0%';$('progressText').textContent='Starting…';$('samplesText').textContent='0 samples';['mPnl','mReturn','mTrades','mFreq','mWr','mWins','mPf','mExpectancy','mDd','mDdPct','mHash','mElapsed'].forEach(id=>$(id).textContent='—');$('tradesBody').innerHTML='<tr><td colspan="8" class="empty">Running…</td></tr>';drawEquity([])}
function start(){const c=config(),error=validate(c);if(error){alert(error);return}if(worker)worker.terminate();worker=new Worker('./worker.js');worker.onmessage=onMessage;worker.onerror=e=>fail(e.message||'Worker error');lastResult=null;startedAt=performance.now();resetView();setRunning(true);if(c.mode==='remote')worker.postMessage({type:'runRemote',config:c});else worker.postMessage({type:'runFile',config:c,file:$('tickFile').files[0]})}
function stop(){if(worker){worker.terminate();worker=null}setRunning(false);$('progressText').textContent='Stopped'}function fail(msg){setRunning(false);$('engineStatus').textContent='ERROR';$('progressText').textContent=msg;console.error(msg)}
function onMessage(e){const m=e.data||{};if(m.type==='progress'){$('progressBar').style.width=`${Math.max(0,Math.min(100,m.percent||0))}%`;$('progressText').textContent=m.label||'Processing…';$('samplesText').textContent=`${(m.samples||0).toLocaleString()} samples`}else if(m.type==='result'){lastResult=m.result;renderResult(lastResult);setRunning(false);worker=null}else if(m.type==='error')fail(m.error||'Backtest failed')}
async function fingerprint(result){const canonical=JSON.stringify({engine:result.engineVersion,config:result.config,data:result.data,summary:result.summary});const bytes=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(canonical));return[...new Uint8Array(bytes)].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function renderResult(r){r.runFingerprint=await fingerprint(r);const s=r.summary,elapsed=(performance.now()-startedAt)/1000;$('mPnl').textContent=money(s.netPnl);$('mPnl').className=s.netPnl>=0?'good':'bad';$('mReturn').textContent=pct(s.returnPct);$('mTrades').textContent=s.trades.toLocaleString();$('mFreq').textContent=`${fmt(s.tradesPerMonth,1)} / month`;$('mWr').textContent=pct(s.winRate);$('mWins').textContent=`${s.wins} W / ${s.losses} L`;$('mPf').textContent=Number.isFinite(s.profitFactor)?fmt(s.profitFactor,2):'∞';$('mExpectancy').textContent=`${fmt(s.expectancyPips,2)} pips / trade`;$('mDd').textContent=money(-s.maxDrawdown);$('mDdPct').textContent=pct(s.maxDrawdownPct);$('mHash').textContent=r.runFingerprint.slice(0,16);$('mHash').title=r.runFingerprint;$('mElapsed').textContent=`${fmt(elapsed,1)}s · ${r.data.samples.toLocaleString()} ticks`;$('chartLabel').textContent=`${r.config.symbol} · ${r.config.strategy} · ${r.data.label}`;$('tradeCount').textContent=`${r.trades.length.toLocaleString()} stored`;$('exportJson').disabled=false;$('exportCsv').disabled=false;$('progressBar').style.width='100%';$('progressText').textContent='Completed';$('samplesText').textContent=`${r.data.samples.toLocaleString()} samples`;$('evidence').textContent=JSON.stringify({runFingerprint:r.runFingerprint,engineVersion:r.engineVersion,createdAt:r.createdAt,config:r.config,data:r.data,summary:r.summary,limitations:r.limitations},null,2);renderTrades(r.trades);drawEquity(r.equity)}
function renderTrades(rows){if(!rows.length){$('tradesBody').innerHTML='<tr><td colspan="8" class="empty">No completed trades.</td></tr>';return}$('tradesBody').innerHTML=rows.slice(-1000).reverse().map((t,i)=>`<tr><td>${rows.length-i}</td><td>${t.side}</td><td>${t.entry.toFixed(5)}</td><td>${t.exit.toFixed(5)}</td><td>${t.reason}</td><td class="${t.pips>=0?'good':'bad'}">${t.pips.toFixed(1)}</td><td class="${t.pnl>=0?'good':'bad'}">${money(t.pnl)}</td><td>$${fmt(t.equity,2)}</td></tr>`).join('')}
function drawEquity(points){const c=$('equity'),dpr=Math.max(1,window.devicePixelRatio||1),rect=c.getBoundingClientRect();c.width=Math.max(1,Math.floor(rect.width*dpr));c.height=Math.floor(260*dpr);const x=c.getContext('2d');x.scale(dpr,dpr);const w=rect.width,h=260;x.clearRect(0,0,w,h);x.strokeStyle='#232a38';x.lineWidth=1;for(let i=1;i<5;i++){let y=h*i/5;x.beginPath();x.moveTo(0,y);x.lineTo(w,y);x.stroke()}if(!points||points.length<2){x.fillStyle='#737d90';x.font='12px system-ui';x.fillText('Equity curve appears after a completed run.',16,30);return}const ys=points.map(p=>p[1]),mn=Math.min(...ys),mx=Math.max(...ys),range=Math.max(1e-9,mx-mn);x.strokeStyle='#d7ff4f';x.lineWidth=1.6;x.beginPath();points.forEach((p,i)=>{const px=i/(points.length-1)*(w-20)+10,py=h-12-(p[1]-mn)/range*(h-24);i?x.lineTo(px,py):x.moveTo(px,py)});x.stroke()}
function download(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}function exportJson(){if(lastResult)download(`vectorforge-${lastResult.runFingerprint.slice(0,12)}.json`,JSON.stringify(lastResult,null,2),'application/json')}function exportCsv(){if(!lastResult)return;const head='side,entry,exit,reason,pips,pnl,equity\n',body=lastResult.trades.map(t=>[t.side,t.entry,t.exit,t.reason,t.pips,t.pnl,t.equity].join(',')).join('\n');download(`vectorforge-trades-${lastResult.runFingerprint.slice(0,12)}.csv`,head+body,'text/csv')}
function updateStrategy(){const m=strategyMeta[$('strategy').value];$('p1Label').childNodes[0].nodeValue=m[0];$('p2Label').childNodes[0].nodeValue=m[1];$('p1').value=m[2];$('p2').value=m[3]}
$('dataMode').addEventListener('change',()=>{const upload=$('dataMode').value==='upload';$('remoteControls').classList.toggle('hidden',upload);$('fileWrap').classList.toggle('hidden',!upload)});$('strategy').addEventListener('change',updateStrategy);$('runBtn').addEventListener('click',start);$('stopBtn').addEventListener('click',stop);$('exportJson').addEventListener('click',exportJson);$('exportCsv').addEventListener('click',exportCsv);window.addEventListener('resize',()=>lastResult&&drawEquity(lastResult.equity));drawEquity([]);
})();
