/* VectorForge browser worker — streaming, deterministic research backtester. */
'use strict';
const RAW='https://raw.githubusercontent.com/zcbmlijygrdwa/fx_EUR_USD_tick/master';let aborter=null;const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));function postProgress(percent,label,samples){postMessage({type:'progress',percent,label,samples})}function parsePrice(line){const first=line.trim().split(/[\s,;\t]+/,2)[0],n=Number(first);return Number.isFinite(n)&&n>.2&&n<5?n:null}
class Rolling{constructor(n){this.n=n;this.a=new Float64Array(n);this.i=0;this.count=0;this.sum=0;this.sumSq=0}push(v){if(this.count<this.n){this.a[this.i]=v;this.sum+=v;this.sumSq+=v*v;this.i=(this.i+1)%this.n;this.count++;return}const old=this.a[this.i];this.a[this.i]=v;this.i=(this.i+1)%this.n;this.sum+=v-old;this.sumSq+=v*v-old*old}mean(){return this.count?this.sum/this.count:NaN}stdev(){if(!this.count)return NaN;const m=this.mean();return Math.sqrt(Math.max(0,this.sumSq/this.count-m*m))}values(){let out=[];for(let j=0;j<this.count;j++)out.push(this.a[(this.i-this.count+j+this.n)%this.n]);return out}}
class Engine{constructor(c){this.c=c;this.samples=0;this.balance=c.initialBalance;this.peak=this.balance;this.maxDD=0;this.maxDDPct=0;this.position=null;this.trades=[];this.wins=0;this.losses=0;this.grossWin=0;this.grossLoss=0;this.sumPips=0;this.eq=[[0,this.balance]];this.eqEvery=1;this.lastSignal=0;this.monthsProcessed=0;this.r1=new Rolling(Math.max(2,c.p1|0));this.r2=new Rolling(Math.max(2,c.p2|0));this.ema1=null;this.ema2=null;this.prev=null;this.rsiGain=0;this.rsiLoss=0;this.rsiSeed=0}
strategy(price){const c=this.c;let sig=0;if(c.strategy==='sma_cross'){this.r1.push(price);this.r2.push(price);if(this.r1.count===this.r1.n&&this.r2.count===this.r2.n)sig=this.r1.mean()>this.r2.mean()?1:-1}else if(c.strategy==='ema_cross'){const a1=2/(c.p1+1),a2=2/(c.p2+1);this.ema1=this.ema1==null?price:a1*price+(1-a1)*this.ema1;this.ema2=this.ema2==null?price:a2*price+(1-a2)*this.ema2;if(this.samples>=c.p2)sig=this.ema1>this.ema2?1:-1}else if(c.strategy==='rsi_mr'){if(this.prev!=null){const d=price-this.prev,g=Math.max(0,d),l=Math.max(0,-d),n=Math.max(2,c.p1|0);if(this.rsiSeed<n){this.rsiGain+=g;this.rsiLoss+=l;this.rsiSeed++;if(this.rsiSeed===n){this.rsiGain/=n;this.rsiLoss/=n}}else{this.rsiGain=(this.rsiGain*(n-1)+g)/n;this.rsiLoss=(this.rsiLoss*(n-1)+l)/n}if(this.rsiSeed>=n){const rsi=this.rsiLoss===0?100:100-100/(1+this.rsiGain/this.rsiLoss),lo=clamp(c.p2,1,49),hi=100-lo;if(rsi<=lo)sig=1;else if(rsi>=hi)sig=-1}}}else if(c.strategy==='bollinger_mr'){this.r1.push(price);if(this.r1.count===this.r1.n){const m=this.r1.mean(),sd=this.r1.stdev(),dev=Math.max(.1,c.p2/10);if(price<m-dev*sd)sig=1;else if(price>m+dev*sd)sig=-1}}else if(c.strategy==='breakout'){const before=this.r1.values();this.r1.push(price);if(before.length===this.r1.n){let hi=-Infinity,lo=Infinity;for(const v of before){if(v>hi)hi=v;if(v<lo)lo=v}if(price>hi)sig=1;else if(price<lo)sig=-1}}this.prev=price;return sig}
open(side,bid){const c=this.c,pip=c.pipSize,spr=c.spreadPips*pip,slip=c.slippagePips*pip,entry=side>0?bid+spr+slip:bid-slip,d=c.stopLossPips*pip;this.position={side,entry,stop:side>0?entry-d:entry+d,tp:side>0?entry+d*c.rr:entry-d*c.rr}}
close(bid,reason){if(!this.position)return;const c=this.c,p=this.position,pip=c.pipSize,spr=c.spreadPips*pip,slip=c.slippagePips*pip,exit=p.side>0?bid-slip:bid+spr+slip,pips=(p.side>0?(exit-p.entry):(p.entry-exit))/pip,pnl=pips*c.pipValuePerLot*c.lot-c.commissionPerLotRT*c.lot;this.balance+=pnl;this.peak=Math.max(this.peak,this.balance);const dd=this.peak-this.balance;this.maxDD=Math.max(this.maxDD,dd);this.maxDDPct=Math.max(this.maxDDPct,this.peak?dd/this.peak*100:0);if(pnl>0){this.wins++;this.grossWin+=pnl}else{this.losses++;this.grossLoss+=Math.abs(pnl)}this.sumPips+=pips;if(this.trades.length<c.maxTrades)this.trades.push({side:p.side>0?'BUY':'SELL',entry:p.entry,exit,reason,pips,pnl,equity:this.balance});this.position=null;this.recordEquity(true)}
recordEquity(force=false){if(force||this.samples%this.eqEvery===0){if(this.eq.length<3000)this.eq.push([this.samples,this.balance]);else if(this.samples%(this.eqEvery*=2)===0)this.eq.push([this.samples,this.balance])}}
tick(bid){this.samples++;if(this.position){const c=this.c,p=this.position,ask=bid+c.spreadPips*c.pipSize;if(p.side>0){if(bid<=p.stop)this.close(bid,'SL');else if(bid>=p.tp)this.close(bid,'TP')}else{if(ask>=p.stop)this.close(bid,'SL');else if(ask<=p.tp)this.close(bid,'TP')}}const sig=this.strategy(bid);if(sig){if(this.position&&sig!==this.position.side)this.close(bid,'SIGNAL');if(!this.position)this.open(sig,bid);this.lastSignal=sig}this.recordEquity(false)}
finish(lastBid){if(this.position&&Number.isFinite(lastBid))this.close(lastBid,'END');const n=this.wins+this.losses,net=this.balance-this.c.initialBalance;return{engineVersion:this.c.engineVersion,createdAt:new Date().toISOString(),config:this.c,summary:{netPnl:net,returnPct:net/this.c.initialBalance*100,trades:n,wins:this.wins,losses:this.losses,winRate:n?this.wins/n*100:0,profitFactor:this.grossLoss?this.grossWin/this.grossLoss:(this.grossWin?Infinity:0),expectancyPips:n?this.sumPips/n:0,maxDrawdown:this.maxDD,maxDrawdownPct:this.maxDDPct,tradesPerMonth:this.monthsProcessed?n/this.monthsProcessed:n},trades:this.trades,equity:this.eq,limitations:['Execution is a deterministic research approximation, not broker-identical MT5 execution.','Remote source provides sampled EURUSD sell/buy prices at one-second cadence; only first SELL/BID column is used.','Swap, latency, queue position, partial fills and order-book depth are not modeled.']}}
}
async function streamLines(stream,eng,label,totalHint,progressBase=0,progressSpan=100){const reader=stream.getReader(),dec=new TextDecoder();let buf='',bytes=0,lastBid=NaN;while(true){const{value,done}=await reader.read();if(done)break;bytes+=value.byteLength;buf+=dec.decode(value,{stream:true});let pos;while((pos=buf.indexOf('\n'))>=0){const line=buf.slice(0,pos);buf=buf.slice(pos+1);const p=parsePrice(line);if(p!=null){eng.tick(p);lastBid=p}}if(eng.samples%200000<5000){const frac=totalHint?Math.min(1,bytes/totalHint):0;postProgress(progressBase+frac*progressSpan,label,eng.samples)}}if(buf){const p=parsePrice(buf);if(p!=null){eng.tick(p);lastBid=p}}return lastBid}
async function runRemote(c){const eng=new Engine(c),months=c.months;let last=NaN;for(let i=0;i<months.length;i++){const ym=months[i],url=`${RAW}/EURUSD-${ym}_converted.txt`;postProgress(i/months.length*100,`Fetching ${ym}`,eng.samples);const res=await fetch(url,{cache:'no-store',signal:aborter.signal});if(!res.ok)throw new Error(`${ym}: HTTP ${res.status} — source file unavailable`);const len=+(res.headers.get('content-length')||0);last=await streamLines(res.body,eng,`Streaming ${ym}`,len,i/months.length*100,100/months.length);eng.monthsProcessed++}const result=eng.finish(last);result.data={mode:'remote',label:`${months[0]} → ${months[months.length-1]}`,months,samples:eng.samples,sourceRepository:c.source,rawTemplate:`${RAW}/EURUSD-YYYY-MM_converted.txt`,redistributed:false};postMessage({type:'result',result})}
async function runFile(c,file){const eng=new Engine(c);postProgress(0,`Reading ${file.name}`,0);const last=await streamLines(file.stream(),eng,file.name,file.size);eng.monthsProcessed=1;const result=eng.finish(last);result.data={mode:'upload',label:file.name,months:[],samples:eng.samples,sourceRepository:'user upload',sizeBytes:file.size,redistributed:false};postMessage({type:'result',result})}
onmessage=async e=>{const{type,config,file}=e.data||{};aborter=new AbortController();try{if(type==='runRemote')await runRemote(config);else if(type==='runFile')await runFile(config,file);else throw new Error('Unknown command')}catch(err){postMessage({type:'error',error:String(err&&err.message||err)})}};
