import {DatabaseSync} from 'node:sqlite';
import {readFileSync,mkdirSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import * as OS from '../rwa-os-core.mjs';
const HERE=dirname(fileURLToPath(import.meta.url)),now=()=>Date.now(),id=p=>`${p}_${crypto.randomUUID().replaceAll('-','')}`;
export class RWAOperatingDB{
  constructor(path=process.env.RWA_OS_DB||resolve(HERE,'data/rwa-os.sqlite')){if(path!==':memory:')mkdirSync(dirname(path),{recursive:true});this.db=new DatabaseSync(path);this.db.exec(readFileSync(resolve(HERE,'schema.sql'),'utf8'))}
  close(){this.db.close()}
  tx(fn){this.db.exec('BEGIN IMMEDIATE');try{const out=fn();this.db.exec('COMMIT');return out}catch(e){try{this.db.exec('ROLLBACK')}catch{}throw e}}
  audit(actor,action,type,entity,detail={}){this.db.prepare('INSERT INTO audit_log(ts,actor,action,entity_type,entity_id,detail_json) VALUES(?,?,?,?,?,?)').run(now(),actor,action,type,entity,JSON.stringify(detail))}
  async createSeries(input,actor='issuer'){const s=OS.validateSeries(input),m=await OS.termsManifest(s);if(this.db.prepare('SELECT 1 FROM series WHERE id=?').get(s.id))throw Error('series_exists');this.db.prepare('INSERT INTO series(id,type,title,issuer,jurisdiction,currency,total_units,status,immutable_hash,governed_hash,terms_json,evidence_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(s.id,s.type,s.title,s.issuer,s.jurisdiction,s.currency,s.totalUnits,'DRAFT',m.immutableHash,m.governedHash,JSON.stringify(m),JSON.stringify(s.evidence),now());this.audit(actor,'series.create','series',s.id,{immutableHash:m.immutableHash,governedHash:m.governedHash});return this.series(s.id)}
  series(seriesId){const r=this.db.prepare('SELECT * FROM series WHERE id=?').get(String(seriesId).toUpperCase());if(!r)return null;return{...r,terms:JSON.parse(r.terms_json),evidence:JSON.parse(r.evidence_json)}}
  allSeries(){return this.db.prepare('SELECT id,type,title,issuer,jurisdiction,currency,total_units,status,immutable_hash,governed_hash,created_at,activated_at FROM series ORDER BY created_at DESC').all()}
  activateSeries(seriesId,actor='issuer'){const s=this.series(seriesId);if(!s)throw Error('series_not_found');const evidence=JSON.parse(s.evidence_json||'{}'),missing=['ownership','legal','valuation','issuer','disclosure'].filter(k=>!/^https:\/\//i.test(String(evidence[k]||'')));if(missing.length)throw Error(`asset_evidence_missing:${missing.join(',')}`);this.db.prepare("UPDATE series SET status='ACTIVE',activated_at=? WHERE id=?").run(now(),s.id);this.audit(actor,'series.activate','series',s.id,{immutableHash:s.immutable_hash});return this.series(s.id)}
  async proposeGoverned(seriesId,governed,actor='issuer'){const s=this.series(seriesId);if(!s)throw Error('series_not_found');const old=s.terms.governed,g={...old,...governed};const notice=Math.max(Number(old.noticeSeconds||0),Number(g.noticeSeconds||0)),hash=await OS.sha256Hex({seriesId:s.id,...g}),proposal=id('gov'),executeAfter=now()+notice*1000;this.db.prepare('INSERT INTO governed_proposals(id,series_id,governed_json,governed_hash,execute_after,status,created_at) VALUES(?,?,?,?,?,\'PENDING\',?)').run(proposal,s.id,JSON.stringify(g),hash,executeAfter,now());this.audit(actor,'governed.propose','series',s.id,{proposal,hash,executeAfter});return{id:proposal,seriesId:s.id,governed:g,hash,executeAfter,status:'PENDING'}}
  executeGoverned(proposalId,actor='issuer',at=now()){const p=this.db.prepare('SELECT * FROM governed_proposals WHERE id=?').get(proposalId);if(!p)throw Error('proposal_not_found');if(p.status!=='PENDING')throw Error('proposal_not_pending');if(Number(at)<Number(p.execute_after))throw Error('governance_notice_active');const s=this.series(p.series_id),terms={...s.terms,governed:JSON.parse(p.governed_json),governedHash:p.governed_hash};this.tx(()=>{this.db.prepare('UPDATE series SET governed_hash=?,terms_json=? WHERE id=?').run(p.governed_hash,JSON.stringify(terms),s.id);this.db.prepare("UPDATE governed_proposals SET status='EXECUTED',executed_at=? WHERE id=?").run(Number(at),p.id)});this.audit(actor,'governed.execute','series',s.id,{proposal:p.id,hash:p.governed_hash});return this.series(s.id)}
  async ingestTransaction(input,actor='terminal'){const s=this.series(input.seriesId);if(!s||s.status!=='ACTIVE')throw Error('active_series_required');const tx=OS.transaction(input),payloadHash=await OS.sha256Hex(OS.transactionCodePayload(tx));try{this.tx(()=>{this.db.prepare('INSERT INTO business_transactions(id,series_id,merchant_id,location_id,terminal_id,product_id,amount_minor,currency,external_ref,occurred_at,state,payload_hash,metadata_json,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(tx.id,tx.seriesId,tx.merchantId,tx.locationId,tx.terminalId,tx.productId,tx.amountMinor,tx.currency,tx.externalRef,tx.occurredAt,tx.state,payloadHash,JSON.stringify(tx.metadata||{}),now());this.db.prepare('INSERT INTO transaction_events(tx_id,state,at,reason,provider_ref) VALUES(?,?,?,?,?)').run(tx.id,'CREATED',tx.occurredAt,'','')})}catch(e){if(String(e.message).includes('UNIQUE'))throw Error('duplicate_external_reference');throw e}this.audit(actor,'transaction.ingest','transaction',tx.id,{seriesId:tx.seriesId,externalRef:tx.externalRef,payloadHash});return this.transaction(tx.id)}
  transaction(txId){const r=this.db.prepare('SELECT * FROM business_transactions WHERE id=?').get(txId);if(!r)return null;const events=this.db.prepare('SELECT state,at,reason,provider_ref providerRef FROM transaction_events WHERE tx_id=? ORDER BY id').all(txId);return{...r,seriesId:r.series_id,merchantId:r.merchant_id,locationId:r.location_id,terminalId:r.terminal_id,productId:r.product_id,amountMinor:r.amount_minor,externalRef:r.external_ref,occurredAt:r.occurred_at,settledAt:r.settled_at,refundedAt:r.refunded_at,reversedAt:r.reversed_at,metadata:JSON.parse(r.metadata_json||'{}'),events}}
  transitionTransaction(txId,next,{actor='provider',at=now(),reason='',providerRef=''}={}){const raw=this.transaction(txId);if(!raw)throw Error('transaction_not_found');const updated=OS.transitionTransaction(raw,next,{at,reason,providerRef});this.tx(()=>{this.db.prepare('UPDATE business_transactions SET state=?,settled_at=?,refunded_at=?,reversed_at=? WHERE id=?').run(updated.state,updated.settledAt,updated.refundedAt,updated.reversedAt,txId);this.db.prepare('INSERT INTO transaction_events(tx_id,state,at,reason,provider_ref) VALUES(?,?,?,?,?)').run(txId,updated.state,Number(at),String(reason),String(providerRef))});this.audit(actor,'transaction.transition','transaction',txId,{from:raw.state,to:updated.state,providerRef});return this.transaction(txId)}
  ledger(seriesId){return this.db.prepare('SELECT id FROM business_transactions WHERE series_id=? ORDER BY occurred_at').all(String(seriesId).toUpperCase()).map(x=>this.transaction(x.id))}
  addHolderCheckpoints(seriesId,rows,sourceRef,actor='indexer'){const s=this.series(seriesId);if(!s)throw Error('series_not_found');if(!String(sourceRef||'').trim())throw Error('snapshot_source_required');this.tx(()=>{for(const x of rows){const w=String(x.wallet||'').toLowerCase();if(!/^0x[a-f0-9]{40}$/.test(w)||Number(x.balance)<0)throw Error('invalid_holder_checkpoint');this.db.prepare('INSERT OR IGNORE INTO holder_checkpoints(series_id,wallet,balance,ts,source_ref) VALUES(?,?,?,?,?)').run(s.id,w,Number(x.balance),Number(x.ts),String(sourceRef))}});this.audit(actor,'holders.ingest','series',s.id,{count:rows.length,sourceRef});return this.holderCheckpoints(s.id)}
  holderCheckpoints(seriesId){return this.db.prepare('SELECT wallet,balance,ts,source_ref sourceRef FROM holder_checkpoints WHERE series_id=? ORDER BY ts,wallet').all(String(seriesId).toUpperCase())}
  async createDistribution(seriesId,{periodId,expensesMinor=0,deductionsMinor=0,recordAt=now(),periodStart,periodEnd,evidenceUrls=[]}={},actor='issuer'){const s=this.series(seriesId);if(!s||s.status!=='ACTIVE')throw Error('active_series_required');const ledger=this.ledger(s.id),calc=OS.calculateDistribution({terms:s.terms,ledger,expensesMinor,deductionsMinor}),snapshot=OS.holderSnapshot({checkpoints:this.holderCheckpoints(s.id),policy:s.terms.governed.snapshotPolicy,recordAt,periodStart,periodEnd}),allocation=OS.allocateEntitlements(calc.poolMinor,snapshot,{minimumPayoutMinor:s.terms.governed.minimumPayoutMinor}),manifest=await OS.distributionManifest({seriesId:s.id,periodId,calculation:calc,snapshot,allocation,evidenceUrls});const did=id('dist');this.tx(()=>{this.db.prepare('INSERT INTO distributions(id,series_id,period_id,manifest_hash,pool_minor,allocated_minor,withheld_minor,payout_asset,status,manifest_json,created_at) VALUES(?,?,?,?,?,?,?,?,\'AWAITING_FUNDING\',?,?)').run(did,s.id,String(periodId),manifest.manifestHash,manifest.poolMinor,manifest.allocatedMinor,manifest.withheldMinor,manifest.payoutAsset,JSON.stringify(manifest),now());for(const e of manifest.entitlements)this.db.prepare('INSERT INTO entitlements(distribution_id,wallet,amount_minor,weight) VALUES(?,?,?,?)').run(did,e.wallet,e.amountMinor,e.weight)});this.audit(actor,'distribution.create','distribution',did,{seriesId:s.id,periodId,manifestHash:manifest.manifestHash,poolMinor:manifest.poolMinor});return this.distribution(did)}
  distribution(did){const r=this.db.prepare('SELECT * FROM distributions WHERE id=?').get(did);if(!r)return null;return{...r,manifest:JSON.parse(r.manifest_json),entitlements:this.db.prepare('SELECT wallet,amount_minor amountMinor,weight,status,payout_ref payoutRef FROM entitlements WHERE distribution_id=? ORDER BY wallet').all(did)}}
  markFunded(did,fundedRef,actor='treasury'){const d=this.distribution(did);if(!d)throw Error('distribution_not_found');if(!String(fundedRef||'').trim())throw Error('funding_receipt_required');this.db.prepare("UPDATE distributions SET status='FUNDED',funded_ref=? WHERE id=?").run(String(fundedRef),did);this.audit(actor,'distribution.funded','distribution',did,{fundedRef});return this.distribution(did)}
  markPayout(did,wallet,payoutRef,actor='payout-worker'){const d=this.distribution(did);if(!d||d.status!=='FUNDED')throw Error('funded_distribution_required');const w=String(wallet).toLowerCase();if(!String(payoutRef||'').trim())throw Error('payout_receipt_required');const e=this.db.prepare('SELECT * FROM entitlements WHERE distribution_id=? AND wallet=?').get(did,w);if(!e)throw Error('entitlement_not_found');this.db.prepare("UPDATE entitlements SET status='PAID',payout_ref=? WHERE distribution_id=? AND wallet=?").run(String(payoutRef),did,w);const remaining=this.db.prepare("SELECT count(*) n FROM entitlements WHERE distribution_id=? AND status<>'PAID'").get(did).n;if(Number(remaining)===0)this.db.prepare("UPDATE distributions SET status='PAID' WHERE id=?").run(did);this.audit(actor,'entitlement.paid','distribution',did,{wallet:w,payoutRef});return this.distribution(did)}
  investor(wallet){const w=String(wallet||'').toLowerCase();return this.db.prepare('SELECT e.distribution_id distributionId,d.series_id seriesId,d.period_id periodId,e.amount_minor amountMinor,d.payout_asset payoutAsset,e.status,e.payout_ref payoutRef FROM entitlements e JOIN distributions d ON d.id=e.distribution_id WHERE e.wallet=? ORDER BY d.created_at DESC').all(w)}
  async reconcile(seriesId){const s=this.series(seriesId);if(!s)throw Error('series_not_found');const dists=this.db.prepare('SELECT id,manifest_json,pool_minor,allocated_minor FROM distributions WHERE series_id=?').all(s.id);const ledger=this.ledger(s.id),issues=[];const summary=OS.ledgerSummary(ledger);if(summary.duplicateExternalRefs.length)issues.push('duplicate_external_reference');for(const d of dists){const m=JSON.parse(d.manifest_json);if(Number(d.allocated_minor)>Number(d.pool_minor))issues.push(`distribution_overallocated:${d.id}`);if(m.manifestHash!==await OS.sha256Hex(Object.fromEntries(Object.entries(m).filter(([k])=>k!=='manifestHash'&&k!=='status'))).catch(()=>m.manifestHash)){} }const audit=await OS.auditOperatingSystem({series:{id:s.id,type:s.type,title:s.title,issuer:s.issuer,jurisdiction:s.jurisdiction,currency:s.currency,totalUnits:s.total_units,economic:s.terms,evidence:s.evidence},ledger});audit.issues=[...new Set([...audit.issues,...issues])];audit.ok=audit.issues.length===0;return audit}
}
