(()=>{
'use strict';
const $=id=>document.getElementById(id);let current=null,assetCounter=0;
const engineMeta=[['passport','RWA Passport','Identity + credential intent'],['registry','Asset Registry','Business → asset graph'],['proof','Proof Engine','Evidence hashes + provenance'],['valuation','Valuation','DCF / declared value'],['legal','Jurisdiction','Policy + reviewer gate'],['compliance','Compliance','KYB / screening / transfer'],['factory','RWA Factory','Issuance-readiness draft'],['marketplace','Marketplace','Discovery → finance → trade']];
const stageMeta=[['register','REGISTERED'],['verify','VERIFIED'],['value','VALUED'],['finance','FINANCEABLE'],['tokenize','TOKENIZATION READY'],['trade','TRADABLE']];
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const money=(v,c='USD')=>{const n=Number(v);if(!Number.isFinite(n))return'—';try{return new Intl.NumberFormat('en-US',{style:'currency',currency:c,maximumFractionDigits:0}).format(n)}catch{return`${c} ${n.toLocaleString()}`}};
function tone(status=''){const s=upper(status);if(/BLOCKED|MISSING|FAIL|INCOMPLETE/.test(s))return'bad';if(/CREATED|REGISTERED|REVIEWED|MODELLED|APPROVED|CLEAR|READY|ALLOWED|DISCOVERY/.test(s))return'ok';return'warn'}
function upper(v){return String(v||'').toUpperCase()}
function renderEngineGrid(result){$('engineGrid').innerHTML=engineMeta.map(([id,title,sub])=>{const e=result?.[id],status=e?.status||'WAITING';return`<article class="engine ${tone(status)}"><span class="dot"></span><small>${id.toUpperCase()}</small><b>${esc(title)}</b><small>${esc(sub)}</small><div><strong>${esc(status)}</strong></div></article>`}).join('')}
function addAsset(values={}){const tpl=$('assetTemplate');if(!tpl)return;const node=tpl.content.firstElementChild.cloneNode(true);assetCounter++;node.dataset.assetRow=String(assetCounter);node.querySelector('.asset-row-head b').textContent=`Asset ${assetCounter}`;node.querySelectorAll('[data-asset]').forEach(el=>{const k=el.dataset.asset;if(values[k]!=null)el.value=values[k]});node.querySelector('[data-remove-asset]').onclick=()=>{if(document.querySelectorAll('[data-asset-row]').length>1)node.remove()};$('assetRows').appendChild(node)}
function collectAssets(){return[...document.querySelectorAll('[data-asset-row]')].map(row=>{const o={};row.querySelectorAll('[data-asset]').forEach(el=>o[el.dataset.asset]=el.value);return o}).filter(x=>String(x.name||'').trim())}
async function collectEvidence(fd){const files=[...($('evidenceFiles')?.files||[])],rows=[];for(let i=0;i<files.length;i++){const f=files[i],fileSha256=await window.RWA8Engines.hashFile(f);rows.push({id:`FILE-${i+1}`,type:fd.get('evidenceType'),name:f.name,source:fd.get('evidenceSource'),fileSha256,reviewStatus:'UNREVIEWED'})}if(!rows.length&&fd.get('evidenceSource'))rows.push({id:'SOURCE-1',type:fd.get('evidenceType'),name:fd.get('evidenceSource'),source:fd.get('evidenceSource'),reviewStatus:'UNREVIEWED'});return rows}
async function formInput(form){const fd=new FormData(form),evidence=await collectEvidence(fd);return{mode:fd.get('mode'),business:{legalName:fd.get('legalName'),registrationId:fd.get('registrationId'),country:fd.get('country'),businessType:fd.get('businessType'),website:fd.get('website')},assets:collectAssets(),evidence,screening:{status:'PENDING',providerVerified:false},review:{legalApproved:false,valuationApproved:false,kybApproved:false,transferEligible:false,instrumentApproved:false,venueApproved:false}}}
function renderReadiness(r){$('readiness').innerHTML=stageMeta.map(([key,label])=>`<article class="ready-row ${r.ready[key]?'ok':'warn'}"><header><span>${label}</span><b>${r.ready[key]?'READY':'GATED'}</b></header><small>${r.ready[key]?'Acceptance criteria met':'More evidence/review is required'}</small></article>`).join('')}
function renderBlockers(r){const list=r.blockers||[];$('blockerList').innerHTML=list.length?`<ul>${list.map(x=>`<li>${esc(x.replaceAll('_',' '))}</li>`).join('')}</ul>`:'<p class="oktext">No current registration blockers. Higher maturity stages may still require professional approvals.</p>'}
function renderResult(r){current=r;$('resultEmpty').hidden=true;$('result').hidden=false;renderEngineGrid(r);renderReadiness(r);renderBlockers(r);$('passportId').textContent=r.passport.id;$('passportBusiness').textContent=r.passport.business.legalName;$('passportCountry').textContent=r.passport.business.country;$('passportAssets').textContent=String(r.registry.assets.length);$('passportMaturity').textContent=r.maturity;const first=r.valuation.assets.find(x=>x.valuation)?.valuation,currency=r.registry.assets.find(a=>a.currency)?.currency||'USD';$('valuationValue').textContent=r.valuation.totalModelValue?money(r.valuation.totalModelValue,currency):'Insufficient data';$('valuationMethod').textContent=first?`${first.method} · ${r.valuation.disclaimer}`:r.valuation.disclaimer;$('listingLevel').textContent=r.marketplace.listing.maturity;$('listingExecution').textContent=`Visibility ${r.marketplace.listing.visibility} · execution ${r.marketplace.listing.execution}`;$('resultJson').textContent=JSON.stringify(r,null,2);window.RWA8Engines.recordEvent('pipeline_completed',{businessId:r.passport.id,maturity:r.maturity,mode:r.mode});updateNorthStar()}
function renderSaved(){const rows=window.RWA8Engines?.loadSaved?.()||[],host=$('savedList');host.innerHTML=rows.length?rows.map((r,i)=>`<article class="saved-row"><div><b>${esc(r.passport?.business?.legalName||'Business')}</b><small>${esc(r.passport?.id||'')} · ${esc(r.maturity||'REGISTERED_RWA')}</small></div><div><button type="button" data-open-saved="${i}">Open</button><button type="button" data-delete-saved="${esc(r.passport?.id||'')}">Delete</button></div></article>`).join(''):'<p>No saved RWA Passport yet.</p>';host.querySelectorAll('[data-open-saved]').forEach(b=>b.onclick=()=>renderResult(rows[Number(b.dataset.openSaved)]));host.querySelectorAll('[data-delete-saved]').forEach(b=>b.onclick=()=>{window.RWA8Engines.removePassport(b.dataset.deleteSaved);renderSaved();updateNorthStar()})}
function updateNorthStar(){const n=window.RWA8Engines?.northStar?.();$('northStarCount').textContent=String(n?.localActiveBusinesses||0)}
async function submit(e){e.preventDefault();const btn=e.submitter;try{if(btn)btn.disabled=true;const input=await formInput(e.currentTarget);if(!input.assets.length)throw Error('Add at least one asset');const result=await window.RWA8Engines.runPipeline(input);renderResult(result)}catch(err){console.error(err);alert('RWA pipeline failed: '+(err?.message||err))}finally{if(btn)btn.disabled=false}}
function loadDemo(){const f=$('rwaFactoryForm'),set=(name,value)=>{const x=f.elements[name];if(x)x.value=value};set('legalName','Patimban Logistics & Cold Chain');set('registrationId','DEMO-ID-2026-001');set('country','ID');set('businessType','Infrastructure');set('website','https://example.com');set('evidenceSource','DEMO-DATAROOM-001');set('evidenceType','Company Registration');set('mode','REGISTER');$('assetRows').innerHTML='';assetCounter=0;addAsset({assetType:'Infrastructure',country:'ID',name:'Cold Storage & Logistics Facility',description:'Operating cold-chain facility serving export businesses with warehouse, logistics and contracted revenue.',declaredValue:'5000000',currency:'USD',annualRevenue:'1800000',ebitdaMargin:'24',growthRate:'8',discountRate:'16'})}
function clearForm(){setTimeout(()=>{$('assetRows').innerHTML='';assetCounter=0;addAsset();current=null;$('result').hidden=true;$('resultEmpty').hidden=false;renderEngineGrid(null)},0)}
function boot(){renderEngineGrid(null);addAsset();renderSaved();updateNorthStar();$('rwaFactoryForm')?.addEventListener('submit',submit);$('addAsset')?.addEventListener('click',()=>addAsset());$('loadDemo')?.addEventListener('click',loadDemo);$('clearForm')?.addEventListener('click',clearForm);$('savePassport')?.addEventListener('click',()=>{if(current){window.RWA8Engines.savePassport(current);renderSaved();updateNorthStar()}});$('exportPassport')?.addEventListener('click',()=>{if(current)window.RWA8Engines.exportJson(current)});if(new URLSearchParams(location.search).get('embed')==='1')document.documentElement.dataset.embed='1'}
if(window.RWA8Engines)boot();else addEventListener('rwa:8-engines-ready',boot,{once:true});
})();
