(()=>{
'use strict';
if(window.RWARenkoV13)return;
const $=id=>document.getElementById(id);
const RESTS=['https://data-api.binance.vision','https://api.binance.com'];
const PAGE=1000,FIRST_VIEW=60,STORE='rwa_renko_v13_settings';
const METHODS=new Set(['atr','traditional','percentage']);
const now=()=>Date.now(),sleep=ms=>new Promise(r=>setTimeout(r,ms)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fmt=n=>{n=Number(n);if(!Number.isFinite(n))return'—';const a=Math.abs(n),d=a>=1000?2:a>=100?3:a>=1?4:a>=.01?6:8;return n.toLocaleString(undefined,{maximumFractionDigits:d})};
const fmtDate=ms=>Number(ms)?new Date(Number(ms)).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'}):'—';
function decimals(x){const s=String(x);if(s.includes('e-'))return Math.min(12,Number(s.split('e-')[1])||0);const i=s.indexOf('.');return i<0?0:Math.min(12,s.length-i-1)}
function roundTick(v,t){v=Number(v);t=Number(t);if(!(v>0))return Number.EPSILON;if(!(t>0))return v;const q=Math.max(1,Math.round(v/t)),d=decimals(t);return Number((q*t).toFixed(d))}
const C={method:'atr',atrLength:14,atrFactor:1,traditionalBox:100,percentage:.001,wicks:true,confirmBricks:2};
try{Object.assign(C,JSON.parse(localStorage.getItem(STORE)||'{}')||{})}catch{}
if(!METHODS.has(C.method))C.method='atr';C.atrLength=clamp(Math.floor(Number(C.atrLength)||14),1,200);C.atrFactor=clamp(Number(C.atrFactor)||1,.01,20);C.traditionalBox=Math.max(Number.EPSILON,Number(C.traditionalBox)||100);C.percentage=clamp(Number(C.percentage)||.001,.000001,.1);C.wicks=C.wicks!==false;C.confirmBricks=Number(C.confirmBricks)===1?1:2;
const S={version:'13.0.0',generation:0,symbol:'',tickSize:NaN,atrValue:NaN,box:NaN,ticks:[],bricks:[],data:[],tailState:null,buildSeq:0,loading:false,building:false,exhausted:false,oldestAggId:null,lastHistoryTime:0,lastLiveId:null,lastLiveTime:0,feedSeenId:null,feedSeenTime:0,pendingLive:[],following:true,signal:null,processedLiveTrades:0,droppedLiveTrades:0};
let chart=null,series=null,liveLine=null,worker=null,resizeObserver=null,watchTimer=0,rangeTimer=0,metaFrame=0,lastSymbol='';
function save(){try{localStorage.setItem(STORE,JSON.stringify(C))}catch{}}
function setText(id,text){const e=$(id);if(e)e.textContent=text}
function setStatus(text,kind='ready'){const e=$('tvLoadState');if(e){e.textContent=text;e.dataset.kind=kind}const l=$('tvLoading');if(l)l.hidden=kind!=='loading'}
function methodName(m=C.method){return m==='atr'?'ATR':m==='traditional'?'TRADITIONAL':'PERCENTAGE'}
function mode(){setText('modePill',`${methodName()} · TICK · V13`);setText('sourceText','Lossless tick-native Renko · every buffered Binance trade is drained in order · no candle-close interval.')}
function queueMeta(){if(metaFrame)return;metaFrame=requestAnimationFrame(()=>{metaFrame=0;meta()})}
function rawBox(st,price){if(C.method==='traditional')return C.traditionalBox;if(C.method==='atr')return Number(S.atrValue)*C.atrFactor;const base=Number.isFinite(Number(st?.lastClose))&&Math.abs(Number(st.lastClose))>0?Math.abs(Number(st.lastClose)):Math.abs(Number(price));return base*C.percentage}
function currentBox(st=S.tailState,price=Number(window.RWARenkoV3?.state?.lastPrice)){const raw=rawBox(st,price),fallback=Math.max(Number(S.tickSize)||Number.EPSILON,Math.abs(Number(price)||1)*.001);return roundTick(raw>0?raw:fallback,S.tickSize)}
function meta(){const r=chart?.timeScale?.().getVisibleLogicalRange?.(),width=r?Math.max(1,Math.round(r.to-r.from)):FIRST_VIEW;S.box=currentBox();setText('tvZoomValue',String(width));setText('tvBrickMeta',`${Math.min(width,S.data.length)} visible · ${S.data.length.toLocaleString()} confirmed`);setText('tvCoverage',S.ticks.length?`${fmtDate(S.ticks[0]?.time)} → LIVE TICK`:'Preparing trade history');setText('brickValue',fmt(S.box));setText('brickCount',S.data.length.toLocaleString());setText('v11MethodLabel',methodName());setText('v11CurrentBox',fmt(S.box));setText('v11AtrNow',Number.isFinite(S.atrValue)?fmt(S.atrValue):'—');setText('v12LtpSnapshot',fmt(Number(window.RWARenkoV3?.state?.lastPrice)));setText('v11TickSize',fmt(S.tickSize))}
async function fetchJson(path,timeout=12000){const attempts=RESTS.map(root=>new Promise(async(resolve,reject)=>{const c=new AbortController(),tm=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(root+path,{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);resolve(await r.json())}catch(e){reject(e)}finally{clearTimeout(tm)}}));try{return await Promise.any(attempts)}catch(e){throw e?.errors?.at?.(-1)||e||Error('market data unavailable')}}
async function fetchTickSize(symbol){try{const j=await fetchJson(`/api/v3/exchangeInfo?symbol=${encodeURIComponent(symbol)}`),pf=j?.symbols?.[0]?.filters?.find?.(f=>f.filterType==='PRICE_FILTER'),t=Number(pf?.tickSize);if(t>0)return t}catch(e){console.warn('[V13 tick]',e)}return .00000001}
function wilderAtr(rows,len){const tr=[];let prev=NaN;for(const r of rows||[]){const h=Number(r?.[2]),l=Number(r?.[3]),c=Number(r?.[4]);if(![h,l,c].every(Number.isFinite))continue;tr.push(Number.isFinite(prev)?Math.max(h-l,Math.abs(h-prev),Math.abs(l-prev)):h-l);prev=c}if(!tr.length)return NaN;len=Math.max(1,Math.floor(Number(len)||14));if(tr.length<len)return tr.reduce((a,b)=>a+b,0)/tr.length;let a=tr.slice(0,len).reduce((x,y)=>x+y,0)/len;for(let i=len;i<tr.length;i++)a=((a*(len-1))+tr[i])/len;return a}
async function fetchAtr(symbol){try{const rows=await fetchJson(`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=1m&limit=${Math.max(80,C.atrLength+40)}`),t=now(),closed=(Array.isArray(rows)?rows:[]).filter(r=>Number(r?.[6]||0)<t);return wilderAtr(closed,C.atrLength)}catch(e){console.warn('[V13 ATR]',e);return NaN}}
function mapAgg(rows){return(Array.isArray(rows)?rows:[]).map(x=>({id:Number(x.a),price:Number(x.p),qty:Number(x.q)||0,time:Number(x.T),kind:'agg'})).filter(x=>Number.isFinite(x.id)&&Number.isFinite(x.price)&&Number.isFinite(x.time)).sort((a,b)=>a.id-b.id)}
function dedupeTicks(rows){const m=new Map();for(const t of rows||[]){if(!Number.isFinite(Number(t?.price))||!Number.isFinite(Number(t?.time)))continue;const id=Number(t?.id),kind=String(t?.kind||'x'),k=Number.isFinite(id)?`${kind}:${id}`:`${kind}:${t.time}:${t.price}`;m.set(k,t)}return[...m.values()].sort((a,b)=>(Number(a.time)-Number(b.time))||((Number(a.id)||0)-(Number(b.id)||0)))}
async function latestAgg(symbol){return mapAgg(await fetchJson(`/api/v3/aggTrades?symbol=${encodeURIComponent(symbol)}&limit=${PAGE}`,15000))}
async function olderAgg(symbol,fromId){return mapAgg(await fetchJson(`/api/v3/aggTrades?symbol=${encodeURIComponent(symbol)}&fromId=${Math.max(0,Math.floor(fromId))}&limit=${PAGE}`,15000))}
function ensureWorker(){if(worker)return worker;worker=new Worker('renko-v13-worker.js?v=130');return worker}
function normalizeAll(bricks){let t=0;return(bricks||[]).map((b,i)=>{let tm=Math.max(1,Math.floor(Number(b.time||0)/1000));if(tm<=t)tm=t+1;t=tm;const o=Number(b.open),c=Number(b.close),h=Number(b.high),l=Number(b.low),d=Number(b.direction)||0;return{time:tm,open:o,high:Number.isFinite(h)?Math.max(h,o,c):Math.max(o,c),low:Number.isFinite(l)?Math.min(l,o,c):Math.min(o,c),close:c,color:d>0?'#089981':'#f23645',borderColor:d>0?'#089981':'#f23645',wickColor:d>0?'#089981':'#f23645',_dir:d,_reversal:!!b.isReversal,_box:Number(b.box),_ms:Number(b.time||0),_i:i}})}
function rangeAnchor(){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r||!S.data.length)return null;const i=clamp(Math.floor(r.from),0,S.data.length-1),d=S.data[i];return{range:r,index:i,time:d?.time,close:d?.close}}
function restoreAnchor(a){if(!a||!chart||!S.data.length)return;let i=S.data.findIndex(d=>d.time===a.time&&Math.abs(Number(d.close)-Number(a.close))<Math.max(1e-10,Math.abs(Number(a.close))*1e-9));if(i<0)i=S.data.findIndex(d=>d.time>=a.time);if(i<0)return;const sh=i-a.index;chart.timeScale().setVisibleLogicalRange({from:a.range.from+sh,to:a.range.to+sh})}
function workerPayload(id,generation,ticks){return{type:'build',id,generation,method:C.method,traditionalBox:C.traditionalBox,percentage:C.percentage,atrValue:S.atrValue,atrFactor:C.atrFactor,tickSize:S.tickSize,wicks:C.wicks,ticks}}
function rebuild(anchor=null){if(!S.ticks.length||!(S.tickSize>0))return Promise.resolve(false);const generation=S.generation,id=++S.buildSeq,ticks=S.ticks.slice();S.building=true;setStatus('Building lossless tick Renko…','loading');return new Promise((resolve,reject)=>{const w=ensureWorker(),on=e=>{const m=e.data||{};if((m.type!=='built'&&m.type!=='error')||m.id!==id)return;w.removeEventListener('message',on);if(generation!==S.generation||id!==S.buildSeq){resolve(false);return}S.building=false;if(m.type==='error'){reject(Error(m.message||'worker error'));return}S.bricks=Array.isArray(m.bricks)?m.bricks:[];S.data=normalizeAll(S.bricks);S.box=Number(m.box);S.tailState=m.tailState||null;series?.setData(S.data);showChart();restoreAnchor(anchor);flushPendingLive();if(S.following)latestView();setStatus('LIVE · lossless trade drain','ready');evaluateSignal();meta();resolve(true)};w.addEventListener('message',on);try{w.postMessage(workerPayload(id,generation,ticks))}catch(e){w.removeEventListener('message',on);if(id===S.buildSeq)S.building=false;reject(e)}})}
function showChart(){const e=$('chartEmpty');if(e)e.classList.add('hide');const h=$('lwcRenkoHost');if(h)h.style.visibility='visible'}
function latestView(){if(!chart||!S.data.length)return;const n=S.data.length;chart.timeScale().setVisibleLogicalRange({from:Math.max(0,n-FIRST_VIEW),to:n+5});S.following=true;meta()}
function touch(st,p){if(!Number.isFinite(st.pendingHigh))st.pendingHigh=p;if(!Number.isFinite(st.pendingLow))st.pendingLow=p;if(p>st.pendingHigh)st.pendingHigh=p;if(p<st.pendingLow)st.pendingLow=p}
function emitLive(st,out,open,close,dir,t,box,rev){let high=Math.max(open,close),low=Math.min(open,close);if(C.wicks){if(dir>0)low=Math.min(low,st.pendingLow);else high=Math.max(high,st.pendingHigh)}out.push({time:t,open,high,low,close,direction:dir,box,isReversal:!!rev});st.lastClose=close;st.direction=dir;st.lastTime=t;st.pendingHigh=close;st.pendingLow=close}
function processLive(st,tick){const p=Number(tick.price),t=Number(tick.time)||now(),out=[];if(!st||!Number.isFinite(p))return out;touch(st,p);let g=0;while(g++<20000){const b=currentBox(st,p),lc=st.lastClose,d=st.direction;if(!(b>0)||!Number.isFinite(lc))break;if(d===0){if(p>=lc+b){emitLive(st,out,lc,lc+b,1,t,b,false);continue}if(p<=lc-b){emitLive(st,out,lc,lc-b,-1,t,b,false);continue}break}if(d>0){if(p>=lc+b){emitLive(st,out,lc,lc+b,1,t,b,false);continue}if(p<=lc-2*b){emitLive(st,out,lc-b,lc-2*b,-1,t,b,true);continue}break}if(p<=lc-b){emitLive(st,out,lc,lc-b,-1,t,b,false);continue}if(p>=lc+2*b){emitLive(st,out,lc+b,lc+2*b,1,t,b,true);continue}break}touch(st,p);S.box=currentBox(st,p);return out}
function normalizeOne(b){const prev=Number(S.data.at(-1)?.time||0);let t=Math.max(1,Math.floor(Number(b.time||0)/1000));if(t<=prev)t=prev+1;const o=Number(b.open),c=Number(b.close),d=Number(b.direction)||0;return{time:t,open:o,high:Math.max(Number(b.high),o,c),low:Math.min(Number(b.low),o,c),close:c,color:d>0?'#089981':'#f23645',borderColor:d>0?'#089981':'#f23645',wickColor:d>0?'#089981':'#f23645',_dir:d,_reversal:!!b.isReversal,_box:Number(b.box),_ms:Number(b.time||0),_i:S.data.length}}
function updateLiveLine(p){if(!series||!Number.isFinite(p))return;if(liveLine){try{liveLine.applyOptions({price:p})}catch{}}else{try{liveLine=series.createPriceLine({price:p,color:'#2962ff',lineWidth:1,lineStyle:2,axisLabelVisible:true,title:'REAL'})}catch{}}}
function pendingKey(t){const id=Number(t?.id);return Number.isFinite(id)?`i:${id}`:`t:${Number(t?.time)}:${Number(t?.price)}`}
function queuePending(t){const k=pendingKey(t);if(!S.pendingLive.some(x=>pendingKey(x)===k))S.pendingLive.push({...t})}
function ingestLiveTick(t){const id=Number(t?.id),tm=Number(t?.time),p=Number(t?.price);if(!Number.isFinite(p)||!Number.isFinite(tm))return false;if(tm<S.lastHistoryTime)return false;if(S.building){queuePending(t);return false}if(Number.isFinite(id)&&Number.isFinite(S.lastLiveId)&&id<=S.lastLiveId)return false;if(!Number.isFinite(id)&&tm<=S.lastLiveTime)return false;S.lastLiveId=Number.isFinite(id)?id:S.lastLiveId;S.lastLiveTime=Math.max(S.lastLiveTime,tm);S.ticks.push({id:Number.isFinite(id)?id:null,price:p,qty:Number(t.qty)||0,time:tm,kind:'live'});const formed=processLive(S.tailState,{id,price:p,time:tm});S.processedLiveTrades++;for(const b of formed){S.bricks.push(b);const d=normalizeOne(b);S.data.push(d);series?.update(d)}updateLiveLine(p);if(formed.length){if(S.following)latestView();evaluateSignal();setStatus(`LIVE · ${formed.length} brick${formed.length>1?'s':''} locked on trade`,'ready')}queueMeta();return true}
function flushPendingLive(){if(S.building||!S.pendingLive.length)return;const q=S.pendingLive.splice(0).sort((a,b)=>(Number(a.time)-Number(b.time))||((Number(a.id)||0)-(Number(b.id)||0)));for(const t of q)ingestLiveTick(t)}
function drainFeed(){const v=window.RWARenkoV3?.state;if(!v)return;const sym=String(v.selected||'');if(sym&&sym!==lastSymbol){lastSymbol=sym;void resetSymbol(sym);return}const raw=Array.isArray(v.historyTicks)?v.historyTicks:[];if(raw.length){const unseen=[];for(let i=raw.length-1;i>=0;i--){const t=raw[i],id=Number(t?.id),tm=Number(t?.time);if(!Number.isFinite(tm))continue;if(Number.isFinite(S.feedSeenId)&&Number.isFinite(id)){if(id<=S.feedSeenId)break}else if(tm<=S.feedSeenTime)break;unseen.push(t)}unseen.reverse();for(const t of unseen){const id=Number(t?.id),tm=Number(t?.time);if(Number.isFinite(id))S.feedSeenId=id;S.feedSeenTime=Math.max(S.feedSeenTime,Number.isFinite(tm)?tm:0);ingestLiveTick(t)}}const p=Number(v.lastPrice);if(Number.isFinite(p)){updateLiveLine(p);if(S.signal)evaluateSignal()}}
async function loadOlder(targetBricks=120,maxPages=36){if(S.loading||S.exhausted||!Number.isFinite(S.oldestAggId)||S.oldestAggId<=0)return false;const generation=S.generation,symbol=S.symbol,anchor=rangeAnchor(),before=S.data.length;let cursor=Number(S.oldestAggId),pages=0,loaded=false;S.loading=true;S.following=false;setStatus('Loading deep tick history…','loading');try{while(generation===S.generation&&symbol===S.symbol&&!S.exhausted&&pages<maxPages&&S.data.length<before+Math.max(20,Number(targetBricks)||120)){const wave=Math.min(6,maxPages-pages),defs=[];for(let i=1;i<=wave;i++){const from=Math.max(0,Math.floor(cursor-PAGE*i));if(!defs.includes(from))defs.push(from)}const parts=await Promise.all(defs.map(from=>olderAgg(symbol,from).catch(()=>null)));if(generation!==S.generation||symbol!==S.symbol)return false;const rows=[];let contiguous=0;for(const part of parts){if(!Array.isArray(part)||!part.length)break;const valid=part.filter(x=>Number(x.id)<cursor);if(!valid.length)break;rows.push(...valid);contiguous++}if(!rows.length){if(parts[0]&&Array.isArray(parts[0])&&!parts[0].length)S.exhausted=true;break}const next=Math.min(...rows.map(x=>Number(x.id)).filter(Number.isFinite));if(!Number.isFinite(next)||next>=cursor)break;cursor=next;S.oldestAggId=next;S.ticks=dedupeTicks([...rows,...S.ticks]);pages+=Math.max(1,contiguous);loaded=true;await rebuild(anchor);if(defs.includes(0)||cursor<=0){S.exhausted=true;break}}return loaded}catch(e){console.warn('[V13 older]',e);setStatus('Trade history retry','bad');return false}finally{if(generation===S.generation){S.loading=false;flushPendingLive();meta()}}}
function scheduleOlder(){clearTimeout(rangeTimer);rangeTimer=setTimeout(()=>{const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(r&&r.from<36&&!S.loading&&!S.building&&!S.exhausted)void loadOlder(120,36)},90)}
async function resetSymbol(symbol){const generation=++S.generation;++S.buildSeq;S.symbol=symbol;S.tickSize=NaN;S.atrValue=NaN;S.box=NaN;S.ticks=[];S.bricks=[];S.data=[];S.tailState=null;S.loading=false;S.building=false;S.exhausted=false;S.oldestAggId=null;S.lastHistoryTime=0;S.lastLiveId=null;S.lastLiveTime=0;S.feedSeenId=null;S.feedSeenTime=0;S.pendingLive=[];S.signal=null;S.processedLiveTrades=0;S.droppedLiveTrades=0;series?.setData([]);if(liveLine){try{series.removePriceLine(liveLine)}catch{}liveLine=null}mode();setStatus('Connecting trade history…','loading');try{const [tick,atr,rows]=await Promise.all([fetchTickSize(symbol),fetchAtr(symbol),latestAgg(symbol)]);if(generation!==S.generation)return;S.tickSize=tick;S.atrValue=atr;if(rows.length){S.ticks=rows;S.oldestAggId=rows[0].id;S.lastHistoryTime=rows.at(-1).time;S.feedSeenTime=S.lastHistoryTime;await rebuild();let rounds=0;while(generation===S.generation&&S.data.length<FIRST_VIEW&&!S.exhausted&&rounds++<6){if(!await loadOlder(80,24))break}}else{const raw=window.RWARenkoV3?.state?.historyTicks||[];S.ticks=raw.map(x=>({...x,kind:'live'}));if(S.ticks.length){S.feedSeenId=Number(S.ticks.at(-1)?.id)||null;S.feedSeenTime=Number(S.ticks.at(-1)?.time)||0;await rebuild()}}if(generation!==S.generation)return;drainFeed();if(S.data.length){latestView();setStatus('LIVE · lossless trade drain','ready')}else setStatus('Waiting for threshold trade…','ready');meta()}catch(e){console.error('[V13 symbol]',e);setStatus(S.data.length?'LIVE · degraded history':'Feed retry','bad')}}
function deriveSignal(){const a=S.data;if(a.length<3)return{position:'flat',action:'WAIT',reason:'Need more confirmed tick bricks'};const confirm=C.confirmBricks;let position='flat',entry=NaN,entryBox=NaN,lastEvent='WAIT',eventIndex=-1;for(let i=1;i<a.length;i++){const d=Number(a[i]._dir),prev=Number(a[i-1]._dir);if(position==='long'&&d<0){position='flat';lastEvent='EXIT LONG · tick reversal';eventIndex=i;continue}if(position==='short'&&d>0){position='flat';lastEvent='EXIT SHORT · tick reversal';eventIndex=i;continue}if(position!=='flat')continue;if(confirm===1){if(prev<0&&d>0){position='long';entry=Number(a[i].close);entryBox=Number(a[i]._box)||S.box;lastEvent='BUY READY · tick reversal';eventIndex=i}else if(prev>0&&d<0){position='short';entry=Number(a[i].close);entryBox=Number(a[i]._box)||S.box;lastEvent='SELL READY · tick reversal';eventIndex=i}}else if(i>=2){const p2=Number(a[i-2]._dir);if(p2<0&&prev>0&&d>0){position='long';entry=Number(a[i].close);entryBox=Number(a[i]._box)||S.box;lastEvent='BUY READY · reversal + 1';eventIndex=i}else if(p2>0&&prev<0&&d<0){position='short';entry=Number(a[i].close);entryBox=Number(a[i]._box)||S.box;lastEvent='SELL READY · reversal + 1';eventIndex=i}}}const market=Number(window.RWARenkoV3?.state?.lastPrice),close=Number(a.at(-1)?.close),trailBox=Number(a.at(-1)?._box)||S.box;let hard=NaN,trail=NaN,action=lastEvent,reason='Signals use immediately confirmed tick bricks. No interval-close delay.';if(position==='long'){hard=entry-2*entryBox;trail=close-trailBox;if(Number.isFinite(market)&&market<=hard){action='EXIT NOW · real market hard stop';reason='Real price crossed hard stop.'}else if(eventIndex<a.length-1)action='LONG ACTIVE'}else if(position==='short'){hard=entry+2*entryBox;trail=close+trailBox;if(Number.isFinite(market)&&market>=hard){action='EXIT NOW · real market hard stop';reason='Real price crossed hard stop.'}else if(eventIndex<a.length-1)action='SHORT ACTIVE'}else if(!lastEvent.startsWith('EXIT'))action='WAIT';return{position,action,entry,hard,trail,reason}}
function evaluateSignal(){S.signal=deriveSignal();const x=S.signal,age=now()-Number(window.RWARenkoV3?.state?.lastTickTime||0),fresh=age<5000;setText('signalAction',x.action);setText('signalPosition',x.position.toUpperCase());setText('signalEntry',fmt(x.entry));setText('signalMarket',fmt(Number(window.RWARenkoV3?.state?.lastPrice)));setText('signalHardStop',fmt(x.hard));setText('signalTrail',fmt(x.trail));setText('signalReason',x.reason);setText('signalFreshness',fresh?`LIVE ${Math.max(0,age)} ms`:`STALE ${Math.floor(age/1000)} s`);const e=$('signalAction');if(e)e.dataset.kind=x.action.includes('EXIT')?'exit':x.action.includes('BUY')?'buy':x.action.includes('SELL')?'sell':x.position==='long'?'buy':x.position==='short'?'sell':'wait';const f=$('signalFreshness');if(f)f.dataset.kind=fresh?'live':'stale'}
function createChart(){const wrap=$('chartWrap'),L=window.LightweightCharts;if(!wrap||!L)return false;let host=$('lwcRenkoHost');if(!host){host=document.createElement('div');host.id='lwcRenkoHost';host.setAttribute('aria-label','RENKO V13 lossless tick-native chart');wrap.prepend(host)}chart=L.createChart(host,{localization:{locale:'en-US'},layout:{background:{type:L.ColorType?.Solid??'solid',color:'#131722'},textColor:'#b2b5be',attributionLogo:true},grid:{vertLines:{color:'rgba(120,123,134,.14)'},horzLines:{color:'rgba(120,123,134,.14)'}},rightPriceScale:{borderColor:'#2a2e39',minimumWidth:64,scaleMargins:{top:.04,bottom:.05}},timeScale:{borderColor:'#2a2e39',timeVisible:true,secondsVisible:true,rightOffset:8,barSpacing:10,minBarSpacing:2,maxBarSpacing:30,lockVisibleTimeRangeOnResize:true},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true,vertTouchDrag:true},handleScale:{mouseWheel:true,pinch:true,axisPressedMouseMove:{time:true,price:true},axisDoubleClickReset:{time:true,price:true}},kineticScroll:{mouse:true,touch:true},crosshair:{mode:L.CrosshairMode?.Normal??0}});series=chart.addSeries(L.CandlestickSeries,{upColor:'#089981',downColor:'#f23645',borderUpColor:'#089981',borderDownColor:'#f23645',wickUpColor:'#089981',wickDownColor:'#f23645',priceLineVisible:false,lastValueVisible:true});chart.timeScale().subscribeVisibleLogicalRangeChange?.(r=>{if(r&&S.data.length)S.following=r.to>=S.data.length-1;queueMeta();scheduleOlder()});resizeObserver=new ResizeObserver(entries=>{const r=entries[0]?.contentRect;if(r?.width&&r?.height)chart.resize(Math.floor(r.width),Math.floor(r.height))});resizeObserver.observe(wrap);wireNav();return true}
function shiftRange(frac){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r)return;const w=r.to-r.from,d=w*frac;chart.timeScale().setVisibleLogicalRange({from:r.from+d,to:r.to+d})}
function zoomRange(f){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r)return;const mid=(r.from+r.to)/2,w=clamp((r.to-r.from)*f,20,300);chart.timeScale().setVisibleLogicalRange({from:mid-w/2,to:mid+w/2})}
function wireNav(){const click=(id,fn)=>$(id)?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();fn()},{capture:true});click('tvPanOlder',()=>{shiftRange(-.72);setTimeout(scheduleOlder,0)});click('tvPanNewer',()=>shiftRange(.72));click('tvZoomOut',()=>zoomRange(1.25));click('tvZoomIn',()=>zoomRange(.8));click('tvReset',latestView);click('tvLive',latestView)}
function normalizePatch(p={}){if('atrLength'in p)C.atrLength=clamp(Math.floor(Number(p.atrLength)||C.atrLength),1,200);if('atrFactor'in p)C.atrFactor=clamp(Number(p.atrFactor)||C.atrFactor,.01,20);if('traditionalBox'in p)C.traditionalBox=Math.max(Number.EPSILON,Number(p.traditionalBox)||C.traditionalBox);if('percentage'in p)C.percentage=clamp(Number(p.percentage)||C.percentage,.000001,.1);if('wicks'in p)C.wicks=p.wicks!==false;if('confirmBricks'in p)C.confirmBricks=Number(p.confirmBricks)===1?1:2}
async function setMethod(method,patch={}){if(!METHODS.has(method))return false;++S.buildSeq;C.method=method;normalizePatch(patch);save();mode();if(!S.symbol){meta();return true}try{if(method==='atr')S.atrValue=await fetchAtr(S.symbol);const ok=await rebuild(rangeAnchor());if(ok){latestView();meta()}return!!ok}catch(e){console.error('[V13 apply]',e);return false}}
function diagnostics(){return{version:S.version,method:C.method,box:S.box,atrValue:S.atrValue,atrFactor:C.atrFactor,percentage:C.percentage,traditionalBox:C.traditionalBox,ticks:S.ticks.length,bricks:S.data.length,pendingLive:S.pendingLive.length,processedLiveTrades:S.processedLiveTrades,droppedLiveTrades:S.droppedLiveTrades,oldestAggId:S.oldestAggId,lastLiveId:S.lastLiveId,feedSeenId:S.feedSeenId,building:S.building,loading:S.loading}}
async function boot(){for(let i=0;i<240&&(!window.LightweightCharts||!window.RWARenkoV3);i++)await sleep(50);if(!window.LightweightCharts)throw Error('Lightweight Charts unavailable');if(!window.RWARenkoV3)throw Error('Renko trade feed unavailable');if(!createChart())throw Error('chart host unavailable');showChart();window.RWARenkoV13={version:'13.0.0',renderer:'tradingview-lightweight-charts-5.1',formation:'lossless-every-buffered-trade',lockRule:'1x-continuation-2x-reversal',percentageRule:'confirmed-renko-level-times-percent',atrRule:'wilder-atr-times-factor',liveDrain:'all-unseen-v3-trades-in-order',rebuildRule:'latest-build-wins-and-replay-pending-live',state:S,settings:C,setMethod,loadOlder,goLive:latestView,diagnostics};window.RWARenkoV12=window.RWARenkoV13;const initial=String(window.RWARenkoV3.state.selected||'BTCUSDT');lastSymbol=initial;await resetSymbol(initial);watchTimer=setInterval(drainFeed,25)}
boot().catch(e=>{console.error('[RENKO V13]',e);setStatus('Chart retry','bad')});
})();
