(()=>{
'use strict';
if(window.RWARenkoV4)return;
window.RWARenkoV4=true;

const PRIVATE_ORIGINS=['https://seablueprint.com','https://copytolive.com'];
const BINANCE_RESTS=['https://data-api.binance.vision','https://api.binance.com'];
const BINANCE_WSS=['wss://data-stream.binance.vision/ws','wss://stream.binance.com:9443/ws'];
const STORE='rwa_renko_private_adopt_v4';
const DEFAULT_SYMBOL='BTCUSDT';
const TOP_VISIBLE=500;
const PAGE=25000;
const DEFAULT_VISIBLE=180;
const MAX_VISIBLE=2400;
const STABLE_QUOTES=new Set(['USDT','USDC','FDUSD','TUSD','USDP','DAI','BUSD']);
const EXCLUDED_BASES=new Set(['USDT','USDC','FDUSD','TUSD','USDP','DAI','BUSD','EUR','GBP','TRY','BRL','AUD','RUB','UAH','NGN','ZAR','PLN','RON','ARS','CZK','MXN','JPY','IDR','AED']);
const LEVERAGED=/(UP|DOWN|BULL|BEAR)$/i;
const FALLBACK=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','AVAXUSDT','LINKUSDT','DOTUSDT','LTCUSDT','BCHUSDT','TRXUSDT','SUIUSDT','APTUSDT','NEARUSDT','ATOMUSDT','FILUSDT','UNIUSDT','AAVEUSDT','ETCUSDT','HBARUSDT','ICPUSDT','ARBUSDT','OPUSDT'];
const $=id=>document.getElementById(id);
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const state={
  markets:[], marketBySymbol:new Map(), selected:DEFAULT_SYMBOL,
  box:100, bricks:[], historyTicks:[], tickCount:0, lastPrice:NaN, lastTickTime:0,
  lastTradeId:null,lastClose:NaN,direction:0,anchor:NaN,
  visible:DEFAULT_VISIBLE,viewStart:0,historyMode:'all',follow:true,
  sourceMode:'loading',privateOrigin:'',privateMeta:null,privateSupported:null,
  ws:null,wsToken:0,wsEndpoint:0,retryTimer:0,eventSource:null,pollTimer:0,
  renderPending:false,drag:null,savedBoxes:{},sourceErrors:[],loadToken:0,
};

function loadPrefs(){try{const p=JSON.parse(localStorage.getItem(STORE)||'{}');if(typeof p.selected==='string')state.selected=p.selected;if(Number.isFinite(+p.visible))state.visible=clamp(+p.visible,20,MAX_VISIBLE);if(p.boxes&&typeof p.boxes==='object')state.savedBoxes=p.boxes}catch{}}
function savePrefs(){try{localStorage.setItem(STORE,JSON.stringify({selected:state.selected,visible:state.visible,boxes:state.savedBoxes}))}catch{}}
function market(sym=state.selected){return state.marketBySymbol.get(sym)||{symbol:sym,base:String(sym).replace(/(USDT|USDC|FDUSD|BTC|ETH|BNB)$/,''),quote:String(sym).match(/(USDT|USDC|FDUSD|BTC|ETH|BNB)$/)?.[1]||'USDT'}}
function fmt(v){const n=Number(v);if(!Number.isFinite(n))return'—';const a=Math.abs(n),d=a>=1000?2:a>=100?3:a>=1?4:a>=.01?6:8;return n.toLocaleString(undefined,{maximumFractionDigits:d})}
function fmtInput(v){const n=Number(v);if(!Number.isFinite(n))return'';const a=Math.abs(n),d=a>=100?2:a>=1?4:a>=.01?6:8;return n.toFixed(d).replace(/0+$/,'').replace(/\.$/,'')}
function fmtCompact(v){const n=Number(v);if(!Number.isFinite(n))return'—';if(n>=1e9)return`${(n/1e9).toFixed(1)}B`;if(n>=1e6)return`${(n/1e6).toFixed(1)}M`;if(n>=1e3)return`${(n/1e3).toFixed(1)}K`;return fmt(n)}
function fmtDate(secOrMs){const n=Number(secOrMs);if(!Number.isFinite(n)||n<=0)return'—';const ms=n<1e12?n*1000:n;return new Date(ms).toLocaleString(undefined,{year:'numeric',month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})}
function niceNumber(x){if(!(x>0))return 1;const e=Math.floor(Math.log10(x)),f=x/10**e,m=f<=1?1:f<=2?2:f<=2.5?2.5:f<=5?5:10;return m*10**e}
function setText(id,text){const e=$(id);if(e)e.textContent=text}
function setFeed(kind,text){const e=$('feedPill');if(!e)return;e.className='feed-pill'+(kind?` ${kind}`:'');const b=e.querySelector('b');if(b)b.textContent=text}
function setMode(text){const e=$('modePill')||document.querySelector('.mode-pill');if(e)e.textContent=text}
function setMarketMode(text){const e=$('marketModeLabel');if(e)e.textContent=text}
function hideEmpty(){const e=$('chartEmpty');if(e)e.classList.add('hide')}
function showEmpty(title,sub){const e=$('chartEmpty');if(!e)return;e.classList.remove('hide');const b=e.querySelector('b'),s=e.querySelector('small');if(b)b.textContent=title||'Loading…';if(s)s.textContent=sub||''}
function flashPrice(){const e=$('lastPrice');if(!e)return;e.classList.remove('flash');void e.offsetWidth;e.classList.add('flash')}

async function fetchBinance(path,ms=12000){let last;for(const root of BINANCE_RESTS){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(root+path,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);const json=await r.json();clearTimeout(t);return{json,root}}catch(e){clearTimeout(t);last=e;state.sourceErrors.push(`${root}: ${e.message}`)}}throw last||Error('Binance market data unavailable')}
function quoteUsdMap(tickers){const m=new Map([['USDT',1],['USDC',1],['FDUSD',1],['TUSD',1],['USDP',1],['DAI',1],['BUSD',1]]),by=new Map(tickers.map(x=>[x.symbol,x]));for(const q of ['BTC','ETH','BNB','SOL','XRP','DOGE']){const n=Number(by.get(`${q}USDT`)?.lastPrice);if(n>0)m.set(q,n)}return{by,m}}
function eligibleSymbol(x,qUsd){return x&&x.status==='TRADING'&&x.isSpotTradingAllowed!==false&&!EXCLUDED_BASES.has(x.baseAsset)&&!LEVERAGED.test(x.baseAsset)&&(STABLE_QUOTES.has(x.quoteAsset)||qUsd.has(x.quoteAsset))}
async function loadUniverse(){setText('pairTotal','Loading…');try{const [ir,tr]=await Promise.all([fetchBinance('/api/v3/exchangeInfo'),fetchBinance('/api/v3/ticker/24hr')]);const tickers=Array.isArray(tr.json)?tr.json:[],{by,m:qUsd}=quoteUsdMap(tickers),rows=[];for(const x of ir.json.symbols||[]){if(!eligibleSymbol(x,qUsd))continue;const t=by.get(x.symbol)||{},last=Number(t.lastPrice),change=Number(t.priceChangePercent),qv=Number(t.quoteVolume),mult=STABLE_QUOTES.has(x.quoteAsset)?1:(qUsd.get(x.quoteAsset)||0),volumeUsd=Number.isFinite(qv)&&mult>0?qv*mult:0;rows.push({symbol:x.symbol,base:x.baseAsset,quote:x.quoteAsset,last:Number.isFinite(last)?last:NaN,change:Number.isFinite(change)?change:0,volumeUsd,rank:0})}rows.sort((a,b)=>b.volumeUsd-a.volumeUsd||a.symbol.localeCompare(b.symbol));rows.forEach((x,i)=>x.rank=i+1);state.markets=rows;state.marketBySymbol=new Map(rows.map(x=>[x.symbol,x]));if(!state.marketBySymbol.has(state.selected))state.selected=state.marketBySymbol.has(DEFAULT_SYMBOL)?DEFAULT_SYMBOL:(rows[0]?.symbol||DEFAULT_SYMBOL);setText('pairTotal',`${rows.length.toLocaleString()} markets`);setText('universeNote',rows.length>=500?`Top ${TOP_VISIBLE} by 24h liquidity · all ${rows.length.toLocaleString()} searchable`:`${rows.length.toLocaleString()} eligible crypto markets`);renderPairs();renderQuickPairs()}catch(e){console.warn('[Renko] universe fallback',e);state.markets=FALLBACK.map((symbol,i)=>({symbol,base:symbol.replace(/USDT$/,''),quote:'USDT',last:NaN,change:0,volumeUsd:0,rank:i+1}));state.marketBySymbol=new Map(state.markets.map(x=>[x.symbol,x]));setText('pairTotal',`${state.markets.length} fallback`);setText('universeNote','Universe degraded · retrying');renderPairs();renderQuickPairs();setTimeout(loadUniverse,10000)}}
function renderPairs(){const q=String($('pairSearch')?.value||'').trim().toUpperCase(),pool=q?state.markets.filter(x=>x.symbol.includes(q)||x.base.includes(q)||x.quote.includes(q)):state.markets,a=pool.slice(0,TOP_VISIBLE),host=$('pairList');if(!host)return;const f=document.createDocumentFragment();for(const x of a){const b=document.createElement('button');b.type='button';b.className='pair-row'+(x.symbol===state.selected?' active':'');b.dataset.symbol=x.symbol;b.innerHTML=`<span class="rank">#${x.rank}</span><span class="left-meta"><span class="mini-icon">${x.base.slice(0,2)}</span><span><b>${x.base} / ${x.quote}</b><small>${fmtCompact(x.volumeUsd)} 24h</small></span></span><span class="pair-live"><b>${fmt(x.last)}</b><small class="${x.change>=0?'up':'down'}">${x.change>=0?'+':''}${x.change.toFixed(2)}%</small></span>`;b.onclick=()=>selectSymbol(x.symbol);f.appendChild(b)}host.replaceChildren(f);if(!a.length)host.innerHTML='<div class="empty">No crypto market matches.</div>';setText('pairShown',q?`${a.length} results`:`Top ${a.length} shown`)}
function renderQuickPairs(){const h=$('quickPairs');if(!h)return;h.querySelectorAll('[data-quick]').forEach(b=>{const hit=state.markets.find(x=>x.base===b.dataset.quick);b.disabled=!hit;b.dataset.symbol=hit?.symbol||'';b.classList.toggle('active',hit?.symbol===state.selected)})}

function clearConnections(){state.wsToken++;clearTimeout(state.retryTimer);state.retryTimer=0;if(state.ws){try{state.ws.onclose=null;state.ws.close()}catch{}state.ws=null}if(state.eventSource){try{state.eventSource.close()}catch{}state.eventSource=null}clearInterval(state.pollTimer);state.pollTimer=0}
function resetEngine(){state.bricks=[];state.historyTicks=[];state.tickCount=0;state.lastPrice=NaN;state.lastTickTime=0;state.lastTradeId=null;state.lastClose=NaN;state.direction=0;state.anchor=NaN;state.viewStart=0;state.privateMeta=null;state.privateOrigin='';state.privateSupported=null}
function addBrick(open,close,direction,time,source='live'){const t=Number(time)||Date.now();state.bricks.push({i:state.bricks.length+1,open:Number(open),close:Number(close),high:Math.max(open,close),low:Math.min(open,close),direction,time:t<1e12?t*1000:t,source});state.lastClose=Number(close);state.direction=direction}
function seedEngineFromBricks(){const z=state.bricks.at(-1);if(!z)return;state.lastClose=Number(z.close);state.direction=Number(z.direction)||0;state.anchor=state.lastClose}
function applyTraditionalPrice(price,time,source='live'){const p=Number(price);if(!Number.isFinite(p)||!(state.box>0))return false;state.lastPrice=p;state.lastTickTime=Number(time)||Date.now();if(!Number.isFinite(state.lastClose)){state.lastClose=Math.round(p/state.box)*state.box;state.anchor=state.lastClose}let changed=false,guard=0;while(guard++<10000){if(state.direction===0){if(p>=state.lastClose+state.box){addBrick(state.lastClose,state.lastClose+state.box,1,time,source);changed=true;continue}if(p<=state.lastClose-state.box){addBrick(state.lastClose,state.lastClose-state.box,-1,time,source);changed=true;continue}break}if(state.direction===1){if(p>=state.lastClose+state.box){addBrick(state.lastClose,state.lastClose+state.box,1,time,source);changed=true;continue}if(p<=state.lastClose-2*state.box){addBrick(state.lastClose-state.box,state.lastClose-2*state.box,-1,time,source);changed=true;continue}break}if(p<=state.lastClose-state.box){addBrick(state.lastClose,state.lastClose-state.box,-1,time,source);changed=true;continue}if(p>=state.lastClose+2*state.box){addBrick(state.lastClose+state.box,state.lastClose+2*state.box,1,time,source);changed=true;continue}break}state.tickCount++;flashPrice();if(changed&&state.follow&&state.historyMode==='window')state.viewStart=Math.max(0,state.bricks.length-state.visible);updateStats();scheduleDraw();return changed}

function privateUrl(origin,base,{limit=PAGE,offset=0,brickSize=null}={}){const q=new URLSearchParams({limit:String(limit),offset:String(offset),live:'1',history:'all'});if(Number(brickSize)>0)q.set('brickSize',String(brickSize));return`${origin}/api/charting/hyperliquid/renko/${encodeURIComponent(base)}?${q}`}
async function privateFetchJson(url,ms=60000){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(url,{cache:'no-store',credentials:'omit',mode:'cors',signal:c.signal,headers:{Accept:'application/json'}});if(!r.ok){const text=await r.text().catch(()=> '');const err=Error(`HTTP ${r.status}${text?` · ${text.slice(0,120)}`:''}`);err.status=r.status;throw err}return await r.json()}finally{clearTimeout(t)}}
async function fetchPrivatePage(base,opts={}){let last;for(const origin of PRIVATE_ORIGINS){try{const data=await privateFetchJson(privateUrl(origin,base,opts));if(!Array.isArray(data?.candles))throw Error('Invalid Renko history contract');return{data,origin}}catch(e){last=e;if(e.status===404)continue;state.sourceErrors.push(`${origin}: ${e.message}`)}}throw last||Error('Private Renko history unavailable')}
async function loadPrivateHistory(base,customBox=null,token=state.loadToken){setFeed('','FULL HISTORY');setMode('PRIVATE FULL HISTORY · TRADITIONAL');setText('historyState','Loading private Renko history…');showEmpty('Loading full Renko history…','Reading all available history pages from the private Renko engine.');const firstRes=await fetchPrivatePage(base,{limit:PAGE,offset:0,brickSize:customBox});if(token!==state.loadToken)return false;const first=firstRes.data;const resolvedBox=Number(first.brickSize);if(!(resolvedBox>0)||!first.candles.length)throw Error('Private history returned no usable bricks');const total=Number(first.count)||first.candles.length;const parts=[first.candles];let offset=first.candles.length;let hasMore=!!first.hasMore;while(hasMore&&offset<total&&token===state.loadToken){setText('historyState',`Loading full history ${Math.min(offset,total).toLocaleString()} / ${total.toLocaleString()} bricks…`);const next=(await fetchPrivatePage(base,{limit:PAGE,offset,brickSize:resolvedBox})).data;if(!next.candles?.length)break;parts.unshift(next.candles);offset+=next.candles.length;hasMore=!!next.hasMore;if(parts.length>20)break}if(token!==state.loadToken)return false;const all=parts.flat();const dedup=[],seen=new Set();for(const b of all){const open=Number(b.open),close=Number(b.close),time=Number(b.time),dir=Number(b.direction)||Math.sign(close-open);if(!Number.isFinite(open)||!Number.isFinite(close)||!Number.isFinite(time))continue;const k=`${time}|${open}|${close}`;if(seen.has(k))continue;seen.add(k);dedup.push({open,close,high:Number.isFinite(+b.high)?+b.high:Math.max(open,close),low:Number.isFinite(+b.low)?+b.low:Math.min(open,close),direction:dir,time:time<1e12?time*1000:time,source:'private-history'})}dedup.sort((a,b)=>a.time-b.time);state.bricks=dedup.map((b,i)=>({...b,i:i+1}));state.box=resolvedBox;state.privateMeta={...first,count:total};state.privateOrigin=firstRes.origin;state.privateSupported=true;state.sourceMode='private';state.tickCount=Number(first.recordedTickCount)||0;state.lastPrice=Number(state.bricks.at(-1)?.close);state.lastTickTime=(Number(first.historyEnd)||0)*1000;seedEngineFromBricks();state.historyMode='all';state.viewStart=0;state.savedBoxes[state.selected]=resolvedBox;savePrefs();setMarketMode(first.market==='spot'?'HL SPOT':'HL PERP');setText('sourceText',`${new URL(firstRes.origin).hostname} · ${first.construction||'Traditional 2-brick reversal'}`);setText('historyState',`${state.bricks.length.toLocaleString()} / ${total.toLocaleString()} bricks loaded · full private window`);setText('historyIntegrity',`${first.dataQuality||'REAL_MARKET_OBSERVATIONS'} · ${first.source||'private Renko source'} · ${first.hasMore?'paged history combined':'complete window'}`);hideEmpty();updateStats();scheduleDraw();connectPrivateLive(base,firstRes.origin);return true}

function connectPrivateLive(base,origin){clearConnections();setFeed('live','HL LIVE');try{const es=new EventSource(`${origin}/api/charting/hyperliquid/stream/${encodeURIComponent(base)}`);state.eventSource=es;es.onopen=()=>setFeed('live','HL LIVE');es.onmessage=e=>{let d;try{d=JSON.parse(e.data)}catch{return}const px=Number(d.price),t=Number(d.updatedAt)||Date.now();if(px>0){applyTraditionalPrice(px,t,'hl-trade');setFeed('live','HL LIVE')}};es.onerror=()=>{try{es.close()}catch{}state.eventSource=null;startPrivatePolling(base,origin)}}catch{startPrivatePolling(base,origin)}}
function startPrivatePolling(base,origin){if(state.pollTimer)return;setFeed('','HL POLL');const poll=async()=>{try{const d=await privateFetchJson(`${origin}/api/charting/hyperliquid/mids`,12000);const px=Number(d.prices?.[base]??d.mids?.[base]);const t=Number(d.priceUpdatedByCoin?.[base]??d.updatedByCoin?.[base]??d.updatedAt)||Date.now();if(px>0){applyTraditionalPrice(px,t,'hl-live');setFeed('live','HL LIVE')}}catch(e){setFeed('bad','HL RETRY')}};poll();state.pollTimer=setInterval(poll,1500)}

function rememberRawTick(t){state.historyTicks.push(t);if(state.historyTicks.length>250000)state.historyTicks.splice(0,state.historyTicks.length-250000)}
function applyRawTick(t){const id=Number(t.id);if(Number.isFinite(id)&&state.lastTradeId!=null&&id<=state.lastTradeId)return false;if(Number.isFinite(id))state.lastTradeId=id;rememberRawTick(t);return applyTraditionalPrice(t.price,t.time,'binance-trade')}
async function loadRawFallback(symbol,token=state.loadToken){state.privateSupported=false;state.sourceMode='raw';setMode('RAW TICK · TRADITIONAL');setMarketMode('SPOT');setFeed('','RAW WARMUP');setText('historyState','Private full history unavailable · loading recent raw trades…');showEmpty('Loading raw ticks…','Private full history is unavailable for this market; live chart remains raw-trade only.');let ticks=[];try{const r=await fetchBinance(`/api/v3/trades?symbol=${encodeURIComponent(symbol)}&limit=1000`);ticks=(Array.isArray(r.json)?r.json:[]).map(x=>({id:Number(x.id),price:Number(x.price),qty:Number(x.qty),time:Number(x.time)})).filter(x=>Number.isFinite(x.price)&&Number.isFinite(x.time)).sort((a,b)=>a.id-b.id)}catch(e){console.warn('[Renko] raw warmup',e)}if(token!==state.loadToken)return;state.bricks=[];state.historyTicks=[];state.lastClose=NaN;state.direction=0;state.anchor=NaN;state.tickCount=0;state.lastTradeId=null;const saved=Number(state.savedBoxes[state.selected]);state.box=saved>0?saved:(ticks.length?niceNumber(Number(ticks.at(-1).price)*.001):1);for(const t of ticks)applyRawTick(t);state.historyMode='all';state.viewStart=0;setText('sourceText',`Binance raw individual trades · ${symbol.toLowerCase()}@trade`);setText('historyIntegrity','RAW TICK ONLY · Traditional 2-brick reversal · fallback session history (private full-history pair unavailable)');setText('historyState',`${ticks.length.toLocaleString()} raw trades warmup · live ticks continue`);hideEmpty();updateStats();scheduleDraw();connectBinanceLive(symbol)}
function connectBinanceLive(symbol){clearConnections();const token=++state.wsToken,idx=state.wsEndpoint%BINANCE_WSS.length,url=`${BINANCE_WSS[idx]}/${symbol.toLowerCase()}@trade`;setFeed('','CONNECTING');let ws;try{ws=new WebSocket(url)}catch{scheduleBinanceReconnect(symbol,token,true);return}state.ws=ws;ws.onopen=()=>{if(token!==state.wsToken)return;setFeed('live','RAW TICKS')};ws.onmessage=e=>{if(token!==state.wsToken)return;let x;try{x=JSON.parse(e.data)}catch{return}if(x.e!=='trade'||x.s!==symbol)return;applyRawTick({id:Number(x.t),price:Number(x.p),qty:Number(x.q),time:Number(x.T)});setFeed('live','RAW TICKS')};ws.onerror=()=>setFeed('bad','FEED RETRY');ws.onclose=()=>{if(token===state.wsToken)scheduleBinanceReconnect(symbol,token,true)}}
function scheduleBinanceReconnect(symbol,token,rotate){if(token!==state.wsToken)return;if(rotate)state.wsEndpoint=(state.wsEndpoint+1)%BINANCE_WSS.length;clearTimeout(state.retryTimer);state.retryTimer=setTimeout(()=>{if(token===state.wsToken)connectBinanceLive(symbol)},1600)}

async function loadSelected(customBox=null){const token=++state.loadToken;clearConnections();resetEngine();const m=market(),base=m.base;setText('pairName',`${m.base} / ${m.quote}`);setText('pairIcon',m.base.slice(0,2));setText('lastPrice','—');setText('brickCount','0');setText('tickCount','0');setText('historyCoverage','LOADING');setText('historyCount','0 bricks');try{await loadPrivateHistory(base,customBox,token)}catch(e){if(token!==state.loadToken)return;console.warn('[Renko] private history unavailable for',base,e);await loadRawFallback(state.selected,token)}renderPairs();renderQuickPairs()}
function selectSymbol(symbol){if(!symbol||symbol===state.selected)return;state.selected=symbol;savePrefs();loadSelected();document.body.classList.remove('pairs-open')}

function updateStats(){const n=state.bricks.length;setText('lastPrice',fmt(state.lastPrice));setText('brickValue',fmt(state.box));setText('brickCount',n.toLocaleString());setText('tickCount',state.tickCount.toLocaleString());if($('brickSize'))$('brickSize').value=fmtInput(state.box);const last=Number.isFinite(state.lastClose)?state.lastClose:state.lastPrice;if(Number.isFinite(last)&&state.box>0){setText('nextUp',fmt(state.direction===-1?last+2*state.box:last+state.box));setText('nextDown',fmt(state.direction===1?last-2*state.box:last-state.box))}else{setText('nextUp','—');setText('nextDown','—')}const first=state.bricks[0],z=state.bricks.at(-1);setText('historyCount',`${n.toLocaleString()} bricks`);setText('historyFrom',fmtDate(first?.time||state.privateMeta?.historyStart));setText('historyTo',fmtDate(z?.time||state.privateMeta?.historyEnd));setText('historyCoverage',state.historyMode==='all'?'ALL · genesis → live':`WINDOW ${state.viewStart+1}–${Math.min(n,state.viewStart+state.visible)}`);const range=$('historyRange');if(range){const max=Math.max(0,n-state.visible);range.max=String(max);range.value=String(clamp(state.viewStart,0,max));range.disabled=n<=state.visible}setText('visibleValue',state.historyMode==='all'?'ALL':String(state.visible));updateHealth()}
function updateHealth(){const e=$('tickHealth'),age=$('tickAge');if(!e||!age)return;const ms=Date.now()-Number(state.lastTickTime||0);let cls='wait',txt='WAITING';if(state.lastTickTime){if(ms<5000){cls='live';txt='MOVING'}else if(ms<20000){cls='wait';txt='WAITING'}else{cls='bad';txt='STALE'}}e.className=`tick-health ${cls}`;e.textContent=txt;age.textContent=state.lastTickTime?(ms<1000?'now':`${Math.round(ms/1000)}s`):'waiting'}

function getView(){const n=state.bricks.length;if(!n)return{rows:[],start:0,end:0,all:false};if(state.historyMode==='all')return{rows:state.bricks,start:0,end:n,all:true};const max=Math.max(0,n-state.visible);state.viewStart=clamp(state.viewStart,0,max);return{rows:state.bricks.slice(state.viewStart,state.viewStart+state.visible),start:state.viewStart,end:Math.min(n,state.viewStart+state.visible),all:false}}
function scheduleDraw(){if(state.renderPending)return;state.renderPending=true;requestAnimationFrame(()=>{state.renderPending=false;draw()})}
function draw(){const canvas=$('renkoCanvas'),wrap=$('chartWrap');if(!canvas||!wrap)return;const dpr=Math.min(2,window.devicePixelRatio||1),w=Math.max(320,wrap.clientWidth),h=Math.max(280,wrap.clientHeight);if(canvas.width!==Math.round(w*dpr)||canvas.height!==Math.round(h*dpr)){canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);canvas.style.width=`${w}px`;canvas.style.height=`${h}px`}const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.clearRect(0,0,w,h);const view=getView(),rows=view.rows;if(!rows.length){showEmpty('Waiting for Renko bricks…','Live price is connected; the first brick appears after a full box move.');return}hideEmpty();const pad={l:66,r:16,t:16,b:30};let lo=Infinity,hi=-Infinity;for(const b of rows){lo=Math.min(lo,Number(b.low),Number(b.open),Number(b.close));hi=Math.max(hi,Number(b.high),Number(b.open),Number(b.close))}if(!(hi>lo)){hi+=state.box;lo-=state.box}const margin=(hi-lo)*.06||state.box;hi+=margin;lo-=margin;const y=v=>pad.t+(hi-v)/(hi-lo)*(h-pad.t-pad.b);c.strokeStyle='rgba(148,163,184,.12)';c.fillStyle='rgba(148,163,184,.7)';c.font='10px ui-monospace,SFMono-Regular,Menlo,monospace';c.textAlign='right';for(let i=0;i<=5;i++){const yy=pad.t+i*(h-pad.t-pad.b)/5,v=hi-(i/5)*(hi-lo);c.beginPath();c.moveTo(pad.l,yy);c.lineTo(w-pad.r,yy);c.stroke();c.fillText(fmt(v),pad.l-6,yy+3)}const plotW=w-pad.l-pad.r;if(view.all&&rows.length>Math.max(1800,Math.floor(plotW*1.5))){const bins=Math.max(80,Math.floor(plotW)),per=rows.length/bins;c.lineWidth=1;for(let bi=0;bi<bins;bi++){const a=Math.floor(bi*per),b=Math.min(rows.length,Math.max(a+1,Math.floor((bi+1)*per)));let bLo=Infinity,bHi=-Infinity,net=0;for(let j=a;j<b;j++){bLo=Math.min(bLo,rows[j].low);bHi=Math.max(bHi,rows[j].high);net+=rows[j].direction}const x=pad.l+(bi+.5)/bins*plotW;c.strokeStyle=net>=0?'rgba(20,184,166,.78)':'rgba(244,63,94,.78)';c.beginPath();c.moveTo(x,y(bHi));c.lineTo(x,y(bLo));c.stroke()}c.fillStyle='rgba(255,255,255,.55)';c.textAlign='left';c.fillText(`ALL HISTORY compressed overview · ${rows.length.toLocaleString()} bricks`,pad.l+8,pad.t+12)}else{const bw=plotW/rows.length,body=Math.max(1,Math.min(16,bw*.78));for(let i=0;i<rows.length;i++){const b=rows[i],x=pad.l+(i+.5)*bw,yo=y(b.open),yc=y(b.close),top=Math.min(yo,yc),height=Math.max(1,Math.abs(yc-yo));c.fillStyle=b.direction>=0?'rgba(20,184,166,.88)':'rgba(244,63,94,.88)';c.fillRect(x-body/2,top,body,height);if(body>2){c.strokeStyle=b.direction>=0?'rgba(94,234,212,.95)':'rgba(251,113,133,.95)';c.strokeRect(x-body/2,top,body,height)}}}if(Number.isFinite(state.lastPrice)&&state.lastPrice>=lo&&state.lastPrice<=hi){const yy=y(state.lastPrice);c.setLineDash([5,4]);c.strokeStyle='rgba(250,204,21,.8)';c.beginPath();c.moveTo(pad.l,yy);c.lineTo(w-pad.r,yy);c.stroke();c.setLineDash([]);c.fillStyle='rgba(250,204,21,.9)';c.textAlign='left';c.fillText(fmt(state.lastPrice),w-pad.r-58,yy-4)}updateStats()}

function bind(){
  $('pairSearch')?.addEventListener('input',renderPairs);
  $('openPairs')?.addEventListener('click',()=>document.body.classList.toggle('pairs-open'));
  $('quickPairs')?.addEventListener('click',e=>{const b=e.target.closest('[data-quick]');if(b?.dataset.symbol)selectSymbol(b.dataset.symbol)});
  $('applyBrick')?.addEventListener('click',()=>{const n=Number($('brickSize')?.value);if(!(n>0))return;if(state.sourceMode==='private')loadSelected(n);else{state.box=n;state.savedBoxes[state.selected]=n;savePrefs();const ticks=state.historyTicks.slice();state.bricks=[];state.lastClose=NaN;state.direction=0;state.anchor=NaN;state.tickCount=0;state.lastTradeId=null;for(const t of ticks)applyRawTick(t);state.historyMode='all';scheduleDraw()}});
  $('brickSize')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('applyBrick')?.click()});
  $('autoBox')?.addEventListener('click',()=>{if(state.sourceMode==='private')loadSelected(null);else if(Number.isFinite(state.lastPrice)){$('brickSize').value=fmtInput(niceNumber(state.lastPrice*.001));$('applyBrick').click()}});
  document.querySelectorAll('[data-box-pct]').forEach(b=>b.addEventListener('click',()=>{if(!Number.isFinite(state.lastPrice))return;const n=niceNumber(state.lastPrice*Number(b.dataset.boxPct));$('brickSize').value=fmtInput(n);$('applyBrick').click()}));
  $('zoomIn')?.addEventListener('click',()=>{state.historyMode='window';state.visible=clamp(Math.round(state.visible*.75),20,MAX_VISIBLE);state.viewStart=clamp(state.viewStart,0,Math.max(0,state.bricks.length-state.visible));savePrefs();scheduleDraw()});
  $('zoomOut')?.addEventListener('click',()=>{state.historyMode='window';state.visible=clamp(Math.round(state.visible*1.35),20,MAX_VISIBLE);state.viewStart=clamp(state.viewStart,0,Math.max(0,state.bricks.length-state.visible));savePrefs();scheduleDraw()});
  $('historyAll')?.addEventListener('click',()=>{state.historyMode='all';document.querySelectorAll('.history-actions button').forEach(x=>x.classList.remove('active'));$('historyAll').classList.add('active');scheduleDraw()});
  $('historyStart')?.addEventListener('click',()=>{state.historyMode='window';state.viewStart=0;document.querySelectorAll('.history-actions button').forEach(x=>x.classList.remove('active'));$('historyStart').classList.add('active');scheduleDraw()});
  $('historyLive')?.addEventListener('click',()=>{state.historyMode='window';state.viewStart=Math.max(0,state.bricks.length-state.visible);document.querySelectorAll('.history-actions button').forEach(x=>x.classList.remove('active'));$('historyLive').classList.add('active');scheduleDraw()});
  $('historyPrev')?.addEventListener('click',()=>{state.historyMode='window';state.viewStart=Math.max(0,state.viewStart-state.visible);scheduleDraw()});
  $('historyNext')?.addEventListener('click',()=>{state.historyMode='window';state.viewStart=Math.min(Math.max(0,state.bricks.length-state.visible),state.viewStart+state.visible);scheduleDraw()});
  $('historyRange')?.addEventListener('input',e=>{state.historyMode='window';state.viewStart=Number(e.target.value)||0;scheduleDraw()});
  $('followLive')?.addEventListener('change',e=>{state.follow=!!e.target.checked;if(state.follow&&state.historyMode==='window'){state.viewStart=Math.max(0,state.bricks.length-state.visible);scheduleDraw()}});
  $('resetChart')?.addEventListener('click',()=>loadSelected(state.sourceMode==='private'?state.box:null));
  window.addEventListener('resize',scheduleDraw,{passive:true});
  const canvas=$('renkoCanvas');
  canvas?.addEventListener('pointermove',e=>{const view=getView();if(!view.rows.length||view.all)return;const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,padL=66,padR=16,idx=clamp(Math.floor((x-padL)/Math.max(1,r.width-padL-padR)*view.rows.length),0,view.rows.length-1),b=view.rows[idx],tip=$('tooltip');if(!tip)return;tip.hidden=false;tip.innerHTML=`<b>#${view.start+idx+1}</b><br>${b.direction>=0?'UP':'DOWN'} · ${fmt(b.open)} → ${fmt(b.close)}<br>${fmtDate(b.time)}`;tip.style.left=`${clamp(e.clientX-r.left+12,8,r.width-180)}px`;tip.style.top=`${clamp(e.clientY-r.top+12,8,r.height-80)}px`});
  canvas?.addEventListener('pointerleave',()=>{const t=$('tooltip');if(t)t.hidden=true});
}

async function boot(){loadPrefs();bind();setInterval(updateHealth,1000);await loadUniverse();await loadSelected()}
boot().catch(e=>{console.error('[RWA Renko V4]',e);setFeed('bad','ERROR');showEmpty('Renko failed to start',e.message||String(e))});
})();
