(()=>{
'use strict';
if(window.RWARenkoV5)return;
const $=id=>document.getElementById(id);
const BASES=[
  'https://data.binance.vision.s3.ap-northeast-1.amazonaws.com',
  'https://s3-ap-northeast-1.amazonaws.com/data.binance.vision',
  'https://seablueprint.com/rwa-binance-data',
  'https://copytolive.com/rwa-binance-data'
];
const own={worker:null,run:0,symbol:'',box:0,running:false,result:null,lastSelected:'',cacheStatus:'idle',lastChunk:null};
function fmtN(n){return Number(n||0).toLocaleString()}
function fmtBytes(n){n=Number(n||0);if(n>=1073741824)return `${(n/1073741824).toFixed(2)} GB`;if(n>=1048576)return `${(n/1048576).toFixed(1)} MB`;if(n>=1024)return `${(n/1024).toFixed(1)} KB`;return `${n} B`}
function fmtDate(ms){if(!Number(ms))return'—';return new Date(Number(ms)).toLocaleString(undefined,{year:'numeric',month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit',hour12:false})}
function emit(name,detail={}){try{window.dispatchEvent(new CustomEvent(`rwa-renko-${name}`,{detail}))}catch{}}
function status(kind,title,detail=''){const e=$('archiveStatus');if(e){e.className=`archive-status ${kind||''}`;e.textContent=title}if($('archiveDetail'))$('archiveDetail').textContent=detail}
function progress(done,total){const p=total>0?Math.max(0,Math.min(100,done/total*100)):0;if($('archiveProgressFill'))$('archiveProgressFill').style.width=`${p}%`;if($('archiveProgressText'))$('archiveProgressText').textContent=total?`${done}/${total} archives · ${p.toFixed(1)}%`:'Discovering archive coverage…'}
function setButtons(){const start=$('archiveLoad'),cancel=$('archiveCancel');if(start){start.disabled=own.running;start.textContent=own.running?'BACKFILL RUNNING':'RELOAD TOTAL TICK HISTORY'}if(cancel)cancel.disabled=!own.running}
function resetUi(){progress(0,0);status('loading','AUTO LOADING TOTAL RAW TICK HISTORY','Selected market will load Binance Vision individual-trade archives and join them to live @trade ticks.');if($('archiveCoverage'))$('archiveCoverage').textContent='Archive coverage: discovering…';setButtons()}
function cancel(){const symbol=own.symbol,box=own.box;own.run++;if(own.worker){try{own.worker.postMessage({type:'cancel'});own.worker.terminate()}catch{}own.worker=null}own.running=false;emit('archive-cancel',{symbol,box});status('partial','BACKFILL CANCELLED','Loaded raw history remains visible; live raw ticks continue.');setButtons()}
function sameBox(a,b){return Number.isFinite(+a)&&Number.isFinite(+b)&&Math.abs(+a-+b)<=Math.max(1e-12,Math.abs(+a)*1e-10)}
function integrate(r){const v3=window.RWARenkoV3,s=v3?.state;if(!v3||!s)throw Error('Renko V3 engine missing');if(s.selected!==r.symbol)throw Error('Selected market changed during backfill');if(!sameBox(s.box,r.box))throw Error('Fixed brick size changed during backfill; rerun full history for the new box.');const recent=(s.historyTicks||[]).filter(t=>Number(t.time)>Number(r.lastTime)).sort((a,b)=>Number(a.time)-Number(b.time));const bricks=(r.bricks||[]).map((b,i)=>({i:i+1,open:Number(b[0]),close:Number(b[1]),high:Math.max(Number(b[0]),Number(b[1])),low:Math.min(Number(b[0]),Number(b[1])),direction:Number(b[2]),time:Number(b[3]),tradeId:b[4]??null,source:'binance-vision-raw-trade'}));s.bricks=bricks;s.historyTicks=[];s.tickCount=Number(r.ticks)||0;s.lastPrice=Number(bricks.at(-1)?.close);s.lastTickTime=Number(r.lastTime)||0;s.lastTradeId=r.lastId==null?null:Number(r.lastId);s.lastClose=Number(bricks.at(-1)?.close);s.direction=Number(bricks.at(-1)?.direction)||0;s.anchor=s.lastClose;s.genesisTime=Number(r.firstTime)||0;s.genesisTradeId=null;s.rawTrimmed=false;s.pan=0;s.historyMode='all';for(const t of recent){v3.applyTick({id:t.id,price:t.price,qty:t.qty,time:t.time},true,true)}v3.setHistoryMode('all');if($('sourceText'))$('sourceText').textContent='Binance Vision individual trades → Binance @trade live';if($('historyIntegrity'))$('historyIntegrity').textContent=r.complete?`RAW_TICK_COMPLETE · ${fmtN(r.ticks)} historical trades processed · no candle/OHLC/aggTrade`:`RAW_TICK_PARTIAL · ${fmtN(r.ticks)} trades processed · ${r.gaps?.length||0} archive gaps`;if($('historyState'))$('historyState').textContent=r.complete?`Full raw-tick coverage ${fmtDate(r.firstTime)} → live`:`Partial raw-tick coverage ${fmtDate(r.firstTime)} → ${fmtDate(r.lastTime)}`;if($('historyCoverage'))$('historyCoverage').textContent=r.complete?'ALL RAW TICK HISTORY · oldest archive → live':'PARTIAL RAW TICK HISTORY';if($('historyFrom'))$('historyFrom').textContent=fmtDate(r.firstTime);if($('historyTo'))$('historyTo').textContent='LIVE';}
function openDb(){return new Promise((resolve,reject)=>{if(!('indexedDB'in window))return resolve(null);const q=indexedDB.open('rwa-renko-tick-v5',1);q.onupgradeneeded=()=>{if(!q.result.objectStoreNames.contains('cache'))q.result.createObjectStore('cache')};q.onsuccess=()=>resolve(q.result);q.onerror=()=>reject(q.error)})}
async function cachePut(r){try{const db=await openDb();if(!db)return false;const key=`${r.symbol}|${r.box}`;await new Promise((resolve,reject)=>{const tx=db.transaction('cache','readwrite');tx.objectStore('cache').put({...r,savedAt:Date.now()},key);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});db.close();return true}catch(e){console.warn('[Renko V5.3] cache unavailable',e);return false}}
async function cacheGet(symbol,box){try{const db=await openDb();if(!db)return null;const key=`${symbol}|${box}`;const v=await new Promise((resolve,reject)=>{const tx=db.transaction('cache','readonly'),q=tx.objectStore('cache').get(key);q.onsuccess=()=>resolve(q.result||null);q.onerror=()=>reject(q.error)});db.close();return v}catch{return null}}
async function useCacheIfFresh(){const v3=window.RWARenkoV3,s=v3?.state;if(!s||own.running)return;const r=await cacheGet(s.selected,s.box);if(!r||!r.complete||!Array.isArray(r.bricks)||!r.bricks.length)return;const age=Date.now()-Number(r.lastTime||0);if(age>3*86400000)return;try{integrate(r);own.result=r;emit('archive-done',{...r,fromCache:true});status('complete','RAW TICK CACHE LOADED',`${fmtN(r.bricks.length)} bricks · ${fmtN(r.ticks)} raw trades · refreshing live via @trade`);progress(r.total||1,r.total||1);if($('archiveCoverage'))$('archiveCoverage').textContent=`${fmtDate(r.firstTime)} → ${fmtDate(r.lastTime)} + LIVE`; }catch(e){console.warn('[Renko V5.3] cache integrate',e)}}
function start(){const v3=window.RWARenkoV3,s=v3?.state;if(!v3||!s)return;if(own.running)cancel();const symbol=s.selected,box=Number(s.box);if(!(box>0)){status('error','INVALID BRICK SIZE','Set a positive fixed brick size first.');return}own.run++;const token=own.run;own.symbol=symbol;own.box=box;own.running=true;own.result=null;own.lastChunk=null;setButtons();status('loading','DISCOVERING RAW TICK ARCHIVES',`${symbol} · fixed box ${box}`);progress(0,0);emit('archive-start',{token,symbol,box});const w=new Worker(`archive-worker-v5.js?v=53`);own.worker=w;w.onmessage=async ev=>{if(token!==own.run)return;const m=ev.data||{};if(m.type==='status'){status('loading',m.status==='SOURCE'?'FINDING RAW TICK SOURCE':m.status==='DISCOVER'?'DISCOVERING LIFETIME ARCHIVES':String(m.status),m.base||`${symbol} · ${box}`)}else if(m.type==='discover'){status('loading','DISCOVERING LIFETIME ARCHIVES',`${m.month||''} · ${m.probed||0} months probed`)}else if(m.type==='plan'){progress(0,m.total);emit('archive-plan',{token,symbol,box,...m});if($('archiveCoverage'))$('archiveCoverage').textContent=`Target through ${fmtDate(m.end)} · ${m.total} archive segments`;status('loading','RAW TICK BACKFILL STARTED',`${symbol} · source ${m.base}`)}else if(m.type==='chunk'){own.lastChunk=m;emit('archive-chunk',{token,symbol,box,...m})}else if(m.type==='progress'){progress(m.done,m.total);status('loading','PROCESSING RAW TICKS',`${m.key||''} · ${fmtN(m.ticks)} trades · ${fmtN(m.bricks)} bricks · ${fmtBytes(m.downloaded)}`)}else if(m.type==='warning'){emit('archive-warning',{token,symbol,box,...m});status('partial','RAW TICK BACKFILL · GAP DETECTED',m.message||'Archive gap detected; COMPLETE will remain false.')}else if(m.type==='done'){own.running=false;own.worker?.terminate();own.worker=null;own.result=m;emit('archive-done',{token,symbol,box,...m});try{integrate(m);const saved=await cachePut(m);progress(m.done,m.total);if(m.complete){status('complete','COMPLETE RAW TICK HISTORY',`${fmtN(m.ticks)} individual trades → ${fmtN(m.bricks.length)} Traditional Renko bricks · ${fmtDate(m.firstTime)} → live${saved?' · cached locally':''}`)}else{status('partial','PARTIAL RAW TICK HISTORY',`${m.gaps?.length||0} archive gaps · not claiming complete`)}if($('archiveCoverage'))$('archiveCoverage').textContent=`${fmtDate(m.firstTime)} → ${fmtDate(m.lastTime)} + LIVE · ${fmtBytes(m.downloaded)}`;}catch(e){status('error','BACKFILL BUILT BUT NOT APPLIED',e.message)}setButtons()}else if(m.type==='error'){own.running=false;own.worker?.terminate();own.worker=null;emit('archive-error',{token,symbol,box,...m});status('error','RAW TICK BACKFILL FAILED',m.message||'Unknown worker error');setButtons()}};w.onerror=e=>{if(token!==own.run)return;own.running=false;emit('archive-error',{token,symbol,box,message:e.message||'Worker failed'});status('error','ARCHIVE WORKER ERROR',e.message||'Worker failed');setButtons()};w.postMessage({type:'start',symbol,box,bases:BASES})}
function bind(){if($('archiveLoad'))$('archiveLoad').onclick=start;if($('archiveCancel'))$('archiveCancel').onclick=cancel;setInterval(()=>{const s=window.RWARenkoV3?.state;if(!s)return;if(own.lastSelected!==s.selected){if(own.running)cancel();own.lastSelected=s.selected;resetUi();setTimeout(useCacheIfFresh,200)}} ,500)}
async function boot(){for(let i=0;i<100&&!window.RWARenkoV3;i++)await new Promise(r=>setTimeout(r,100));if(!window.RWARenkoV3)throw Error('Renko V3 boot timeout');window.RWARenkoV5={version:'5.3.0',source:'binance-vision-raw-trades-plus-live-at-trade',history:'raw-tick-archive-lifetime-auto',construction:'traditional-fixed-box',reversalBoxes:2,state:own,start,cancel,bases:BASES};window.RWARenko={...window.RWARenkoV3,version:'5.3.0',source:'raw-trade-ticks-only',history:'raw-tick-lifetime-archives',historyScope:'oldest-available-binance-vision-raw-trade-to-live',archive:window.RWARenkoV5};bind();own.lastSelected=window.RWARenkoV3.state.selected;resetUi();setTimeout(useCacheIfFresh,500)}
boot().catch(e=>{console.error('[Renko V5.3]',e);status('error','RENKO V5 FAILED TO START',e.message)});
})();
