(()=>{
'use strict';
if(window.RWARenkoV5Auto)return;
const MAX_SAMPLES=9000,EDGE_KEEP=1800;
const state={lastKey:'',armed:false,previewActive:false,previewCount:0,previewTicks:0,previewFirst:0,previewLast:0,previewStride:1,previewSamples:[],head:[],tail:[],drawTimer:0,mode:'all',complete:false,partial:false};
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const $=id=>document.getElementById(id);
function current(){const v3=window.RWARenkoV3,v5=window.RWARenkoV5,s=v3?.state;return {v3,v5,s,key:s&&Number(s.box)>0?`${s.selected}|${Number(s.box)}`:''}}
function fmtN(n){return Number(n||0).toLocaleString()}
function fmtDate(ms){if(!Number(ms))return'—';return new Date(Number(ms)).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'})}
function ensurePreview(){const wrap=$('chartWrap');if(!wrap)return null;let c=$('archivePreview');if(!c){c=document.createElement('canvas');c.id='archivePreview';c.setAttribute('aria-label','Total raw tick Traditional Renko history');Object.assign(c.style,{position:'absolute',inset:'0',width:'100%',height:'100%',zIndex:'3',pointerEvents:'none',background:'#070b10'});wrap.appendChild(c)}return c}
function resetPreview(){state.previewActive=false;state.previewCount=0;state.previewTicks=0;state.previewFirst=0;state.previewLast=0;state.previewStride=1;state.previewSamples=[];state.head=[];state.tail=[];state.complete=false;state.partial=false;state.mode='all';clearTimeout(state.drawTimer);state.drawTimer=0;const c=$('archivePreview');if(c){c.style.display='none';const x=c.getContext('2d');x?.clearRect(0,0,c.width,c.height)}syncLabels(true)}
function hidePreview(){state.mode='live';const c=$('archivePreview');if(c)c.style.display='none';state.previewActive=state.previewCount>0;syncButtons();const st=$('v5HistoryState');if(st)st.textContent=`LIVE raw ticks · ${fmtN(state.previewCount)} historical bricks retained`}
function pushEdge(arr,item,max=EDGE_KEEP){arr.push(item);if(arr.length>max)arr.splice(0,arr.length-max)}
function absorbChunk(m){const chunk=Array.isArray(m.bricks)?m.bricks:[];if(!chunk.length)return;state.previewActive=true;if(state.mode!=='live')state.mode='all';state.previewCount=Math.max(state.previewCount,Number(m.bricksTotal)||0);state.previewTicks=Math.max(state.previewTicks,Number(m.ticks)||0);state.previewFirst=state.previewFirst||Number(m.firstTime)||0;state.previewLast=Math.max(state.previewLast,Number(m.lastTime)||0);const start=Math.max(0,state.previewCount-chunk.length);for(let j=0;j<chunk.length;j++){const item={idx:start+j,b:chunk[j]};if(state.head.length<EDGE_KEEP)state.head.push(item);pushEdge(state.tail,item);if(item.idx%state.previewStride===0)state.previewSamples.push(item)}while(state.previewSamples.length>MAX_SAMPLES){state.previewStride*=2;state.previewSamples=state.previewSamples.filter(x=>x.idx%state.previewStride===0)}syncLabels();scheduleDraw()}
function sourceForMode(){if(state.mode==='start')return state.head;if(state.mode==='end')return state.tail;return state.previewSamples}
function bounds(list){let min=Infinity,max=-Infinity;for(const s of list){const o=Number(s.b?.[0]),c=Number(s.b?.[1]);if(Number.isFinite(o)&&Number.isFinite(c)){min=Math.min(min,o,c);max=Math.max(max,o,c)}}if(!Number.isFinite(min)||!Number.isFinite(max)||min===max){min=0;max=1}return{min,max}}
function scheduleDraw(){if(state.drawTimer||state.mode==='live')return;state.drawTimer=setTimeout(()=>{state.drawTimer=0;drawPreview()},80)}
function drawPreview(){if(!state.previewActive||state.mode==='live')return;const list=sourceForMode();if(!list.length)return;const c=ensurePreview(),wrap=$('chartWrap');if(!c||!wrap)return;c.style.display='block';const r=wrap.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),w=Math.max(320,Math.floor(r.width)),h=Math.max(240,Math.floor(r.height));if(c.width!==Math.floor(w*dpr)||c.height!==Math.floor(h*dpr)){c.width=Math.floor(w*dpr);c.height=Math.floor(h*dpr)}const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);x.fillStyle='#070b10';x.fillRect(0,0,w,h);const padL=48,padR=16,padT=34,padB=36,cw=w-padL-padR,ch=h-padT-padB,{min,max}=bounds(list),span=Math.max(Number.EPSILON,max-min),y=p=>padT+(max-p)/span*ch;x.strokeStyle='rgba(255,255,255,.07)';x.lineWidth=1;for(let i=0;i<=4;i++){const yy=padT+ch*i/4;x.beginPath();x.moveTo(padL,yy);x.lineTo(w-padR,yy);x.stroke();x.fillStyle='#697486';x.font='10px system-ui,-apple-system,sans-serif';x.fillText((max-span*i/4).toLocaleString(undefined,{maximumFractionDigits:4}),4,yy+3)}const firstIdx=list[0].idx,lastIdx=list.at(-1).idx,indexSpan=Math.max(1,lastIdx-firstIdx+1),step=cw/indexSpan,bodyW=Math.max(1,Math.min(12,step*.88));for(const s of list){const b=s.b,o=Number(b?.[0]),cl=Number(b?.[1]),dir=Number(b?.[2]);if(!Number.isFinite(o)||!Number.isFinite(cl))continue;const xx=padL+(s.idx-firstIdx)/indexSpan*cw,yo=y(o),yc=y(cl),top=Math.min(yo,yc),height=Math.max(1,Math.abs(yc-yo));x.fillStyle=dir>=0?'rgba(52,211,153,.84)':'rgba(251,113,133,.84)';x.strokeStyle=dir>=0?'rgba(110,231,183,.98)':'rgba(253,164,175,.98)';x.lineWidth=1;x.fillRect(xx-bodyW/2,top,bodyW,height);if(bodyW>=2)x.strokeRect(xx-bodyW/2,top,bodyW,height)}x.fillStyle='#e6edf7';x.font='600 12px system-ui,-apple-system,sans-serif';const modeLabel=state.mode==='all'?'ALL HISTORY':state.mode==='start'?'START':'LATEST HISTORY';x.fillText(`${modeLabel} · ${fmtN(state.previewCount)} Traditional Renko bricks`,padL,18);x.fillStyle='#8d99aa';x.font='11px system-ui,-apple-system,sans-serif';x.fillText(`${fmtDate(state.previewFirst)} → ${fmtDate(state.previewLast)} · ${fmtN(state.previewTicks)} individual trades`,padL,h-10)}
function syncLabels(reset=false){const hc=$('v5HistoryCount'),cov=$('v5HistoryCoverage'),hf=$('v5HistoryFrom'),ht=$('v5HistoryTo'),hs=$('v5HistoryState');if(reset||!state.previewCount){if(hc)hc.textContent='0 historical bricks';if(cov)cov.textContent='LOADING OLDEST RAW TICK → LIVE';if(hf)hf.textContent='—';if(ht)ht.textContent='LIVE';if(hs)hs.textContent='Automatic raw-tick lifetime backfill pending';syncButtons();return}if(hc)hc.textContent=`${fmtN(state.previewCount)} historical bricks`;if(cov)cov.textContent=`${state.complete?'COMPLETE RAW TICK HISTORY':'RAW TICK HISTORY BUILDING'} · ${fmtDate(state.previewFirst)} → ${fmtDate(state.previewLast)}`;if(hf)hf.textContent=fmtDate(state.previewFirst);if(ht)ht.textContent=state.complete?'LIVE':`${fmtDate(state.previewLast)} → LIVE`;if(hs)hs.textContent=state.mode==='live'?`LIVE raw ticks · ${fmtN(state.previewCount)} historical bricks retained`:state.complete?`Complete raw-tick Traditional Renko · ${fmtN(state.previewCount)} bricks`:`Building raw-tick Traditional Renko · ${fmtN(state.previewCount)} bricks loaded`;syncButtons()}
function syncButtons(){for(const [id,mode] of [['historyStart','start'],['historyAll','all'],['historyLive','live']])$(id)?.classList.toggle('active',state.mode===mode)}
function setMode(mode){if(!state.previewCount)return;state.mode=mode;if(mode==='live'){hidePreview();return}state.previewActive=true;syncLabels();scheduleDraw()}
function bindHistoryControls(){const bind=(id,fn)=>$(id)?.addEventListener('click',e=>{if(!state.previewCount)return;e.preventDefault();e.stopImmediatePropagation();fn()},true);bind('historyAll',()=>setMode('all'));bind('historyStart',()=>setMode('start'));bind('historyLive',()=>setMode('live'));bind('historyPrev',()=>setMode(state.mode==='end'?'all':'start'));bind('historyNext',()=>setMode(state.mode==='start'?'all':'end'))}
async function maybeStart(){const {v5,s,key}=current();if(!v5||!s||!key)return;if(state.lastKey===key&&state.armed)return;state.lastKey=key;state.armed=true;resetPreview();if(v5.state.running)v5.cancel();const status=$('archiveStatus'),detail=$('archiveDetail');if(status){status.className='archive-status loading';status.textContent='AUTO LOADING TOTAL RAW TICK HISTORY'}if(detail)detail.textContent=`${s.selected} · Traditional fixed box ${s.box} · oldest available individual trade → live`;await sleep(350);const now=current();if(now.key!==key)return;const cached=now.v5?.state?.result;if(cached?.complete&&cached.symbol===s.selected&&Number(cached.box)===Number(s.box))return;now.v5?.start()}
function onStart(e){const d=e.detail||{};const {s}=current();if(d.symbol!==s?.selected)return;resetPreview();state.lastKey=`${d.symbol}|${Number(d.box)}`;state.armed=true}
function onChunk(e){const d=e.detail||{};const {s}=current();if(d.symbol!==s?.selected||Number(d.box)!==Number(s?.box))return;absorbChunk(d)}
function onDone(e){const d=e.detail||{};const {s}=current();if(d.symbol!==s?.selected||Number(d.box)!==Number(s?.box))return;if(!state.previewCount&&Array.isArray(d.bricks)&&d.bricks.length)absorbChunk({...d,bricksTotal:d.bricks.length,ticks:d.ticks});state.complete=Boolean(d.complete);state.partial=!d.complete;state.previewActive=state.previewCount>0;syncLabels();if(state.mode!=='live')scheduleDraw();const status=$('archiveStatus');if(status&&state.previewCount){status.className=`archive-status ${state.complete?'complete':'partial'}`;status.textContent=state.complete?'COMPLETE RAW TICK HISTORY':'PARTIAL RAW TICK HISTORY'}}
function onError(){state.partial=true;if(state.previewCount){state.previewActive=true;if(state.mode==='live')state.mode='all';syncLabels();scheduleDraw()}}
async function boot(){for(let i=0;i<150&&!window.RWARenkoV5;i++)await sleep(100);if(!window.RWARenkoV5)throw Error('Renko V5 unavailable');window.RWARenkoV5Auto={version:'5.4.0',mode:'auto-selected-market-lifetime-raw-tick',preview:'owned-history-ui-traditional-bricks',state,maybeStart,drawPreview,previewChunk:absorbChunk,resetPreview,setMode};window.addEventListener('rwa-renko-archive-start',onStart);window.addEventListener('rwa-renko-archive-chunk',onChunk);window.addEventListener('rwa-renko-archive-done',onDone);window.addEventListener('rwa-renko-archive-error',onError);window.addEventListener('resize',()=>{if(state.previewActive&&state.mode!=='live')scheduleDraw()},{passive:true});bindHistoryControls();const b=$('archiveLoad');if(b)b.title='Reload total raw-tick history for selected market';setInterval(()=>{const {key}=current();if(state.previewActive)syncLabels();if(key&&key!==state.lastKey){state.armed=false;maybeStart().catch(console.error)}},250);syncLabels(true);maybeStart().catch(console.error)}
boot().catch(e=>console.error('[Renko V5.4 Auto]',e));
})();
