(()=>{
'use strict';
if(window.RWARenkoTV)return;
const E=window.RWARenkoTVEngine;if(!E)throw new Error('RWARenkoTVEngine missing');
const $=id=>document.getElementById(id),q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const RESTS=['https://data-api.binance.vision','https://api.binance.com'];
const WS_ROOTS=['wss://data-stream.binance.vision/ws','wss://stream.binance.com:9443/ws'];
const STORE='rwa_renko_tradingview_settings_v1';
const INTERVALS=new Set(['1s','1m','3m','5m','15m','30m','1h','4h','1d']);
const defaults={source:'close',interval:'1m',method:'atr',atrLength:14,boxSize:1,percentage:.01,wicks:true};
const settings={...defaults};try{Object.assign(settings,JSON.parse(localStorage.getItem(STORE)||'{}')||{})}catch{}
if(!['close','ohlc'].includes(settings.source))settings.source='close';if(!INTERVALS.has(settings.interval))settings.interval='1m';if(!['atr','traditional','percentage'].includes(settings.method))settings.method='atr';settings.atrLength=Math.max(1,Math.min(500,Math.floor(Number(settings.atrLength)||14)));settings.boxSize=Math.max(Number.EPSILON,Number(settings.boxSize)||1);settings.percentage=Math.max(.000001,Math.min(10,Number(settings.percentage)||.01));settings.wicks=settings.wicks!==false;
const state={version:'16.0.0-tv-public-docs',symbol:'',tickSize:NaN,lastPrice:NaN,closedBars:[],currentBar:null,confirmed:[],projection:[],confirmedData:[],projectionData:[],box:NaN,atr:NaN,base:null,status:'boot',historyPages:0,lastEventAt:0,generation:0,following:true,formationSource:'source-interval-close-or-ohlc',confirmationRule:'source-interval-close',projectionRule:'realtime-provisional-until-source-interval-close',publicDocsParity:true,exactProprietaryOutputParity:false};
let chart,series,projectionSeries,priceLine,resizeObserver,ws,wsFallback=0,ageTimer=0,marketRows=[],activeAbort=null,historyBusy=false,lastLogicalWidth=65;
const fmt=n=>{n=Number(n);if(!Number.isFinite(n))return'—';const a=Math.abs(n),d=a>=1000?2:a>=100?3:a>=1?4:a>=.01?6:8;return n.toLocaleString(undefined,{maximumFractionDigits:d})};
const fmtDate=ms=>Number(ms)?new Date(Number(ms)).toLocaleString(undefined,{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'—';
const save=()=>{try{localStorage.setItem(STORE,JSON.stringify(settings))}catch{}};
function setText(id,v){const el=$(id);if(el)el.textContent=v}
function setFeed(text,live=false){const el=$('feedPill');if(!el)return;el.classList.toggle('live',!!live);const b=el.querySelector('b');if(b)b.textContent=text}
function setLoad(text,kind='loading'){const e=$('tvLoadState');if(e){e.textContent=text;e.className=`load-state ${kind==='live'?'live':''}`}}
function normalizeSymbol(s){s=String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'');if(!s)return'BTCUSDT';if(!/(USDT|USDC|FDUSD|BTC|ETH|BNB)$/.test(s)&&/^[A-Z0-9]{2,10}$/.test(s))return`${s}USDT`;return s}
function splitSymbol(sym){for(const quote of ['USDT','USDC','FDUSD','BTC','ETH','BNB'])if(sym.endsWith(quote)&&sym.length>quote.length)return[sym.slice(0,-quote.length),quote];return[sym,'']}
function setUrlSymbol(sym){try{const u=new URL(location.href);u.searchParams.set('symbol',splitSymbol(sym)[0]);history.replaceState(null,'',u)}catch{}}
async function fetchJson(path,timeout=15000,signal){const jobs=RESTS.map(root=>new Promise(async(resolve,reject)=>{const c=new AbortController();const relay=()=>c.abort();if(signal)signal.addEventListener('abort',relay,{once:true});const tm=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(root+path,{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status} ${path}`);resolve(await r.json())}catch(e){reject(e)}finally{clearTimeout(tm);if(signal)signal.removeEventListener('abort',relay)}}));try{return await Promise.any(jobs)}catch(e){throw e?.errors?.at?.(-1)||e||new Error('market data unavailable')}}
function mapKlines(rows){return(Array.isArray(rows)?rows:[]).map(x=>({openTime:Number(x[0]),open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[5])||0,closeTime:Number(x[6])})).filter(b=>[b.openTime,b.open,b.high,b.low,b.close,b.closeTime].every(Number.isFinite)).sort((a,b)=>a.openTime-b.openTime)}
function dedupeBars(rows){const m=new Map();for(const b of rows||[])m.set(Number(b.openTime),b);return[...m.values()].sort((a,b)=>a.openTime-b.openTime)}
async function fetchKlines(symbol,interval,endTime=null,signal=null){let p=`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(interval)}&limit=1000`;if(Number.isFinite(Number(endTime)))p+=`&endTime=${Math.floor(Number(endTime))}`;return mapKlines(await fetchJson(p,18000,signal))}
async function fetchMeta(symbol,signal){const j=await fetchJson(`/api/v3/exchangeInfo?symbol=${encodeURIComponent(symbol)}`,15000,signal),s=j?.symbols?.[0],pf=s?.filters?.find?.(f=>f.filterType==='PRICE_FILTER'),tick=Number(pf?.tickSize);if(!(tick>0))throw new Error('minimum tick unavailable');return{tick,symbol:s?.symbol||symbol,status:s?.status||'',base:s?.baseAsset||splitSymbol(symbol)[0],quote:s?.quoteAsset||splitSymbol(symbol)[1]}}
async function fetchLast(symbol,signal){const j=await fetchJson(`/api/v3/ticker/price?symbol=${encodeURIComponent(symbol)}`,12000,signal),p=Number(j?.price);return p>0?p:NaN}
function initChart(){if(chart)return;const host=$('chartHost');if(!host)return;chart=LightweightCharts.createChart(host,{width:host.clientWidth,height:host.clientHeight,layout:{background:{type:'solid',color:'#101620'},textColor:'#9da3ae',fontSize:11},grid:{vertLines:{color:'#202837'},horzLines:{color:'#202837'}},rightPriceScale:{borderColor:'#30394a'},timeScale:{borderColor:'#30394a',timeVisible:true,secondsVisible:settings.interval==='1s',rightOffset:5,barSpacing:10,minBarSpacing:3},crosshair:{mode:0}});const add=(opts)=>chart.addSeries?chart.addSeries(LightweightCharts.CandlestickSeries,opts):chart.addCandlestickSeries(opts);series=add({upColor:'#089981',downColor:'#f23645',borderUpColor:'#089981',borderDownColor:'#f23645',wickUpColor:'#089981',wickDownColor:'#f23645',priceLineVisible:false,lastValueVisible:true});projectionSeries=add({upColor:'#a9dcc3',downColor:'#f5a6ae',borderUpColor:'#a9dcc3',borderDownColor:'#f5a6ae',wickUpColor:'#a9dcc3',wickDownColor:'#f5a6ae',priceLineVisible:false,lastValueVisible:false});resizeObserver=new ResizeObserver(()=>chart.applyOptions({width:host.clientWidth,height:host.clientHeight}));resizeObserver.observe(host);chart.timeScale().subscribeVisibleLogicalRangeChange(r=>{if(!r)return;lastLogicalWidth=Math.max(10,Math.round(r.to-r.from));state.following=r.to>state.confirmedData.length-4;if(r.from<12)void loadOlderPage()})}
function normalizeData(bricks,projection=false,startTime=0){let last=Math.floor(Number(startTime)||0),i=0;return(bricks||[]).map(b=>{let tm=Math.max(1,Math.floor(Number(b.sourceTime||0)/1000));if(tm<=last)tm=last+1;last=tm;const dir=Number(b.direction)||0,up=projection?'#a9dcc3':'#089981',down=projection?'#f5a6ae':'#f23645',color=dir>0?up:down;return{time:tm,open:Number(b.open),high:Number(b.high),low:Number(b.low),close:Number(b.close),color,borderColor:color,wickColor:color,_sourceTime:Number(b.sourceTime||0),_projection:projection,_dir:dir,_i:i++}})}
function render(fit=false){initChart();state.confirmedData=normalizeData(state.confirmed,false,0);const last=Number(state.confirmedData.at(-1)?.time||0);state.projectionData=normalizeData(state.projection,true,last);series?.setData(state.confirmedData);projectionSeries?.setData(state.projectionData);if(Number.isFinite(state.lastPrice)){if(priceLine){try{priceLine.applyOptions({price:state.lastPrice})}catch{}}else{try{priceLine=series?.createPriceLine({price:state.lastPrice,color:'#2962ff',lineWidth:1,lineStyle:2,axisLabelVisible:true,title:'REAL'})}catch{}}}const empty=$('chartEmpty');if(empty&&state.confirmedData.length)empty.classList.add('hide');if(fit||state.following)latestView();updateMeta()}
function latestView(){if(!chart||!state.confirmedData.length)return;const n=state.confirmedData.length,total=n+state.projectionData.length,w=Math.max(45,Math.min(75,lastLogicalWidth||65));chart.timeScale().setVisibleLogicalRange({from:Math.max(0,total-w),to:total+5});state.following=true}
function rebuild({fit=false}={}){if(!state.closedBars.length||!(state.tickSize>0))return;const base=E.build(state.closedBars,settings,state.tickSize);state.base=base;state.box=base.box;state.atr=base.atr;state.confirmed=base.bricks;state.projection=state.currentBar?E.project(base,state.currentBar,settings,state.tickSize):[];render(fit);updateAudit()}
function updateMeta(){const src=settings.source.toUpperCase(),method=settings.method==='atr'?'ATR':settings.method==='traditional'?'TRADITIONAL':'PERCENTAGE (LTP)';setText('modePill',`${method} · ${settings.interval} · ${src}`);setText('sourceText',`TradingView documented model · ${settings.interval} source ${src} · historical bricks lock on source-interval close · realtime bricks are provisional projections.`);setText('pairName',splitSymbol(state.symbol).join(' / '));setText('pairIcon',splitSymbol(state.symbol)[0].slice(0,2));setText('lastPrice',fmt(state.lastPrice));setText('brickValue',fmt(state.box));setText('brickCount',(state.confirmed?.length||0).toLocaleString());setText('projectionCount',(state.projection?.length||0).toLocaleString());setText('sourceBarCount',(state.closedBars?.length||0).toLocaleString());setText('currentMethod',method);setText('currentSource',src);setText('currentInterval',settings.interval);setText('currentAtr',fmt(state.atr));setText('ltpSnapshot',fmt(state.closedBars.at(-1)?.close));setText('minTick',fmt(state.tickSize));setText('tvBrickMeta',`${state.confirmed.length.toLocaleString()} confirmed · ${state.projection.length} projection`);const from=state.closedBars[0]?.openTime,to=state.closedBars.at(-1)?.closeTime;setText('tvCoverage',from?`${fmtDate(from)} → ${fmtDate(to)} · ${state.closedBars.length.toLocaleString()} source bars`:'Preparing source history');const p=state.projection.length;setLoad(p?`LIVE · ${p} projection brick${p===1?'':'s'} · locks on ${settings.interval} close`:`LIVE · waiting threshold · locks on ${settings.interval} close`,'live');qa('.method').forEach(el=>el.classList.toggle('active',el.dataset.method===settings.method));qa('.method .method-title span').forEach(el=>{const card=el.closest('.method');el.textContent=card?.dataset.method===settings.method?'ACTIVE':'READY'});const feed=$('tickHealth');if(feed){feed.textContent=state.status==='live'?'LIVE PROJECTION':'WAITING';feed.className=`health ${state.status==='live'?'live':''}`}}
function updateAudit(){const a=E.audit(state.confirmed),set=(id,ok,text)=>{const e=$(id);if(e){e.classList.toggle('ok',!!ok);e.textContent=`${ok?'✓':'!'} ${text}`}};set('auditSource',true,`Source ${settings.source.toUpperCase()} @ ${settings.interval}`);set('auditContinuation',a.continuation,'1× continuation');set('auditReversal',a.reversal,'2× reversal');set('auditProjection',true,'projection ≠ confirmed');set('auditWicks',a.wicksDirectional,settings.wicks?'directional wicks':'wicks off')}
function splitLatestBars(rows){const now=Date.now(),a=dedupeBars(rows),closed=[],open=[];for(const b of a){if(b.closeTime<now-50)closed.push(b);else open.push(b)}return{closed,current:open.at(-1)||null}}
function syncInputs(){if($('sourceSelect'))$('sourceSelect').value=settings.source;if($('intervalSelect'))$('intervalSelect').value=settings.interval;if($('atrLength'))$('atrLength').value=String(settings.atrLength);if($('traditionalBox'))$('traditionalBox').value=String(settings.boxSize);if($('percentageValue'))$('percentageValue').value=String(settings.percentage*100);if($('wicksToggle'))$('wicksToggle').checked=settings.wicks}
function wireControls(){syncInputs();$('sourceSelect')?.addEventListener('change',e=>{settings.source=e.target.value==='ohlc'?'ohlc':'close';save();rebuild({fit:true})});$('intervalSelect')?.addEventListener('change',e=>{const v=e.target.value;if(INTERVALS.has(v)){settings.interval=v;save();void loadSymbol(state.symbol,{fit:true})}});$('wicksToggle')?.addEventListener('change',e=>{settings.wicks=!!e.target.checked;save();rebuild()});qa('[data-apply-method]').forEach(btn=>btn.addEventListener('click',()=>{const m=btn.dataset.applyMethod;if(m==='atr'){settings.atrLength=Math.max(1,Math.min(500,Math.floor(Number($('atrLength')?.value)||14)))}else if(m==='traditional'){settings.boxSize=Math.max(Number.EPSILON,Number($('traditionalBox')?.value)||1)}else if(m==='percentage'){settings.percentage=Math.max(.000001,Math.min(10,(Number($('percentageValue')?.value)||1)/100))}settings.method=m;save();rebuild({fit:true})}));qa('[data-quick]').forEach(b=>b.addEventListener('click',()=>void loadSymbol(`${b.dataset.quick}USDT`,{fit:true})));$('openPairs')?.addEventListener('click',()=>q('.markets')?.classList.toggle('open'));$('pairSearch')?.addEventListener('input',renderMarkets);$('tvLive')?.addEventListener('click',latestView);$('tvZoomIn')?.addEventListener('click',()=>zoom(.75));$('tvZoomOut')?.addEventListener('click',()=>zoom(1.25));$('tvPanOlder')?.addEventListener('click',()=>pan(-.6));$('tvPanNewer')?.addEventListener('click',()=>pan(.6));$('tvReset')?.addEventListener('click',()=>{lastLogicalWidth=65;latestView()})}
function zoom(mult){if(!chart)return;const r=chart.timeScale().getVisibleLogicalRange();if(!r)return;const mid=(r.from+r.to)/2,w=Math.max(15,Math.min(220,(r.to-r.from)*mult));chart.timeScale().setVisibleLogicalRange({from:mid-w/2,to:mid+w/2});lastLogicalWidth=Math.round(w)}
function pan(frac){if(!chart)return;const r=chart.timeScale().getVisibleLogicalRange();if(!r)return;const w=r.to-r.from,d=w*frac;chart.timeScale().setVisibleLogicalRange({from:r.from+d,to:r.to+d})}
function parseWsBar(k){return{openTime:Number(k.t),closeTime:Number(k.T),open:Number(k.o),high:Number(k.h),low:Number(k.l),close:Number(k.c),volume:Number(k.v)||0}}
function closeSocket(){if(ws){try{ws.onopen=ws.onclose=ws.onerror=ws.onmessage=null;ws.close()}catch{}ws=null}}
function connectSocket(generation){closeSocket();const symbol=state.symbol.toLowerCase(),interval=settings.interval,root=WS_ROOTS[wsFallback%WS_ROOTS.length],url=`${root}/${symbol}@kline_${interval}`;try{ws=new WebSocket(url)}catch(e){scheduleWsFallback(generation);return}ws.onopen=()=>{if(generation!==state.generation)return;setFeed('LIVE',true);state.status='live';state.lastEventAt=Date.now();updateMeta()};ws.onerror=()=>{};ws.onclose=()=>{if(generation!==state.generation)return;setFeed('RECONNECTING',false);scheduleWsFallback(generation)};ws.onmessage=e=>{if(generation!==state.generation)return;try{const m=JSON.parse(e.data),k=m?.k;if(!k)return;const b=parseWsBar(k);state.lastPrice=b.close;state.lastEventAt=Date.now();if(k.x){state.closedBars=dedupeBars([...state.closedBars,b]);state.currentBar=null;rebuild();}else{state.currentBar=b;if(state.base){state.projection=E.project(state.base,b,settings,state.tickSize);render(false)}else rebuild()}setFeed('LIVE',true)}catch(err){console.warn('[RENKO TV websocket]',err)}}}
function scheduleWsFallback(generation){setTimeout(()=>{if(generation!==state.generation)return;wsFallback++;connectSocket(generation)},1200)}
async function loadSymbol(symbol,{fit=false}={}){symbol=normalizeSymbol(symbol||state.symbol);const generation=++state.generation;state.symbol=symbol;state.status='loading';state.closedBars=[];state.currentBar=null;state.confirmed=[];state.projection=[];state.historyPages=0;state.base=null;setUrlSymbol(symbol);setFeed('CONNECTING',false);setLoad(`Loading ${settings.interval} source bars…`,'loading');const empty=$('chartEmpty');if(empty){empty.classList.remove('hide');empty.querySelector('b').textContent=`Loading ${symbol} ${settings.interval} source…`;empty.querySelector('small').textContent='Historical source bars first; realtime is projection until interval close.'}closeSocket();activeAbort?.abort();activeAbort=new AbortController();try{const [meta,rows,last]=await Promise.all([fetchMeta(symbol,activeAbort.signal),fetchKlines(symbol,settings.interval,null,activeAbort.signal),fetchLast(symbol,activeAbort.signal)]);if(generation!==state.generation)return false;state.tickSize=meta.tick;state.lastPrice=last;const split=splitLatestBars(rows);state.closedBars=split.closed;state.currentBar=split.current;state.historyPages=1;rebuild({fit:true});state.status='live';connectSocket(generation);updateMeta();void loadOlderPage();return true}catch(e){if(generation!==state.generation||activeAbort?.signal.aborted)return false;state.status='error';setLoad(`DATA ERROR · ${String(e?.message||e)}`,'error');setFeed('OFFLINE',false);console.error('[RENKO TV load]',e);return false}}
async function loadOlderPage(){if(historyBusy||state.status==='error'||state.historyPages>=5||!state.closedBars.length)return false;historyBusy=true;const generation=state.generation,oldest=state.closedBars[0]?.openTime;try{const rows=await fetchKlines(state.symbol,settings.interval,Number(oldest)-1,null);if(generation!==state.generation)return false;const older=rows.filter(b=>b.openTime<oldest);if(!older.length){state.historyPages=5;return false}state.closedBars=dedupeBars([...older,...state.closedBars]);state.historyPages++;const follow=state.following;rebuild({fit:false});if(follow)latestView();return true}catch(e){console.warn('[RENKO TV older history]',e);return false}finally{historyBusy=false}}
async function loadMarkets(){try{const [info,tickers]=await Promise.all([fetchJson('/api/v3/exchangeInfo',20000),fetchJson('/api/v3/ticker/24hr',20000)]),tm=new Map((Array.isArray(tickers)?tickers:[]).map(t=>[t.symbol,t]));marketRows=(info?.symbols||[]).filter(s=>s.status==='TRADING'&&s.isSpotTradingAllowed!==false).map(s=>{const t=tm.get(s.symbol)||{};return{symbol:s.symbol,base:s.baseAsset,quote:s.quoteAsset,price:Number(t.lastPrice),pct:Number(t.priceChangePercent),vol:Number(t.quoteVolume)||0}}).filter(x=>Number.isFinite(x.price)&&x.price>0).sort((a,b)=>b.vol-a.vol);renderMarkets();setText('pairTotal',`${marketRows.length.toLocaleString()} markets`)}catch(e){const el=$('pairList');if(el)el.innerHTML='<div class="empty">Market universe unavailable. Quick pairs and direct symbol URL still work.</div>';console.warn('[RENKO TV markets]',e)}}
function renderMarkets(){const host=$('pairList');if(!host)return;const term=String($('pairSearch')?.value||'').trim().toUpperCase(),rows=(term?marketRows.filter(x=>`${x.base}${x.quote}${x.symbol}`.includes(term)):marketRows).slice(0,500);setText('pairShown',term?`${rows.length} matches`:`Top ${Math.min(500,rows.length)} shown`);setText('universeNote',marketRows.length?`Search all ${marketRows.length.toLocaleString()} spot markets`:'Loading universe…');host.textContent='';if(!rows.length){host.innerHTML='<div class="empty">No matching pair.</div>';return}const frag=document.createDocumentFragment();for(const r of rows){const [base,quote]=[r.base,r.quote],row=document.createElement('button');row.type='button';row.className=`pair-row ${r.symbol===state.symbol?'active':''}`;row.innerHTML=`<span class="pair-icon">${base.slice(0,2)}</span><span class="pair-main"><b>${base} / ${quote}</b><small>${fmt(r.vol)} 24h quote</small></span><span class="pair-price"><b>${fmt(r.price)}</b><small class="${r.pct>=0?'up':'down'}">${r.pct>=0?'+':''}${fmt(r.pct)}%</small></span>`;row.addEventListener('click',()=>{q('.markets')?.classList.remove('open');void loadSymbol(r.symbol,{fit:true})});frag.appendChild(row)}host.appendChild(frag)}
function startAge(){clearInterval(ageTimer);ageTimer=setInterval(()=>{const age=state.lastEventAt?Math.max(0,Date.now()-state.lastEventAt):0;setText('tickAge',state.lastEventAt?`${Math.round(age/1000)}s since kline update`:'waiting');if(age>15000&&state.status==='live')setFeed('STALE',false)},1000)}
function expose(){window.RWARenkoTV={version:'1.0.0',engine:E,state,settings,loadSymbol,rebuild,loadOlderPage,contract:{reference:'TradingView public Renko documentation',historical:'chart-resolution Close or OHLC',realtime:'projection until source interval close',traditional:'fixed box; 1x continuation; 2x reversal',percentage:'latest closed price x percent, nearest min tick, fixed across rebuild',atr:'Wilder ATR from regular source-interval OHLC',wicks:'Close extrema for Close source; High/Low for OHLC source',exactProprietaryIntrabarOrdering:'not publicly specified'}};window.RWARenkoV15=window.RWARenkoTV}
async function boot(){expose();wireControls();initChart();startAge();void loadMarkets();const p=new URLSearchParams(location.search),sym=normalizeSymbol(p.get('symbol')||'SOLUSDT');await loadSymbol(sym,{fit:true});window.dispatchEvent(new CustomEvent('renko:tv-ready',{detail:{symbol:state.symbol,version:window.RWARenkoTV.version}}))}
boot().catch(e=>{console.error(e);setLoad(String(e?.message||e),'error')});
})();
