(()=>{
'use strict';
if(window.RWARenkoV14)return;
const $=id=>document.getElementById(id);
const RESTS=['https://data-api.binance.vision','https://api.binance.com'];
const PAGE=1000,BATCH=4,FIRST_VIEW=60,STORE='rwa_renko_v14_settings';
const METHODS=new Set(['atr','traditional','percentage']),SOURCES=new Set(['close','ohlc']),RESOLUTIONS=new Set(['1m','3m','5m','15m','30m','1h','4h','1d']);
const now=()=>Date.now(),sleep=ms=>new Promise(r=>setTimeout(r,ms)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fmt=n=>{n=Number(n);if(!Number.isFinite(n))return'—';const a=Math.abs(n),d=a>=1000?2:a>=100?3:a>=1?4:a>=.01?6:8;return n.toLocaleString(undefined,{maximumFractionDigits:d})};
const fmtDate=ms=>Number(ms)?new Date(Number(ms)).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'}):'—';
const C={method:'atr',atrLength:14,traditionalBox:100,percentage:.01,source:'close',resolution:'1m',wicks:true,confirmBricks:2};
try{Object.assign(C,JSON.parse(localStorage.getItem(STORE)||'{}')||{})}catch{}
if(!METHODS.has(C.method))C.method='atr';if(!SOURCES.has(C.source))C.source='close';if(!RESOLUTIONS.has(C.resolution))C.resolution='1m';C.atrLength=clamp(Math.floor(Number(C.atrLength)||14),1,200);C.traditionalBox=Math.max(Number.EPSILON,Number(C.traditionalBox)||100);C.percentage=clamp(Number(C.percentage)||.01,.000001,.1);C.wicks=C.wicks!==false;C.confirmBricks=Number(C.confirmBricks)===1?1:2;
const S={version:'14.2.0',generation:0,symbol:'',tickSize:NaN,ltpSnapshot:NaN,atrValue:NaN,box:NaN,bars:[],currentBar:null,bricks:[],data:[],tailState:null,projection:[],buildSeq:0,loading:false,building:false,exhausted:false,following:true,latestClosedOpen:0,lastProjectionPrice:NaN,signal:null};
let chart=null,series=null,projectionSeries=null,liveLine=null,worker=null,resizeObserver=null,rangeTimer=0,watchTimer=0,refreshTimer=0,metaFrame=0,lastSymbol='';
function save(){try{localStorage.setItem(STORE,JSON.stringify(C))}catch{}}
function setText(id,text){const e=$(id);if(e)e.textContent=text}
function setStatus(text,kind='ready'){const e=$('tvLoadState');if(e){e.textContent=text;e.dataset.kind=kind}const l=$('tvLoading');if(l)l.hidden=kind!=='loading'}
function methodName(m=C.method){return m==='atr'?'ATR':m==='traditional'?'TRADITIONAL':'PERCENTAGE (LTP)'}
function sourceName(){return C.source==='ohlc'?'OHLC':'CLOSE'}
function mode(){setText('modePill',`${methodName()} · ${C.resolution.toUpperCase()} · TV PARITY`);setText('sourceText',`TradingView documented parity · ${sourceName()} source · ${C.resolution} resolution · realtime bricks project until source bar closes.`)}
function queueMeta(){if(metaFrame)return;metaFrame=requestAnimationFrame(()=>{metaFrame=0;meta()})}
function meta(){const r=chart?.timeScale?.().getVisibleLogicalRange?.(),width=r?Math.max(1,Math.round(r.to-r.from)):FIRST_VIEW;setText('tvZoomValue',String(width));setText('tvBrickMeta',`${Math.min(width,S.data.length)} visible · ${S.data.length.toLocaleString()} confirmed${S.projection.length?` · ${S.projection.length} projected`:''}`);setText('tvCoverage',S.bars.length?`${fmtDate(S.bars[0]?.[0])} → ${C.resolution} LIVE`:'Preparing history');setText('brickValue',fmt(S.box));setText('brickCount',S.data.length.toLocaleString());setText('v11MethodLabel',methodName());setText('v11CurrentBox',fmt(S.box));setText('v11AtrNow',Number.isFinite(S.atrValue)?fmt(S.atrValue):'—');setText('v12LtpSnapshot',fmt(S.ltpSnapshot));setText('v11TickSize',fmt(S.tickSize))}
async function fetchJson(path,timeout=12000){const attempts=RESTS.map(root=>new Promise(async(resolve,reject)=>{const c=new AbortController(),tm=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(root+path,{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);resolve(await r.json())}catch(e){reject(e)}finally{clearTimeout(tm)}}));try{return await Promise.any(attempts)}catch(e){throw e?.errors?.at?.(-1)||e||Error('market data unavailable')}}
async function fetchTickSize(symbol){try{const j=await fetchJson(`/api/v3/exchangeInfo?symbol=${encodeURIComponent(symbol)}`),pf=j?.symbols?.[0]?.filters?.find?.(f=>f.filterType==='PRICE_FILTER'),t=Number(pf?.tickSize);if(t>0)return t}catch(e){console.warn('[V14 tick]',e)}return .00000001}
async function fetchLtp(symbol){try{const j=await fetchJson(`/api/v3/ticker/price?symbol=${encodeURIComponent(symbol)}`),p=Number(j?.price);if(p>0)return p}catch(e){console.warn('[V14 LTP]',e)}const p=Number(window.RWARenkoV3?.state?.lastPrice);return p>0?p:NaN}
function dedupeBars(rows){const m=new Map();for(const r of rows||[]){const t=Number(r?.[0]);if(Number.isFinite(t))m.set(t,r)}return[...m.values()].sort((a,b)=>Number(a[0])-Number(b[0]))}
async function fetchBars(symbol,endTime,limit=PAGE){const q=`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(C.resolution)}&limit=${limit}${Number.isFinite(endTime)?`&endTime=${Math.floor(endTime)}`:''}`;return await fetchJson(q,15000)}
function splitBars(rows){const t=now(),all=Array.isArray(rows)?rows:[],closed=all.filter(r=>Number(r?.[6]||0)<t),current=all.filter(r=>Number(r?.[0])&&Number(r?.[6]||0)>=t).at(-1)||null;return{closed,current}}
function ensureWorker(){if(worker)return worker;worker=new Worker('renko-v14-worker.js?v=142');return worker}
function normalizeAll(bricks){let t=0;return(bricks||[]).map((b,i)=>{let tm=Math.max(1,Math.floor(Number(b.time||0)/1000));if(tm<=t)tm=t+1;t=tm;const o=Number(b.open),c=Number(b.close),h=Number(b.high),l=Number(b.low),d=Number(b.direction)||0;return{time:tm,open:o,high:Number.isFinite(h)?Math.max(h,o,c):Math.max(o,c),low:Number.isFinite(l)?Math.min(l,o,c):Math.min(o,c),close:c,color:d>0?'#089981':'#f23645',borderColor:d>0?'#089981':'#f23645',wickColor:d>0?'#089981':'#f23645',_dir:d,_reversal:!!b.isReversal,_box:Number(b.box),_ms:Number(b.time||0),_sourceTime:Number(b.sourceTime||0),_i:i}})}
function rangeAnchor(){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r||!S.data.length)return null;const i=clamp(Math.floor(r.from),0,S.data.length-1),d=S.data[i];return{range:r,index:i,time:d?.time,close:d?.close}}
function restoreAnchor(a){if(!a||!chart||!S.data.length)return;let i=S.data.findIndex(d=>d.time===a.time&&Math.abs(Number(d.close)-Number(a.close))<Math.max(1e-10,Math.abs(Number(a.close))*1e-9));if(i<0)i=S.data.findIndex(d=>d.time>=a.time);if(i<0)return;const sh=i-a.index;chart.timeScale().setVisibleLogicalRange({from:a.range.from+sh,to:a.range.to+sh})}
function rebuild(anchor=null){if(!S.bars.length||!(S.tickSize>0))return Promise.resolve(false);const generation=S.generation,id=++S.buildSeq,bars=S.bars.map(r=>r.slice(0,7));S.building=true;setStatus('Building TradingView-parity Renko…','loading');return new Promise((resolve,reject)=>{const w=ensureWorker(),on=e=>{const m=e.data||{};if((m.type!=='built'&&m.type!=='error')||m.id!==id)return;w.removeEventListener('message',on);if(generation!==S.generation||id!==S.buildSeq){resolve(false);return}S.building=false;if(m.type==='error'){reject(Error(m.message||'worker error'));return}S.bricks=Array.isArray(m.bricks)?m.bricks:[];S.data=normalizeAll(S.bricks);S.box=Number(m.box);S.atrValue=Number(m.atrValue);S.tailState=m.tailState||null;series?.setData(S.data);showChart();restoreAnchor(anchor);projectCurrent();if(S.following)latestView();setStatus('TV PARITY · confirmed history','ready');evaluateSignal();meta();resolve(true)};w.addEventListener('message',on);try{w.postMessage({type:'build',id,generation,method:C.method,traditionalBox:C.traditionalBox,percentage:C.percentage,ltpSnapshot:S.ltpSnapshot,atrLength:C.atrLength,tickSize:S.tickSize,wicks:C.wicks,source:C.source,bars})}catch(e){w.removeEventListener('message',on);if(id===S.buildSeq)S.building=false;reject(e)}})}
function showChart(){const e=$('chartEmpty');if(e)e.classList.add('hide');const h=$('lwcRenkoHost');if(h)h.style.visibility='visible'}
function latestView(){if(!chart||!S.data.length)return;const n=S.data.length;chart.timeScale().setVisibleLogicalRange({from:Math.max(0,n-FIRST_VIEW),to:n+5+S.projection.length});S.following=true;meta()}
function cloneTail(s){return s?{lastClose:Number(s.lastClose),direction:Number(s.direction)||0,pendingHigh:Number(s.pendingHigh),pendingLow:Number(s.pendingLow),anchor:Number(s.anchor),lastTime:Number(s.lastTime)||0}:null}
function touch(st,p){if(!Number.isFinite(st.pendingHigh))st.pendingHigh=p;if(!Number.isFinite(st.pendingLow))st.pendingLow=p;if(p>st.pendingHigh)st.pendingHigh=p;if(p<st.pendingLow)st.pendingLow=p}
function emitProjection(st,out,open,close,dir,t,box,rev){let high=Math.max(open,close),low=Math.min(open,close);if(C.wicks){if(dir>0)low=Math.min(low,st.pendingLow);else high=Math.max(high,st.pendingHigh)}out.push({time:t,open,high,low,close,direction:dir,box,isReversal:!!rev});st.lastClose=close;st.direction=dir;st.pendingHigh=close;st.pendingLow=close}
function processProjection(st,p,t,box,out){p=Number(p);if(!st||!Number.isFinite(p)||!(box>0))return;touch(st,p);let g=0;while(g++<10000){const lc=st.lastClose,d=st.direction;if(d===0){if(p>=lc+box){emitProjection(st,out,lc,lc+box,1,t,box,false);continue}if(p<=lc-box){emitProjection(st,out,lc,lc-box,-1,t,box,false);continue}break}if(d>0){if(p>=lc+box){emitProjection(st,out,lc,lc+box,1,t,box,false);continue}if(p<=lc-2*box){emitProjection(st,out,lc-box,lc-2*box,-1,t,box,true);continue}break}if(p<=lc-box){emitProjection(st,out,lc,lc-box,-1,t,box,false);continue}if(p>=lc+2*box){emitProjection(st,out,lc+box,lc+2*box,1,t,box,true);continue}break}touch(st,p)}
function projectionPath(){const b=S.currentBar;if(!b)return[];const o=Number(b[1]),h=Number(b[2]),l=Number(b[3]),c=Number(b[4]);if(C.source==='close')return Number.isFinite(S.lastProjectionPrice)?[S.lastProjectionPrice]:[c];if(![o,h,l,c].every(Number.isFinite))return[];return c>=o?[o,l,h,c]:[o,h,l,c]}
function projectCurrent(){if(!projectionSeries||!S.tailState||!(S.box>0)){S.projection=[];projectionSeries?.setData([]);return}const st=cloneTail(S.tailState),out=[],time=Number(S.currentBar?.[0]||now());for(const p of projectionPath())processProjection(st,p,time,S.box,out);const base=S.data.length?S.data.at(-1).time:Math.floor(time/1000),bars=out.map((b,i)=>({time:base+i+1,open:b.open,high:b.high,low:b.low,close:b.close,color:b.direction>0?'rgba(8,153,129,.28)':'rgba(242,54,69,.28)',borderColor:b.direction>0?'rgba(8,153,129,.70)':'rgba(242,54,69,.70)',wickColor:b.direction>0?'rgba(8,153,129,.65)':'rgba(242,54,69,.65)'}));S.projection=bars;projectionSeries.setData(bars);meta()}
function updateCurrentFromTrade(t){const p=Number(t?.price),tm=Number(t?.time);if(!Number.isFinite(p)||!Number.isFinite(tm)||!S.symbol)return;S.lastProjectionPrice=p;if(S.currentBar){const start=Number(S.currentBar[0]),end=Number(S.currentBar[6]);if(tm>=start&&tm<=end){S.currentBar[2]=String(Math.max(Number(S.currentBar[2]),p));S.currentBar[3]=String(Math.min(Number(S.currentBar[3]),p));S.currentBar[4]=String(p)}}updateLiveLine(p);projectCurrent()}
function updateLiveLine(p){if(!series||!Number.isFinite(p))return;if(liveLine){try{liveLine.applyOptions({price:p})}catch{}}else{try{liveLine=series.createPriceLine({price:p,color:'#2962ff',lineWidth:1,lineStyle:2,axisLabelVisible:true,title:'REAL'})}catch{}}}
async function refreshClosed(){if(!S.symbol||S.loading)return;const generation=S.generation,symbol=S.symbol;try{const rows=await fetchBars(symbol,undefined,4);if(generation!==S.generation||symbol!==S.symbol)return;const {closed,current}=splitBars(rows),latestOpen=Number(closed.at(-1)?.[0]||0),before=S.latestClosedOpen;if(current)S.currentBar=current;if(latestOpen>before){S.bars=dedupeBars([...S.bars,...closed]);S.latestClosedOpen=latestOpen;await rebuild(rangeAnchor())}else projectCurrent()}catch(e){console.warn('[V14 refresh]',e)}}
async function loadOlder(count=BATCH){if(S.loading||S.exhausted||!S.bars.length)return false;const generation=S.generation,symbol=S.symbol,first=Number(S.bars[0]?.[0]),anchor=rangeAnchor();S.loading=true;S.following=false;setStatus('Loading older TradingView source bars…','loading');try{let cursor=first,added=0;for(let i=0;i<count&&generation===S.generation;i++){const rows=await fetchBars(symbol,cursor-1,PAGE),{closed}=splitBars(rows);const older=closed.filter(r=>Number(r?.[0])<cursor);if(!older.length){S.exhausted=true;break}const before=S.bars.length;S.bars=dedupeBars([...older,...S.bars]);added+=S.bars.length-before;const next=Number(S.bars[0]?.[0]);if(!(next<cursor)){S.exhausted=true;break}cursor=next;if(older.length<PAGE){S.exhausted=true;break}}if(added>0)await rebuild(anchor);return added>0}catch(e){console.warn('[V14 older]',e);setStatus('History retry','bad');return false}finally{if(generation===S.generation){S.loading=false;meta()}}}
function scheduleOlder(){clearTimeout(rangeTimer);rangeTimer=setTimeout(()=>{const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(r&&r.from<24&&!S.loading&&!S.building&&!S.exhausted)void loadOlder(BATCH)},120)}
function requestedBase(){try{return String(new URLSearchParams(location.search).get('symbol')||'').toUpperCase().replace(/[^A-Z0-9]/g,'')}catch{return''}}
function resolveRequested(req){const v=window.RWARenkoV3?.state;if(!req||!v)return'';if(v.marketBySymbol?.has?.(req))return req;const rows=Array.isArray(v.markets)?v.markets.filter(x=>String(x.base).toUpperCase()===req):[];const pref=['USDT','USDC','FDUSD','BTC','ETH','BNB'];return rows.sort((a,b)=>(pref.indexOf(a.quote)<0?99:pref.indexOf(a.quote))-(pref.indexOf(b.quote)<0?99:pref.indexOf(b.quote))||Number(b.volumeUsd||0)-Number(a.volumeUsd||0))[0]?.symbol||''}
async function applyRequestedSymbol(){const req=requestedBase();if(!req)return;for(let i=0;i<240&&!(window.RWARenkoV3?.state?.markets?.length);i++)await sleep(25);const target=resolveRequested(req);if(target&&target!==window.RWARenkoV3.state.selected)await window.RWARenkoV3.selectSymbol(target)}
async function resetSymbol(symbol){const generation=++S.generation;++S.buildSeq;S.symbol=symbol;S.tickSize=NaN;S.ltpSnapshot=NaN;S.atrValue=NaN;S.box=NaN;S.bars=[];S.currentBar=null;S.bricks=[];S.data=[];S.tailState=null;S.projection=[];S.loading=false;S.building=false;S.exhausted=false;S.following=true;S.latestClosedOpen=0;S.lastProjectionPrice=NaN;S.signal=null;series?.setData([]);projectionSeries?.setData([]);if(liveLine){try{series.removePriceLine(liveLine)}catch{}liveLine=null}mode();setStatus('Loading TradingView source bars…','loading');try{const [tick,ltp,rows]=await Promise.all([fetchTickSize(symbol),fetchLtp(symbol),fetchBars(symbol)]);if(generation!==S.generation)return;S.tickSize=tick;S.ltpSnapshot=ltp;const sp=splitBars(rows);S.bars=dedupeBars(sp.closed);S.currentBar=sp.current;S.latestClosedOpen=Number(S.bars.at(-1)?.[0]||0);if(S.bars.length)await rebuild();let rounds=0;while(generation===S.generation&&S.data.length<FIRST_VIEW&&!S.exhausted&&rounds++<4){if(!await loadOlder(BATCH))break}if(generation!==S.generation)return;if(S.data.length){latestView();setStatus('TV PARITY · confirmed history','ready')}else setStatus('Waiting for source-bar move…','ready');meta();await refreshClosed()}catch(e){console.error('[V14 symbol]',e);setStatus('Source feed retry','bad')}}
function deriveSignal(){const a=S.data;if(a.length<3)return{position:'flat',action:'WAIT',reason:'Need more confirmed Renko bricks'};const confirm=C.confirmBricks;let position='flat',entry=NaN,entryBox=NaN,lastEvent='WAIT',eventIndex=-1;for(let i=1;i<a.length;i++){const d=Number(a[i]._dir),prev=Number(a[i-1]._dir);if(position==='long'&&d<0){position='flat';lastEvent='EXIT LONG · confirmed reversal';eventIndex=i;continue}if(position==='short'&&d>0){position='flat';lastEvent='EXIT SHORT · confirmed reversal';eventIndex=i;continue}if(position!=='flat')continue;if(confirm===1){if(prev<0&&d>0){position='long';entry=Number(a[i].close);entryBox=Number(a[i]._box)||S.box;lastEvent='BUY READY · confirmed reversal';eventIndex=i}else if(prev>0&&d<0){position='short';entry=Number(a[i].close);entryBox=Number(a[i]._box)||S.box;lastEvent='SELL READY · confirmed reversal';eventIndex=i}}else if(i>=2){const p2=Number(a[i-2]._dir);if(p2<0&&prev>0&&d>0){position='long';entry=Number(a[i].close);entryBox=Number(a[i]._box)||S.box;lastEvent='BUY READY · reversal + 1';eventIndex=i}else if(p2>0&&prev<0&&d<0){position='short';entry=Number(a[i].close);entryBox=Number(a[i]._box)||S.box;lastEvent='SELL READY · reversal + 1';eventIndex=i}}}const market=Number(window.RWARenkoV3?.state?.lastPrice),close=Number(a.at(-1)?.close),trailBox=Number(a.at(-1)?._box)||S.box;let hard=NaN,trail=NaN,action=lastEvent,reason='Signals use confirmed source-interval bricks; projection bricks never trigger entries.';if(position==='long'){hard=entry-2*entryBox;trail=close-trailBox;if(Number.isFinite(market)&&market<=hard){action='EXIT NOW · real market hard stop';reason='Real price crossed hard stop.'}else if(eventIndex<a.length-1)action='LONG ACTIVE'}else if(position==='short'){hard=entry+2*entryBox;trail=close+trailBox;if(Number.isFinite(market)&&market>=hard){action='EXIT NOW · real market hard stop';reason='Real price crossed hard stop.'}else if(eventIndex<a.length-1)action='SHORT ACTIVE'}else if(!lastEvent.startsWith('EXIT'))action='WAIT';return{position,action,entry,hard,trail,reason}}
function evaluateSignal(){S.signal=deriveSignal();const x=S.signal,age=now()-Number(window.RWARenkoV3?.state?.lastTickTime||0),fresh=age<5000;setText('signalAction',x.action);setText('signalPosition',x.position.toUpperCase());setText('signalEntry',fmt(x.entry));setText('signalMarket',fmt(Number(window.RWARenkoV3?.state?.lastPrice)));setText('signalHardStop',fmt(x.hard));setText('signalTrail',fmt(x.trail));setText('signalReason',x.reason);setText('signalFreshness',fresh?`LIVE ${Math.max(0,age)} ms`:`STALE ${Math.floor(age/1000)} s`);const e=$('signalAction');if(e)e.dataset.kind=x.action.includes('EXIT')?'exit':x.action.includes('BUY')?'buy':x.action.includes('SELL')?'sell':x.position==='long'?'buy':x.position==='short'?'sell':'wait';const f=$('signalFreshness');if(f)f.dataset.kind=fresh?'live':'stale'}
function createChart(){const wrap=$('chartWrap'),L=window.LightweightCharts;if(!wrap||!L)return false;let host=$('lwcRenkoHost');if(!host){host=document.createElement('div');host.id='lwcRenkoHost';host.setAttribute('aria-label','RENKO V14 TradingView parity chart');wrap.prepend(host)}chart=L.createChart(host,{localization:{locale:'en-US'},layout:{background:{type:L.ColorType?.Solid??'solid',color:'#131722'},textColor:'#b2b5be',attributionLogo:true},grid:{vertLines:{color:'rgba(120,123,134,.14)'},horzLines:{color:'rgba(120,123,134,.14)'}},rightPriceScale:{borderColor:'#2a2e39',minimumWidth:64,scaleMargins:{top:.04,bottom:.05}},timeScale:{borderColor:'#2a2e39',timeVisible:true,secondsVisible:false,rightOffset:8,barSpacing:10,minBarSpacing:2,maxBarSpacing:30,lockVisibleTimeRangeOnResize:true},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true,vertTouchDrag:true},handleScale:{mouseWheel:true,pinch:true,axisPressedMouseMove:{time:true,price:true},axisDoubleClickReset:{time:true,price:true}},kineticScroll:{mouse:true,touch:true},crosshair:{mode:L.CrosshairMode?.Normal??0}});series=chart.addSeries(L.CandlestickSeries,{upColor:'#089981',downColor:'#f23645',borderUpColor:'#089981',borderDownColor:'#f23645',wickUpColor:'#089981',wickDownColor:'#f23645',priceLineVisible:false,lastValueVisible:true});projectionSeries=chart.addSeries(L.CandlestickSeries,{upColor:'rgba(8,153,129,.25)',downColor:'rgba(242,54,69,.25)',borderUpColor:'rgba(8,153,129,.70)',borderDownColor:'rgba(242,54,69,.70)',wickUpColor:'rgba(8,153,129,.55)',wickDownColor:'rgba(242,54,69,.55)',priceLineVisible:false,lastValueVisible:false});chart.timeScale().subscribeVisibleLogicalRangeChange?.(r=>{if(r&&S.data.length)S.following=r.to>=S.data.length-1;queueMeta();scheduleOlder()});resizeObserver=new ResizeObserver(entries=>{const r=entries[0]?.contentRect;if(r?.width&&r?.height)chart.resize(Math.floor(r.width),Math.floor(r.height))});resizeObserver.observe(wrap);wireNav();return true}
function shiftRange(frac){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r)return;const w=r.to-r.from,d=w*frac;chart.timeScale().setVisibleLogicalRange({from:r.from+d,to:r.to+d})}
function zoomRange(f){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r)return;const mid=(r.from+r.to)/2,w=clamp((r.to-r.from)*f,20,300);chart.timeScale().setVisibleLogicalRange({from:mid-w/2,to:mid+w/2})}
function wireNav(){const click=(id,fn)=>$(id)?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();fn()},{capture:true});click('tvPanOlder',()=>{shiftRange(-.72);setTimeout(scheduleOlder,0)});click('tvPanNewer',()=>shiftRange(.72));click('tvZoomOut',()=>zoomRange(1.25));click('tvZoomIn',()=>zoomRange(.8));click('tvReset',latestView);click('tvLive',latestView)}
function normalizePatch(p={}){if('atrLength'in p)C.atrLength=clamp(Math.floor(Number(p.atrLength)||C.atrLength),1,200);if('traditionalBox'in p)C.traditionalBox=Math.max(Number.EPSILON,Number(p.traditionalBox)||C.traditionalBox);if('percentage'in p)C.percentage=clamp(Number(p.percentage)||C.percentage,.000001,.1);if('source'in p&&SOURCES.has(p.source))C.source=p.source;if('resolution'in p&&RESOLUTIONS.has(p.resolution))C.resolution=p.resolution;if('wicks'in p)C.wicks=p.wicks!==false;if('confirmBricks'in p)C.confirmBricks=Number(p.confirmBricks)===1?1:2}
async function applySettings(method=C.method,patch={}){if(!METHODS.has(method))return false;const oldResolution=C.resolution,oldSource=C.source;C.method=method;normalizePatch(patch);save();mode();if(!S.symbol)return true;if(oldResolution!==C.resolution)return resetSymbol(S.symbol).then(()=>true);if(oldSource!==C.source)return rebuild(rangeAnchor());return rebuild(rangeAnchor())}
async function refreshLtpAndRebuild(){if(!S.symbol)return false;S.ltpSnapshot=await fetchLtp(S.symbol);return rebuild(rangeAnchor())}
function watchFeed(){const v=window.RWARenkoV3?.state;if(!v)return;const sym=String(v.selected||'');if(sym&&sym!==lastSymbol){lastSymbol=sym;void resetSymbol(sym);return}const t=v.historyTicks?.at?.(-1);if(t)updateCurrentFromTrade(t);const p=Number(v.lastPrice);if(Number.isFinite(p)){updateLiveLine(p);if(S.signal)evaluateSignal()}}
async function boot(){for(let i=0;i<300&&(!window.LightweightCharts||!window.RWARenkoV3);i++)await sleep(50);if(!window.LightweightCharts)throw Error('Lightweight Charts unavailable');if(!window.RWARenkoV3)throw Error('market feed unavailable');await applyRequestedSymbol();if(!createChart())throw Error('chart host unavailable');showChart();window.RWARenkoV14={version:'14.2.0',renderer:'tradingview-lightweight-charts-5.1',parityTarget:'TradingView documented Renko behavior',historicalConfirmation:'source-resolution-close',realtimeBehavior:'projection-until-source-bar-closes',sourceModes:['close','ohlc'],methods:['atr','traditional','percentage-ltp'],percentageRule:'symbol-load-ltp-fixed-across-bars',atrRule:'latest-completed-wilder-atr-snapshot-fixed-across-chart',wickRule:'discarded-source-extremes-directional',state:S,settings:C,applySettings,setMethod:(m,p)=>applySettings(m,p),setSource:s=>applySettings(C.method,{source:s}),setResolution:r=>applySettings(C.method,{resolution:r}),reloadPercentageLtp:refreshLtpAndRebuild,loadOlder,goLive:latestView};window.RWARenkoV12=window.RWARenkoV14;const initial=String(window.RWARenkoV3.state.selected||'BTCUSDT');lastSymbol=initial;await resetSymbol(initial);watchTimer=setInterval(watchFeed,80);refreshTimer=setInterval(refreshClosed,1000)}
boot().catch(e=>{console.error('[RENKO V14]',e);setStatus('Chart retry','bad')});
})();
