(()=>{
'use strict';
if(window.RWARenkoV7)return;
const $=id=>document.getElementById(id);
const COLORS={bg:'#131722',grid:'rgba(120,123,134,.16)',text:'#b2b5be',textStrong:'#d1d4dc',up:'#089981',down:'#f23645',axis:'#2a2e39',cross:'rgba(178,181,190,.65)',line:'#2962ff'};
const state={version:'7.0.0',mode:'tradingview-style-renderer',mx:null,my:null,inside:false,lastDraw:0,frames:0};
function fmtPrice(v){const n=Number(v);if(!Number.isFinite(n))return'—';const a=Math.abs(n);const d=a>=10000?2:a>=1000?2:a>=100?3:a>=1?4:a>=.01?6:8;return n.toLocaleString(undefined,{maximumFractionDigits:d});}
function fmtDate(ms,withTime=false){if(!Number(ms))return'—';const d=new Date(Number(ms));return withTime?d.toLocaleString(undefined,{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit'}):d.toLocaleDateString(undefined,{month:'short',day:'2-digit'});}
function visible(){const v=window.RWARenkoV6,s=v?.state;if(!s?.bricks?.length)return[];const end=Math.max(0,s.bricks.length-(s.offset||0)),start=Math.max(0,end-50);return s.bricks.slice(start,end);}
function ensure(){const wrap=$('chartWrap');if(!wrap)return null;let c=$('tvRenkoCanvas');if(!c){c=document.createElement('canvas');c.id='tvRenkoCanvas';c.setAttribute('aria-label','TradingView-style Traditional Renko renderer');Object.assign(c.style,{position:'absolute',inset:'0',width:'100%',height:'100%',zIndex:'7',pointerEvents:'none',background:COLORS.bg});wrap.appendChild(c);wrap.dataset.tvRenko='v7';wrap.addEventListener('pointermove',e=>{const r=wrap.getBoundingClientRect();state.mx=e.clientX-r.left;state.my=e.clientY-r.top;state.inside=true;draw();},{passive:true});wrap.addEventListener('pointerleave',()=>{state.inside=false;state.mx=state.my=null;draw();},{passive:true});}
return c;}
function niceRange(list){let lo=Infinity,hi=-Infinity;for(const b of list){lo=Math.min(lo,Number(b.open),Number(b.close));hi=Math.max(hi,Number(b.open),Number(b.close));}const live=Number(window.RWARenkoV3?.state?.lastPrice),v6=window.RWARenkoV6?.state;if((v6?.offset||0)===0&&Number.isFinite(live)){lo=Math.min(lo,live);hi=Math.max(hi,live);}if(!Number.isFinite(lo)||!Number.isFinite(hi)){lo=0;hi=1;}if(lo===hi){const p=Math.max(Math.abs(lo)*.005,1);lo-=p;hi+=p;}const pad=Math.max((hi-lo)*.08,Number(v6?.box||0)*.5||0);return{lo:lo-pad,hi:hi+pad};}
function rounded(ctx,x,y,w,h,r=3){const rr=Math.min(r,Math.abs(w)/2,Math.abs(h)/2);ctx.beginPath();ctx.roundRect(x,y,w,h,rr);}
function draw(){const v6=window.RWARenkoV6,s=v6?.state,c=ensure();if(!c||!s)return;if(s.mode==='live'||s.mode==='raw'){c.style.display='none';return;}c.style.display='block';const list=visible();if(!list.length)return;const wrap=$('chartWrap'),r=wrap.getBoundingClientRect(),dpr=Math.min(2,window.devicePixelRatio||1),w=Math.max(340,Math.floor(r.width)),h=Math.max(280,Math.floor(r.height));if(c.width!==Math.floor(w*dpr)||c.height!==Math.floor(h*dpr)){c.width=Math.floor(w*dpr);c.height=Math.floor(h*dpr);}const x=c.getContext('2d');x.setTransform(dpr,0,0,dpr,0,0);x.clearRect(0,0,w,h);x.fillStyle=COLORS.bg;x.fillRect(0,0,w,h);
const m={l:16,r:78,t:28,b:34},cw=w-m.l-m.r,ch=h-m.t-m.b,{lo,hi}=niceRange(list),span=hi-lo,y=p=>m.t+(hi-p)/span*ch;
// Trading terminal grid.
x.strokeStyle=COLORS.grid;x.lineWidth=1;for(let i=0;i<=5;i++){const yy=m.t+ch*i/5;x.beginPath();x.moveTo(m.l,yy+.5);x.lineTo(w-m.r,yy+.5);x.stroke();}for(let i=0;i<=6;i++){const xx=m.l+cw*i/6;x.beginPath();x.moveTo(xx+.5,m.t);x.lineTo(xx+.5,h-m.b);x.stroke();}
// Right price scale.
x.fillStyle=COLORS.bg;x.fillRect(w-m.r,0,m.r,h);x.strokeStyle=COLORS.axis;x.beginPath();x.moveTo(w-m.r+.5,0);x.lineTo(w-m.r+.5,h);x.stroke();x.font='11px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';x.textBaseline='middle';for(let i=0;i<=5;i++){const p=hi-span*i/5,yy=m.t+ch*i/5;x.fillStyle=COLORS.text;x.fillText(fmtPrice(p),w-m.r+8,yy);}
// Bottom time scale.
x.fillStyle=COLORS.bg;x.fillRect(0,h-m.b,w,m.b);x.strokeStyle=COLORS.axis;x.beginPath();x.moveTo(0,h-m.b+.5);x.lineTo(w,h-m.b+.5);x.stroke();x.textBaseline='top';x.fillStyle=COLORS.text;const ticks=Math.min(6,Math.max(2,Math.floor(cw/150)));for(let i=0;i<ticks;i++){const idx=Math.round(i*(list.length-1)/(ticks-1)),xx=m.l+(idx+.5)*cw/list.length;x.fillText(fmtDate(list[idx]?.time),Math.max(2,Math.min(w-m.r-46,xx-20)),h-m.b+9);}
// Renko bricks: equal fixed-box geometry, contiguous horizontal sequence.
const step=cw/list.length,bw=Math.max(4,Math.min(22,step*.86));list.forEach((b,i)=>{const xx=m.l+(i+.5)*step,yo=y(Number(b.open)),yc=y(Number(b.close)),top=Math.min(yo,yc),bh=Math.max(2,Math.abs(yc-yo)),up=Number(b.direction)>=0;x.fillStyle=up?COLORS.up:COLORS.down;x.strokeStyle=up?'#22ab94':'#f7525f';x.lineWidth=1;rounded(x,xx-bw/2,top,bw,bh,1.5);x.fill();x.stroke();});
// Last market price is venue price, not a synthetic fill.
const live=Number(window.RWARenkoV3?.state?.lastPrice);if((s.offset||0)===0&&Number.isFinite(live)){const yy=y(live);if(yy>=m.t&&yy<=h-m.b){x.setLineDash([4,4]);x.strokeStyle=COLORS.line;x.beginPath();x.moveTo(m.l,yy+.5);x.lineTo(w-m.r,yy+.5);x.stroke();x.setLineDash([]);const label=fmtPrice(live);x.font='600 11px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';const tw=x.measureText(label).width+14;x.fillStyle=COLORS.line;rounded(x,w-m.r+2,yy-10,Math.min(m.r-4,tw),20,3);x.fill();x.fillStyle='#fff';x.textBaseline='middle';x.fillText(label,w-m.r+8,yy);}}
// Crosshair + hover brick detail, TradingView-style interaction.
if(state.inside&&state.mx!=null&&state.my!=null&&state.mx>=m.l&&state.mx<=w-m.r&&state.my>=m.t&&state.my<=h-m.b){const cx=state.mx,cy=state.my;x.setLineDash([3,3]);x.strokeStyle=COLORS.cross;x.beginPath();x.moveTo(cx+.5,m.t);x.lineTo(cx+.5,h-m.b);x.moveTo(m.l,cy+.5);x.lineTo(w-m.r,cy+.5);x.stroke();x.setLineDash([]);const hp=hi-(cy-m.t)/ch*span,idx=Math.max(0,Math.min(list.length-1,Math.floor((cx-m.l)/step))),b=list[idx];const pl=fmtPrice(hp);x.font='11px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';x.fillStyle='#363a45';rounded(x,w-m.r+2,cy-10,m.r-4,20,3);x.fill();x.fillStyle='#fff';x.textBaseline='middle';x.fillText(pl,w-m.r+7,cy);const date=fmtDate(b?.time,true),dw=Math.min(150,Math.max(76,x.measureText(date).width+14));x.fillStyle='#363a45';rounded(x,Math.max(0,Math.min(w-m.r-dw,cx-dw/2)),h-m.b+2,dw,22,3);x.fill();x.fillStyle='#fff';x.textBaseline='middle';x.fillText(date,Math.max(7,Math.min(w-m.r-dw+7,cx-dw/2+7)),h-m.b+13);const title=`${b?.direction>=0?'UP':'DOWN'}  O ${fmtPrice(b?.open)}  C ${fmtPrice(b?.close)}`;x.fillStyle='rgba(19,23,34,.88)';rounded(x,m.l+8,m.t+7,Math.min(cw-16,Math.max(235,x.measureText(title).width+20)),28,4);x.fill();x.fillStyle=COLORS.textStrong;x.font='600 11px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';x.textBaseline='middle';x.fillText(title,m.l+17,m.t+21);}
// Header inside plotting area.
x.fillStyle=COLORS.textStrong;x.font='600 12px -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif';x.textBaseline='alphabetic';x.fillText(`${s.symbol||''} · RENKO · Traditional · Box ${fmtPrice(s.box)}`,m.l+6,17);state.lastDraw=performance.now();state.frames++;}
function loop(){draw();setTimeout(loop,180);}
function init(){const wrap=$('chartWrap');if(!wrap||!window.RWARenkoV6){setTimeout(init,60);return;}ensure();draw();loop();window.RWARenkoV7={...state,draw,get state(){return state;},renderer:'tv-like-price-time-crosshair-v1',traditional:{continuationBoxes:1,reversalBoxes:2},history:'delegated-to-v61-lazy',live:'delegated-to-individual-@trade'};}
init();
})();
