(()=>{
'use strict';
if(window.RWARenkoV12)return;
const $=id=>document.getElementById(id);
const RESTS=['https://data-api.binance.vision','https://api.binance.com'];
const PAGE=1000,FIRST_VIEW=60,MAX_TICKS=150000,STORE='rwa_renko_v12_settings';
const METHODS=new Set(['atr','traditional','percentage']);
const now=()=>Date.now(),sleep=ms=>new Promise(r=>setTimeout(r,ms)),clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fmt=n=>{n=Number(n);if(!Number.isFinite(n))return'—';const a=Math.abs(n),d=a>=1000?2:a>=100?3:a>=1?4:a>=.01?6:8;return n.toLocaleString(undefined,{maximumFractionDigits:d})};
const fmtDate=ms=>Number(ms)?new Date(Number(ms)).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'}):'—';
const C={method:'atr',atrLength:14,traditionalBox:100,percentage:.01,wicks:true,confirmBricks:2};
try{Object.assign(C,JSON.parse(localStorage.getItem(STORE)||'{}')||{})}catch{}
if(!METHODS.has(C.method))C.method='atr';C.atrLength=clamp(Math.floor(Number(C.atrLength)||14),1,200);C.traditionalBox=Math.max(Number.EPSILON,Number(C.traditionalBox)||100);C.percentage=clamp(Number(C.percentage)||.01,.00001,.1);C.wicks=C.wicks!==false;C.confirmBricks=Number(C.confirmBricks)===1?1:2;
const S={version:'12.0.0',generation:0,symbol:'',tickSize:NaN,ltpSnapshot:NaN,atrBox:NaN,box:NaN,ticks:[],bricks:[],data:[],tailState:null,buildSeq:0,loading:false,building:false,exhausted:false,oldestAggId:null,lastHistoryTime:0,lastLiveId:null,lastLiveTime:0,following:true,signal:null};
let chart=null,series=null,liveLine=null,worker=null,resizeObserver=null,watchTimer=0,rangeTimer=0,metaFrame=0,lastSymbol='';
function save(){try{localStorage.setItem(STORE,JSON.stringify(C))}catch{}}
function setText(id,text){const e=$(id);if(e)e.textContent=text}
function setStatus(text,kind='ready'){const e=$('tvLoadState');if(e){e.textContent=text;e.dataset.kind=kind}const l=$('tvLoading');if(l)l.hidden=kind!=='loading'}
function methodName(m=C.method){return m==='atr'?'ATR':m==='traditional'?'TRADITIONAL':'PERCENTAGE (LTP)'}
function mode(){setText('modePill',`${methodName()} · TICK · V12`);setText('sourceText','Tick-native Renko · every Binance trade can lock one or many bricks immediately · no candle-close interval.')}
function queueMeta(){if(metaFrame)return;metaFrame=requestAnimationFrame(()=>{metaFrame=0;meta()})}
function meta(){const r=chart?.timeScale?.().getVisibleLogicalRange?.(),width=r?Math.max(1,Math.round(r.to-r.from)):FIRST_VIEW;setText('tvZoomValue',String(width));setText('tvBrickMeta',`${Math.min(width,S.data.length)} visible · ${S.data.length.toLocaleString()} confirmed`);setText('tvCoverage',S.ticks.length?`${fmtDate(S.ticks[0]?.time)} → LIVE TICK`:'Preparing trade history');setText('brickValue',fmt(S.box));setText('brickCount',S.data.length.toLocaleString());setText('v11MethodLabel',methodName());setText('v11CurrentBox',fmt(S.box));setText('v11AtrNow',Number.isFinite(S.atrBox)?fmt(S.atrBox):'—');setText('v12LtpSnapshot',fmt(S.ltpSnapshot));setText('v11TickSize',fmt(S.tickSize))}
async function fetchJson(path,timeout=12000){const attempts=RESTS.map(root=>new Promise(async(resolve,reject)=>{const c=new AbortController(),tm=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(root+path,{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);resolve(await r.json())}catch(e){reject(e)}finally{clearTimeout(tm)}}));try{return await Promise.any(attempts)}catch(e){throw e?.errors?.at?.(-1)||e||Error('market data unavailable')}}
async function fetchTickSize(symbol){try{const j=await fetchJson(`/api/v3/exchangeInfo?symbol=${encodeURIComponent(symbol)}`),pf=j?.symbols?.[0]?.filters?.find?.(f=>f.filterType==='PRICE_FILTER'),t=Number(pf?.tickSize);if(t>0)return t}catch(e){console.warn('[V12 tick]',e)}return .00000001}
async function fetchLtp(symbol){try{const j=await fetchJson(`/api/v3/ticker/price?symbol=${encodeURIComponent(symbol)}`),p=Number(j?.price);if(Number.isFinite(p)&&p>0)return p}catch(e){console.warn('[V12 LTP]',e)}const p=Number(window.RWARenkoV3?.state?.lastPrice);return Number.isFinite(p)?p:NaN}
function wilderAtr(rows,len){const tr=[];let prev=NaN;for(const r of rows||[]){const h=Number(r?.[2]),l=Number(r?.[3]),c=Number(r?.[4]);if(![h,l,c].every(Number.isFinite))continue;tr.push(Number.isFinite(prev)?Math.max(h-l,Math.abs(h-prev),Math.abs(l-prev)):h-l);prev=c}if(!tr.length)return NaN;len=Math.max(1,Math.floor(Number(len)||14));if(tr.length<len)return tr.reduce((a,b)=>a+b,0)/tr.length;let a=tr.slice(0,len).reduce((x,y)=>x+y,0)/len;for(let i=len;i<tr.length;i++)a=((a*(len-1))+tr[i])/len;return a}
async function fetchAtrBox(symbol){try{const rows=await fetchJson(`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=1m&limit=${Math.max(60,C.atrLength+30)}`),t=now(),closed=(Array.isArray(rows)?rows:[]).filter(r=>Number(r?.[6]||0)<t);return wilderAtr(closed,C.atrLength)}catch(e){console.warn('[V12 ATR sizing]',e);return NaN}}
function mapAgg(rows){return(Array.isArray(rows)?rows:[]).map(x=>({id:Number(x.a),price:Number(x.p),qty:Number(x.q)||0,time:Number(x.T),kind:'agg'})).filter(x=>Number.isFinite(x.id)&&Number.isFinite(x.price)&&Number.isFinite(x.time)).sort((a,b)=>a.id-b.id)}
function dedupeTicks(rows){const m=new Map();for(const t of rows||[]){if(!Number.isFinite(Number(t?.price))||!Number.isFinite(Number(t?.time)))continue;const k=`${t.kind||'x'}:${t.id??''}:${t.time}:${t.price}`;m.set(k,t)}return[...m.values()].sort((a,b)=>(Number(a.time)-Number(b.time))||((Number(a.id)||0)-(Number(b.id)||0)))}
async function latestAgg(symbol){return mapAgg(await fetchJson(`/api/v3/aggTrades?symbol=${encodeURIComponent(symbol)}&limit=${PAGE}`,15000))}
async function olderAgg(symbol,fromId){return mapAgg(await fetchJson(`/api/v3/aggTrades?symbol=${encodeURIComponent(symbol)}&fromId=${Math.max(0,Math.floor(fromId))}&limit=${PAGE}`,15000))}
function ensureWorker(){if(worker)return worker;worker=new Worker('renko-v12-worker.js?v=120');return worker}
function normalizeAll(bricks){let t=0;return(bricks||[]).map((b,i)=>{let tm=Math.max(1,Math.floor(Number(b.time||0)/1000));if(tm<=t)tm=t+1;t=tm;const o=Number(b.open),c=Number(b.close),h=Number(b.high),l=Number(b.low),d=Number(b.direction)||0;return{time:tm,open:o,high:Number.isFinite(h)?Math.max(h,o,c):Math.max(o,c),low:Number.isFinite(l)?Math.min(l,o,c):Math.min(o,c),close:c,color:d>0?'#089981':'#f23645',borderColor:d>0?'#089981':'#f23645',wickColor:d>0?'#089981':'#f23645',_dir:d,_reversal:!!b.isReversal,_box:Number(b.box),_ms:Number(b.time||0),_i:i}})}
function rangeAnchor(){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r||!S.data.length)return null;const i=clamp(Math.floor(r.from),0,S.data.length-1),d=S.data[i];return{range:r,index:i,time:d?.time,close:d?.close}}
function restoreAnchor(a){if(!a||!chart||!S.data.length)return;let i=S.data.findIndex(d=>d.time===a.time&&Math.abs(Number(d.close)-Number(a.close))<Math.max(1e-10,Math.abs(Number(a.close))*1e-9));if(i<0)i=S.data.findIndex(d=>d.time>=a.time);if(i<0)return;const sh=i-a.index;chart.timeScale().setVisibleLogicalRange({from:a.range.from+sh,to:a.range.to+sh})}
function rebuild(anchor=null){if(!S.ticks.length||!(S.tickSize>0))return Promise.resolve(false);const generation=S.generation,id=++S.buildSeq,ticks=S.ticks.slice();S.building=true;setStatus('Building tick Renko…','loading');return new Promise((resolve,reject)=>{const w=ensureWorker(),on=e=>{const m=e.data||{};if((m.type!=='built'&&m.type!=='error')||m.id!==id)return;w.removeEventListener('message',on);if(generation!==S.generation){resolve(false);return}S.building=false;if(m.type==='error'){reject(Error(m.message||'worker error'));return}S.bricks=Array.isArray(m.bricks)?m.bricks:[];S.data=normalizeAll(S.bricks);S.box=Number(m.box);S.tailState=m.tailState||null;series?.setData(S.data);showChart();restoreAnchor(anchor);if(S.following)latestView();setStatus('LIVE · every trade locks','ready');evaluateSignal();meta();resolve(true)};w.addEventListener('message',on);try{w.postMessage({type:'build',id,generation,method:C.method,traditionalBox:C.traditionalBox,percentage:C.percentage,atrBox:S.atrBox,ltpSnapshot:S.ltpSnapshot,tickSize:S.tickSize,wicks:C.wicks,ticks})}catch(e){w.removeEventListener('message',on);S.building=false;reject(e)}})}
function showChart(){const e=$('chartEmpty');if(e)e.classList.add('hide');const h=$('lwcRenkoHost');if(h)h.style.visibility='visible'}
function latestView(){if(!chart||!S.data.length)return;const n=S.data.length;chart.timeScale().setVisibleLogicalRange({from:Math.max(0,n-FIRST_VIEW),to:n+5});S.following=true;meta()}
function cloneTail(s){return s?{lastClose:Number(s.lastClose),direction:Number(s.direction)||0,pendingHigh:Number(s.pendingHigh),pendingLow:Number(s.pendingLow),anchor:Number(s.anchor),lastTime:Number(s.lastTime)||0}:null}
function touch(st,p){if(!Number.isFinite(st.pendingHigh))st.pendingHigh=p;if(!Number.isFinite(st.pendingLow))st.pendingLow=p;if(p>st.pendingHigh)st.pendingHigh=p;if(p<st.pendingLow)st.pendingLow=p}
function emit(st,out,open,close,dir,t,rev){let high=Math.max(open,close),low=Math.min(open,close);if(C.wicks){if(dir>0)low=Math.min(low,st.pendingLow);else high=Math.max(high,st.pendingHigh)}out.push({time:t,open,high,low,close,direction:dir,box:S.box,isReversal:!!rev});st.lastClose=close;st.direction=dir;st.lastTime=t;st.pendingHigh=close;st.pendingLow=close}
function processLive(st,tick){const p=Number(tick.price),t=Number(tick.time)||now(),out=[];if(!st||!Number.isFinite(p)||!(S.box>0))return out;touch(st,p);let g=0;while(g++<10000){const lc=st.lastClose,d=st.direction,b=S.box;if(d===0){if(p>=lc+b){emit(st,out,lc,lc+b,1,t,false);continue}if(p<=lc-b){emit(st,out,lc,lc-b,-1,t,false);continue}break}if(d>0){if(p>=lc+b){emit(st,out,lc,lc+b,1,t,false);continue}if(p<=lc-2*b){emit(st,out,lc-b,lc-2*b,-1,t,true);continue}break}if(p<=lc-b){emit(st,out,lc,lc-b,-1,t,false);continue}if(p>=lc+2*b){emit(st,out,lc+b,lc+2*b,1,t,true);continue}break}touch(st,p);return out}
function normalizeOne(b){const prev=Number(S.data.at(-1)?.time||0);let t=Math.max(1,Math.floor(Number(b.time||0)/1000));if(t<=prev)t=prev+1;const o=Number(b.open),c=Number(b.close),d=Number(b.direction)||0;return{time:t,open:o,high:Math.max(Number(b.high),o,c),low:Math.min(Number(b.low),o,c),close:c,color:d>0?'#089981':'#f23645',borderColor:d>0?'#089981':'#f23645',wickColor:d>0?'#089981':'#f23645',_dir:d,_reversal:!!b.isReversal,_box:S.box,_ms:Number(b.time||0),_i:S.data.length}}
function updateLiveLine(p){if(!series||!Number.isFinite(p))return;if(liveLine){try{liveLine.applyOptions({price:p})}catch{}}else{try{liveLine=series.createPriceLine({price:p,color:'#2962ff',lineWidth:1,lineStyle:2,axisLabelVisible:true,title:'REAL'})}catch{}}}
function appendLiveTick(t){if(S.building||S.loading||!S.tailState||!S.data.length)return;const id=Number(t?.id),tm=Number(t?.time),p=Number(t?.price);if(!Number.isFinite(p)||!Number.isFinite(tm))return;if(Number.isFinite(id)&&id===S.lastLiveId&&tm===S.lastLiveTime)return;if(tm<S.lastHistoryTime)return;S.lastLiveId=Number.isFinite(id)?id:S.lastLiveId;S.lastLiveTime=tm;S.ticks.push({id:Number.isFinite(id)?id:null,price:p,qty:Number(t.qty)||0,time:tm,kind:'live'});if(S.ticks.length>MAX_TICKS)S.ticks.splice(0,S.ticks.length-MAX_TICKS);const formed=processLive(S.tailState,{id,price:p,time:tm});for(const b of formed){S.bricks.push(b);const d=normalizeOne(b);S.data.push(d);series?.update(d)}updateLiveLine(p);if(formed.length){if(S.following)latestView();evaluateSignal();setStatus(`LIVE · ${formed.length} brick${formed.length>1?'s':''} locked on trade`,'ready')}meta()}
async function loadOlder(){if(S.loading||S.exhausted||!Number.isFinite(S.oldestAggId)||S.oldestAggId<=0)return false;const generation=S.generation,symbol=S.symbol,anchor=rangeAnchor(),oldest=S.oldestAggId;S.loading=true;setStatus('Loading older trade history…','loading');try{const from=Math.max(0,oldest-PAGE),rows=(await olderAgg(symbol,from)).filter(x=>x.id<oldest);if(generation!==S.generation||symbol!==S.symbol)return false;if(!rows.length){S.exhausted=true;return false}S.oldestAggId=Math.min(...rows.map(x=>x.id));S.ticks=dedupeTicks([...rows,...S.ticks]);await rebuild(anchor);return true}catch(e){console.warn('[V12 older]',e);setStatus('Trade history retry','bad');return false}finally{if(generation===S.generation)S.loading=false}}
function scheduleOlder(){clearTimeout(rangeTimer);rangeTimer=setTimeout(()=>{const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(r&&r.from<20&&!S.loading&&!S.building&&!S.exhausted)void loadOlder()},160)}
async function resetSymbol(symbol){const generation=++S.generation;S.symbol=symbol;S.tickSize=NaN;S.ltpSnapshot=NaN;S.atrBox=NaN;S.box=NaN;S.ticks=[];S.bricks=[];S.data=[];S.tailState=null;S.loading=false;S.building=false;S.exhausted=false;S.oldestAggId=null;S.lastHistoryTime=0;S.lastLiveId=null;S.lastLiveTime=0;S.signal=null;series?.setData([]);if(liveLine){try{series.removePriceLine(liveLine)}catch{}liveLine=null}mode();setStatus('Connecting raw trade history…','loading');try{const [tick,ltp,atr,rows]=await Promise.all([fetchTickSize(symbol),fetchLtp(symbol),fetchAtrBox(symbol),latestAgg(symbol)]);if(generation!==S.generation)return;S.tickSize=tick;S.ltpSnapshot=ltp;S.atrBox=atr;if(rows.length){S.ticks=rows;S.oldestAggId=rows[0].id;S.lastHistoryTime=rows.at(-1).time;await rebuild();let rounds=0;while(generation===S.generation&&S.data.length<FIRST_VIEW&&!S.exhausted&&rounds++<5){if(!await loadOlder())break}}else{const raw=window.RWARenkoV3?.state?.historyTicks||[];S.ticks=raw.map(x=>({...x,kind:'live'}));S.lastHistoryTime=0;if(S.ticks.length)await rebuild()}if(generation!==S.generation)return;if(S.data.length){latestView();setStatus('LIVE · every trade locks','ready')}else setStatus('Waiting for threshold trade…','ready');meta()}catch(e){console.error('[V12 boot symbol]',e);const raw=window.RWARenkoV3?.state?.historyTicks||[];S.ticks=raw.map(x=>({...x,kind:'live'}));if(S.ticks.length&&S.tickSize>0)await rebuild();setStatus(S.data.length?'LIVE · fallback raw ticks':'Feed retry','bad')}}
function deriveSignal(){const a=S.data;if(a.length<3)return{position:'flat',action:'WAIT',reason:'Need more confirmed tick bricks'};const confirm=C.confirmBricks;let position='flat',entry=NaN,entryBox=NaN,lastEvent='WAIT',eventIndex=-1;for(let i=1;i<a.length;i++){const d=Number(a[i]._dir),prev=Number(a[i-1]._dir);if(position==='long'&&d<0){position='flat';lastEvent='EXIT LONG · tick reversal';eventIndex=i;continue}if(position==='short'&&d>0){position='flat';lastEvent='EXIT SHORT · tick reversal';eventIndex=i;continue}if(position!=='flat')continue;if(confirm===1){if(prev<0&&d>0){position='long';entry=Number(a[i].close);entryBox=S.box;lastEvent='BUY READY · tick reversal';eventIndex=i}else if(prev>0&&d<0){position='short';entry=Number(a[i].close);entryBox=S.box;lastEvent='SELL READY · tick reversal';eventIndex=i}}else if(i>=2){const p2=Number(a[i-2]._dir);if(p2<0&&prev>0&&d>0){position='long';entry=Number(a[i].close);entryBox=S.box;lastEvent='BUY READY · reversal + 1';eventIndex=i}else if(p2>0&&prev<0&&d<0){position='short';entry=Number(a[i].close);entryBox=S.box;lastEvent='SELL READY · reversal + 1';eventIndex=i}}}const market=Number(window.RWARenkoV3?.state?.lastPrice),close=Number(a.at(-1)?.close);let hard=NaN,trail=NaN,action=lastEvent,reason='Signals use immediately confirmed tick bricks. No interval-close delay.';if(position==='long'){hard=entry-2*entryBox;trail=close-S.box;if(Number.isFinite(market)&&market<=hard){action='EXIT NOW · real market hard stop';reason='Real price crossed hard stop.'}else if(eventIndex<a.length-1)action='LONG ACTIVE'}else if(position==='short'){hard=entry+2*entryBox;trail=close+S.box;if(Number.isFinite(market)&&market>=hard){action='EXIT NOW · real market hard stop';reason='Real price crossed hard stop.'}else if(eventIndex<a.length-1)action='SHORT ACTIVE'}else if(!lastEvent.startsWith('EXIT'))action='WAIT';return{position,action,entry,hard,trail,reason}}
function evaluateSignal(){S.signal=deriveSignal();const x=S.signal,age=now()-Number(window.RWARenkoV3?.state?.lastTickTime||0),fresh=age<5000;setText('signalAction',x.action);setText('signalPosition',x.position.toUpperCase());setText('signalEntry',fmt(x.entry));setText('signalMarket',fmt(Number(window.RWARenkoV3?.state?.lastPrice)));setText('signalHardStop',fmt(x.hard));setText('signalTrail',fmt(x.trail));setText('signalReason',x.reason);setText('signalFreshness',fresh?`LIVE ${Math.max(0,age)} ms`:`STALE ${Math.floor(age/1000)} s`);const e=$('signalAction');if(e)e.dataset.kind=x.action.includes('EXIT')?'exit':x.action.includes('BUY')?'buy':x.action.includes('SELL')?'sell':x.position==='long'?'buy':x.position==='short'?'sell':'wait';const f=$('signalFreshness');if(f)f.dataset.kind=fresh?'live':'stale'}
function createChart(){const wrap=$('chartWrap'),L=window.LightweightCharts;if(!wrap||!L)return false;let host=$('lwcRenkoHost');if(!host){host=document.createElement('div');host.id='lwcRenkoHost';host.setAttribute('aria-label','RENKO V12 tick-native chart');wrap.prepend(host)}chart=L.createChart(host,{localization:{locale:'en-US'},layout:{background:{type:L.ColorType?.Solid??'solid',color:'#131722'},textColor:'#b2b5be',attributionLogo:true},grid:{vertLines:{color:'rgba(120,123,134,.14)'},horzLines:{color:'rgba(120,123,134,.14)'}},rightPriceScale:{borderColor:'#2a2e39',minimumWidth:64,scaleMargins:{top:.04,bottom:.05}},timeScale:{borderColor:'#2a2e39',timeVisible:true,secondsVisible:true,rightOffset:8,barSpacing:10,minBarSpacing:2,maxBarSpacing:30,lockVisibleTimeRangeOnResize:true},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true,vertTouchDrag:true},handleScale:{mouseWheel:true,pinch:true,axisPressedMouseMove:{time:true,price:true},axisDoubleClickReset:{time:true,price:true}},kineticScroll:{mouse:true,touch:true},crosshair:{mode:L.CrosshairMode?.Normal??0}});series=chart.addSeries(L.CandlestickSeries,{upColor:'#089981',downColor:'#f23645',borderUpColor:'#089981',borderDownColor:'#f23645',wickUpColor:'#089981',wickDownColor:'#f23645',priceLineVisible:false,lastValueVisible:true});chart.timeScale().subscribeVisibleLogicalRangeChange?.(r=>{if(r&&S.data.length)S.following=r.to>=S.data.length-1;queueMeta();scheduleOlder()});resizeObserver=new ResizeObserver(entries=>{const r=entries[0]?.contentRect;if(r?.width&&r?.height)chart.resize(Math.floor(r.width),Math.floor(r.height))});resizeObserver.observe(wrap);wireNav();return true}
function shiftRange(frac){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r)return;const w=r.to-r.from,d=w*frac;chart.timeScale().setVisibleLogicalRange({from:r.from+d,to:r.to+d})}
function zoomRange(f){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r)return;const mid=(r.from+r.to)/2,w=clamp((r.to-r.from)*f,20,300);chart.timeScale().setVisibleLogicalRange({from:mid-w/2,to:mid+w/2})}
function wireNav(){const click=(id,fn)=>$(id)?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();fn()},{capture:true});click('tvPanOlder',()=>shiftRange(-.72));click('tvPanNewer',()=>shiftRange(.72));click('tvZoomOut',()=>zoomRange(1.25));click('tvZoomIn',()=>zoomRange(.8));click('tvReset',latestView);click('tvLive',latestView)}
function syncForm(){document.querySelectorAll('[data-renko-method]').forEach(b=>b.classList.toggle('active',b.dataset.renkoMethod===C.method));const set=(id,v)=>{const e=$(id);if(e)e.value=String(v)};set('brickSize',C.traditionalBox);set('v11AtrLength',C.atrLength);set('v11Percent',C.percentage*100);if($('v11Wicks'))$('v11Wicks').checked=!!C.wicks;if($('v11Confirm'))$('v11Confirm').value=String(C.confirmBricks);document.querySelectorAll('[data-method-fields]').forEach(e=>e.hidden=e.dataset.methodFields!==C.method);mode();meta()}
function readForm(){C.traditionalBox=Math.max(Number.EPSILON,Number($('brickSize')?.value)||C.traditionalBox);C.atrLength=clamp(Math.floor(Number($('v11AtrLength')?.value)||14),1,200);C.percentage=clamp((Number($('v11Percent')?.value)||1)/100,.00001,.1);C.wicks=!!$('v11Wicks')?.checked;C.confirmBricks=Number($('v11Confirm')?.value)===1?1:2;save()}
async function applyMethod(method){if(!METHODS.has(method))return;C.method=method;save();syncForm();if(S.symbol){if(method==='atr')S.atrBox=await fetchAtrBox(S.symbol);if(method==='percentage')S.ltpSnapshot=await fetchLtp(S.symbol);await rebuild(rangeAnchor());latestView()}}
function wireSettings(){document.querySelectorAll('[data-renko-method]').forEach(b=>b.addEventListener('click',()=>void applyMethod(b.dataset.renkoMethod)));$('v11Apply')?.addEventListener('click',async()=>{readForm();if(C.method==='atr')S.atrBox=await fetchAtrBox(S.symbol);if(C.method==='percentage')S.ltpSnapshot=await fetchLtp(S.symbol);await rebuild(rangeAnchor());latestView();syncForm()});$('v11Wicks')?.addEventListener('change',async()=>{readForm();await rebuild(rangeAnchor());if(S.following)latestView();syncForm()});$('v11Confirm')?.addEventListener('change',()=>{readForm();evaluateSignal()})}
function watchTick(){const v=window.RWARenkoV3?.state;if(!v)return;const sym=String(v.selected||'');if(sym&&sym!==lastSymbol){lastSymbol=sym;void resetSymbol(sym);return}const t=v.historyTicks?.at?.(-1);if(t)appendLiveTick(t);const p=Number(v.lastPrice);if(Number.isFinite(p)){updateLiveLine(p);if(S.signal)evaluateSignal()}}
async function boot(){for(let i=0;i<240&&(!window.LightweightCharts||!window.RWARenkoV3);i++)await sleep(50);if(!window.LightweightCharts)throw Error('Lightweight Charts unavailable');if(!window.RWARenkoV3)throw Error('Renko trade feed unavailable');if(!createChart())throw Error('chart host unavailable');wireSettings();syncForm();showChart();window.RWARenkoV12={version:'12.0.0',renderer:'tradingview-lightweight-charts-5.1',formation:'tick-by-tick',lockRule:'every-trade-threshold',continuationBoxes:1,reversalBoxes:2,historicalSource:'binance-public-aggTrades',liveSource:'binance-individual-@trade',wickSource:'actual-trade-extremes',atrRole:'box-sizing-only-1m-calibration',state:S,settings:C,setMethod:applyMethod,loadOlder,goLive:latestView};const initial=String(window.RWARenkoV3.state.selected||'BTCUSDT');lastSymbol=initial;await resetSymbol(initial);watchTimer=setInterval(watchTick,50)}
boot().catch(e=>{console.error('[Renko V12]',e);setStatus('Chart retry','bad')});
})();
