(()=>{
'use strict';
if(window.RWARenkoV11)return;

const $=id=>document.getElementById(id);
const RESTS=['https://data-api.binance.vision','https://api.binance.com'];
const PAGE=1000,BATCH=4,FIRST_VIEW=60;
const STORE='rwa_renko_v11_settings',BAR_CACHE='rwa_renko_v11_bars_';
const METHODS=new Set(['atr','traditional','percentage']);
const SOURCES=new Set(['close','ohlc']);
const INTERVALS={'1m':60000,'3m':180000,'5m':300000,'15m':900000,'30m':1800000,'1h':3600000,'4h':14400000,'1d':86400000};
const now=()=>Date.now();
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fmt=n=>{n=Number(n);if(!Number.isFinite(n))return'—';const a=Math.abs(n),d=a>=1000?2:a>=100?3:a>=1?4:a>=.01?6:8;return n.toLocaleString(undefined,{maximumFractionDigits:d})};
const fmtDate=ms=>Number(ms)?new Date(Number(ms)).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'}):'—';
const intervalMs=()=>INTERVALS[C.interval]||60000;

const C={method:'atr',source:'close',interval:'1m',atrLength:14,traditionalBox:100,percentage:.01,wicks:true,projection:true,confirmBricks:2};
try{Object.assign(C,JSON.parse(localStorage.getItem(STORE)||'{}')||{})}catch{}
if(!METHODS.has(C.method))C.method='atr';if(!SOURCES.has(C.source))C.source='close';if(!INTERVALS[C.interval])C.interval='1m';
C.atrLength=clamp(Math.floor(Number(C.atrLength)||14),1,200);C.traditionalBox=Math.max(Number.EPSILON,Number(C.traditionalBox)||100);C.percentage=clamp(Number(C.percentage)||.01,.00001,.1);C.wicks=C.wicks!==false;C.projection=C.projection!==false;C.confirmBricks=Number(C.confirmBricks)===1?1:2;

const S={version:'11.0.0',generation:0,symbol:'',method:C.method,source:C.source,interval:C.interval,tickSize:NaN,box:NaN,atr:NaN,bars:[],bricks:[],data:[],tailState:null,loading:false,building:false,booting:false,exhausted:false,following:true,latestClosedTime:0,buildSeq:0,loadSeq:0,lastRefreshAt:0,historyAbort:null,signal:null,projectionPrice:NaN,projState:null,projBricks:[],projLastId:null,projLastTime:0};
let chart=null,series=null,projectionSeries=null,liveLine=null,worker=null,resizeObserver=null;let rangeTimer=0,watchTimer=0,barTimer=0,lastSymbol='',metaFrame=0;

function saveSettings(){try{localStorage.setItem(STORE,JSON.stringify(C))}catch{}}
function setText(id,text){const e=$(id);if(e)e.textContent=text}
function setStatus(text,kind='ready'){const e=$('tvLoadState');if(e){e.textContent=text;e.dataset.kind=kind}const l=$('tvLoading');if(l)l.hidden=kind!=='loading'}
function methodName(m=S.method){return m==='atr'?'ATR':m==='traditional'?'TRADITIONAL':'PERCENTAGE (LTP)'}
function sourceName(){return C.source==='ohlc'?'OHLC':'CLOSE'}
function setModePill(){setText('modePill',`${methodName()} · ${sourceName()} · ${C.interval} · V11`);setText('sourceText',`TradingView-rule parity · Source ${sourceName()} · ${C.interval} · completed interval bricks locked; live trades are projection only.`);}
function queueMeta(){if(metaFrame)return;metaFrame=requestAnimationFrame(()=>{metaFrame=0;setMeta()})}
function setMeta(){const r=chart?.timeScale?.().getVisibleLogicalRange?.(),width=r?Math.max(1,Math.round(r.to-r.from)):FIRST_VIEW;setText('tvZoomValue',String(width));setText('tvBrickMeta',`${Math.min(width,S.data.length)} visible · ${S.data.length.toLocaleString()} locked`);setText('tvCoverage',S.bars.length?`${fmtDate(S.bars[0]?.[0])} → live`:'Preparing history');setText('brickValue',fmt(S.box));setText('brickCount',S.data.length.toLocaleString());setText('v11MethodLabel',methodName());setText('v11CurrentBox',fmt(S.box));setText('v11AtrNow',Number.isFinite(S.atr)?fmt(S.atr):'—');setText('v11SourceLabel',sourceName());setText('v11IntervalLabel',C.interval);setText('v11TickSize',fmt(S.tickSize));}

async function fetchJson(path,timeout=12000,signal){
  if(signal?.aborted)throw new DOMException('Aborted','AbortError');
  const attempts=RESTS.map(root=>new Promise(async(resolve,reject)=>{const c=new AbortController(),abort=()=>c.abort(),tm=setTimeout(abort,timeout);signal?.addEventListener('abort',abort,{once:true});try{const r=await fetch(root+path,{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);resolve(await r.json())}catch(e){reject(e)}finally{clearTimeout(tm);signal?.removeEventListener('abort',abort)}}));
  try{return await Promise.any(attempts)}catch(e){throw e?.errors?.at?.(-1)||e||Error('market data unavailable')}
}
async function fetchSymbolMeta(symbol,signal){
  try{const j=await fetchJson(`/api/v3/exchangeInfo?symbol=${encodeURIComponent(symbol)}`,12000,signal),x=j?.symbols?.[0],pf=x?.filters?.find?.(f=>f.filterType==='PRICE_FILTER'),tick=Number(pf?.tickSize);if(tick>0)return tick}catch(e){console.warn('[Renko V11 tickSize]',e)}
  const p=Number(window.RWARenkoV3?.state?.lastPrice);if(Number.isFinite(p)){if(p>=1000)return .01;if(p>=1)return .0001;if(p>=.01)return .000001;return .00000001}return .00000001;
}
async function fetchPage(endTime,symbol=S.symbol,signal=S.historyAbort?.signal){const q=`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${encodeURIComponent(C.interval)}&limit=${PAGE}${Number.isFinite(endTime)?`&endTime=${Math.floor(endTime)}`:''}`,rows=await fetchJson(q,15000,signal),t=now();return(Array.isArray(rows)?rows:[]).filter(r=>Number(r?.[0])&&Number(r?.[6]||0)<t)}
function dedupe(rows){const m=new Map();for(const r of rows||[]){const t=Number(r?.[0]);if(Number.isFinite(t))m.set(t,r)}return[...m.values()].sort((a,b)=>Number(a[0])-Number(b[0]))}

function ensureWorker(){if(worker)return worker;worker=new Worker('renko-v11-worker.js?v=111');return worker}
function normalize(bricks){let last=0;return(bricks||[]).map((b,i)=>{let t=Math.max(1,Math.floor(Number(b.time||0)/1000));if(t<=last)t=last+1;last=t;const o=Number(b.open),c=Number(b.close),h=Number(b.high),l=Number(b.low),dir=Number(b.direction)||0;return{time:t,open:o,high:Number.isFinite(h)?Math.max(h,o,c):Math.max(o,c),low:Number.isFinite(l)?Math.min(l,o,c):Math.min(o,c),close:c,color:dir>=0?'#089981':'#f23645',borderColor:dir>=0?'#089981':'#f23645',wickColor:dir>=0?'#089981':'#f23645',_ms:Number(b.time||0),_dir:dir,_box:Number(b.box)||S.box,_reversal:!!b.isReversal,_i:i}})}
function rebuild(anchor=null){
  if(!S.bars.length||!(S.tickSize>0))return Promise.resolve(false);
  const generation=S.generation,id=++S.buildSeq,bars=S.bars.map(r=>r.slice(0,7));S.building=true;setStatus('Building TradingView-rule Renko…','loading');
  return new Promise((resolve,reject)=>{const w=ensureWorker();const on=e=>{const m=e.data||{};if((m.type!=='built'&&m.type!=='error')||m.id!==id)return;w.removeEventListener('message',on);if(generation!==S.generation){resolve(false);return}if(m.type==='error'){S.building=false;reject(Error(m.message||'worker error'));return}S.bricks=Array.isArray(m.bricks)?m.bricks:[];S.data=normalize(S.bricks);S.box=Number(m.box);S.atr=Number(m.atr);S.tailState=m.tailState||null;S.latestClosedTime=Number(S.bars.at(-1)?.[6]||0);S.building=false;series?.setData(S.data);showChart();restoreAnchor(anchor);setStatus('Ready','ready');resetProjectionFromBuffer();evaluateSignal();setMeta();resolve(true)};w.addEventListener('message',on);try{w.postMessage({type:'build',id,generation,method:C.method,source:C.source,interval:C.interval,traditionalBox:C.traditionalBox,atrLength:C.atrLength,percentage:C.percentage,tickSize:S.tickSize,wicks:C.wicks,bars})}catch(e){w.removeEventListener('message',on);S.building=false;reject(e)}})
}
function showChart(){const e=$('chartEmpty');if(e)e.classList.add('hide');const h=$('lwcRenkoHost');if(h)h.style.visibility='visible'}
function latestView(){if(!chart||!S.data.length)return;const n=S.data.length;chart.timeScale().setVisibleLogicalRange({from:Math.max(0,n-FIRST_VIEW),to:n+5});S.following=true;setMeta()}
function rangeAnchor(){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r||!S.data.length)return null;const idx=clamp(Math.floor(r.from),0,S.data.length-1),d=S.data[idx];return{range:r,index:idx,time:d?.time,close:d?.close}}
function restoreAnchor(a){if(!a||!chart||!S.data.length)return;let idx=S.data.findIndex(d=>d.time===a.time&&Math.abs(Number(d.close)-Number(a.close))<Math.max(1e-10,Math.abs(Number(a.close))*1e-9));if(idx<0)idx=S.data.findIndex(d=>d.time>=a.time);if(idx<0)return;const shift=idx-a.index;chart.timeScale().setVisibleLogicalRange({from:a.range.from+shift,to:a.range.to+shift})}

function barCacheKey(){return`${BAR_CACHE}${C.interval}_${S.symbol}`}
function saveBars(){try{localStorage.setItem(barCacheKey(),JSON.stringify({v:110,interval:C.interval,savedAt:now(),bars:S.bars.slice(-PAGE)}))}catch{}}
async function loadBarsCache(generation){const candidates=[barCacheKey()];if(C.interval==='1m')candidates.push(`rwa_renko_v10_bars_${S.symbol}`);for(const key of candidates){try{const x=JSON.parse(localStorage.getItem(key)||'null');if(!x||now()-Number(x.savedAt)>86400000||!Array.isArray(x.bars)||!x.bars.length)continue;S.bars=dedupe(x.bars);await rebuild();if(generation!==S.generation)return false;latestView();setStatus('Cached · refreshing','ready');return true}catch{}}return false}
async function olderBatch(count=BATCH){
  if(S.loading||S.exhausted||!S.bars.length)return false;const generation=S.generation,seq=++S.loadSeq,symbol=S.symbol,first=Number(S.bars[0][0]),anchor=rangeAnchor();S.loading=true;setStatus('Loading older history…','loading');
  try{const step=PAGE*intervalMs(),ends=Array.from({length:count},(_,i)=>first-1-i*step),settled=await Promise.allSettled(ends.map(end=>fetchPage(end,symbol)));if(generation!==S.generation||seq!==S.loadSeq||symbol!==S.symbol)return false;const pages=settled.filter(x=>x.status==='fulfilled').map(x=>x.value),rows=pages.flat();if(!rows.length){S.exhausted=true;setStatus('History start reached','ready');return false}const before=S.bars.length;S.bars=dedupe([...rows,...S.bars]);const added=S.bars.length-before;if(added===0||pages.every(p=>p.length<PAGE))S.exhausted=true;if(added>0)await rebuild(anchor);return added>0}catch(e){if(generation===S.generation)setStatus('History retry','bad');console.warn('[Renko V11 older]',e);return false}finally{if(generation===S.generation){S.loading=false;setMeta()}}}
function scheduleOlder(){clearTimeout(rangeTimer);rangeTimer=setTimeout(()=>{if(S.loading||S.booting||S.exhausted||S.building)return;const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(r&&r.from<24)void olderBatch(BATCH)},160)}
async function bootHistory(generation){
  S.booting=true;try{S.tickSize=await fetchSymbolMeta(S.symbol,S.historyAbort?.signal);if(generation!==S.generation)return;const painted=await loadBarsCache(generation);if(generation!==S.generation)return;setStatus(painted?'Refreshing latest…':'Loading chart…',painted?'ready':'loading');const latest=await fetchPage(undefined,S.symbol);if(generation!==S.generation)return;if(latest.length){S.bars=dedupe(latest);await rebuild();saveBars()}let rounds=0;while(generation===S.generation&&S.data.length<FIRST_VIEW&&!S.exhausted&&rounds++<5){const ok=await olderBatch(BATCH);if(!ok)break;await sleep(0)}if(generation!==S.generation)return;if(S.data.length){latestView();setStatus('Ready','ready')}else setStatus('Offline · retrying','bad');setMeta();setTimeout(scheduleOlder,250)}catch(e){if(generation===S.generation)setStatus(S.data.length?'Cached · feed retry':'Offline · retrying','bad');console.error('[Renko V11 boot]',e)}finally{if(generation===S.generation)S.booting=false}
}
function resetForSymbol(symbol){S.historyAbort?.abort();S.historyAbort=new AbortController();clearTimeout(rangeTimer);S.generation++;S.symbol=symbol;S.method=C.method;S.source=C.source;S.interval=C.interval;S.tickSize=NaN;S.box=NaN;S.atr=NaN;S.bars=[];S.bricks=[];S.data=[];S.tailState=null;S.loading=false;S.building=false;S.booting=false;S.exhausted=false;S.following=true;S.latestClosedTime=0;S.projState=null;S.projBricks=[];S.projLastId=null;S.projLastTime=0;S.signal=null;series?.setData([]);projectionSeries?.setData([]);if(liveLine){try{series.removePriceLine(liveLine)}catch{}liveLine=null}setModePill();setStatus('Connecting source interval…','loading');setMeta();void bootHistory(S.generation)}

function cloneTail(s){return s?{lastClose:Number(s.lastClose),direction:Number(s.direction)||0,pendingHigh:Number(s.pendingHigh),pendingLow:Number(s.pendingLow),anchor:Number(s.anchor),lastSourceTime:Number(s.lastSourceTime)||0}:null}
function projTouch(st,p){if(!Number.isFinite(st.pendingHigh))st.pendingHigh=p;if(!Number.isFinite(st.pendingLow))st.pendingLow=p;if(p>st.pendingHigh)st.pendingHigh=p;if(p<st.pendingLow)st.pendingLow=p}
function projReset(st,p){st.pendingHigh=p;st.pendingLow=p}
function emitProj(st,out,open,close,dir,t,isRev){let high=Math.max(open,close),low=Math.min(open,close);if(C.wicks){if(dir>0)low=Math.min(low,st.pendingLow);else high=Math.max(high,st.pendingHigh)}out.push({time:t,open,high,low,close,direction:dir,box:S.box,isReversal:!!isRev});st.lastClose=close;st.direction=dir;projReset(st,close)}
function processProjectionPrice(st,p,t,out){p=Number(p);if(!Number.isFinite(p)||!(S.box>0)||!st)return;projTouch(st,p);let g=0;while(g++<5000){const lc=st.lastClose,d=st.direction,b=S.box;if(d===0){if(p>=lc+b){emitProj(st,out,lc,lc+b,1,t,false);continue}if(p<=lc-b){emitProj(st,out,lc,lc-b,-1,t,false);continue}break}if(d>0){if(p>=lc+b){emitProj(st,out,lc,lc+b,1,t,false);continue}if(p<=lc-2*b){emitProj(st,out,lc-b,lc-2*b,-1,t,true);continue}break}if(p<=lc-b){emitProj(st,out,lc,lc-b,-1,t,false);continue}if(p>=lc+2*b){emitProj(st,out,lc+b,lc+2*b,1,t,true);continue}break}projTouch(st,p)}
function partialProjection(){const st=S.projState,p=Number(S.projectionPrice);if(!st||!Number.isFinite(p)||!(S.box>0))return null;const b=S.box,lc=st.lastClose,d=st.direction;let open=lc,close=p,dir=0;if(d>0){if(p>=lc){open=lc;close=Math.min(p,lc+b);dir=1}else if(p<=lc-b){open=lc-b;close=Math.max(p,lc-2*b);dir=-1}else return null}else if(d<0){if(p<=lc){open=lc;close=Math.max(p,lc-b);dir=-1}else if(p>=lc+b){open=lc+b;close=Math.min(p,lc+2*b);dir=1}else return null}else{dir=p>=lc?1:-1;open=lc;close=p}if(Math.abs(close-open)<Math.max(Number.EPSILON,S.tickSize*.01))return null;let high=Math.max(open,close),low=Math.min(open,close);if(C.wicks){if(dir>0)low=Math.min(low,S.projState.pendingLow);else high=Math.max(high,S.projState.pendingHigh)}return{open,high,low,close,direction:dir,partial:true}}
function renderProjection(){
  if(!projectionSeries)return;if(!C.projection||!S.data.length||!S.projState){projectionSeries.setData([]);setText('projectionState','PROJECTION OFF');return}const baseTime=Number(S.data.at(-1)?.time||Math.floor(now()/1000));let n=0;const rows=S.projBricks.map(b=>({time:baseTime+(++n),open:b.open,high:b.high,low:b.low,close:b.close,color:b.direction>0?'rgba(8,153,129,.28)':'rgba(242,54,69,.28)',borderColor:b.direction>0?'rgba(8,153,129,.82)':'rgba(242,54,69,.82)',wickColor:'rgba(149,152,161,.8)'}));const part=partialProjection();if(part)rows.push({time:baseTime+(++n),open:part.open,high:part.high,low:part.low,close:part.close,color:part.direction>0?'rgba(8,153,129,.16)':'rgba(242,54,69,.16)',borderColor:part.direction>0?'rgba(8,153,129,.65)':'rgba(242,54,69,.65)',wickColor:'rgba(149,152,161,.72)'});projectionSeries.setData(rows);setText('projectionState',rows.length?`PROJECTION · ${S.projBricks.length} full${part?' + partial':''} · UNLOCKED`:'PROJECTION · waiting for threshold')
}
function appendProjectionTick(t,render=true){if(!S.tailState||!S.data.length||Number(t?.time)<=S.latestClosedTime)return;const id=t.id??`${t.time}:${t.price}`;if(id===S.projLastId)return;S.projLastId=id;S.projLastTime=Number(t.time)||0;const p=Number(t.price);if(!Number.isFinite(p))return;S.projectionPrice=p;processProjectionPrice(S.projState,p,Number(t.time),S.projBricks);updateLiveLine(p);if(render)renderProjection();const boundary=S.latestClosedTime+intervalMs();if(Number(t.time)>boundary)void refreshLatestBars(true)}
function resetProjectionFromBuffer(){S.projState=cloneTail(S.tailState);S.projBricks=[];S.projLastId=null;S.projLastTime=0;const ticks=window.RWARenkoV3?.state?.historyTicks;if(Array.isArray(ticks)&&S.projState){for(const t of ticks)if(Number(t.time)>S.latestClosedTime)appendProjectionTick(t,false)}const p=Number(window.RWARenkoV3?.state?.lastPrice);if(Number.isFinite(p)){S.projectionPrice=p;updateLiveLine(p)}renderProjection();updateSignalPanel()}
function updateLiveLine(p){if(!series||!Number.isFinite(p))return;if(liveLine){try{liveLine.applyOptions({price:p})}catch{}}else{try{liveLine=series.createPriceLine({price:p,color:'#2962ff',lineWidth:1,lineStyle:2,axisLabelVisible:true,title:'REAL'})}catch{}}}
function watchTick(){const v=window.RWARenkoV3?.state;if(!v)return;const t=v.historyTicks?.at?.(-1);if(t)appendProjectionTick(t,true);const p=Number(v.lastPrice);if(Number.isFinite(p)){S.projectionPrice=p;updateLiveLine(p);renderProjection();updateSignalPanel()}}

function deriveSignal(){const a=S.data;if(a.length<3)return{position:'flat',action:'WAIT',reason:'Need more locked bricks'};const confirm=C.confirmBricks;let position='flat',entry=NaN,entryBox=NaN,lastEvent='WAIT',eventIndex=-1;for(let i=1;i<a.length;i++){const d=Number(a[i]._dir),prev=Number(a[i-1]._dir);if(position==='long'&&d<0){position='flat';lastEvent='EXIT LONG · locked reversal';eventIndex=i;continue}if(position==='short'&&d>0){position='flat';lastEvent='EXIT SHORT · locked reversal';eventIndex=i;continue}if(position!=='flat')continue;if(confirm===1){if(prev<0&&d>0){position='long';entry=Number(a[i].close);entryBox=S.box;lastEvent='BUY READY · reversal locked';eventIndex=i}else if(prev>0&&d<0){position='short';entry=Number(a[i].close);entryBox=S.box;lastEvent='SELL READY · reversal locked';eventIndex=i}}else if(i>=2){const p2=Number(a[i-2]._dir);if(p2<0&&prev>0&&d>0){position='long';entry=Number(a[i].close);entryBox=S.box;lastEvent='BUY READY · reversal + 1 locked';eventIndex=i}else if(p2>0&&prev<0&&d<0){position='short';entry=Number(a[i].close);entryBox=S.box;lastEvent='SELL READY · reversal + 1 locked';eventIndex=i}}}const last=a.at(-1),market=Number(window.RWARenkoV3?.state?.lastPrice),close=Number(last?.close),box=S.box;let hard=NaN,trail=NaN,action=lastEvent,reason='Locked Renko only. Projection bricks never trigger entry/exit.';if(position==='long'){hard=entry-2*entryBox;trail=close-box;if(Number.isFinite(market)&&market<=hard){action='EXIT NOW · real market hard stop';reason='Real market price crossed hard stop before a locked reversal.'}else if(eventIndex<a.length-1)action='LONG ACTIVE'}else if(position==='short'){hard=entry+2*entryBox;trail=close+box;if(Number.isFinite(market)&&market>=hard){action='EXIT NOW · real market hard stop';reason='Real market price crossed hard stop before a locked reversal.'}else if(eventIndex<a.length-1)action='SHORT ACTIVE'}else if(lastEvent.startsWith('EXIT'))action=lastEvent;else action='WAIT';return{position,action,entry,entryBox,hard,trail,market,close,reason,eventIndex}}
function evaluateSignal(){S.signal=deriveSignal();updateSignalPanel()}
function updateSignalPanel(){if(!S.signal)S.signal=deriveSignal();const x=S.signal,age=now()-Number(window.RWARenkoV3?.state?.lastTickTime||0),fresh=age<5000;setText('signalAction',x.action||'WAIT');setText('signalPosition',(x.position||'flat').toUpperCase());setText('signalEntry',fmt(x.entry));setText('signalMarket',fmt(Number(window.RWARenkoV3?.state?.lastPrice)));setText('signalHardStop',fmt(x.hard));setText('signalTrail',fmt(x.trail));setText('signalReason',x.reason||'—');const e=$('signalAction');if(e)e.dataset.kind=(x.action||'').includes('EXIT')?'exit':(x.action||'').includes('BUY')?'buy':(x.action||'').includes('SELL')?'sell':(x.position==='long'?'buy':x.position==='short'?'sell':'wait');setText('signalFreshness',fresh?`LIVE ${Math.max(0,age)} ms`:`STALE ${Math.floor(age/1000)} s`);const f=$('signalFreshness');if(f)f.dataset.kind=fresh?'live':'stale'}

function createChart(){const wrap=$('chartWrap'),L=window.LightweightCharts;if(!wrap||!L)return false;let host=$('lwcRenkoHost');if(!host){host=document.createElement('div');host.id='lwcRenkoHost';host.setAttribute('aria-label','RENKO V11 TradingView-rule chart');wrap.prepend(host)}chart=L.createChart(host,{localization:{locale:'en-US'},layout:{background:{type:L.ColorType?.Solid??'solid',color:'#131722'},textColor:'#b2b5be',attributionLogo:true},grid:{vertLines:{color:'rgba(120,123,134,.14)'},horzLines:{color:'rgba(120,123,134,.14)'}},rightPriceScale:{borderColor:'#2a2e39',minimumWidth:64,scaleMargins:{top:.04,bottom:.05}},timeScale:{borderColor:'#2a2e39',timeVisible:true,secondsVisible:false,rightOffset:8,barSpacing:10,minBarSpacing:2,maxBarSpacing:30,lockVisibleTimeRangeOnResize:true},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true,vertTouchDrag:true},handleScale:{mouseWheel:true,pinch:true,axisPressedMouseMove:{time:true,price:true},axisDoubleClickReset:{time:true,price:true}},kineticScroll:{mouse:true,touch:true},crosshair:{mode:L.CrosshairMode?.Normal??0}});series=chart.addSeries(L.CandlestickSeries,{upColor:'#089981',downColor:'#f23645',borderUpColor:'#089981',borderDownColor:'#f23645',wickUpColor:'#089981',wickDownColor:'#f23645',priceLineVisible:false,lastValueVisible:true});projectionSeries=chart.addSeries(L.CandlestickSeries,{upColor:'rgba(8,153,129,.24)',downColor:'rgba(242,54,69,.24)',borderUpColor:'rgba(8,153,129,.72)',borderDownColor:'rgba(242,54,69,.72)',wickUpColor:'rgba(149,152,161,.78)',wickDownColor:'rgba(149,152,161,.78)',priceLineVisible:false,lastValueVisible:false});chart.timeScale().subscribeVisibleLogicalRangeChange?.(r=>{if(r&&S.data.length)S.following=r.to>=S.data.length-1;queueMeta();scheduleOlder()});resizeObserver=new ResizeObserver(entries=>{const r=entries[0]?.contentRect;if(r?.width&&r?.height)chart.resize(Math.floor(r.width),Math.floor(r.height))});resizeObserver.observe(wrap);wireNav();return true}
function shiftRange(frac){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r)return;const w=r.to-r.from,d=w*frac;chart.timeScale().setVisibleLogicalRange({from:r.from+d,to:r.to+d})}
function zoomRange(f){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r)return;const mid=(r.from+r.to)/2,w=clamp((r.to-r.from)*f,20,300);chart.timeScale().setVisibleLogicalRange({from:mid-w/2,to:mid+w/2})}
function wireNav(){const click=(id,fn)=>$(id)?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();fn()},{capture:true});click('tvPanOlder',()=>shiftRange(-.72));click('tvPanNewer',()=>shiftRange(.72));click('tvZoomOut',()=>zoomRange(1.25));click('tvZoomIn',()=>zoomRange(.8));click('tvReset',latestView);click('tvLive',latestView)}
function syncForm(){document.querySelectorAll('[data-renko-method]').forEach(b=>b.classList.toggle('active',b.dataset.renkoMethod===C.method));const set=(id,v)=>{const e=$(id);if(e)e.value=String(v)};set('brickSize',C.traditionalBox);set('v11AtrLength',C.atrLength);set('v11Percent',C.percentage*100);set('v11Source',C.source);set('v11Interval',C.interval);if($('v11Wicks'))$('v11Wicks').checked=!!C.wicks;if($('v11Projection'))$('v11Projection').checked=!!C.projection;if($('v11Confirm'))$('v11Confirm').value=String(C.confirmBricks);document.querySelectorAll('[data-method-fields]').forEach(e=>e.hidden=e.dataset.methodFields!==C.method);setModePill();setMeta()}
function readSettingsFromForm(){C.traditionalBox=Math.max(Number.EPSILON,Number($('brickSize')?.value)||C.traditionalBox);C.atrLength=clamp(Math.floor(Number($('v11AtrLength')?.value)||14),1,200);C.percentage=clamp((Number($('v11Percent')?.value)||1)/100,.00001,.1);const src=String($('v11Source')?.value||C.source);if(SOURCES.has(src))C.source=src;const intv=String($('v11Interval')?.value||C.interval);if(INTERVALS[intv])C.interval=intv;C.wicks=!!$('v11Wicks')?.checked;C.projection=!!$('v11Projection')?.checked;C.confirmBricks=Number($('v11Confirm')?.value)===1?1:2;saveSettings()}
async function applyMethod(method,{force=false}={}){if(!METHODS.has(method))return;C.method=method;S.method=method;saveSettings();syncForm();if(!S.bars.length)return;await rebuild(rangeAnchor());if(force||S.following)latestView();evaluateSignal()}
function wireSettings(){document.querySelectorAll('[data-renko-method]').forEach(b=>b.addEventListener('click',()=>applyMethod(b.dataset.renkoMethod,{force:true})));$('v11Apply')?.addEventListener('click',async()=>{const oldInterval=C.interval;readSettingsFromForm();S.method=C.method;S.source=C.source;S.interval=C.interval;if(oldInterval!==C.interval){resetForSymbol(S.symbol);syncForm();return}await rebuild(rangeAnchor());latestView();renderProjection();evaluateSignal();syncForm()});$('v11Source')?.addEventListener('change',async()=>{readSettingsFromForm();S.source=C.source;await rebuild(rangeAnchor());latestView();syncForm()});$('v11Interval')?.addEventListener('change',()=>{readSettingsFromForm();S.interval=C.interval;resetForSymbol(S.symbol);syncForm()});$('v11Wicks')?.addEventListener('change',async()=>{readSettingsFromForm();await rebuild(rangeAnchor());if(S.following)latestView();syncForm()});$('v11Projection')?.addEventListener('change',()=>{readSettingsFromForm();renderProjection()});$('v11Confirm')?.addEventListener('change',()=>{readSettingsFromForm();evaluateSignal()})}
async function refreshLatestBars(force=false){if(document.hidden||S.booting||S.loading||!S.symbol||(!force&&now()-S.lastRefreshAt<2500))return;S.lastRefreshAt=now();const generation=S.generation;try{const rows=await fetchJson(`/api/v3/klines?symbol=${encodeURIComponent(S.symbol)}&interval=${encodeURIComponent(C.interval)}&limit=4`,8000),t=now(),closed=(Array.isArray(rows)?rows:[]).filter(r=>Number(r?.[6]||0)<t);if(generation!==S.generation||!closed.length)return;const before=Number(S.bars.at(-1)?.[0]||0),after=Number(closed.at(-1)?.[0]||0);if(after>before){S.bars=dedupe([...S.bars,...closed]);await rebuild(rangeAnchor());saveBars();if(S.following)latestView()}}catch(e){console.warn('[Renko V11 refresh]',e)}}
async function boot(){for(let i=0;i<240&&(!window.LightweightCharts||!window.RWARenkoV3);i++)await sleep(50);if(!window.LightweightCharts)throw Error('Lightweight Charts unavailable');if(!window.RWARenkoV3)throw Error('Renko market engine unavailable');if(!createChart())throw Error('chart host unavailable');wireSettings();syncForm();showChart();window.RWARenkoV11={version:'11.0.0',renderer:'tradingview-lightweight-charts-5.1',methods:['atr','traditional','percentage'],sources:['close','ohlc'],intervals:Object.keys(INTERVALS),historicalSource:'binance-resolution-ohlc',liveSource:'binance-individual-@trade-projection-only',executionPrice:'real-market-price',signalRule:'locked-renko-only',state:S,settings:C,setMethod:applyMethod,loadOlder:olderBatch,goLive:latestView};watchTimer=setInterval(()=>{const v=window.RWARenkoV3?.state;if(!v)return;const sym=String(v.selected||'');if(sym&&sym!==lastSymbol){lastSymbol=sym;resetForSymbol(sym)}watchTick()},100);barTimer=setInterval(()=>void refreshLatestBars(false),3000);const initial=String(window.RWARenkoV3.state.selected||'BTCUSDT');lastSymbol=initial;resetForSymbol(initial)}
boot().catch(e=>{console.error('[Renko V11]',e);setStatus('Chart retry','bad')});
})();
