(()=>{
'use strict';
if(window.RWARenkoTV)return;
const E=window.RWARenkoTVEngine;if(!E)throw new Error('RWARenkoTVEngine missing');
const $=id=>document.getElementById(id),q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const RESTS=['https://data-api.binance.vision','https://api.binance.com'];
const WS_ROOTS=['wss://data-stream.binance.vision/ws','wss://stream.binance.com:9443/ws'];
const STORE='rwa_renko_tradingview_settings_v1',FIXED_INTERVAL='1s';
const LAUNCH_PAIRS=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','TRXUSDT','AVAXUSDT','LINKUSDT','DOTUSDT','LTCUSDT','BCHUSDT','UNIUSDT','AAVEUSDT','XLMUSDT','ETCUSDT','NEARUSDT','ICPUSDT','FILUSDT','APTUSDT','ARBUSDT','OPUSDT','SUIUSDT','SHIBUSDT','PEPEUSDT','HBARUSDT','INJUSDT','ATOMUSDT','IMXUSDT','GRTUSDT','ALGOUSDT','VETUSDT','SEIUSDT','TIAUSDT','WLDUSDT','STXUSDT','LDOUSDT','QNTUSDT','FETUSDT','ENAUSDT','PENDLEUSDT','RUNEUSDT','THETAUSDT','SANDUSDT','MANAUSDT','CRVUSDT','COMPUSDT','ZECUSDT','EGLDUSDT'];
const defaults={source:'close',interval:FIXED_INTERVAL,method:'atr',atrLength:14,boxSize:1,percentage:.01,wicks:true};
const settings={...defaults};try{Object.assign(settings,JSON.parse(localStorage.getItem(STORE)||'{}')||{})}catch{}
if(!['close','ohlc'].includes(settings.source))settings.source='close';if(!['atr','traditional','percentage'].includes(settings.method))settings.method='atr';settings.atrLength=Math.max(1,Math.floor(Number(settings.atrLength)||14));settings.boxSize=Math.max(Number.EPSILON,Number(settings.boxSize)||1);settings.percentage=Math.max(.000001,Math.min(10,Number(settings.percentage)||.01));settings.wicks=settings.wicks!==false;delete settings.interval;Object.defineProperty(settings,'interval',{enumerable:true,configurable:false,get:()=>FIXED_INTERVAL,set:()=>FIXED_INTERVAL});
const state={version:'18.1.0-precision-safe',symbol:'',pendingSymbol:'',tickSize:NaN,lastPrice:NaN,closedBars:[],currentBar:null,confirmed:[],projection:[],confirmedData:[],projectionData:[],box:NaN,atr:NaN,base:null,status:'boot',historyPages:0,lastEventAt:0,generation:0,following:true,formationSource:'fixed-1s-close-or-ohlc',confirmationRule:'fixed-1s-close',projectionRule:'realtime-provisional-until-1s-close',publicDocsParity:true,exactProprietaryOutputParity:false};
let chart,series,projectionSeries,priceLine,resizeObserver,ws,wsFallback=0,ageTimer=0,marketRows=[],marketLoaded=false,marketLoading=false,activeAbort=null,historyBusy=false,lastLogicalWidth=65,lastOlderAt=0;
const marketMeta=new Map();
function precisionFor(...values){let p=2;for(const v of values){const a=Math.abs(Number(v));if(!(a>0)||!Number.isFinite(a))continue;if(a>=1000)p=Math.max(p,2);else if(a>=100)p=Math.max(p,3);else if(a>=1)p=Math.max(p,4);else if(a>=.01)p=Math.max(p,6);else p=Math.max(p,Math.min(14,Math.ceil(-Math.log10(a))+2))}return p}
const fmt=n=>{n=Number(n);if(!Number.isFinite(n))return'—';return n.toLocaleString(undefined,{maximumFractionDigits:precisionFor(n)})};
const fmtDate=ms=>Number(ms)?new Date(Number(ms)).toLocaleString(undefined,{month:'short',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';
const save=()=>{try{localStorage.setItem(STORE,JSON.stringify(settings))}catch{}};
function setText(id,v){const el=$(id);if(el)el.textContent=v}
function setFeed(text,live=false){const el=$('feedPill');if(!el)return;el.classList.toggle('live',!!live);const b=el.querySelector('b');if(b)b.textContent=text}
function setLoad(text,kind='loading'){const e=$('tvLoadState');if(e){e.textContent=text;e.className=`load-state ${kind==='live'?'live':''}`}}
function normalizeSymbol(s){s=String(s||'').toUpperCase().replace(/[^A-Z0-9]/g,'');if(!s)return'BTCUSDT';if(!/(USDT|USDC|FDUSD|BTC|ETH|BNB)$/.test(s)&&/^[A-Z0-9]{2,10}$/.test(s))return`${s}USDT`;return s}
function splitSymbol(sym){for(const quote of ['USDT','USDC','FDUSD','BTC','ETH','BNB'])if(sym.endsWith(quote)&&sym.length>quote.length)return[sym.slice(0,-quote.length),quote];return[sym,'']}
function setUrlSymbol(sym){try{const u=new URL(location.href);u.searchParams.set('symbol',splitSymbol(sym)[0]);history.replaceState(null,'',u)}catch{}}
async function fetchJson(path,timeout=15000,signal){let last=null;for(const root of RESTS){if(signal?.aborted)throw new DOMException('Aborted','AbortError');const c=new AbortController(),relay=()=>c.abort();if(signal)signal.addEventListener('abort',relay,{once:true});const tm=setTimeout(()=>c.abort(),timeout);try{const r=await fetch(root+path,{cache:'no-store',credentials:'omit',signal:c.signal});if(!r.ok)throw new Error(`HTTP ${r.status} ${path}`);return await r.json()}catch(e){last=e;if(signal?.aborted)throw e}finally{clearTimeout(tm);if(signal)signal.removeEventListener('abort',relay)}}throw last||new Error('market data unavailable')}
function mapKlines(rows){return(Array.isArray(rows)?rows:[]).map(x=>({openTime:Number(x[0]),open:Number(x[1]),high:Number(x[2]),low:Number(x[3]),close:Number(x[4]),volume:Number(x[5])||0,closeTime:Number(x[6])})).filter(b=>[b.openTime,b.open,b.high,b.low,b.close,b.closeTime].every(Number.isFinite)).sort((a,b)=>a.openTime-b.openTime)}
function dedupeBars(rows){const m=new Map();for(const b of rows||[])m.set(Number(b.openTime),b);return[...m.values()].sort((a,b)=>a.openTime-b.openTime)}
async function fetchKlines(symbol,endTime=null,signal=null){let p=`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=${FIXED_INTERVAL}&limit=1000`;if(endTime!==null&&endTime!==undefined&&Number.isFinite(Number(endTime)))p+=`&endTime=${Math.floor(Number(endTime))}`;return mapKlines(await fetchJson(p,14000,signal))}
async function fetchMeta(symbol,signal){const cached=marketMeta.get(symbol);if(cached?.tick>0)return cached;const j=await fetchJson(`/api/v3/exchangeInfo?symbol=${encodeURIComponent(symbol)}`,12000,signal),s=j?.symbols?.[0],pf=s?.filters?.find?.(f=>f.filterType==='PRICE_FILTER'),tick=Number(pf?.tickSize);if(!(tick>0))throw new Error('minimum tick unavailable');const out={tick,symbol:s?.symbol||symbol,status:s?.status||'',base:s?.baseAsset||splitSymbol(symbol)[0],quote:s?.quoteAsset||splitSymbol(symbol)[1],price:Number(cached?.price)||NaN,vol:Number(cached?.vol)||0,pct:Number(cached?.pct)||0};marketMeta.set(symbol,out);return out}
function initChart(){if(chart)return;const host=$('chartHost');if(!host)return;chart=LightweightCharts.createChart(host,{width:host.clientWidth,height:host.clientHeight,layout:{background:{type:'solid',color:'#101620'},textColor:'#9da3ae',fontSize:11},grid:{vertLines:{color:'#202837'},horzLines:{color:'#202837'}},rightPriceScale:{borderColor:'#30394a'},timeScale:{borderColor:'#30394a',timeVisible:true,secondsVisible:true,rightOffset:5,barSpacing:10,minBarSpacing:3},crosshair:{mode:0}});const add=opts=>chart.addSeries?chart.addSeries(LightweightCharts.CandlestickSeries,opts):chart.addCandlestickSeries(opts);series=add({upColor:'#089981',downColor:'#f23645',borderUpColor:'#089981',borderDownColor:'#f23645',wickUpColor:'#089981',wickDownColor:'#f23645',priceLineVisible:false,lastValueVisible:true});projectionSeries=add({upColor:'#a9dcc3',downColor:'#f5a6ae',borderUpColor:'#a9dcc3',borderDownColor:'#f5a6ae',wickUpColor:'#a9dcc3',wickDownColor:'#f5a6ae',priceLineVisible:false,lastValueVisible:false});resizeObserver=new ResizeObserver(()=>chart.applyOptions({width:host.clientWidth,height:host.clientHeight}));resizeObserver.observe(host);chart.timeScale().subscribeVisibleLogicalRangeChange(r=>{if(!r)return;lastLogicalWidth=Math.max(10,Math.round(r.to-r.from));state.following=r.to>state.confirmedData.length-4;if(state.status==='live'&&r.from<8&&Date.now()-lastOlderAt>900){lastOlderAt=Date.now();void loadOlderPage()}})}
function syncPriceFormat(){if(!series||!projectionSeries)return;const p=precisionFor(state.lastPrice,state.tickSize,state.box,state.atr),pf={type:'price',precision:p,minMove:10**(-p)};try{series.applyOptions({priceFormat:pf});projectionSeries.applyOptions({priceFormat:pf})}catch{}document.documentElement.dataset.renkoPricePrecision=String(p)}
function normalizeData(bricks,projection=false,startTime=0){let last=Math.floor(Number(startTime)||0),i=0;return(bricks||[]).map(b=>{let tm=Math.max(1,Math.floor(Number(b.sourceTime||0)/1000));if(tm<=last)tm=last+1;last=tm;const dir=Number(b.direction)||0,up=projection?'#a9dcc3':'#089981',down=projection?'#f5a6ae':'#f23645',color=dir>0?up:down;return{time:tm,open:Number(b.open),high:Number(b.high),low:Number(b.low),close:Number(b.close),color,borderColor:color,wickColor:color,_sourceTime:Number(b.sourceTime||0),_projection:projection,_dir:dir,_i:i++}})}
function render(fit=false){initChart();state.confirmedData=normalizeData(state.confirmed,false,0);const last=Number(state.confirmedData.at(-1)?.time||0);state.projectionData=normalizeData(state.projection,true,last);syncPriceFormat();series?.setData(state.confirmedData);projectionSeries?.setData(state.projectionData);if(Number.isFinite(state.lastPrice)){if(priceLine){try{priceLine.applyOptions({price:state.lastPrice})}catch{}}else{try{priceLine=series?.createPriceLine({price:state.lastPrice,color:'#2962ff',lineWidth:1,lineStyle:2,axisLabelVisible:true,title:'REAL'})}catch{}}}const empty=$('chartEmpty');if(empty&&state.confirmedData.length)empty.classList.add('hide');if(fit||state.following)latestView();updateMeta()}
function latestView(){if(!chart||!state.confirmedData.length)return;const total=state.confirmedData.length+state.projectionData.length,w=Math.max(45,Math.min(75,lastLogicalWidth||65));chart.timeScale().setVisibleLogicalRange({from:Math.max(0,total-w),to:total+5});state.following=true}
function rebuild({fit=false}={}){if(!state.closedBars.length||!(state.tickSize>0))return;const base=E.build(state.closedBars,settings,state.tickSize);state.base=base;state.box=base.box;state.atr=base.atr;state.confirmed=base.bricks;state.projection=state.currentBar?E.project(base,state.currentBar,settings,state.tickSize):[];render(fit);updateAudit()}
function updateMeta(){const src=settings.source.toUpperCase(),method=settings.method==='atr'?'ATR':settings.method==='traditional'?'TRADITIONAL':'PERCENTAGE (LTP)';setText('modePill',`${method} · 1s · ${src}`);setText('sourceText',`TradingView documented model · fixed 1s source ${src} · historical bricks lock on each 1-second close · realtime bricks are provisional projections.`);setText('pairName',splitSymbol(state.symbol).join(' / '));setText('pairIcon',splitSymbol(state.symbol)[0].slice(0,2));setText('lastPrice',fmt(state.lastPrice));setText('brickValue',fmt(state.box));setText('brickCount',(state.confirmed?.length||0).toLocaleString());setText('projectionCount',(state.projection?.length||0).toLocaleString());setText('sourceBarCount',(state.closedBars?.length||0).toLocaleString());setText('currentMethod',method);setText('currentSource',src);setText('currentInterval','1s');setText('currentAtr',fmt(state.atr));setText('ltpSnapshot',fmt(state.percentageLtpSnapshot||state.lastPrice));setText('minTick',fmt(state.tickSize));setText('tvBrickMeta',`${state.confirmed.length.toLocaleString()} confirmed · ${state.projection.length} projection`);Object.assign(document.documentElement.dataset,{renkoVisibleAtr:fmt(state.atr),renkoVisibleBox:fmt(state.box)});const from=state.closedBars[0]?.openTime,to=state.closedBars.at(-1)?.closeTime;setText('tvCoverage',from?`${fmtDate(from)} → ${fmtDate(to)} · ${state.closedBars.length.toLocaleString()} fixed-1s source bars`:'Preparing fixed-1s source history');if(state.status==='live'){const p=state.projection.length;setLoad(p?`LIVE · ${p} projection brick${p===1?'':'s'} · locks on 1s close`:'LIVE · waiting threshold · locks on 1s close','live')}qa('.method').forEach(el=>el.classList.toggle('active',el.dataset.method===settings.method));qa('.method .method-title span').forEach(el=>{const card=el.closest('.method');el.textContent=card?.dataset.method===settings.method?'ACTIVE':'READY'});const feed=$('tickHealth');if(feed){feed.textContent=state.status==='live'?'LIVE PROJECTION':state.status==='switching'?'SWITCHING':'WAITING';feed.className=`health ${state.status==='live'?'live':''}`}}
function updateAudit(){const a=E.audit(state.confirmed),set=(id,ok,text)=>{const e=$(id);if(e){e.classList.toggle('ok',!!ok);e.textContent=`${ok?'✓':'!'} ${text}`}};set('auditSource',settings.interval==='1s',`Fixed 1s · ${settings.source.toUpperCase()}`);set('auditContinuation',a.continuation,'1× continuation');set('auditReversal',a.reversal,'2× reversal');set('auditProjection',true,'projection ≠ confirmed');set('auditWicks',a.wicksDirectional,settings.wicks?'directional wicks':'wicks off')}
function splitLatestBars(rows){const now=Date.now(),a=dedupeBars(rows),closed=[],open=[];for(const b of a){if(b.closeTime<now-50)closed.push(b);else open.push(b)}return{closed,current:open.at(-1)||null}}
function syncInputs(){if($('sourceSelect'))$('sourceSelect').value=settings.source;if($('atrLength'))$('atrLength').value=String(settings.atrLength);if($('traditionalBox'))$('traditionalBox').value=String(settings.boxSize);if($('percentageValue'))$('percentageValue').value=String(settings.percentage*100);if($('wicksToggle'))$('wicksToggle').checked=settings.wicks}
function wireControls(){syncInputs();$('sourceSelect')?.addEventListener('change',e=>{settings.source=e.target.value==='ohlc'?'ohlc':'close';save();rebuild({fit:true})});$('wicksToggle')?.addEventListener('change',e=>{settings.wicks=!!e.target.checked;save();rebuild()});qa('[data-apply-method]').forEach(btn=>btn.addEventListener('click',()=>{const m=btn.dataset.applyMethod;if(m==='atr')settings.atrLength=Math.max(1,Math.floor(Number($('atrLength')?.value)||14));else if(m==='traditional')settings.boxSize=Math.max(Number.EPSILON,Number($('traditionalBox')?.value)||1);else if(m==='percentage')settings.percentage=Math.max(.000001,Math.min(10,(Number($('percentageValue')?.value)||1)/100));settings.method=m;save();rebuild({fit:true})}));qa('[data-quick]').forEach(b=>b.addEventListener('click',()=>void loadSymbol(`${b.dataset.quick}USDT`,{fit:true})));$('openPairs')?.addEventListener('click',()=>q('.markets')?.classList.toggle('open'));$('pairSearch')?.addEventListener('focus',()=>void loadMarkets());$('pairSearch')?.addEventListener('input',()=>{renderMarkets();if(!marketLoaded&&!marketLoading)void loadMarkets()});$('tvLive')?.addEventListener('click',latestView);$('tvZoomIn')?.addEventListener('click',()=>zoom(.75));$('tvZoomOut')?.addEventListener('click',()=>zoom(1.25));$('tvPanOlder')?.addEventListener('click',()=>pan(-.6));$('tvPanNewer')?.addEventListener('click',()=>pan(.6));$('tvReset')?.addEventListener('click',()=>{lastLogicalWidth=65;latestView()})}
function zoom(mult){if(!chart)return;const r=chart.timeScale().getVisibleLogicalRange();if(!r)return;const mid=(r.from+r.to)/2,w=Math.max(15,Math.min(220,(r.to-r.from)*mult));chart.timeScale().setVisibleLogicalRange({from:mid-w/2,to:mid+w/2});lastLogicalWidth=Math.round(w)}
function pan(frac){if(!chart)return;const r=chart.timeScale().getVisibleLogicalRange();if(!r)return;const w=r.to-r.from,d=w*frac;chart.timeScale().setVisibleLogicalRange({from:r.from+d,to:r.to+d})}
function parseWsBar(k){return{openTime:Number(k.t),closeTime:Number(k.T),open:Number(k.o),high:Number(k.h),low:Number(k.l),close:Number(k.c),volume:Number(k.v)||0}}
function closeSocket(){if(ws){try{ws.onopen=ws.onclose=ws.onerror=ws.onmessage=null;ws.close()}catch{}ws=null}}
function connectSocket(generation){closeSocket();const symbol=state.symbol.toLowerCase(),root=WS_ROOTS[wsFallback%WS_ROOTS.length],url=`${root}/${symbol}@kline_1s`;try{ws=new WebSocket(url)}catch{scheduleWsFallback(generation);return}ws.onopen=()=>{if(generation!==state.generation)return;state.status='live';state.lastEventAt=Date.now();setFeed('LIVE',true);updateMeta()};ws.onerror=()=>{};ws.onclose=()=>{if(generation!==state.generation)return;setFeed('RECONNECTING',false);scheduleWsFallback(generation)};ws.onmessage=e=>{if(generation!==state.generation)return;try{const m=JSON.parse(e.data),k=m?.k;if(!k||String(k.i||'1s')!=='1s')return;const b=parseWsBar(k);state.lastPrice=b.close;state.lastEventAt=Date.now();if(k.x){state.closedBars=dedupeBars([...state.closedBars,b]);state.currentBar=null;rebuild()}else{state.currentBar=b;if(state.base){state.projection=E.project(state.base,b,settings,state.tickSize);render(false)}else rebuild()}setFeed('LIVE',true)}catch(err){console.warn('[RENKO TV websocket]',err)}}}
function scheduleWsFallback(generation){setTimeout(()=>{if(generation!==state.generation||state.status==='switching')return;wsFallback++;connectSocket(generation)},1200)}
async function loadSymbol(symbol,{fit=false}={}){symbol=normalizeSymbol(symbol||state.symbol);if(symbol===state.symbol&&state.status==='live')return true;const generation=++state.generation,previous=state.symbol,hadChart=state.confirmedData.length>0||state.confirmed.length>0;state.pendingSymbol=symbol;state.status=hadChart?'switching':'loading';setUrlSymbol(symbol);const [base,quote]=splitSymbol(symbol);setText('pairName',`${base} / ${quote}`);setText('pairIcon',base.slice(0,2));setFeed(hadChart?'SWITCHING':'CONNECTING',false);setLoad(hadChart?`Switching to ${base} / ${quote} · keeping current chart visible…`:`Loading ${symbol} fixed 1s source…`,'loading');const empty=$('chartEmpty');if(empty&&!hadChart){empty.classList.remove('hide');empty.querySelector('b').textContent=`Loading ${symbol} fixed 1s source…`;empty.querySelector('small').textContent='Historical fixed-1s source bars first; realtime is projection until each 1-second close.'}closeSocket();activeAbort?.abort();activeAbort=new AbortController();wsFallback=0;if(previous&&previous!==symbol){delete settings._exactBox;delete state.atrMatrixPrepared;delete state.atrHistorySatisfied;delete state.atrRaw;delete state.atrAppliedLength}
  try{const [meta,rows]=await Promise.all([fetchMeta(symbol,activeAbort.signal),fetchKlines(symbol,null,activeAbort.signal)]);if(generation!==state.generation)return false;if(!rows.length)throw new Error('no fixed-1s bars returned');const split=splitLatestBars(rows),last=Number(split.current?.close||split.closed.at(-1)?.close||rows.at(-1)?.close);state.symbol=symbol;state.pendingSymbol='';state.tickSize=meta.tick;state.lastPrice=last;state.closedBars=split.closed;state.currentBar=split.current;state.confirmed=[];state.projection=[];state.base=null;state.historyPages=1;state.status='applying';rebuild({fit:true});state.status='live';setFeed('LIVE',true);updateMeta();connectSocket(generation);marketMeta.set(symbol,{...meta,price:last});return true}catch(e){if(generation!==state.generation||activeAbort?.signal.aborted)return false;state.pendingSymbol='';if(hadChart&&previous){state.status='live';setUrlSymbol(previous);setText('pairName',splitSymbol(previous).join(' / '));setText('pairIcon',splitSymbol(previous)[0].slice(0,2));setFeed('LIVE · PREVIOUS',true);setLoad(`SWITCH FAILED · ${String(e?.message||e)} · previous chart kept`,'error');connectSocket(generation)}else{state.status='error';setLoad(`DATA ERROR · ${String(e?.message||e)}`,'error');setFeed('OFFLINE',false)}console.error('[RENKO TV load]',e);return false}}
async function loadOlderPage(){if(historyBusy||state.status!=='live'||state.historyPages>=5||!state.closedBars.length)return false;historyBusy=true;const generation=state.generation,oldest=state.closedBars[0]?.openTime;try{const rows=await fetchKlines(state.symbol,Number(oldest)-1,null);if(generation!==state.generation)return false;const older=rows.filter(b=>b.openTime<oldest);if(!older.length){state.historyPages=5;return false}state.closedBars=dedupeBars([...older,...state.closedBars]);state.historyPages++;const follow=state.following;rebuild({fit:false});if(follow)latestView();return true}catch(e){console.warn('[RENKO TV older history]',e);return false}finally{historyBusy=false}}
function launchRows(){return LAUNCH_PAIRS.map(symbol=>{const [base,quote]=splitSymbol(symbol);return{symbol,base,quote,price:Number(marketMeta.get(symbol)?.price),pct:0,vol:0,launch:true}})}
async function loadMarkets(){if(marketLoaded||marketLoading)return;marketLoading=true;setText('universeNote','Loading full spot universe on demand…');try{const [info,tickers]=await Promise.all([fetchJson('/api/v3/exchangeInfo',20000),fetchJson('/api/v3/ticker/24hr',20000)]),tm=new Map((Array.isArray(tickers)?tickers:[]).map(t=>[t.symbol,t]));marketRows=(info?.symbols||[]).filter(s=>s.status==='TRADING'&&s.isSpotTradingAllowed!==false).map(s=>{const t=tm.get(s.symbol)||{},pf=s?.filters?.find?.(f=>f.filterType==='PRICE_FILTER'),row={symbol:s.symbol,base:s.baseAsset,quote:s.quoteAsset,price:Number(t.lastPrice),pct:Number(t.priceChangePercent),vol:Number(t.quoteVolume)||0,tick:Number(pf?.tickSize)};if(row.tick>0)marketMeta.set(row.symbol,{tick:row.tick,symbol:row.symbol,status:s.status,base:row.base,quote:row.quote,price:row.price,vol:row.vol,pct:row.pct});return row}).filter(x=>Number.isFinite(x.price)&&x.price>0).sort((a,b)=>b.vol-a.vol);marketLoaded=true;renderMarkets();setText('pairTotal',`${marketRows.length.toLocaleString()} markets`)}catch(e){marketRows=launchRows();renderMarkets();setText('universeNote','Fast 50 ready · full universe unavailable');console.warn('[RENKO TV markets]',e)}finally{marketLoading=false}}
function renderMarkets(){const host=$('pairList');if(!host)return;const term=String($('pairSearch')?.value||'').trim().toUpperCase(),rows=(term?marketRows.filter(x=>`${x.base}${x.quote}${x.symbol}`.includes(term)):marketRows).slice(0,500);setText('pairShown',term?`${rows.length} matches`:(marketLoaded?`Top ${Math.min(500,rows.length)} shown`:'50 launch pairs'));setText('universeNote',marketLoaded?`Search all ${marketRows.length.toLocaleString()} spot markets`:'Fast 50 ready · focus search to load all spot markets');host.textContent='';if(!rows.length){host.innerHTML='<div class="empty">No matching pair.</div>';return}const frag=document.createDocumentFragment();for(const r of rows){const row=document.createElement('button');row.type='button';row.className=`pair-row ${r.symbol===state.symbol?'active':''}`;row.dataset.symbol=r.symbol;const detail=r.launch?'Instant launch pair · 1s':`${fmt(r.vol)} 24h quote`,price=Number.isFinite(r.price)&&r.price>0?fmt(r.price):'—',pct=Number.isFinite(r.pct)?`${r.pct>=0?'+':''}${fmt(r.pct)}%`:'1s';row.innerHTML=`<span class="pair-icon">${r.base.slice(0,2)}</span><span class="pair-main"><b>${r.base} / ${r.quote}</b><small>${detail}</small></span><span class="pair-price"><b>${price}</b><small class="${r.pct>=0?'up':'down'}">${pct}</small></span>`;row.addEventListener('click',()=>{q('.markets')?.classList.remove('open');void loadSymbol(r.symbol,{fit:true})});frag.appendChild(row)}host.appendChild(frag)}
function startAge(){clearInterval(ageTimer);ageTimer=setInterval(()=>{const age=state.lastEventAt?Math.max(0,Date.now()-state.lastEventAt):0;setText('tickAge',state.lastEventAt?`${Math.round(age/1000)}s since 1s kline update`:'waiting');if(age>15000&&state.status==='live')setFeed('STALE',false)},1000)}
function expose(){window.RWARenkoTV={version:'3.1.0-precision-safe',engine:E,state,settings,loadSymbol,rebuild,loadOlderPage,loadMarkets,launchPairs:[...LAUNCH_PAIRS],precisionFor,contract:{reference:'TradingView public Renko documentation',historical:'fixed 1-second Close or OHLC only; no timeframe selector',realtime:'projection until each 1-second source candle closes',traditional:'fixed box; 1x continuation; 2x reversal',percentage:'symbol-load LTP x percent, nearest min tick, fixed across rebuild',atr:'Wilder ATR from regular fixed-1s OHLC; positive raw ATR is box without clamp',wicks:'Close extrema for Close source; High/Low for OHLC source',pairSwitch:'atomic swap; previous chart stays visible while next fixed-1s source loads',displayPrecision:'dynamic precision preserves tiny positive ATR/box values and Renko price labels without rendering them as zero',exactProprietaryIntrabarOrdering:'not publicly specified'}};window.RWARenkoV15=window.RWARenkoTV}
async function boot(){expose();wireControls();initChart();startAge();marketRows=launchRows();renderMarkets();setText('pairTotal','50 fast');const p=new URLSearchParams(location.search),sym=normalizeSymbol(p.get('symbol')||'SOLUSDT');await loadSymbol(sym,{fit:true});window.dispatchEvent(new CustomEvent('renko:tv-ready',{detail:{symbol:state.symbol,version:window.RWARenkoTV.version,interval:'1s'}}))}
boot().catch(e=>{console.error(e);setLoad(String(e?.message||e),'error')});
})();