(()=>{
'use strict';
if(window.RWARenkoV9)return;
const $=id=>document.getElementById(id);
const RESTS=['https://data-api.binance.vision','https://api.binance.com'];
const PAGE=1000,BATCH=4,FIRST_VIEW=50,MINUTE=60000,CACHE='rwa_renko_v9_seed_',BAR_CACHE='rwa_renko_v9_bars_';
const S={version:'9.1.0',generation:0,symbol:'',box:0,key:'',bars:[],bricks:[],data:[],loading:false,building:false,booting:false,exhausted:false,cached:false,following:true,latestClosedTime:0,buildSeq:0,loadSeq:0,lastLoad:null,lastLiveId:null,frames:0,lastUniverse:0};
let chart=null,series=null,liveLine=null,worker=null,resizeObserver=null,rangeTimer=0,metaFrame=0,watchTimer=0,tickTimer=0,lastKey='',historyAbort=null;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
const fmt=n=>{n=Number(n);if(!Number.isFinite(n))return'—';const a=Math.abs(n),d=a>=1000?2:a>=100?3:a>=1?4:a>=.01?6:8;return n.toLocaleString(undefined,{maximumFractionDigits:d})};
const fmtDate=ms=>Number(ms)?new Date(Number(ms)).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'}):'—';
function setStatus(text,kind='ready'){const e=$('tvLoadState');if(e){e.textContent=text;e.dataset.kind=kind}const l=$('tvLoading');if(l)l.hidden=kind!=='loading'}
function setMeta(){const ts=chart?.timeScale?.(),r=ts?.getVisibleLogicalRange?.();const width=r?Math.max(1,Math.round(r.to-r.from)):FIRST_VIEW;if($('tvZoomValue'))$('tvZoomValue').textContent=String(width);if($('tvBrickMeta'))$('tvBrickMeta').textContent=`${Math.min(width,S.data.length)} visible · ${S.data.length.toLocaleString()} loaded`;if($('tvCoverage'))$('tvCoverage').textContent=S.bars.length?`${fmtDate(S.bars[0]?.[0])} → live`:'Preparing history'}
function queueMeta(){if(metaFrame)return;metaFrame=requestAnimationFrame(()=>{metaFrame=0;setMeta()})}
async function fetchJson(path,timeout=7000,signal){if(signal?.aborted)throw new DOMException('Aborted','AbortError');const attempts=RESTS.map(root=>new Promise(async(resolve,reject)=>{const c=new AbortController(),abort=()=>c.abort(),tm=setTimeout(abort,timeout);signal?.addEventListener('abort',abort,{once:true});try{const r=await fetch(root+path,{cache:'default',credentials:'omit',signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);resolve(await r.json())}catch(e){reject(e)}finally{clearTimeout(tm);signal?.removeEventListener('abort',abort)}}));try{return await Promise.any(attempts)}catch(e){throw e?.errors?.at?.(-1)||e||Error('market data unavailable')}}
async function fetchPage(endTime,symbol=S.symbol,signal=historyAbort?.signal){const q=`/api/v3/klines?symbol=${encodeURIComponent(symbol)}&interval=1m&limit=${PAGE}${Number.isFinite(endTime)?`&endTime=${Math.floor(endTime)}`:''}`;const rows=await fetchJson(q,15000,signal),now=Date.now();return(Array.isArray(rows)?rows:[]).filter(r=>Number(r?.[0])&&Number(r?.[6]||0)<now)}
function dedupe(rows){const m=new Map();for(const r of rows||[]){const t=Number(r?.[0]);if(Number.isFinite(t))m.set(t,r)}return[...m.values()].sort((a,b)=>Number(a[0])-Number(b[0]))}
function ensureWorker(){if(worker)return worker;worker=new Worker('renko-v8-worker.js?v=80');return worker}
function normalize(bricks){let last=0;return(bricks||[]).map((b,i)=>{let t=Math.max(1,Math.floor(Number(b.time||0)/1000));if(t<=last)t=last+1;last=t;const o=Number(b.open),c=Number(b.close);return{time:t,open:o,high:Math.max(o,c),low:Math.min(o,c),close:c,color:Number(b.direction)>=0?'#089981':'#f23645',borderColor:Number(b.direction)>=0?'#22ab94':'#f7525f',wickColor:Number(b.direction)>=0?'#089981':'#f23645',_ms:Number(b.time||0),_dir:Number(b.direction)||0,_i:i}})}
function cacheKey(){return`${CACHE}${S.symbol}|${Number(S.box).toPrecision(12)}`}
function barCacheKey(){return`${BAR_CACHE}${S.symbol}`}
function saveCache(){if(S.data.length<FIRST_VIEW)return;try{localStorage.setItem(cacheKey(),JSON.stringify({v:90,symbol:S.symbol,box:S.box,savedAt:Date.now(),data:S.data.slice(-FIRST_VIEW)}))}catch{}}
function loadCache(){try{const x=JSON.parse(localStorage.getItem(cacheKey())||'null');if(!x||x.v!==90||!Array.isArray(x.data)||x.data.length<FIRST_VIEW)return false;S.data=x.data;S.cached=true;series?.setData(S.data);showChart();latest50(false);setStatus('Cached · refreshing','ready');setMeta();return true}catch{return false}}
function saveBars(){try{localStorage.setItem(barCacheKey(),JSON.stringify({v:91,savedAt:Date.now(),bars:S.bars.slice(-PAGE)}))}catch{}}
async function loadBarsCache(generation){try{const x=JSON.parse(localStorage.getItem(barCacheKey())||'null');if(!x||x.v!==91||Date.now()-Number(x.savedAt)>86400000||!Array.isArray(x.bars)||!x.bars.length)return false;S.bars=dedupe(x.bars);await rebuild();if(generation!==S.generation)return false;S.cached=true;latest50(false);setStatus('Cached · live refresh','ready');return true}catch{return false}}
function rangeAnchor(){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r||!S.data.length)return null;const idx=clamp(Math.floor(r.from),0,S.data.length-1),d=S.data[idx];return{range:r,index:idx,time:d?.time,close:d?.close}}
function restoreAnchor(anchor){if(!anchor||!chart||!S.data.length)return;let idx=S.data.findIndex(d=>d.time===anchor.time&&Math.abs(Number(d.close)-Number(anchor.close))<=Math.max(1e-12,Math.abs(Number(anchor.close))*1e-10));if(idx<0)idx=S.data.findIndex(d=>d.time>=anchor.time);if(idx<0)return;const shift=idx-anchor.index;chart.timeScale().setVisibleLogicalRange({from:anchor.range.from+shift,to:anchor.range.to+shift})}
function rebuild(anchor=null){const generation=S.generation,id=++S.buildSeq,bars=S.bars.map(r=>r.slice(0,7)),box=S.box;S.building=true;return new Promise((resolve,reject)=>{const w=ensureWorker(),on=e=>{const m=e.data||{};if(m.type!=='built'||m.id!==id)return;w.removeEventListener('message',on);if(generation!==S.generation){resolve(false);return}S.bricks=Array.isArray(m.bricks)?m.bricks:[];S.data=normalize(S.bricks);S.latestClosedTime=Number(S.bars.at(-1)?.[6]||0);S.building=false;series?.setData(S.data);showChart();restoreAnchor(anchor);saveCache();setMeta();updateLiveFromBuffer();resolve(true)};w.addEventListener('message',on);try{w.postMessage({type:'build',id,generation,box,bars})}catch(e){w.removeEventListener('message',on);S.building=false;reject(e)}})}
function showChart(){const e=$('chartEmpty');if(e)e.classList.add('hide');const h=$('lwcRenkoHost');if(h)h.style.visibility='visible'}
function latest50(){if(!chart||!S.data.length)return;const n=S.data.length;chart.timeScale().setVisibleLogicalRange({from:Math.max(0,n-FIRST_VIEW),to:n+4});setMeta()}
async function olderBatch(count=BATCH){if(S.loading||S.exhausted||!S.bars.length)return false;const generation=S.generation,seq=++S.loadSeq,symbol=S.symbol,first=Number(S.bars[0][0]),anchor=rangeAnchor();S.loading=true;setStatus('Loading older…','loading');try{const ends=Array.from({length:count},(_,i)=>first-1-i*PAGE*MINUTE),settled=await Promise.allSettled(ends.map(end=>fetchPage(end,symbol)));if(generation!==S.generation||seq!==S.loadSeq||symbol!==S.symbol)return false;const pages=settled.filter(x=>x.status==='fulfilled').map(x=>x.value),rows=pages.flat();if(!rows.length){S.exhausted=true;setStatus('History start reached','ready');return false}const before=S.bars.length;S.bars=dedupe([...rows,...S.bars]);const added=S.bars.length-before;S.lastLoad={added,pages:pages.length,first:Number(S.bars[0]?.[0]||0)};if(added===0||pages.some(p=>p.length<PAGE))S.exhausted=added===0||pages.every(p=>p.length<PAGE);if(added>0)await rebuild(anchor);setStatus(S.exhausted?'History start reached':'Ready','ready');return added>0}catch(e){if(generation===S.generation)setStatus('History retry','bad');console.warn('[Renko V9 older]',e);return false}finally{if(generation===S.generation){S.loading=false;setMeta()}}}
function scheduleOlder(){clearTimeout(rangeTimer);rangeTimer=setTimeout(()=>{if(S.loading||S.booting||S.exhausted||S.building)return;const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(r&&r.from<24)void olderBatch(BATCH)},140)}
async function bootHistory(generation){S.booting=true;try{const painted=await loadBarsCache(generation);if(generation!==S.generation)return;setStatus(painted?'Ready · refreshing':'Loading chart…',painted?'ready':'loading');const latest=await fetchPage(undefined,S.symbol);if(generation!==S.generation)return;if(latest.length){S.bars=dedupe(latest);await rebuild();saveBars()}let rounds=0;while(generation===S.generation&&S.data.length<FIRST_VIEW&&!S.exhausted&&rounds++<4){const ok=await olderBatch(BATCH);if(!ok)break;await new Promise(r=>setTimeout(r,0))}if(generation!==S.generation)return;if(S.data.length){latest50(false);setStatus(S.data.length>=FIRST_VIEW?'Ready':'Ready · older history in background','ready')}else setStatus('Offline · retrying','bad');setMeta();setTimeout(scheduleOlder,250)}catch(e){if(generation===S.generation)setStatus(S.data.length?'Cached · feed retry':'Offline · retrying','bad');console.error('[Renko V9 boot]',e)}finally{if(generation===S.generation)S.booting=false}}
function reset(symbol,box){historyAbort?.abort();historyAbort=new AbortController();clearTimeout(rangeTimer);const hadData=S.data.length>0;S.generation++;S.symbol=symbol;S.box=box;S.key=`${symbol}|${box}`;S.bars=[];S.bricks=[];S.data=[];S.loading=false;S.building=false;S.booting=false;S.exhausted=false;S.cached=false;S.following=true;S.latestClosedTime=0;S.lastLoad=null;S.lastLiveId=null;if(!hadData)series?.setData([]);if(liveLine){try{series.removePriceLine(liveLine)}catch{}liveLine=null}showChart();setStatus(hadData?'Switching · previous chart stays visible':'Chart ready · connecting data','ready');setMeta();loadCache();void bootHistory(S.generation)}
function appendLiveTick(t){if(!series||!S.data.length||!(S.box>0)||Number(t.time)<=S.latestClosedTime)return;const id=t.id??t.time;if(id===S.lastLiveId)return;S.lastLiveId=id;const last=S.data.at(-1),lastDir=Number(last._dir);let lastClose=Number(last.close),direction=(lastDir===1||lastDir===-1)?lastDir:(Number(last.close)>=Number(last.open)?1:-1),p=Number(t.price),guard=0;if(!Number.isFinite(p))return;const updateLine=()=>{if(liveLine){try{liveLine.applyOptions({price:p})}catch{}}else{try{liveLine=series.createPriceLine({price:p,color:'#2962ff',lineWidth:1,lineStyle:2,axisLabelVisible:true,title:'LIVE'})}catch{}}};if(Math.abs(p-lastClose)/S.box>2000){updateLine();setStatus('Live feed resyncing','bad');return}const add=(open,close,dir)=>{const prev=S.data.at(-1);const time=Math.max(Math.floor(Number(t.time)/1000),Number(prev?.time||0)+1);const d={time,open,high:Math.max(open,close),low:Math.min(open,close),close,color:dir>=0?'#089981':'#f23645',borderColor:dir>=0?'#22ab94':'#f7525f',wickColor:dir>=0?'#089981':'#f23645',_ms:Number(t.time),_dir:dir,_i:S.data.length};S.data.push(d);series.update(d);lastClose=close;direction=dir};while(guard++<2001){if(direction>=0){if(p>=lastClose+S.box){add(lastClose,lastClose+S.box,1);continue}if(p<=lastClose-2*S.box){add(lastClose-S.box,lastClose-2*S.box,-1);continue}break}else{if(p<=lastClose-S.box){add(lastClose,lastClose-S.box,-1);continue}if(p>=lastClose+2*S.box){add(lastClose+S.box,lastClose+2*S.box,1);continue}break}}updateLine();if(guard>1){if(S.following)chart.timeScale().scrollToRealTime?.();saveCache();queueMeta()}S.frames++}
function updateLiveFromBuffer(){const ticks=window.RWARenkoV3?.state?.historyTicks;if(!Array.isArray(ticks)||!ticks.length)return;for(const t of ticks){if(Number(t.time)>S.latestClosedTime)appendLiveTick(t)}}
function watchTick(){const v=window.RWARenkoV3?.state;if(!v)return;const t=v.historyTicks?.at?.(-1);if(t)appendLiveTick(t);const p=Number(v.lastPrice);if(Number.isFinite(p)&&liveLine){try{liveLine.applyOptions({price:p})}catch{}}}
function createNativeChart(){const wrap=$('chartWrap'),L=window.LightweightCharts;if(!wrap||!L)return false;let host=$('lwcRenkoHost');if(!host){host=document.createElement('div');host.id='lwcRenkoHost';host.setAttribute('aria-label','Native Lightweight Charts Traditional Renko');wrap.prepend(host)}chart=L.createChart(host,{localization:{locale:'en-US'},layout:{background:{type:L.ColorType?.Solid??'solid',color:'#131722'},textColor:'#b2b5be',attributionLogo:true},grid:{vertLines:{color:'rgba(120,123,134,.14)'},horzLines:{color:'rgba(120,123,134,.14)'}},rightPriceScale:{borderColor:'#2a2e39',minimumWidth:64,scaleMargins:{top:.04,bottom:.05}},timeScale:{borderColor:'#2a2e39',timeVisible:true,secondsVisible:false,rightOffset:8,barSpacing:10,minBarSpacing:2,maxBarSpacing:28,fixLeftEdge:false,fixRightEdge:false,lockVisibleTimeRangeOnResize:true},handleScroll:{mouseWheel:true,pressedMouseMove:true,horzTouchDrag:true,vertTouchDrag:true},handleScale:{mouseWheel:true,pinch:true,axisPressedMouseMove:{time:true,price:true},axisDoubleClickReset:{time:true,price:true}},kineticScroll:{mouse:true,touch:true},crosshair:{mode:L.CrosshairMode?.Normal??0}});series=chart.addSeries(L.CandlestickSeries,{upColor:'#089981',downColor:'#f23645',borderUpColor:'#22ab94',borderDownColor:'#f7525f',wickUpColor:'#089981',wickDownColor:'#f23645',priceLineVisible:false,lastValueVisible:true});chart.timeScale().subscribeVisibleLogicalRangeChange?.(r=>{if(r&&S.data.length)S.following=r.to>=S.data.length-1;queueMeta();scheduleOlder()});resizeObserver=new ResizeObserver(entries=>{const r=entries[0]?.contentRect;if(r?.width&&r?.height)chart.resize(Math.floor(r.width),Math.floor(r.height))});resizeObserver.observe(wrap);wireControls();return true}
function shiftRange(frac){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r)return;const w=r.to-r.from,d=w*frac;chart.timeScale().setVisibleLogicalRange({from:r.from+d,to:r.to+d})}
function zoomRange(factor){const r=chart?.timeScale?.().getVisibleLogicalRange?.();if(!r)return;const mid=(r.from+r.to)/2,w=clamp((r.to-r.from)*factor,20,240);chart.timeScale().setVisibleLogicalRange({from:mid-w/2,to:mid+w/2})}
function wireControls(){const click=(id,fn)=>$(id)?.addEventListener('click',e=>{e.preventDefault();e.stopImmediatePropagation();fn()},{capture:true});click('tvPanOlder',()=>shiftRange(-.72));click('tvPanNewer',()=>shiftRange(.72));click('tvZoomOut',()=>zoomRange(1.25));click('tvZoomIn',()=>zoomRange(.8));click('tvReset',()=>{S.following=true;latest50()});click('tvLive',()=>{S.following=true;latest50()});window.addEventListener('keydown',e=>{if(e.target?.matches?.('input,textarea'))return;if(e.key==='ArrowLeft'){e.preventDefault();shiftRange(-.25)}else if(e.key==='ArrowRight'){e.preventDefault();shiftRange(.25)}else if(e.key==='+'||e.key==='='){e.preventDefault();zoomRange(.8)}else if(e.key==='-'){e.preventDefault();zoomRange(1.25)}else if(e.key==='End'){e.preventDefault();S.following=true;latest50()}},{passive:false})}
async function boot(){for(let i=0;i<200&&(!window.LightweightCharts||!window.RWARenkoV3);i++)await new Promise(r=>setTimeout(r,50));if(!window.LightweightCharts)throw Error('Lightweight Charts unavailable');if(!window.RWARenkoV3)throw Error('Renko market engine unavailable');if(!createNativeChart())throw Error('chart host unavailable');showChart();S.interactiveAt=performance.now();window.RWARenkoV9={version:'9.1.0',mode:'native-lightweight-charts',renderer:'tradingview-lightweight-charts-5.1',traditional:{continuationBoxes:1,reversalBoxes:2},historicalSource:'binance-1m-close-background-worker',liveSource:'binance-individual-@trade',state:S,chart,series,loadOlder:olderBatch,goLive:()=>{S.following=true;latest50(false)},latest50};watchTimer=setInterval(()=>{const v=window.RWARenkoV3?.state;if(!v)return;const box=Number(v.box),key=box>0?`${v.selected}|${box}`:'';if(key&&key!==lastKey){lastKey=key;reset(v.selected,box)}},80);tickTimer=setInterval(watchTick,80);const v=window.RWARenkoV3.state;if(Number(v.box)>0){lastKey=`${v.selected}|${Number(v.box)}`;reset(v.selected,Number(v.box))}}
boot().catch(e=>{console.error('[Renko V9]',e);setStatus('Chart retry','bad')});
})();
