(()=>{
'use strict';
if(window.RWARenkoV3)return;

const RESTS=['https://data-api.binance.vision','https://api.binance.com'];
const WSS=['wss://data-stream.binance.vision/ws','wss://stream.binance.com:9443/ws'];
const STORE='rwa_renko_traditional_v3';
const DEFAULT_SYMBOL='BTCUSDT';
const TOP_VISIBLE=500;
const RENDER_LIMIT=500;
const RAW_BUFFER_LIMIT=250000;
const DEFAULT_WINDOW=160;
const MAX_WINDOW=2000;
const STABLE_QUOTES=new Set(['USDT','USDC','FDUSD','TUSD','USDP','DAI','BUSD']);
const EXCLUDED_BASES=new Set(['USDT','USDC','FDUSD','TUSD','USDP','DAI','BUSD','EUR','GBP','TRY','BRL','AUD','RUB','UAH','NGN','ZAR','PLN','RON','ARS','CZK','MXN','JPY','IDR','AED']);
const LEVERAGED=/(UP|DOWN|BULL|BEAR)$/i;
const FALLBACK=['BTCUSDT','ETHUSDT','BNBUSDT','SOLUSDT','XRPUSDT','DOGEUSDT','ADAUSDT','AVAXUSDT','LINKUSDT','DOTUSDT','LTCUSDT','BCHUSDT','TRXUSDT','SUIUSDT','APTUSDT','NEARUSDT','ATOMUSDT','FILUSDT','UNIUSDT','AAVEUSDT','ETCUSDT','HBARUSDT','ICPUSDT','ARBUSDT','OPUSDT','INJUSDT','TIAUSDT','SEIUSDT','RENDERUSDT','PEPEUSDT'];
const $=id=>document.getElementById(id);
const state={markets:[],marketBySymbol:new Map(),symbols:[],selected:DEFAULT_SYMBOL,box:100,bricks:[],historyTicks:[],tickCount:0,lastPrice:NaN,lastTickTime:0,lastTradeId:null,lastClose:NaN,direction:0,anchor:NaN,visible:DEFAULT_WINDOW,pan:0,historyMode:'all',genesisTime:0,genesisTradeId:null,rawTrimmed:false,ws:null,wsToken:0,wsEndpoint:0,retry:0,retryTimer:0,renderPending:false,renderSlice:null,drag:null,savedBoxes:{},tickerTimer:0,healthTimer:0,polling:false,lastPollAt:0,lastUniverseAt:0,feedState:'CONNECTING',sourceErrors:[]};

function loadPrefs(){try{const p=JSON.parse(localStorage.getItem(STORE)||'{}');if(typeof p.selected==='string')state.selected=p.selected;if(Number.isFinite(Number(p.visible)))state.visible=Math.max(20,Math.min(MAX_WINDOW,Number(p.visible)));if(p.boxes&&typeof p.boxes==='object')state.savedBoxes=p.boxes;if(p.historyMode==='all'||p.historyMode==='window')state.historyMode=p.historyMode}catch{}}
function savePrefs(){try{localStorage.setItem(STORE,JSON.stringify({selected:state.selected,visible:state.visible,boxes:state.savedBoxes,historyMode:state.historyMode}))}catch{}}
function market(sym=state.selected){return state.marketBySymbol.get(sym)||{symbol:sym,base:String(sym).replace(/(USDT|USDC|FDUSD|BTC|ETH|BNB)$/,''),quote:String(sym).match(/(USDT|USDC|FDUSD|BTC|ETH|BNB)$/)?.[1]||''}}
function fmt(v){const n=Number(v);if(!Number.isFinite(n))return '—';const a=Math.abs(n),d=a>=1000?2:a>=100?3:a>=1?4:a>=.01?6:8;return n.toLocaleString(undefined,{maximumFractionDigits:d})}
function fmtCompact(v){const n=Number(v);if(!Number.isFinite(n))return '—';if(n>=1e9)return `${(n/1e9).toFixed(1)}B`;if(n>=1e6)return `${(n/1e6).toFixed(1)}M`;if(n>=1e3)return `${(n/1e3).toFixed(1)}K`;return fmt(n)}
function fmtInput(v){const n=Number(v);if(!Number.isFinite(n))return '';const a=Math.abs(n),d=a>=100?2:a>=1?4:a>=.01?6:8;return n.toFixed(d).replace(/0+$/,'').replace(/\.$/,'')}
function niceNumber(x){if(!(x>0))return 1;const e=Math.floor(Math.log10(x)),f=x/10**e,m=f<=1?1:f<=2?2:f<=5?5:10;return m*10**e}
function setText(id,text){const e=$(id);if(e)e.textContent=text}
function setFeed(kind,text){state.feedState=text;const e=$('feedPill');if(!e)return;e.className='feed-pill'+(kind?` ${kind}`:'');const b=e.querySelector('b');if(b)b.textContent=text}
async function fetchJson(path,ms=10000){let last;for(const root of RESTS){const c=new AbortController(),t=setTimeout(()=>c.abort(),ms);try{const r=await fetch(root+path,{cache:'no-store',signal:c.signal});if(!r.ok)throw Error(`HTTP ${r.status}`);const j=await r.json();clearTimeout(t);return{json:j,root}}catch(e){clearTimeout(t);last=e;state.sourceErrors.push(`${root}: ${e.message}`)}}throw last||Error('All market-data endpoints failed')}

function quoteUsdMap(tickers){const m=new Map([['USDT',1],['USDC',1],['FDUSD',1],['TUSD',1],['USDP',1],['DAI',1],['BUSD',1]]),by=new Map(tickers.map(x=>[x.symbol,x]));for(const q of ['BTC','ETH','BNB','SOL','XRP','DOGE']){const n=Number(by.get(`${q}USDT`)?.lastPrice);if(n>0)m.set(q,n)}return{by,m}}
function eligibleSymbol(x,qUsd){return x&&x.status==='TRADING'&&x.isSpotTradingAllowed!==false&&!EXCLUDED_BASES.has(x.baseAsset)&&!LEVERAGED.test(x.baseAsset)&&(STABLE_QUOTES.has(x.quoteAsset)||qUsd.has(x.quoteAsset))}
async function loadUniverse(){setText('pairTotal','Loading…');try{const [infoRes,tickerRes]=await Promise.all([fetchJson('/api/v3/exchangeInfo',12000),fetchJson('/api/v3/ticker/24hr',12000)]);const tickers=Array.isArray(tickerRes.json)?tickerRes.json:[],{by,m:qUsd}=quoteUsdMap(tickers),rows=[];for(const x of infoRes.json.symbols||[]){if(!eligibleSymbol(x,qUsd))continue;const t=by.get(x.symbol)||{},last=Number(t.lastPrice),change=Number(t.priceChangePercent),qv=Number(t.quoteVolume),mult=STABLE_QUOTES.has(x.quoteAsset)?1:(qUsd.get(x.quoteAsset)||0),volumeUsd=Number.isFinite(qv)&&mult>0?qv*mult:0;rows.push({symbol:x.symbol,base:x.baseAsset,quote:x.quoteAsset,last:Number.isFinite(last)?last:NaN,change:Number.isFinite(change)?change:0,volumeUsd,rank:0})}rows.sort((a,b)=>b.volumeUsd-a.volumeUsd||a.symbol.localeCompare(b.symbol));rows.forEach((x,i)=>x.rank=i+1);state.markets=rows;state.marketBySymbol=new Map(rows.map(x=>[x.symbol,x]));state.symbols=rows.map(x=>x.symbol);state.lastUniverseAt=Date.now();if(!state.marketBySymbol.has(state.selected))state.selected=state.marketBySymbol.has(DEFAULT_SYMBOL)?DEFAULT_SYMBOL:(rows[0]?.symbol||DEFAULT_SYMBOL);const shown=Math.min(TOP_VISIBLE,rows.length);setText('pairTotal',`${rows.length.toLocaleString()} markets`);setText('universeNote',rows.length>=500?`Top ${shown} by 24h liquidity · all ${rows.length.toLocaleString()} searchable`:`${rows.length.toLocaleString()} eligible Binance crypto markets available`);renderPairs();renderQuickPairs()}catch(e){console.warn('Renko universe degraded',e);state.markets=FALLBACK.map((symbol,i)=>({symbol,base:symbol.replace(/USDT$/,''),quote:'USDT',last:NaN,change:0,volumeUsd:0,rank:i+1}));state.marketBySymbol=new Map(state.markets.map(x=>[x.symbol,x]));state.symbols=state.markets.map(x=>x.symbol);if(!state.symbols.includes(state.selected))state.selected=DEFAULT_SYMBOL;setText('pairTotal',`${state.symbols.length} fallback pairs`);setText('universeNote','Market universe degraded · retrying automatically');renderPairs();renderQuickPairs();setTimeout(loadUniverse,8000)}}
function renderPairs(){const q=String($('pairSearch')?.value||'').trim().toUpperCase(),pool=q?state.markets.filter(x=>x.symbol.includes(q)||x.base.includes(q)||x.quote.includes(q)):state.markets,a=pool.slice(0,RENDER_LIMIT),box=$('pairList');if(!box)return;const f=document.createDocumentFragment();for(const x of a){const row=document.createElement('button');row.type='button';row.className='pair-row'+(x.symbol===state.selected?' active':'');row.dataset.symbol=x.symbol;row.innerHTML=`<span class="rank">#${x.rank}</span><span class="left-meta"><span class="mini-icon">${x.base.slice(0,2)}</span><span><b>${x.base} / ${x.quote}</b><small>${fmtCompact(x.volumeUsd)} 24h</small></span></span><span class="pair-live"><b>${fmt(x.last)}</b><small class="${x.change>=0?'up':'down'}">${x.change>=0?'+':''}${x.change.toFixed(2)}%</small></span>`;row.onclick=()=>selectSymbol(x.symbol);f.appendChild(row)}box.replaceChildren(f);if(!a.length)box.innerHTML='<div class="empty">No crypto market matches.</div>';setText('pairShown',q?`${a.length} result${a.length===1?'':'s'}`:`Top ${a.length} shown`)}
function renderQuickPairs(){const host=$('quickPairs');if(!host)return;host.querySelectorAll('[data-quick]').forEach(b=>{const base=b.dataset.quick,hit=state.markets.find(x=>x.base===base);b.disabled=!hit;b.dataset.symbol=hit?.symbol||'';b.classList.toggle('active',hit?.symbol===state.selected)})}

function resetEngine({newGenesis=false}={}){state.bricks=[];state.tickCount=0;state.lastPrice=NaN;state.lastTickTime=0;state.lastTradeId=null;state.lastClose=NaN;state.direction=0;state.anchor=NaN;state.pan=0;if(newGenesis){state.genesisTime=0;state.genesisTradeId=null;state.rawTrimmed=false}}
function addBrick(open,close,direction,tick){state.bricks.push({i:state.bricks.length+1,open,close,high:Math.max(open,close),low:Math.min(open,close),direction,time:Number(tick.time||Date.now()),tradeId:tick.id??null});state.lastClose=close;state.direction=direction}
function rememberTick(id,p,qty,time){state.historyTicks.push({id:Number.isFinite(id)?id:null,price:p,qty:Number(qty)||0,time});if(!state.genesisTime){state.genesisTime=time;state.genesisTradeId=Number.isFinite(id)?id:null}if(state.historyTicks.length>RAW_BUFFER_LIMIT){state.historyTicks.splice(0,state.historyTicks.length-RAW_BUFFER_LIMIT);state.rawTrimmed=true}}
function applyTick(tick,count=true,remember=true){const p=Number(tick.price);if(!Number.isFinite(p)||!(state.box>0))return false;const id=tick.id==null?null:Number(tick.id);if(id!=null&&Number.isFinite(id)&&state.lastTradeId!=null&&id<=state.lastTradeId)return false;if(id!=null&&Number.isFinite(id))state.lastTradeId=id;state.lastPrice=p;state.lastTickTime=Number(tick.time||Date.now());if(count)state.tickCount++;if(remember)rememberTick(id,p,tick.qty,state.lastTickTime);if(!Number.isFinite(state.anchor)){state.anchor=Math.floor(p/state.box)*state.box;state.lastClose=state.anchor}let guard=0;while(guard++<5000){if(state.direction===0){if(p>=state.lastClose+state.box){addBrick(state.lastClose,state.lastClose+state.box,1,tick);continue}if(p<=state.lastClose-state.box){addBrick(state.lastClose,state.lastClose-state.box,-1,tick);continue}break}if(state.direction===1){if(p>=state.lastClose+state.box){addBrick(state.lastClose,state.lastClose+state.box,1,tick);continue}if(p<=state.lastClose-2*state.box){addBrick(state.lastClose-state.box,state.lastClose-2*state.box,-1,tick);continue}break}if(p<=state.lastClose-state.box){addBrick(state.lastClose,state.lastClose-state.box,-1,tick);continue}if(p>=state.lastClose+2*state.box){addBrick(state.lastClose+state.box,state.lastClose+2*state.box,1,tick);continue}break}flashPrice();return true}
function rebuild({restartGenesis=false}={}){const ticks=state.historyTicks.slice(),oldBox=state.box;if(restartGenesis){state.genesisTime=ticks[0]?.time||Date.now();state.genesisTradeId=ticks[0]?.id??null;state.rawTrimmed=false}resetEngine();state.box=oldBox;state.historyTicks=[];for(const t of ticks)applyTick(t,true,true);setText('brickValue',fmt(state.box));if($('brickSize'))$('brickSize').value=fmtInput(state.box);state.historyMode='all';state.pan=0;updateStats();scheduleDraw()}
function suggestedBox(ticks=state.historyTicks){const prices=ticks.map(x=>Number(x.price)).filter(Number.isFinite);if(!prices.length)return Number.isFinite(state.lastPrice)?niceNumber(state.lastPrice*.001):1;const last=prices.at(-1),hi=Math.max(...prices),lo=Math.min(...prices),range=hi-lo;return niceNumber(Math.max(range/24,last*.00018,Number.EPSILON))}
function setBox(v,save=true){const n=Number(v);if(!(n>0))return false;state.box=n;if(save){state.savedBoxes[state.selected]=n;savePrefs()}rebuild({restartGenesis:state.rawTrimmed});return true}
function applyPreset(pct){if(Number.isFinite(state.lastPrice))setBox(niceNumber(state.lastPrice*pct),true)}
function useAutoBox(){setBox(suggestedBox(),true)}

async function loadHistory(symbol){setFeed('','LOADING');setText('historyState','Loading chart genesis from 1,000 raw trades…');$('chartEmpty')?.classList.remove('hide');let ticks=[];try{const r=await fetchJson(`/api/v3/trades?symbol=${encodeURIComponent(symbol)}&limit=1000`,10000);ticks=(Array.isArray(r.json)?r.json:[]).map(x=>({id:Number(x.id),price:Number(x.price),qty:Number(x.qty),time:Number(x.time)})).filter(x=>Number.isFinite(x.price)&&Number.isFinite(x.time)).sort((a,b)=>(a.id-b.id)||(a.time-b.time))}catch(e){console.warn('Renko raw trade warmup',e);setText('historyState',`Warmup unavailable · ${e.message}`)}if(symbol!==state.selected)return;state.historyTicks=[];resetEngine({newGenesis:true});const saved=Number(state.savedBoxes?.[symbol]);if(saved>0)state.box=saved;else if(ticks.length)state.box=suggestedBox(ticks);for(const t of ticks)applyTick(t,true,true);state.historyMode='all';state.pan=0;setText('historyState',ticks.length?`${ticks.length.toLocaleString()} raw trades seeded chart genesis · all formed bricks retained`:'Live raw ticks only · genesis starts with first live trade');connectLive(symbol);updateStats();scheduleDraw()}
function closeLive(){state.wsToken++;clearTimeout(state.retryTimer);state.retryTimer=0;if(state.ws){try{state.ws.onclose=null;state.ws.close()}catch{}state.ws=null}}
function connectLive(symbol){closeLive();const token=state.wsToken,endpoint=state.wsEndpoint%WSS.length,url=`${WSS[endpoint]}/${symbol.toLowerCase()}@trade`;setFeed('','CONNECTING');let ws;try{ws=new WebSocket(url)}catch{scheduleReconnect(symbol,token,true);return}state.ws=ws;ws.onopen=()=>{if(token!==state.wsToken)return;state.retry=0;setFeed('live','LIVE TICKS')};ws.onmessage=e=>{if(token!==state.wsToken)return;let x;try{x=JSON.parse(e.data)}catch{return}if(x.e!=='trade'||x.s!==symbol)return;if(applyTick({id:Number(x.t),price:Number(x.p),qty:Number(x.q),time:Number(x.T)},true,true)){setFeed('live','LIVE TICKS');scheduleDraw()}};ws.onerror=()=>{if(token===state.wsToken)setFeed('bad','FEED RETRY')};ws.onclose=()=>{if(token!==state.wsToken)return;scheduleReconnect(symbol,token,true)}}
function scheduleReconnect(symbol,token,rotate=false){if(token!==state.wsToken)return;clearTimeout(state.retryTimer);if(rotate)state.wsEndpoint=(state.wsEndpoint+1)%WSS.length;const delay=Math.min(12000,700*2**Math.min(state.retry++,5));setFeed('','RECONNECTING');state.retryTimer=setTimeout(()=>{if(token===state.wsToken&&symbol===state.selected)connectLive(symbol)},delay)}
async function pollLatestRawTrade(){if(state.polling||!state.selected)return;state.polling=true;state.lastPollAt=Date.now();try{const r=await fetchJson(`/api/v3/trades?symbol=${encodeURIComponent(state.selected)}&limit=1`,7000),x=Array.isArray(r.json)?r.json[0]:null;if(x&&applyTick({id:Number(x.id),price:Number(x.price),qty:Number(x.qty),time:Number(x.time)},true,true)){setFeed('live','LIVE · REST TICK');scheduleDraw()}}catch(e){console.warn('Renko raw tick watchdog',e)}finally{state.polling=false}}

async function selectSymbol(symbol){if(!state.marketBySymbol.has(symbol)&&!state.symbols.includes(symbol))return;state.selected=symbol;savePrefs();renderPairs();renderQuickPairs();const m=market();setText('pairName',`${m.base} / ${m.quote}`);setText('pairIcon',m.base.slice(0,2));setText('sourceText',`Binance raw trade tick · ${m.symbol}@trade`);state.historyTicks=[];resetEngine({newGenesis:true});updateStats();scheduleDraw();document.querySelector('.markets')?.classList.remove('open');await loadHistory(symbol)}
function thresholds(){if(!Number.isFinite(state.lastClose)||!(state.box>0))return{up:NaN,down:NaN};if(state.direction===1)return{up:state.lastClose+state.box,down:state.lastClose-2*state.box};if(state.direction===-1)return{up:state.lastClose+2*state.box,down:state.lastClose-state.box};return{up:state.lastClose+state.box,down:state.lastClose-state.box}}
function dateLabel(t,withTime=true){if(!Number.isFinite(Number(t)))return '—';const d=new Date(Number(t));return withTime?d.toLocaleString():d.toLocaleDateString()}
function historyBounds(){const n=state.bricks.length;if(!n)return{from:state.genesisTime||state.lastTickTime,to:state.lastTickTime,count:0};return{from:state.bricks[0].time,to:state.bricks[n-1].time,count:n}}
function setHistoryMode(mode){state.historyMode=mode==='window'?'window':'all';if(state.historyMode==='all')state.pan=0;savePrefs();updateHistoryUI();scheduleDraw()}
function goStart(){state.historyMode='window';state.pan=Math.max(0,state.bricks.length-state.visible);savePrefs();updateHistoryUI();scheduleDraw()}
function goLive(){state.historyMode='window';state.pan=0;if($('followLive'))$('followLive').checked=true;savePrefs();updateHistoryUI();scheduleDraw()}
function panWindow(delta){state.historyMode='window';state.pan=Math.max(0,Math.min(Math.max(0,state.bricks.length-state.visible),state.pan+delta));if($('followLive')&&state.pan>0)$('followLive').checked=false;savePrefs();updateHistoryUI();scheduleDraw()}
function updateHistoryUI(){const n=state.bricks.length,b=historyBounds(),all=state.historyMode==='all';setText('historyCount',`${n.toLocaleString()} bricks`);setText('historyFrom',dateLabel(b.from));setText('historyTo',dateLabel(b.to));setText('historyCoverage',all?`ALL · genesis → live`:`WINDOW · ${Math.min(state.visible,n).toLocaleString()} bricks`);const a=$('historyAll');if(a)a.classList.toggle('active',all);const live=$('historyLive');if(live)live.classList.toggle('active',!all&&state.pan===0);const range=$('historyRange');if(range){const max=Math.max(0,n-state.visible),start=Math.max(0,n-state.pan-Math.min(state.visible,n));range.max=String(max);range.value=String(Math.min(max,start));range.disabled=all||max===0}const note=$('historyIntegrity');if(note)note.textContent=state.rawTrimmed?'Full brick history retained · old raw ticks compacted; changing box starts a new genesis':'Full brick history retained from chart genesis'}
function updateStats(){setText('lastPrice',fmt(state.lastPrice));setText('brickValue',fmt(state.box));setText('brickCount',state.bricks.length.toLocaleString());setText('tickCount',state.tickCount.toLocaleString());setText('visibleValue',state.historyMode==='all'?'ALL':state.visible);const t=thresholds();setText('nextUp',fmt(t.up));setText('nextDown',fmt(t.down));$('chartEmpty')?.classList.toggle('hide',state.tickCount>0||state.bricks.length>0);const m=market();if(Number.isFinite(state.lastPrice)){m.last=state.lastPrice;const row=document.querySelector(`.pair-row[data-symbol="${CSS.escape(state.selected)}"] .pair-live b`);if(row)row.textContent=fmt(state.lastPrice)}updateHistoryUI()}
function flashPrice(){const e=$('lastPrice');if(!e)return;e.classList.remove('tick-flash');void e.offsetWidth;e.classList.add('tick-flash')}

function scheduleDraw(){if(state.renderPending)return;state.renderPending=true;requestAnimationFrame(()=>{state.renderPending=false;draw();updateStats()})}
function canvasSize(){const c=$('renkoCanvas'),r=c.getBoundingClientRect(),d=Math.min(2,window.devicePixelRatio||1),w=Math.max(1,Math.round(r.width)),h=Math.max(1,Math.round(r.height));if(c.width!==Math.round(w*d)||c.height!==Math.round(h*d)){c.width=Math.round(w*d);c.height=Math.round(h*d)}const x=c.getContext('2d');x.setTransform(d,0,0,d,0,0);return{c,x,w,h}}
function sliceBricks(){const n=state.bricks.length;if(state.historyMode==='all')return{start:0,end:n,a:state.bricks,all:true};const end=Math.max(0,n-state.pan),start=Math.max(0,end-state.visible);return{start,end,a:state.bricks.slice(start,end),all:false}}
function roundRect(ctx,x,y,w,h,r,fill,stroke){if(w<0){x+=w;w=-w}if(h<0){y+=h;h=-h}r=Math.min(r,w/2,h/2);ctx.beginPath();ctx.moveTo(x+r,y);ctx.arcTo(x+w,y,x+w,y+h,r);ctx.arcTo(x+w,y+h,x,y+h,r);ctx.arcTo(x,y+h,x,y,r);ctx.arcTo(x,y,x+w,y,r);if(fill)ctx.fill();if(stroke)ctx.stroke()}
function drawGrid(x,w,h,pad,lo,hi,yy){x.lineWidth=1;x.font='600 7px system-ui';x.textAlign='left';x.textBaseline='middle';for(let i=0;i<=6;i++){const y=pad.t+(h-pad.t-pad.b)*i/6;x.strokeStyle='#151b22';x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();if(yy){x.fillStyle='#596572';x.fillText(fmt(hi-(hi-lo)*i/6),w-pad.r+7,y)}}}
function drawTimeLabels(x,a,pad,w,h,count,step){if(!a.length)return;const span=(a.at(-1)?.time||0)-(a[0]?.time||0),every=Math.max(1,Math.ceil(a.length/6));x.fillStyle='#56616e';x.font='600 7px system-ui';x.textAlign='center';for(let i=0;i<a.length;i+=every){const cx=pad.l+(i+(count-a.length)+.5)*step,dt=new Date(a[i].time),label=span>86400000?`${dt.getMonth()+1}/${dt.getDate()}`:`${String(dt.getHours()).padStart(2,'0')}:${String(dt.getMinutes()).padStart(2,'0')}`;x.fillText(label,cx,h-11)}}
function drawBrickSeries(x,a,pad,cw,yy,count){if(!a.length)return;const step=cw/count;if(step>=.7){const bw=Math.max(1,Math.min(24,step*.76));a.forEach((b,i)=>{const cx=pad.l+(i+(count-a.length)+.5)*step,y1=yy(b.open),y2=yy(b.close),top=Math.min(y1,y2),height=Math.max(1,Math.abs(y2-y1));x.fillStyle=b.direction>0?'#2dbb86':'#e65d70';x.strokeStyle=b.direction>0?'#55d8a8':'#ff7b8b';x.globalAlpha=.9;x.fillRect(cx-bw/2,top,bw,height);x.globalAlpha=1;if(bw>2)x.strokeRect(cx-bw/2+.5,top+.5,Math.max(1,bw-1),Math.max(1,height-1))});return}const maxDraw=Math.max(300,Math.floor(cw*1.7)),stride=Math.max(1,Math.ceil(a.length/maxDraw)),groups=Math.ceil(a.length/stride),gStep=cw/groups;for(let gi=0,i=0;i<a.length;i+=stride,gi++){const g=a.slice(i,Math.min(a.length,i+stride)),first=g[0],last=g[g.length-1],lo=Math.min(...g.map(b=>b.low)),hi=Math.max(...g.map(b=>b.high)),cx=pad.l+(gi+.5)*gStep,yhi=yy(hi),ylo=yy(lo),yo=yy(first.open),yc=yy(last.close),up=last.close>=first.open;x.strokeStyle=up?'#3ccf98':'#ef687a';x.globalAlpha=.72;x.beginPath();x.moveTo(cx,yhi);x.lineTo(cx,ylo);x.stroke();x.globalAlpha=.9;x.fillStyle=up?'#2dbb86':'#e65d70';x.fillRect(cx-Math.max(.5,gStep*.34),Math.min(yo,yc),Math.max(1,gStep*.68),Math.max(1,Math.abs(yc-yo)));x.globalAlpha=1}}
function draw(){const {x,w,h}=canvasSize();x.clearRect(0,0,w,h);x.fillStyle='#080b0f';x.fillRect(0,0,w,h);const pad={l:10,r:72,t:18,b:28},cw=Math.max(1,w-pad.l-pad.r),ch=Math.max(1,h-pad.t-pad.b),sl=sliceBricks();state.renderSlice=sl;const lows=[],highs=[];for(const b of sl.a){lows.push(b.low);highs.push(b.high)}if(Number.isFinite(state.lastPrice)){lows.push(state.lastPrice);highs.push(state.lastPrice)}if(!lows.length){drawGrid(x,w,h,pad,0,1);return}let lo=Math.min(...lows),hi=Math.max(...highs);const extra=Math.max(state.box*1.5,(hi-lo)*.08||state.box);lo-=extra;hi+=extra;const range=hi-lo||1,yy=v=>pad.t+(hi-v)/range*ch;drawGrid(x,w,h,pad,lo,hi,yy);const count=sl.all?Math.max(1,sl.a.length):Math.max(state.visible,sl.a.length||1),step=cw/count;drawBrickSeries(x,sl.a,pad,cw,yy,count);const t=thresholds();for(const [v,col] of [[t.up,'#2f9f78'],[t.down,'#b34d5c']])if(Number.isFinite(v)&&v>=lo&&v<=hi){const y=yy(v);x.save();x.setLineDash([4,5]);x.strokeStyle=col;x.globalAlpha=.45;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();x.restore()}if(Number.isFinite(state.lastPrice)){const y=yy(state.lastPrice);x.strokeStyle='#8d7ef4';x.globalAlpha=.65;x.beginPath();x.moveTo(pad.l,y);x.lineTo(w-pad.r,y);x.stroke();x.globalAlpha=1;x.fillStyle='#796bea';roundRect(x,w-pad.r+5,y-10,63,20,5,true,false);x.fillStyle='#fff';x.font='700 8px system-ui';x.textAlign='center';x.textBaseline='middle';x.fillText(fmt(state.lastPrice),w-pad.r+36,y)}drawTimeLabels(x,sl.a,pad,w,h,count,step)}

async function refreshTickerUniverse(){if(document.hidden||Date.now()-state.lastUniverseAt<15000)return;try{const r=await fetchJson('/api/v3/ticker/24hr',9000),tickers=Array.isArray(r.json)?r.json:[],by=new Map(tickers.map(x=>[x.symbol,x]));for(const m of state.markets){const t=by.get(m.symbol);if(!t)continue;const last=Number(t.lastPrice),chg=Number(t.priceChangePercent);if(Number.isFinite(last))m.last=last;if(Number.isFinite(chg))m.change=chg}state.lastUniverseAt=Date.now();renderPairs()}catch(e){console.warn('Ticker refresh skipped',e)}}
function healthTick(){const now=Date.now(),age=state.lastTickTime?now-state.lastTickTime:Infinity;setText('tickAge',Number.isFinite(age)?(age<1000?`${age} ms`:`${Math.floor(age/1000)} s`):'waiting');const health=$('tickHealth');if(health){health.className='tick-health '+(age<5000?'ok':age<20000?'wait':'bad');health.textContent=age<5000?'MOVING':age<20000?'WAITING':'STALE'}if(age>12000&&now-state.lastPollAt>9000)pollLatestRawTrade();if(age>35000&&state.ws&&state.ws.readyState===WebSocket.OPEN)scheduleReconnect(state.selected,state.wsToken,true)}
function bind(){
  $('pairSearch')?.addEventListener('input',renderPairs);
  $('applyBrick')?.addEventListener('click',()=>{if(!setBox($('brickSize')?.value,true))$('brickSize')?.focus()});
  $('brickSize')?.addEventListener('keydown',e=>{if(e.key==='Enter')$('applyBrick')?.click()});
  $('zoomIn')?.addEventListener('click',()=>{state.historyMode='window';state.visible=Math.max(20,state.visible-20);savePrefs();scheduleDraw()});
  $('zoomOut')?.addEventListener('click',()=>{state.historyMode='window';state.visible=Math.min(MAX_WINDOW,state.visible+20);savePrefs();scheduleDraw()});
  $('resetChart')?.addEventListener('click',()=>rebuild({restartGenesis:state.rawTrimmed}));
  $('autoBox')?.addEventListener('click',useAutoBox);
  document.querySelectorAll('[data-box-pct]').forEach(b=>b.addEventListener('click',()=>applyPreset(Number(b.dataset.boxPct))));
  $('quickPairs')?.addEventListener('click',e=>{const b=e.target.closest('[data-quick]');if(b?.dataset.symbol)selectSymbol(b.dataset.symbol)});
  $('openPairs')?.addEventListener('click',()=>document.querySelector('.markets')?.classList.toggle('open'));
  $('historyAll')?.addEventListener('click',()=>setHistoryMode('all'));
  $('historyStart')?.addEventListener('click',goStart);
  $('historyLive')?.addEventListener('click',goLive);
  $('historyPrev')?.addEventListener('click',()=>panWindow(Math.max(20,Math.floor(state.visible*.8))));
  $('historyNext')?.addEventListener('click',()=>panWindow(-Math.max(20,Math.floor(state.visible*.8))));
  $('historyRange')?.addEventListener('input',e=>{const n=state.bricks.length,start=Number(e.target.value)||0;state.historyMode='window';state.pan=Math.max(0,n-(start+state.visible));if($('followLive'))$('followLive').checked=state.pan===0;updateHistoryUI();scheduleDraw()});
  $('followLive')?.addEventListener('change',e=>{if(e.target.checked)goLive()});
  const wrap=$('chartWrap');if(wrap){wrap.addEventListener('wheel',e=>{e.preventDefault();if(state.historyMode==='all'){state.historyMode='window';state.visible=Math.min(300,Math.max(80,state.bricks.length||DEFAULT_WINDOW));state.pan=0}else state.visible=Math.max(20,Math.min(MAX_WINDOW,state.visible+(e.deltaY>0?20:-20)));savePrefs();scheduleDraw()},{passive:false});wrap.addEventListener('pointerdown',e=>{if(state.historyMode==='all'){state.historyMode='window';state.visible=Math.min(300,Math.max(80,state.bricks.length||DEFAULT_WINDOW));state.pan=0}state.drag={x:e.clientX,pan:state.pan};wrap.setPointerCapture?.(e.pointerId)});wrap.addEventListener('pointermove',e=>{if(!state.drag)return;const d=e.clientX-state.drag.x,step=Math.max(5,wrap.clientWidth/state.visible);state.pan=Math.max(0,Math.min(Math.max(0,state.bricks.length-state.visible),Math.round(state.drag.pan-d/step)));if($('followLive')?.checked&&state.pan>0)$('followLive').checked=false;scheduleDraw()});wrap.addEventListener('pointerup',()=>state.drag=null);wrap.addEventListener('pointercancel',()=>state.drag=null)}
  window.addEventListener('resize',scheduleDraw,{passive:true});
  document.addEventListener('visibilitychange',()=>{if(!document.hidden){healthTick();if(Date.now()-state.lastTickTime>15000)connectLive(state.selected)}})
}
async function boot(){loadPrefs();bind();await loadUniverse();await selectSymbol(state.selected);clearInterval(state.healthTimer);state.healthTimer=setInterval(healthTick,1000);clearInterval(state.tickerTimer);state.tickerTimer=setInterval(refreshTickerUniverse,30000);healthTick()}

window.RWARenkoV3={version:'3.0.0',source:'raw-trade-ticks-only',method:'traditional-fixed-box',reversalBoxes:2,universe:'top-500-liquidity-plus-search-all',history:'all-bricks-from-chart-genesis',historyScope:'chart-genesis-not-exchange-lifetime',state,applyTick,setBox,selectSymbol,setHistoryMode,goStart,goLive,historyBounds,reloadUniverse:loadUniverse,refreshTickerUniverse};window.RWARenko=window.RWARenkoV3;boot().catch(e=>{console.error('RWA Renko boot',e);setFeed('bad','RETRY');setText('historyState',`Startup retry · ${e.message}`);setTimeout(()=>boot().catch(console.error),5000)});
})();
