import assert from 'node:assert/strict';
import fs from 'node:fs';import path from 'node:path';import {fileURLToPath} from 'node:url';import solc from 'solc';import ganache from 'ganache';import {ethers} from 'ethers';
const here=path.dirname(fileURLToPath(import.meta.url)),root=path.resolve(here,'..');const read=r=>fs.readFileSync(path.join(root,r),'utf8');
function findImports(p){for(const x of [path.join(root,p),path.join(root,'contracts',p),path.join(root,'node_modules',p)])if(fs.existsSync(x))return{contents:fs.readFileSync(x,'utf8')};return{error:`Import not found: ${p}`}}
function compile(){const sources={};for(const f of ['contracts/RWAToken.sol','contracts/RWASeriesRegistry.sol','contracts/RWADistributionVault.sol'])sources[f]={content:read(f)};const out=JSON.parse(solc.compile(JSON.stringify({language:'Solidity',sources,settings:{optimizer:{enabled:true,runs:200},outputSelection:{'*':{'*':['abi','evm.bytecode.object']}}}}),{import:findImports}));const errors=(out.errors||[]).filter(x=>x.severity==='error');if(errors.length)throw Error(errors.map(x=>x.formattedMessage).join('\n'));return out.contracts}
const artifact=(c,f,n)=>c[f][n];async function deploy(a,s,args=[]){const f=new ethers.ContractFactory(a.abi,'0x'+a.evm.bytecode.object,s),c=await f.deploy(...args);await c.waitForDeployment();return c}async function reverts(fn,label){let ok=false;try{const x=await fn();if(x?.wait)await x.wait()}catch{ok=true}assert.equal(ok,true,label)}
const c=compile(),rpc=ganache.provider({logging:{quiet:true},wallet:{totalAccounts:6,defaultBalance:1000}}),provider=new ethers.BrowserProvider(rpc),admin=await provider.getSigner(0),treasury=await provider.getSigner(1),a=await provider.getSigner(2),b=await provider.getSigner(3);const adminAddr=await admin.getAddress(),treasuryAddr=await treasury.getAddress(),aAddr=await a.getAddress(),bAddr=await b.getAddress();
const registry=await deploy(artifact(c,'contracts/RWASeriesRegistry.sol','RWASeriesRegistry'),admin,[adminAddr,100]);const ISSUER=await registry.ISSUER_ROLE(),REVIEWER=await registry.REVIEWER_ROLE();await(await registry.grantRole(ISSUER,adminAddr)).wait();await(await registry.grantRole(REVIEWER,adminAddr)).wait();const sid=ethers.id('HOTEL-BALI-001'),meta=ethers.id('metadata'),immutable=ethers.id('immutable-economics-v1'),governed=ethers.id('governed-v1'),legal=ethers.id('legal-evidence');await(await registry.createSeries(sid,adminAddr,meta,immutable,governed)).wait();await reverts(()=>registry.activateSeries(sid,ethers.ZeroHash),'legal evidence required');await(await registry.activateSeries(sid,legal)).wait();let s=await registry.series(sid);assert.equal(s.active,true);assert.equal(s.immutableEconomicHash,immutable);
const salt=ethers.id('proposal-1'),newGoverned=ethers.id('governed-v2'),pid=await registry.proposeGovernedEconomicHash.staticCall(sid,newGoverned,salt);await(await registry.proposeGovernedEconomicHash(sid,newGoverned,salt)).wait();const proposal=await registry.proposal(pid),latest=await provider.getBlock('latest');assert.ok(Number(proposal.executeAfter)>Number(latest.timestamp),'governed change must have a future executeAfter');await reverts(()=>registry.executeGovernedEconomicHash(sid,pid),'notice must block immediate governed change');s=await registry.series(sid);assert.equal(s.governedEconomicHash,governed,'governed hash must stay unchanged during notice');assert.equal(s.immutableEconomicHash,immutable,'immutable economics must not mutate');
const token=await deploy(artifact(c,'contracts/RWAToken.sol','RWAToken'),admin,['Payout USD','pUSD',treasuryAddr,ethers.parseEther('100000')]);const vault=await deploy(artifact(c,'contracts/RWADistributionVault.sol','RWADistributionVault'),admin,[adminAddr,await registry.getAddress()]);const DISTRIBUTOR=await vault.DISTRIBUTOR_ROLE();await(await vault.grantRole(DISTRIBUTOR,treasuryAddr)).wait();const coder=ethers.AbiCoder.defaultAbiCoder();const leaf=(index,account,amount)=>ethers.keccak256(ethers.concat([ethers.keccak256(coder.encode(['uint256','address','uint256'],[index,account,amount]))]));const amountA=ethers.parseEther('600'),amountB=ethers.parseEther('400'),leafA=leaf(0,aAddr,amountA),leafB=leaf(1,bAddr,amountB);const rootHash=BigInt(leafA)<BigInt(leafB)?ethers.keccak256(ethers.concat([leafA,leafB])):ethers.keccak256(ethers.concat([leafB,leafA]));const total=amountA+amountB;await(await token.connect(treasury).approve(await vault.getAddress(),total)).wait();const block=await provider.getBlock('latest'),deadline=Number(block.timestamp)+1000;await(await vault.connect(treasury).fundDistribution(sid,await token.getAddress(),total,rootHash,ethers.id('manifest-v1'),deadline)).wait();assert.equal(await token.balanceOf(await vault.getAddress()),total);await(await vault.claim(1,0,aAddr,amountA,[leafB])).wait();assert.equal(await token.balanceOf(aAddr),amountA);assert.equal(await vault.isClaimed(1,0),true);await reverts(()=>vault.claim(1,0,aAddr,amountA,[leafB]),'double claim blocked');await reverts(()=>vault.claim(1,1,bAddr,amountB,[ethers.ZeroHash]),'invalid proof blocked');await(await vault.claim(1,1,bAddr,amountB,[leafA])).wait();const d=await vault.distribution(1);assert.equal(d.claimed,total);assert.equal(await token.balanceOf(bAddr),amountB);console.log('RWA Series + Distribution contracts PASS: legal activation evidence, immutable economics, enforced future governance notice, active-series funding, immutable Merkle root, exact funded claims, double-claim/invalid-proof protection.');
