import fs from 'node:fs/promises';
import path from 'node:path';
import process from 'node:process';
import { chromium } from 'playwright';

const baseUrl=process.env.RENKO_BASE_URL||'http://127.0.0.1:4173/rwa/renko/';
const expectedSha=process.env.RENKO_EXPECTED_SHA||'';
const outDir=process.env.RENKO_OUTPUT_DIR||'artifacts/renko-wheel-pan-no-zoom';
await fs.mkdir(outDir,{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1672,height:941}});
const pageErrors=[];page.on('pageerror',e=>pageErrors.push(String(e)));
const url=new URL(baseUrl);url.searchParams.set('gold','1');url.searchParams.set('wheelPanNoZoomProof','1');url.searchParams.set('cb',String(Date.now()));
await page.goto(url.toString(),{waitUntil:'domcontentloaded',timeout:120000});
await page.waitForFunction(()=>document.querySelector('#chartHost canvas')&&window.RWARenkoTV?.state?.symbol==='XAUUSD'&&window.RWARenkoGoldTotalHistory&&window.RWARenkoGoldWheelPanLock?.version==='1.3.0-full-prepend-size-lock'&&window.RWARenkoGoldWheelPanLock?.revision==='2.1.2-microtask-prepaint-scale-lock'&&window.RWARenkoGoldExplicitZoom?.implementation==='1.2.0-deep-zoom-history-demand'&&window.RWARenkoGoldExplicitZoom?.revision==='1.2.2-deep-threshold-demand'&&window.RWARenkoGoldManualViewport?.version==='4.4.0-synchronous-history-scale'&&window.RWARenkoGoldManualViewport?.revision==='4.5.0-range-event-scale'&&document.documentElement.dataset.renkoGoldRecent==='true',{timeout:120000});
let deployedSha=null;if(baseUrl.startsWith('https://')){deployedSha=(await(await fetch(new URL('deployment-sha.txt?wheelProof=1',baseUrl))).text()).trim();if(expectedSha&&deployedSha!==expectedSha)throw new Error(`public SHA mismatch ${deployedSha} != ${expectedSha}`)}
await page.fill('#traditionalBox','10');await page.click('[data-apply-method="traditional"]');await page.waitForFunction(()=>window.RWARenkoTV?.settings?.method==='traditional'&&Math.abs(Number(window.RWARenkoTV?.state?.box)-10)<1e-9,{timeout:60000});
const box=await page.locator('#chartHost').boundingBox();if(!box)throw new Error('chartHost missing');
const getState=()=>page.evaluate(()=>{const ts=window.__RWARenkoChart?.timeScale?.(),o=ts?.options?.()||{},r=ts?.getVisibleLogicalRange?.(),H=window.RWARenkoGoldTotalHistory,T=window.RWARenkoTV,Z=window.RWARenkoGoldExplicitZoom,M=window.RWARenkoGoldManualViewport;return{barSpacing:Number(o.barSpacing),minBarSpacing:Number(o.minBarSpacing),logical:r?{from:Number(r.from),to:Number(r.to)}:null,width:r?Number(r.to)-Number(r.from):null,scrollPosition:Number(ts?.scrollPosition?.()),prepends:Number(H?.stats?.prepends||0),autoTriggers:Number(H?.stats?.autoTriggers||0),autoEdgeBars:Number(H?.autoEdgeBars),suppressedScrollEvents:Number(H?.stats?.suppressedScrollEvents||0),busy:!!H?.busy,oldestSecond:Math.floor(Number(T?.state?.closedBars?.[0]?.openTime||0)/1000),wheelStats:{...window.RWARenkoGoldWheelPanLock?.stats},wheelVersion:window.RWARenkoGoldWheelPanLock?.version,wheelRevision:window.RWARenkoGoldWheelPanLock?.revision,sizeLockSpacing:window.RWARenkoGoldWheelPanLock?.sizeLockSpacing??null,zoomStats:{...Z?.stats},zoomVersion:Z?.version,zoomImplementation:Z?.implementation,zoomRevision:Z?.revision,zoomMaxWidth:Number(Z?.maxWidth||0),zoomDeepHistoryWidth:Number(Z?.deepHistoryWidth||0),zoomHistoryPump:!!Z?.historyPumpActive,manualVersion:M?.version,manualRevision:M?.revision,manualStats:{...M?.stats},zoomActive:document.documentElement.dataset.renkoGoldExplicitZoom,method:T?.settings?.method,box:Number(T?.state?.box),panOnly:document.documentElement.dataset.renkoGoldWheelPanOnly}});
const delta=(a,b)=>Math.abs(Number(a)-Number(b));
const assertScale=(before,after,label)=>{if(!(Number.isFinite(before.barSpacing)&&Number.isFinite(after.barSpacing)))throw new Error(`${label} non-finite spacing`);if(delta(before.barSpacing,after.barSpacing)>1e-9)throw new Error(`${label} visual brick spacing changed ${before.barSpacing} -> ${after.barSpacing}`)};
const assertZoomIn=(before,after,label)=>{if(!(Number.isFinite(before.width)&&Number.isFinite(after.width)&&after.width<before.width-.25))throw new Error(`${label} did not zoom in ${before.width} -> ${after.width}`)};
const assertZoomOut=(before,after,label)=>{if(!(Number.isFinite(before.width)&&Number.isFinite(after.width)&&after.width>before.width+.25))throw new Error(`${label} did not zoom out ${before.width} -> ${after.width}`)};
async function waitStableSpacing(stableMs=900,timeout=12000){let last=null,stableSince=Date.now(),started=Date.now(),samples=[];while(Date.now()-started<timeout){const s=await getState();samples.push(s.barSpacing);if(!Number.isFinite(last)||delta(last,s.barSpacing)>1e-9){last=s.barSpacing;stableSince=Date.now()}if(Date.now()-stableSince>=stableMs&&!s.busy&&!s.zoomHistoryPump)return{s,samples};await page.waitForTimeout(75)}throw new Error(`barSpacing/busy never stable ${JSON.stringify({samples:samples.slice(-30),state:await getState()})}`)}
async function liveStable(){await page.click('#tvLive');await page.waitForTimeout(80);return waitStableSpacing()}
async function resetView(){await page.click('#tvReset');await page.waitForTimeout(260);return getState()}
await page.mouse.move(box.x+box.width*.55,box.y+box.height*.45);
const zoomBase=await resetView();
await page.click('#tvZoomIn');await page.waitForTimeout(220);const zoomButtonIn=await getState();assertZoomIn(zoomBase,zoomButtonIn,'button +');
await page.click('#tvZoomOut');await page.waitForTimeout(220);const zoomButtonOut=await getState();assertZoomOut(zoomButtonIn,zoomButtonOut,'button -');
const verticalBase=await resetView();await page.mouse.move(box.x+box.width*.55,box.y+box.height*.45);await page.mouse.wheel(0,-120);await page.waitForTimeout(260);const verticalIn=await getState();assertZoomIn(verticalBase,verticalIn,'vertical wheel zoom in');await page.mouse.wheel(0,120);await page.waitForTimeout(260);const verticalOut=await getState();assertZoomOut(verticalIn,verticalOut,'vertical wheel zoom out');
const pinchBase=await resetView();await page.mouse.move(box.x+box.width*.55,box.y+box.height*.45);await page.keyboard.down('Control');await page.mouse.wheel(0,-100);await page.keyboard.up('Control');await page.waitForTimeout(260);const pinchIn=await getState();assertZoomIn(pinchBase,pinchIn,'ctrl/pinch zoom in');if(Number(pinchIn.zoomStats?.pinchZooms||0)<1)throw new Error('ctrl/pinch gesture was not handled by explicit zoom');
const farBase=await resetView(),farPrependsBefore=farBase.prepends;
for(let i=0;i<5;i++){await page.click('#tvZoomOut');await page.waitForTimeout(100)}
await page.waitForFunction(({before})=>{const Z=window.RWARenkoGoldExplicitZoom,H=window.RWARenkoGoldTotalHistory,ts=window.__RWARenkoChart?.timeScale?.(),r=ts?.getVisibleLogicalRange?.();return r&&Number(r.to)-Number(r.from)>=300&&Number(H?.stats?.prepends||0)>before&&Number(Z?.stats?.historySuccesses||0)>0&&!H?.busy&&!Z?.historyPumpActive},{before:farPrependsBefore},{timeout:180000});
await page.waitForTimeout(400);const farOut=await getState();if(farOut.width<300)throw new Error(`deep zoom-out too shallow ${farOut.width}`);if(farOut.prepends<=farPrependsBefore)throw new Error('deep zoom-out did not demand-load older history');if(farOut.zoomMaxWidth<1000)throw new Error(`deep zoom max too small ${farOut.zoomMaxWidth}`);if(farOut.zoomDeepHistoryWidth>120)throw new Error(`deep history threshold too high ${farOut.zoomDeepHistoryWidth}`);if(!(farOut.minBarSpacing<=.05+.000001))throw new Error(`zoom-out minimum spacing was not relaxed ${farOut.minBarSpacing}`);
await resetView();
const zoomContract={buttonIn:{before:zoomBase.width,after:zoomButtonIn.width},buttonOut:{before:zoomButtonIn.width,after:zoomButtonOut.width},verticalIn:{before:verticalBase.width,after:verticalIn.width},verticalOut:{before:verticalIn.width,after:verticalOut.width},pinchIn:{before:pinchBase.width,after:pinchIn.width},farOut:{before:farBase.width,after:farOut.width,prependsBefore:farPrependsBefore,prependsAfter:farOut.prepends,historySuccesses:farOut.zoomStats?.historySuccesses,maxWidth:farOut.zoomMaxWidth,deepHistoryWidth:farOut.zoomDeepHistoryWidth,minBarSpacing:farOut.minBarSpacing},zoomStats:farOut.zoomStats};
const initial=await liveStable();await page.mouse.move(box.x+box.width*.55,box.y+box.height*.45);await page.screenshot({path:path.join(outDir,'BEFORE.png'),fullPage:true});
const noWheelA=initial.s;await page.waitForTimeout(1200);const noWheelB=await getState();assertScale(noWheelA,noWheelB,'no-wheel baseline stability');
const candidates=[[-160,80],[-160,-80],[160,80],[160,-80]];let vector=null,bestScroll=0,calibration=[];
for(const [dx,dy] of candidates){const stable=await liveStable();await page.mouse.move(box.x+box.width*.55,box.y+box.height*.45);const a=stable.s;await page.mouse.wheel(dx,dy);await page.waitForTimeout(1100);const b=await getState();assertScale(a,b,`calibration ${dx},${dy}`);const move=Number(b.logical?.from)-Number(a.logical?.from),scrollMove=Number(b.scrollPosition)-Number(a.scrollPosition);calibration.push({dx,dy,move,scrollMove,beforeSpacing:a.barSpacing,afterSpacing:b.barSpacing,beforeWidth:a.width,afterWidth:b.width,beforeFrom:a.logical?.from,afterFrom:b.logical?.from,beforeScroll:a.scrollPosition,afterScroll:b.scrollPosition,prependsBefore:a.prepends,prependsAfter:b.prepends,autoTriggersBefore:a.autoTriggers,autoTriggersAfter:b.autoTriggers,corrections:b.wheelStats.corrections,maxInternalBarSpacingDelta:b.wheelStats.maxBarSpacingDelta,maxPaintBarSpacingDelta:b.wheelStats.maxPaintBarSpacingDelta,zoomWheelBefore:a.zoomStats?.wheelZooms,zoomWheelAfter:b.zoomStats?.wheelZooms});if(Number.isFinite(scrollMove)&&scrollMove<bestScroll){bestScroll=scrollMove;vector=[dx,dy]}}
if(!vector)throw new Error(`mixed/real wheel could not pan older by scroll position: ${JSON.stringify(calibration)}`);
await liveStable();await page.mouse.move(box.x+box.width*.55,box.y+box.height*.45);
const rows=[];const start=(await getState()).prepends;
for(let cycle=1;cycle<=3;cycle++){
  const target=start+cycle,baseline=await getState();let triggered=false,lastProbe=baseline;
  for(let n=0;n<1800;n++){
    const s=await getState();lastProbe=s;if(s.prepends>=target){triggered=true;break}if(s.busy){await page.waitForTimeout(35);continue}
    await page.mouse.wheel(vector[0],vector[1]);
    if(n%12===0){await page.waitForTimeout(55);const mid=await getState();lastProbe=mid;assertScale(baseline,mid,`cycle ${cycle} wheel ${n}`)}else await page.waitForTimeout(18);
  }
  if(!triggered){await page.waitForTimeout(800);lastProbe=await getState();triggered=lastProbe.prepends>=target}
  if(!triggered)throw new Error(`back-scroll failed to prepend cycle ${cycle}: ${JSON.stringify({vector,calibration,baseline,lastProbe,target})}`);
  await page.waitForFunction(n=>!window.RWARenkoGoldTotalHistory.busy&&window.RWARenkoGoldTotalHistory.stats.prepends>=n,target,{timeout:180000});await page.waitForTimeout(1500);
  const after=await getState();assertScale(baseline,after,`cycle ${cycle} settled`);if(after.method!=='traditional'||delta(after.box,10)>1e-9)throw new Error(`Traditional 10 changed during scroll cycle ${cycle}`);if(after.panOnly!=='true'||after.wheelVersion!=='1.3.0-full-prepend-size-lock'||after.wheelRevision!=='2.1.2-microtask-prepaint-scale-lock')throw new Error('wheel pan microtask pre-paint guard not active');if(after.zoomActive!=='true'||after.zoomImplementation!=='1.2.0-deep-zoom-history-demand'||after.zoomRevision!=='1.2.2-deep-threshold-demand')throw new Error('deep explicit zoom guard not active');if(after.manualVersion!=='4.4.0-synchronous-history-scale'||after.manualRevision!=='4.5.0-range-event-scale')throw new Error('history range-event scale guard not active');rows.push({cycle,beforeSpacing:baseline.barSpacing,afterSpacing:after.barSpacing,beforeWidth:baseline.width,afterWidth:after.width,beforeScroll:baseline.scrollPosition,afterScroll:after.scrollPosition,prepends:after.prepends,autoTriggers:after.autoTriggers,corrections:after.wheelStats.corrections,prePaintCorrections:after.wheelStats.prePaintCorrections,maxInternalBarSpacingDelta:after.wheelStats.maxBarSpacingDelta,maxPaintBarSpacingDelta:after.wheelStats.maxPaintBarSpacingDelta,historyRangeScaleRepairs:after.manualStats.historyRangeScaleRepairs,zoomWheelEvents:after.zoomStats?.wheelZooms});
}
await page.screenshot({path:path.join(outDir,'AFTER.png'),fullPage:true});
const final=await getState();if(Number(final.wheelStats?.maxPaintBarSpacingDelta||0)>1e-9)throw new Error(`paint-visible pan spacing drift detected ${final.wheelStats.maxPaintBarSpacingDelta}`);if(pageErrors.length)throw new Error(`page errors ${JSON.stringify(pageErrors)}`);const report={token:'RENKO_GOLD_DEEP_ZOOM_HISTORY_AND_PAN_PASS',sha:deployedSha||expectedSha||null,baseUrl,traditionalBox:10,zoomContract,noWheelBaseline:{before:noWheelA.barSpacing,after:noWheelB.barSpacing,samples:initial.samples},vector,calibration,rows,final};await fs.writeFile(path.join(outDir,'report.json'),JSON.stringify(report,null,2));console.log(report.token,JSON.stringify(report));await browser.close();