import fs from 'node:fs/promises';
import path from 'node:path';
import { chromium } from 'playwright';

const base=process.env.RENKO_BASE_URL||'http://127.0.0.1:4173/rwa/renko/';
const out=process.env.RENKO_TRACE_OUTPUT||'artifacts/first-mixed-trace';
await fs.mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1672,height:941}});
const url=new URL(base);url.searchParams.set('gold','1');url.searchParams.set('traceMixed','1');url.searchParams.set('cb',Date.now());
await page.goto(url.toString(),{waitUntil:'domcontentloaded',timeout:120000});
await page.waitForFunction(()=>document.querySelector('#chartHost canvas')&&window.RWARenkoTV?.state?.symbol==='XAUUSD'&&window.RWARenkoGoldTotalHistory&&window.RWARenkoGoldWheelPanLock?.revision==='2.1.2-microtask-prepaint-scale-lock'&&window.RWARenkoGoldExplicitZoom?.revision==='1.2.2-deep-threshold-demand'&&window.RWARenkoGoldManualViewport?.atomicRevision==='4.6.0-atomic-visual-freeze'&&document.documentElement.dataset.renkoGoldRecent==='true',{timeout:120000});
await page.fill('#traditionalBox','10');await page.click('[data-apply-method="traditional"]');
await page.waitForFunction(()=>window.RWARenkoTV?.settings?.method==='traditional'&&Math.abs(Number(window.RWARenkoTV?.state?.box)-10)<1e-9,{timeout:60000});
const box=await page.locator('#chartHost').boundingBox();if(!box)throw new Error('chartHost missing');
const state=()=>page.evaluate(()=>{const t=window.__RWARenkoChart?.timeScale?.(),o=t?.options?.()||{},r=t?.getVisibleLogicalRange?.(),H=window.RWARenkoGoldTotalHistory,W=window.RWARenkoGoldWheelPanLock,M=window.RWARenkoGoldManualViewport,A=window.RWARenkoGoldViewportAuthority,Z=window.RWARenkoGoldExplicitZoom,T=window.RWARenkoTV;return{now:performance.now(),spacing:Number(o.barSpacing),rightOffset:Number(o.rightOffset),logical:r?{from:Number(r.from),to:Number(r.to),width:Number(r.to)-Number(r.from)}:null,scroll:Number(t?.scrollPosition?.()),busy:!!H?.busy,prepends:Number(H?.stats?.prepends||0),autoTriggers:Number(H?.stats?.autoTriggers||0),oldest:Math.floor(Number(T?.state?.closedBars?.[0]?.openTime||0)/1000),following:!!T?.state?.following,interactionOwner:document.documentElement.dataset.renkoGoldInteractionOwner,pan:{revision:W?.revision,sizeLockSpacing:W?.sizeLockSpacing??null,stats:{...(W?.stats||{})}},manual:{version:M?.version,revision:M?.revision,atomicRevision:M?.atomicRevision,visualFreezeActive:!!M?.visualFreezeActive,locked:!!M?.locked,inHistoryMutation:!!M?.inHistoryMutation,suppressing:!!M?.suppressingRangeChanges,stats:{...(M?.stats||{})}},authority:{hold:A?.hold||null,stats:{...(A?.stats||{})}},zoom:{implementation:Z?.implementation,revision:Z?.revision,stats:{...(Z?.stats||{})}}}});
const waitStable=async(stableMs=900,timeout=10000)=>{let last=null,since=Date.now(),start=Date.now();while(Date.now()-start<timeout){const s=await state();if(last===null||Math.abs(s.spacing-last)>1e-9){last=s.spacing;since=Date.now()}if(Date.now()-since>=stableMs&&!s.busy&&!s.manual.visualFreezeActive)return s;await page.waitForTimeout(75)}throw new Error('never stable')};
await page.mouse.move(box.x+box.width*.55,box.y+box.height*.45);
await page.click('#tvReset');await page.waitForTimeout(220);
await page.click('#tvZoomIn');await page.waitForTimeout(220);await page.click('#tvZoomOut');await page.waitForTimeout(220);
await page.click('#tvReset');await page.waitForTimeout(220);await page.mouse.move(box.x+box.width*.55,box.y+box.height*.45);await page.mouse.wheel(0,-120);await page.waitForTimeout(260);await page.mouse.wheel(0,120);await page.waitForTimeout(260);
await page.click('#tvReset');await page.waitForTimeout(220);await page.mouse.move(box.x+box.width*.55,box.y+box.height*.45);await page.keyboard.down('Control');await page.mouse.wheel(0,-100);await page.keyboard.up('Control');await page.waitForTimeout(260);
await page.click('#tvReset');await page.waitForTimeout(220);await page.click('#tvLive');await page.waitForTimeout(80);await waitStable();await page.waitForTimeout(1200);
await page.mouse.move(box.x+box.width*.55,box.y+box.height*.45);
const samples=[];samples.push({dt:-1,...await state()});const baseline=samples[0].spacing;
const t0=Date.now();await page.mouse.wheel(-160,80);
for(const ms of [0,16,50,100,200,350,550,800,1100,1500,2200,2800]){const left=ms-(Date.now()-t0);if(left>0)await page.waitForTimeout(left);samples.push({dt:Date.now()-t0,...await state()})}
const internalDriftSamples=samples.filter(s=>Math.abs(Number(s.spacing)-Number(baseline))>1e-9);
const visibleDriftSamples=internalDriftSamples.filter(s=>!s.manual.visualFreezeActive);
const final=samples.at(-1);const freezeSamples=samples.filter(s=>s.manual.visualFreezeActive);
const report={token:'RENKO_GOLD_FIRST_MIXED_ATOMIC_VISUAL_PASS',base,baseline,internalDriftSamples:internalDriftSamples.map(x=>({dt:x.dt,spacing:x.spacing,frozen:x.manual.visualFreezeActive})),visibleDriftSamples:visibleDriftSamples.map(x=>({dt:x.dt,spacing:x.spacing})),freezeSamples:freezeSamples.length,samples};
await fs.writeFile(path.join(out,'trace.json'),JSON.stringify(report,null,2));
if(visibleDriftSamples.length)throw new Error(`first mixed-wheel USER-VISIBLE scale drift ${JSON.stringify(visibleDriftSamples.map(x=>({dt:x.dt,spacing:x.spacing})))}`);
if(Number(final?.prepends||0)<1)throw new Error('first mixed-wheel did not load older history');
if(final?.manual?.visualFreezeActive)throw new Error('visual freeze did not release after history settled');
if(Number(final?.manual?.stats?.visualFreezes||0)<1)throw new Error('history transaction did not use atomic visual freeze');
if(internalDriftSamples.length&&!freezeSamples.length)throw new Error('internal scale churn was not covered by visual freeze');
if(Math.abs(Number(final.spacing)-Number(baseline))>1e-9)throw new Error(`final spacing drift ${baseline} -> ${final.spacing}`);
console.log(report.token,JSON.stringify(report));
await browser.close();
