import {chromium} from 'playwright';
const BASE=process.env.RWA_LIVE_BASE||'https://narzulalistiqlal.github.io/rwa/';
const browser=await chromium.launch({headless:true});
const fail=[];const check=(v,m)=>{if(!v)fail.push(m)};
async function test(viewport,label){const context=await browser.newContext({viewport});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e?.message||e)));await page.goto(`${BASE}?storefront-smoke=${Date.now()}`,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(1800);check(await page.locator('[data-rwa-shop]').first().isVisible().catch(()=>false),`${label}: Shop navigation missing`);const shop=page.locator('[data-rwa-shop]').first();if(await shop.isVisible().catch(()=>false)){await shop.click();check(await page.locator('#rwaShopScreen.open').isVisible().catch(()=>false),`${label}: storefront did not open`);check(await page.locator('.rwa-store-card').count().catch(()=>0)>=1,`${label}: store blueprint cards missing`);check((await page.locator('.rwa-live-guard').textContent().catch(()=>''))?.includes('UI blueprints'),`${label}: preview/live guard missing`);check(await page.locator('.rwa-store-card .rwa-store-actions button:disabled').count().catch(()=>0)>=1,`${label}: preview token trade must be disabled`);const search=page.locator('#rwaShopSearch');await search.fill('Retail');check((await search.inputValue().catch(()=>''))==='Retail',`${label}: storefront search lost typed value`);check(await search.evaluate(e=>document.activeElement===e).catch(()=>false),`${label}: storefront search lost focus`);await search.fill('');await page.locator('[data-shop-tab="products"]').click();check(await page.locator('.rwa-product-card').count().catch(()=>0)>=1,`${label}: product grid missing`);check((await page.locator('.rwa-product-card .rwa-product-price b').first().textContent().catch(()=>''))==='Price pending',`${label}: preview product must not show a fabricated price`);check(await page.locator('.rwa-product-card [data-add-cart]:disabled').count().catch(()=>0)>=1,`${label}: preview products must not enter live cart`);await page.locator('#rwaCommandOpen').click();check(await page.locator('#rwaCommandLayer.open').isVisible().catch(()=>false),`${label}: command palette did not open`);await page.keyboard.press('Escape');await page.locator('#rwaShopClose').click()}const overflow=await page.evaluate(()=>({w:innerWidth,sw:document.documentElement.scrollWidth}));check(overflow.sw<=overflow.w+3,`${label}: horizontal overflow ${overflow.sw}>${overflow.w}`);check(errors.length===0,`${label}: uncaught JS error(s): ${errors.join(' | ')}`);await context.close()}
await test({width:1440,height:1000},'desktop');await test({width:390,height:844},'mobile');
{
 const context=await browser.newContext({viewport:{width:390,height:844}}),page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(String(e?.message||e)));await page.goto(`${BASE}trade/?storefront-smoke=${Date.now()}`,{waitUntil:'domcontentloaded',timeout:30000});await page.waitForTimeout(1600);check(await page.locator('.rwa-store-link').isVisible().catch(()=>false),'trade mobile: Physical Stores nav link missing');check(await page.locator('.rwa-trade-commerce-strip').isVisible().catch(()=>false),'trade mobile: RWA commerce strip missing');check(await page.locator('.rwa-trade-mobile-store').isVisible().catch(()=>false),'trade mobile: floating store action missing');const overflow=await page.evaluate(()=>({w:innerWidth,sw:document.documentElement.scrollWidth}));check(overflow.sw<=overflow.w+3,`trade mobile: horizontal overflow ${overflow.sw}>${overflow.w}`);check(errors.length===0,`trade mobile: uncaught JS error(s): ${errors.join(' | ')}`);await context.close()
}
await browser.close();if(fail.length){console.error(JSON.stringify({ok:false,contract:'rwa-storefront-browser-v2',fail},null,2));process.exit(1)}console.log(JSON.stringify({ok:true,contract:'rwa-storefront-browser-v2',surfaces:['desktop storefront','mobile storefront','honest preview states','search focus','trade mobile commerce link','command palette']},null,2));
