import {DatabaseSync} from 'node:sqlite';
import {readFileSync,mkdirSync} from 'node:fs';
import {dirname,resolve} from 'node:path';
import {fileURLToPath} from 'node:url';
import {createHash,randomUUID} from 'node:crypto';

const HERE=dirname(fileURLToPath(import.meta.url));
const now=()=>Date.now();
export const sha256=v=>createHash('sha256').update(String(v)).digest('hex');
export const stableJson=v=>JSON.stringify(v,Object.keys(v||{}).sort());
export const id=(prefix='id')=>`${prefix}_${randomUUID().replaceAll('-','')}`;

export class CommerceDB{
  constructor(path=process.env.RWA_COMMERCE_DB||resolve(HERE,'data/commerce.sqlite')){
    mkdirSync(dirname(path),{recursive:true});
    this.path=path;
    this.db=new DatabaseSync(path);
    this.db.exec(readFileSync(resolve(HERE,'schema.sql'),'utf8'));
    this.db.prepare("INSERT INTO meta(key,value) VALUES('schema','1') ON CONFLICT(key) DO UPDATE SET value=excluded.value").run();
  }
  close(){this.db.close()}
  transaction(fn){this.db.exec('BEGIN IMMEDIATE');try{const out=fn();this.db.exec('COMMIT');return out}catch(e){try{this.db.exec('ROLLBACK')}catch{}throw e}}
  cleanup(){const t=now();this.db.prepare('DELETE FROM challenges WHERE expires_at < ?').run(t);this.db.prepare('DELETE FROM sessions WHERE expires_at < ? OR revoked_at IS NOT NULL').run(t);this.db.prepare('DELETE FROM quotes WHERE expires_at < ? AND consumed_at IS NULL').run(t);}
  challengePut({wallet,nonce,message,expiresAt}){this.db.prepare('INSERT INTO challenges(wallet,nonce,message,expires_at,created_at) VALUES(?,?,?,?,?) ON CONFLICT(wallet) DO UPDATE SET nonce=excluded.nonce,message=excluded.message,expires_at=excluded.expires_at,created_at=excluded.created_at').run(wallet,nonce,message,expiresAt,now())}
  challengeGet(wallet){return this.db.prepare('SELECT * FROM challenges WHERE wallet=?').get(wallet)}
  challengeDelete(wallet){this.db.prepare('DELETE FROM challenges WHERE wallet=?').run(wallet)}
  sessionPut({tokenHash,wallet,expiresAt}){this.db.prepare('INSERT INTO sessions(token_hash,wallet,expires_at,created_at) VALUES(?,?,?,?)').run(tokenHash,wallet,expiresAt,now())}
  sessionGet(tokenHash){return this.db.prepare('SELECT * FROM sessions WHERE token_hash=? AND revoked_at IS NULL AND expires_at>?').get(tokenHash,now())}
  sessionRevoke(tokenHash){this.db.prepare('UPDATE sessions SET revoked_at=? WHERE token_hash=?').run(now(),tokenHash)}
  stores(){return this.db.prepare("SELECT * FROM stores WHERE status='VERIFIED' AND store_verified=1 AND asset_verified=1 ORDER BY name").all()}
  store(token){return this.db.prepare('SELECT * FROM stores WHERE token=?').get(String(token).toUpperCase())}
  upsertStore(s){this.db.prepare(`INSERT INTO stores(token,name,category,full_address,lat,lng,contact,opening_hours,storefront_photo_url,business_registration_url,merchant_identity_url,catalog_url,asset_verified,store_verified,trade_enabled,status,registry_hash,updated_at)
    VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(token) DO UPDATE SET name=excluded.name,category=excluded.category,full_address=excluded.full_address,lat=excluded.lat,lng=excluded.lng,contact=excluded.contact,opening_hours=excluded.opening_hours,storefront_photo_url=excluded.storefront_photo_url,business_registration_url=excluded.business_registration_url,merchant_identity_url=excluded.merchant_identity_url,catalog_url=excluded.catalog_url,asset_verified=excluded.asset_verified,store_verified=excluded.store_verified,trade_enabled=excluded.trade_enabled,status=excluded.status,registry_hash=excluded.registry_hash,updated_at=excluded.updated_at`).run(s.token,s.name,s.category,s.fullAddress,s.lat,s.lng,s.contact||'',s.openingHours||'',s.photo,s.business,s.merchant,s.catalog||'',s.assetVerified?1:0,s.storeVerified?1:0,s.tradeEnabled?1:0,s.status,s.registryHash,now())}
  products(token=null){return token?this.db.prepare('SELECT p.*,i.on_hand,i.reserved,(i.on_hand-i.reserved) available FROM products p JOIN inventory i ON i.product_id=p.id WHERE p.store_token=? AND p.active=1 ORDER BY p.name').all(String(token).toUpperCase()):this.db.prepare("SELECT p.*,i.on_hand,i.reserved,(i.on_hand-i.reserved) available FROM products p JOIN inventory i ON i.product_id=p.id JOIN stores s ON s.token=p.store_token WHERE p.active=1 AND s.status='VERIFIED' AND s.store_verified=1 AND s.asset_verified=1 ORDER BY p.name").all()}
  product(productId){return this.db.prepare('SELECT p.*,i.on_hand,i.reserved,(i.on_hand-i.reserved) available,s.status store_status,s.store_verified,s.asset_verified FROM products p JOIN inventory i ON i.product_id=p.id JOIN stores s ON s.token=p.store_token WHERE p.id=?').get(productId)}
  upsertProduct(p){this.transaction(()=>{this.db.prepare(`INSERT INTO products(id,store_token,sku,name,description,price_cents,currency,active,pickup,shipping,image_url,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET store_token=excluded.store_token,sku=excluded.sku,name=excluded.name,description=excluded.description,price_cents=excluded.price_cents,currency=excluded.currency,active=excluded.active,pickup=excluded.pickup,shipping=excluded.shipping,pickup=excluded.pickup,image_url=excluded.image_url,updated_at=excluded.updated_at`).run(p.id,p.storeToken,p.sku,p.name,p.description||'',p.priceCents,p.currency||'USD',p.active===false?0:1,p.pickup===false?0:1,p.shipping===false?0:1,p.imageUrl||'',now());this.db.prepare('INSERT INTO inventory(product_id,on_hand,reserved,updated_at) VALUES(?,?,0,?) ON CONFLICT(product_id) DO NOTHING').run(p.id,Math.max(0,Number(p.onHand||0)),now())})}
  inventorySet(productId,onHand){const n=Math.max(0,Math.trunc(Number(onHand)));const row=this.db.prepare('SELECT reserved FROM inventory WHERE product_id=?').get(productId);if(!row)throw Error('product_not_found');if(n<Number(row.reserved))throw Error('inventory_below_reserved');this.db.prepare('UPDATE inventory SET on_hand=?,updated_at=? WHERE product_id=?').run(n,now(),productId);return this.product(productId)}
  quotePut(q){this.db.prepare('INSERT INTO quotes(id,wallet,currency,subtotal_cents,tax_cents,shipping_cents,total_cents,fulfillment,destination_json,items_json,quote_hash,expires_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').run(q.id,q.wallet||'',q.currency,q.subtotalCents,q.taxCents,q.shippingCents,q.totalCents,q.fulfillment,JSON.stringify(q.destination||{}),JSON.stringify(q.items),q.quoteHash,q.expiresAt,now());return q}
  quote(id){const q=this.db.prepare('SELECT * FROM quotes WHERE id=?').get(id);if(!q)return null;return{...q,destination:JSON.parse(q.destination_json||'{}'),items:JSON.parse(q.items_json||'[]')}}
  order(id){const o=this.db.prepare('SELECT * FROM orders WHERE id=?').get(id);if(!o)return null;const items=this.db.prepare('SELECT * FROM order_items WHERE order_id=? ORDER BY name').all(id);return{...o,contact:JSON.parse(o.contact_json||'{}'),destination:JSON.parse(o.destination_json||'{}'),items}}
  ordersByWallet(wallet){return this.db.prepare('SELECT id,status,total_cents,currency,fulfillment,payment_mode,created_at,updated_at FROM orders WHERE wallet=? ORDER BY created_at DESC LIMIT 100').all(wallet)}
  createOrder({quote,wallet,contact,notes,paymentMode,paymentReference}){return this.transaction(()=>{const fresh=this.db.prepare('SELECT consumed_at,expires_at FROM quotes WHERE id=?').get(quote.id);if(!fresh||fresh.consumed_at)throw Error('quote_consumed');if(Number(fresh.expires_at)<=now())throw Error('quote_expired');for(const item of quote.items){const inv=this.db.prepare('SELECT on_hand,reserved FROM inventory WHERE product_id=?').get(item.productId);if(!inv||Number(inv.on_hand)-Number(inv.reserved)<item.qty)throw Error(`insufficient_stock:${item.productId}`)}for(const item of quote.items)this.db.prepare('UPDATE inventory SET reserved=reserved+?,updated_at=? WHERE product_id=?').run(item.qty,now(),item.productId);const orderId=id('ord'),t=now();this.db.prepare('INSERT INTO orders(id,wallet,quote_id,currency,subtotal_cents,tax_cents,shipping_cents,total_cents,fulfillment,contact_json,destination_json,notes,status,payment_mode,payment_reference,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(orderId,wallet,quote.id,quote.currency,quote.subtotal_cents,quote.tax_cents,quote.shipping_cents,quote.total_cents,quote.fulfillment,JSON.stringify(contact||{}),JSON.stringify(quote.destination||{}),String(notes||''),'AWAITING_PAYMENT',paymentMode,paymentReference||'',t,t);for(const item of quote.items)this.db.prepare('INSERT INTO order_items(order_id,product_id,store_token,sku,name,unit_price_cents,qty) VALUES(?,?,?,?,?,?,?)').run(orderId,item.productId,item.storeToken,item.sku,item.name,item.unitPriceCents,item.qty);this.db.prepare('UPDATE quotes SET consumed_at=? WHERE id=?').run(t,quote.id);return this.order(orderId)})}
  transitionOrder(orderId,next,{actor='admin',paymentReference=''}={}){const allowed={AWAITING_PAYMENT:['PAID','CANCELLED'],PAID:['FULFILLING','CANCELLED'],FULFILLING:['READY_FOR_PICKUP','SHIPPED','CANCELLED'],READY_FOR_PICKUP:['COMPLETED','CANCELLED'],SHIPPED:['COMPLETED','CANCELLED'],COMPLETED:[],CANCELLED:[]};return this.transaction(()=>{const o=this.order(orderId);if(!o)throw Error('order_not_found');if(!(allowed[o.status]||[]).includes(next))throw Error(`invalid_transition:${o.status}->${next}`);const t=now();if(next==='CANCELLED'){for(const item of o.items)this.db.prepare('UPDATE inventory SET reserved=MAX(0,reserved-?),updated_at=? WHERE product_id=?').run(item.qty,t,item.product_id)}if(next==='COMPLETED'){for(const item of o.items)this.db.prepare('UPDATE inventory SET on_hand=MAX(0,on_hand-?),reserved=MAX(0,reserved-?),updated_at=? WHERE product_id=?').run(item.qty,item.qty,t,item.product_id)}this.db.prepare('UPDATE orders SET status=?,payment_reference=CASE WHEN ?<>\'\' THEN ? ELSE payment_reference END,paid_at=CASE WHEN ?=\'PAID\' THEN ? ELSE paid_at END,completed_at=CASE WHEN ?=\'COMPLETED\' THEN ? ELSE completed_at END,cancelled_at=CASE WHEN ?=\'CANCELLED\' THEN ? ELSE cancelled_at END,updated_at=? WHERE id=?').run(next,paymentReference,paymentReference,next,t,next,t,next,t,t,orderId);this.audit(actor,'order.transition','order',orderId,{from:o.status,to:next});return this.order(orderId)})}
  idemGet(scope,key){return this.db.prepare('SELECT * FROM idempotency WHERE scope=? AND key=?').get(scope,key)}
  idemPut(scope,key,requestHash,statusCode,response){this.db.prepare('INSERT OR IGNORE INTO idempotency(scope,key,request_hash,response_json,status_code,created_at) VALUES(?,?,?,?,?,?)').run(scope,key,requestHash,JSON.stringify(response),statusCode,now())}
  audit(actor,action,entityType,entityId,detail={}){this.db.prepare('INSERT INTO audit_log(ts,actor,action,entity_type,entity_id,detail_json) VALUES(?,?,?,?,?,?)').run(now(),actor,action,entityType,entityId,JSON.stringify(detail))}
  auditRecent(limit=100){return this.db.prepare('SELECT * FROM audit_log ORDER BY ts DESC LIMIT ?').all(Math.max(1,Math.min(500,Number(limit)||100)))}
}
