import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {DatabaseSync} from 'node:sqlite';
import {BusinessStore} from '../store.mjs';
import {CommerceReader} from '../commerce-reader.mjs';
import {reconcileBusiness,validateBusiness,distributionPreview} from '../validation.mjs';

function commerce(path){const db=new DatabaseSync(path);db.exec(`CREATE TABLE orders(id TEXT PRIMARY KEY,wallet TEXT,currency TEXT,total_cents INTEGER,status TEXT,payment_reference TEXT,paid_at INTEGER,completed_at INTEGER,updated_at INTEGER);CREATE TABLE order_items(order_id TEXT,store_token TEXT);CREATE TABLE refunds(order_id TEXT,amount_cents INTEGER,status TEXT);`);return db}
function setup(){const dir=mkdtempSync(join(tmpdir(),'rwa-business-')),businessPath=join(dir,'business.sqlite'),commercePath=join(dir,'commerce.sqlite'),store=new BusinessStore(businessPath),c=commerce(commercePath),reader=new CommerceReader(commercePath);store.upsertBusiness({id:'BUS-HOTEL-001',seriesId:'HOTEL-001',name:'Pilot Hotel',category:'HOTEL',status:'ACTIVE',kybVerified:true,evidenceHash:'evidence-hash'});store.bindWallet('BUS-HOTEL-001','0x1111111111111111111111111111111111111111',{identityVerified:true});store.bindStore('BUS-HOTEL-001','HOTEL001');return{dir,store,c,reader}}
function close(x){x.reader.close();x.c.close();x.store.close();rmSync(x.dir,{recursive:true,force:true})}

test('paid commerce order reconciles and transaction-validates business',()=>{const x=setup();try{const t=Date.now();x.c.prepare('INSERT INTO orders VALUES(?,?,?,?,?,?,?,?,?)').run('ord1','0x2222222222222222222222222222222222222222','IDR',100000,'PAID','midtrans-tx-1',t,null,t);x.c.prepare('INSERT INTO order_items VALUES(?,?)').run('ord1','HOTEL001');const rec=reconcileBusiness(x.store,x.reader,'BUS-HOTEL-001');assert.equal(rec.status,'PASS');assert.equal(rec.expected_net_cents,100000);const v=validateBusiness(x.store,'BUS-HOTEL-001');assert.equal(v.state,'TRANSACTION_VALIDATED');assert.equal(v.net_settled_cents,100000)}finally{close(x)}});

test('successful refund reduces eligible revenue and distribution conserves minor units',()=>{const x=setup();try{const t=Date.now();x.c.prepare('INSERT INTO orders VALUES(?,?,?,?,?,?,?,?,?)').run('ord2','0x3333333333333333333333333333333333333333','IDR',100000,'COMPLETED','midtrans-tx-2',t,t,t);x.c.prepare('INSERT INTO order_items VALUES(?,?)').run('ord2','HOTEL001');x.c.prepare('INSERT INTO refunds VALUES(?,?,?)').run('ord2',25000,'SUCCEEDED');reconcileBusiness(x.store,x.reader,'BUS-HOTEL-001');const v=validateBusiness(x.store,'BUS-HOTEL-001');assert.equal(v.state,'TRANSACTION_VALIDATED');assert.equal(v.net_settled_cents,75000);const out=distributionPreview(x.store,'BUS-HOTEL-001',{investorAllocationBps:4000,reserveBps:1000,holders:[{wallet:'0xa',units:2},{wallet:'0xb',units:1}]});assert.equal(out.manifest.eligible_revenue_cents,75000);assert.equal(out.manifest.reserve_cents,7500);assert.equal(out.manifest.distributable_cents,27000);assert.equal(out.entitlements.reduce((n,e)=>n+e.amount_cents,0),27000);assert.equal(out.conservation,true)}finally{close(x)}});

test('wallet connection without identity and settlement cannot be transaction validated',()=>{const dir=mkdtempSync(join(tmpdir(),'rwa-business-')),store=new BusinessStore(join(dir,'business.sqlite'));try{store.upsertBusiness({id:'BUS-PROP-001',seriesId:'PROP-001',name:'Property',category:'PROPERTY',status:'ACTIVE',kybVerified:false});store.bindWallet('BUS-PROP-001','0x4444444444444444444444444444444444444444',{identityVerified:false});const v=validateBusiness(store,'BUS-PROP-001');assert.equal(v.state,'CONNECTED');assert.throws(()=>distributionPreview(store,'BUS-PROP-001',{investorAllocationBps:1000,holders:[{wallet:'0xa',units:1}]}),/business_not_transaction_validated/)}finally{store.close();rmSync(dir,{recursive:true,force:true})}});

test('stale evidence downgrades validation',()=>{const x=setup();try{x.store.setPolicy('BUS-HOTEL-001',{maxSettlementAgeMs:1000});const old=Date.now()-5000;x.c.prepare('INSERT INTO orders VALUES(?,?,?,?,?,?,?,?,?)').run('ord3','0x5555555555555555555555555555555555555555','IDR',50000,'PAID','midtrans-tx-3',old,null,old);x.c.prepare('INSERT INTO order_items VALUES(?,?)').run('ord3','HOTEL001');reconcileBusiness(x.store,x.reader,'BUS-HOTEL-001');const v=validateBusiness(x.store,'BUS-HOTEL-001');assert.equal(v.state,'VALIDATION_STALE')}finally{close(x)}});

test('approved POS API transaction requires settlement evidence plus reconciliation',()=>{const x=setup();try{const tx=x.store.ingestExternal({businessId:'BUS-HOTEL-001',storeToken:'HOTEL001',terminalId:'POS-1',productServiceId:'ROOM-DELUXE',amountCents:125000,currency:'IDR',state:'PAID',paymentReference:'bank-pay-1',externalRef:'pos-order-1'});x.store.settleExternal(tx.id,{settlementReference:'bank-settle-1',evidenceUrl:'https://evidence.example/settlement/1'});let v=validateBusiness(x.store,'BUS-HOTEL-001');assert.equal(v.state,'VALIDATION_SUSPENDED');const sum=x.store.ledgerSummary('BUS-HOTEL-001');x.store.reconciliationPut({businessId:'BUS-HOTEL-001',expectedNetCents:Number(sum.net_cents),ledgerNetCents:Number(sum.net_cents),differenceCents:0,reconciliationBps:10000,qualifyingCount:Number(sum.settled_count),refundCents:Number(sum.refund_cents),status:'PASS',detail:{source:'EXTERNAL_PROVIDER_EVIDENCE',provider_reference:'bank-settle-1',evidence_url:'https://evidence.example/settlement/1'}});v=validateBusiness(x.store,'BUS-HOTEL-001');assert.equal(v.state,'TRANSACTION_VALIDATED');assert.equal(v.net_settled_cents,125000)}finally{close(x)}});
