"use client";
import * as React from "react";
import { useRouter } from "next/navigation";
import { AppShell } from "@/components/app";
import { Button } from "@/components/ui";
import { businesses } from "./data";
import { BusinessCard, SearchBox, SectionHeader } from "./shared";
import "./discovery.css";

export function BusinessDirectory(){
 const router=useRouter(); const [category,setCategory]=React.useState("All Categories"); const [country,setCountry]=React.useState("All Countries"); const [verified,setVerified]=React.useState("All Businesses"); const [sort,setSort]=React.useState("Trending"); const [grid,setGrid]=React.useState(true); const [page,setPage]=React.useState(1);
 const categories=["All Categories","Food & Beverage","Real Estate","Shipping & Logistics","Finance","Consumer Goods","Hospitality","Energy & Utilities","Agriculture","Technology","Other"];
 const countries=["All Countries","Indonesia","Singapore","United States","UAE","Malaysia","More Countries"];
 const filtered=businesses.filter(b=>(category==="All Categories"||b.category===category)&&(country==="All Countries"||b.country===country)&&(verified!=="Verified Only"||b.verified));
 function reset(){setCategory("All Categories");setCountry("All Countries");setVerified("All Businesses");setSort("Trending");setPage(1)}
 return <AppShell><main className="directory-layout page-pad"><aside className="filter-sidebar"><div className="filter-title"><b>FILTER BUSINESSES</b><button onClick={reset}>Clear All</button></div><SearchBox placeholder="Search filter options" onSubmit={q=>router.push(`/search?q=${encodeURIComponent(q)}`)}/><h3>CATEGORIES <button onClick={()=>setCategory("All Categories")}>View all</button></h3>{categories.map((x,i)=><button className="side-filter" key={x} data-active={category===x?"true":undefined} onClick={()=>setCategory(x)}><span>{x}</span><em>{142-i*11}</em></button>)}<h3>COUNTRY <button onClick={()=>setCountry("All Countries")}>View all</button></h3>{countries.map((x,i)=><button className="side-filter" key={x} data-active={country===x?"true":undefined} onClick={()=>setCountry(x)}><span>{x}</span><em>{36-i*5}</em></button>)}<h3>VERIFIED STATUS</h3>{["All Businesses","Verified Only","Not Verified"].map((x,i)=><button className="side-filter" key={x} data-active={verified===x?"true":undefined} onClick={()=>setVerified(x)}><span>{x}</span><em>{[142,96,46][i]}</em></button>)}</aside>
 <section className="directory-main"><div className="directory-title"><h1>Businesses</h1><SearchBox placeholder="Search businesses, sectors, or countries" onSubmit={q=>router.push(`/search?q=${encodeURIComponent(q)}`)}/></div><div className="directory-controls"><select aria-label="Country filter" value={country} onChange={e=>setCountry(e.target.value)}>{countries.slice(0,6).map(x=><option key={x}>{x}</option>)}</select><select aria-label="Category filter" value={category} onChange={e=>setCategory(e.target.value)}>{categories.map(x=><option key={x}>{x}</option>)}</select><select aria-label="Verified filter" value={verified} onChange={e=>setVerified(e.target.value)}><option>All Businesses</option><option>Verified Only</option><option>Not Verified</option></select><select aria-label="Sort businesses" value={sort} onChange={e=>setSort(e.target.value)}><option>Trending</option><option>Market Cap</option><option>Followers</option><option>Newest</option></select><div className="view-toggle"><button aria-pressed={grid} onClick={()=>setGrid(true)}>▦</button><button aria-pressed={!grid} onClick={()=>setGrid(false)}>☷</button></div></div><p className="result-count">{filtered.length || businesses.length} businesses found</p><div className={grid?"business-grid":"business-grid list-view"}>{(filtered.length?filtered:businesses).map(b=><BusinessCard business={b} key={b.slug}/>)}</div><div className="pagination"><button disabled={page===1} onClick={()=>setPage(p=>Math.max(1,p-1))}>‹</button>{[1,2,3,4,5].map(n=><button key={n} data-active={page===n?"true":undefined} onClick={()=>setPage(n)}>{n}</button>)}<button onClick={()=>setPage(p=>p+1)}>›</button></div></section>
 <aside className="directory-side"><section className="panel"><SectionHeader title="TRENDING BUSINESSES" href="/businesses"/><div className="rank-list">{businesses.slice(0,5).map((b,i)=><button key={b.slug} onClick={()=>router.push(`/businesses/${b.slug}`)}><span>{i+1}</span><b>{b.name}</b><small>{b.followers} Followers</small><em>{b.change}</em></button>)}</div></section><section className="panel donut-panel"><SectionHeader title="CATEGORY BREAKDOWN" href="/businesses"/><div className="donut">142<small>Total</small></div><p>Real Estate 19.7% · Food & Beverage 16.2% · Finance 8.5%</p></section><section className="panel snapshot-grid"><h2>BUSINESS SNAPSHOT</h2>{[["142","Total Businesses"],["96","Verified Businesses"],["$696.6M","Total Market Cap"],["325K","Total Followers"],["24","Countries"],["12","Categories"]].map(([n,l])=><button key={l} onClick={()=>router.push(`/search?q=${encodeURIComponent(l)}`)}><b>{n}</b><span>{l}</span></button>)}</section></aside></main></AppShell>
}
