"use client";
import * as React from "react";
import Link from "next/link";
import { AppShell } from "@/components/app";
import { Badge, Button } from "@/components/ui";
import { JoinRewardsModal, ShareModal } from "@/components/overlays";
import { businesses, assets, people } from "./data";
import { FollowButton, SearchBox, SectionHeader } from "./shared";
import { useRouter } from "next/navigation";
import "./discovery.css";

const watch = [
 ["KOPI","Kopi Nusantara","$2.48","+8.72%"], ["SEAB","Seablueprint Estate","$66,842.35","+1.82%"], ["MBAY","Marina Bay Residences","$1,250.00","+2.10%"], ["BLUE","Blue Ocean Shipping","$950.00","+1.21%"], ["PHUKET","Phuket Seaview Villas","$1,780.00","-0.35%"],
] as const;

export function HomeFeed(){
 const router=useRouter(); const [feed,setFeed]=React.useState("For You"); const [post,setPost]=React.useState(""); const [shareOpen,setShareOpen]=React.useState(false); const [rewardsOpen,setRewardsOpen]=React.useState(false); const [liked,setLiked]=React.useState<Record<string,boolean>>({});
 return <AppShell><main className="home-layout">
  <aside className="home-left">
   <section className="panel profile-panel"><div className="home-profile"><span className="large-avatar">AM</span><div><b>Alex Morgan ✓</b><small>Level 3 · Researcher</small></div></div><div className="level-bar"><i/></div><small>3,245 XP to Level 4</small><div className="profile-stats"><span><b>2.48K</b>Followers</span><span><b>312</b>Following</span><span><b>92.6</b>Reputation</span></div></section>
   <SearchBox placeholder="Search businesses, tokens, posts..." onSubmit={q=>router.push(`/search?q=${encodeURIComponent(q)}`)}/>
   <section className="panel"><SectionHeader title="Watchlist" href="/watchlist"/><div className="compact-list">{watch.map(([s,n,p,c])=><Link href={`/search?q=${s}`} key={s}><b>{s}</b><span>{n}</span><strong>{p}</strong><em className={c.startsWith("+")?"positive":"negative"}>{c}</em></Link>)}</div></section>
   <section className="panel"><SectionHeader title="Following" href="/community"/><div className="following-summary"><button onClick={()=>router.push("/businesses")}><b>128</b>Businesses</button><button onClick={()=>router.push("/community")}><b>46</b>Investors</button><button onClick={()=>router.push("/community")}><b>34</b>Analysts</button></div></section>
   <section className="panel"><h2>Quick Filters</h2><div className="chip-grid">{["All Feed","Business Updates","Trader Activity","Theses","Rewards","Market News"].map(x=><button key={x} data-active={feed===x?"true":undefined} onClick={()=>setFeed(x)}>{x}</button>)}</div></section>
   <section className="panel"><SectionHeader title="Trending Tags"/><div className="tag-cloud">{["#Coffee","#RealEstate","#Hospitality","#Shipping","#RWA","#Indonesia","#DeFi","#Sustainability"].map(t=><button key={t} onClick={()=>router.push(`/search?q=${encodeURIComponent(t)}`)}>{t}</button>)}</div></section>
  </aside>
  <section className="feed-column">
   <section className="panel composer"><div className="composer-row"><span className="person-avatar">AM</span><input value={post} onChange={e=>setPost(e.target.value)} placeholder="What's on your mind? Share your thesis, update, or market insight..."/></div><div className="composer-actions"><div><button onClick={()=>setPost(v=>`${v} [Photo]`)}>▧ Photo</button><button onClick={()=>setPost(v=>`${v} [Poll]`)}>▥ Poll</button><button onClick={()=>setPost(v=>`${v} [Chart]`)}>⌁ Chart</button><button onClick={()=>setPost(v=>`${v} $KOPI`)}>◉ Token</button></div><Button size="sm" disabled={!post.trim()} onClick={()=>{setPost("");}}>Post</Button></div></section>
   <div className="feed-tabs">{["For You","Following","Top","Latest"].map(x=><button key={x} data-active={feed===x?"true":undefined} onClick={()=>setFeed(x)}>{x}</button>)}</div>
   <article className="panel feed-post"><div className="post-head"><span className="entity-logo">KO</span><div><Badge tone="primary">BUSINESS UPDATE</Badge> <b>Kopi Nusantara ✓</b><small> · 2h ago</small></div></div><div className="post-media-grid"><div><h3>Kopi Nusantara opened a new Bali location! 🌴☕</h3><p>We're excited to announce our newest café in Canggu, Bali. Thank you to our amazing community for your support!</p></div><div className="post-image coffee-image"/></div><div className="post-actions"><button onClick={()=>setLiked(v=>({...v,kopi:!v.kopi}))}>{liked.kopi?"♥":"♡"} 128</button><button onClick={()=>router.push("/community/thesis/kopi-bali-update")}>◯ 24</button><button onClick={()=>setShareOpen(true)}>↗ Share</button><Link href="/businesses/kopi-nusantara">View Business</Link></div></article>
   <article className="panel feed-post"><div className="post-head"><span className="person-avatar">AM</span><b>@Alex</b><small> · 3h ago</small></div><div className="trade-post"><p><Link href="/community/users/alex-morgan">@Alex</Link> bought 1,000 <Link href="/search?q=KOPI">$KOPI</Link> at $2.42</p><Link className="mini-token-card" href="/businesses/kopi-nusantara/token"><b>KOPI</b><span>$2.48</span><em>+8.72%</em></Link></div><div className="post-actions"><button onClick={()=>setLiked(v=>({...v,buy:!v.buy}))}>{liked.buy?"♥":"♡"} 45</button><button onClick={()=>router.push("/community/thesis/alex-kopi-buy")}>◯ 12</button><button onClick={()=>setShareOpen(true)}>↗ Share</button><Link href="/businesses/kopi-nusantara/token">View Token</Link></div></article>
   <article className="panel feed-post"><div className="post-head"><span className="person-avatar">CQ</span><div><Badge tone="purple">THESIS</Badge> <b>CoffeeQueen ✓</b><small> · 5h ago</small></div></div><div className="post-media-grid"><div><h3>Why $KOPI is Brewing Long-Term Value ☕</h3><p>Kopi Nusantara has built a vertically integrated coffee ecosystem with improving margins, strong brand loyalty, and international expansion.</p><Link className="text-link" href="/community/thesis/kopi-long-term-value">Read Thesis →</Link></div><div className="chart-card"><b>KOPI</b><strong>$2.48</strong><em>+8.72%</em><svg viewBox="0 0 260 70" aria-label="KOPI miniature trend"><polyline fill="none" stroke="currentColor" points="0,60 20,48 40,52 60,39 80,43 100,27 120,34 140,20 160,29 180,15 200,23 220,8 240,17 260,3"/></svg><Button size="sm" onClick={()=>router.push("/trade/kopi")}>Buy Token</Button></div></div><div className="post-actions"><button onClick={()=>setLiked(v=>({...v,thesis:!v.thesis}))}>{liked.thesis?"♥":"♡"} 87</button><button onClick={()=>router.push("/community/thesis/kopi-long-term-value")}>◯ 36</button><button onClick={()=>setShareOpen(true)}>↗ Share</button></div></article>
   <article className="panel feed-post rewards-post"><Badge tone="warning">REWARDS HIGHLIGHT</Badge><div><h3>New milestone unlocked! 🎉</h3><p>Top 500 holders will share 50,000 KOPI in weekly rewards.</p></div><Button variant="secondary" onClick={()=>setRewardsOpen(true)}>Join Rewards</Button></article>
   <article className="panel feed-post news-post"><Badge tone="primary">MARKET NEWS</Badge><div><h3>Real-World Asset Market Cap Hits $12.8B, Up 18% This Week</h3><p>Tokenized real estate and commodities lead growth as institutional adoption accelerates.</p></div><Link href="/intelligence">Read More →</Link></article>
  </section>
  <aside className="home-right">
   <section className="panel"><SectionHeader title="Trending Businesses" href="/businesses"/><div className="rank-list">{businesses.slice(0,5).map((b,i)=><Link href={`/businesses/${b.slug}`} key={b.slug}><span>{i+1}</span><b>{b.name}</b><small>{b.marketCap} MC</small><em>{b.change}</em></Link>)}</div></section>
   <section className="panel"><SectionHeader title="Trending RWAs" href="/rwa"/><div className="rank-list">{assets.slice(0,5).map((a,i)=><Link href={`/rwa/${a.slug}`} key={a.slug}><span>{i+1}</span><b>{a.symbol}</b><small>{a.name}</small><em>{a.yield}</em></Link>)}</div></section>
   <section className="panel"><SectionHeader title="People to Follow" href="/community"/>{people.map(p=><div className="mini-person" key={p.slug}><Link href={`/community/users/${p.slug}`}><span className="person-avatar">{p.name.split(" ").map(x=>x[0]).join("")}</span><span><b>{p.name}</b><small>{p.role}</small></span></Link><FollowButton/></div>)}</section>
   <section className="panel market-snapshot"><h2>Market Snapshot</h2><div className="snapshot-kpis"><span>Total Market Cap<b>$12.82B</b></span><span>24H Volume<b>$1.42B <em>+6.71%</em></b></span></div><div className="big-chart"><svg viewBox="0 0 300 110"><polyline fill="none" stroke="currentColor" points="0,100 25,85 45,90 70,72 95,77 115,55 140,61 160,44 185,49 210,27 235,35 260,15 280,20 300,5"/></svg></div><Button variant="secondary" onClick={()=>router.push("/markets")}>Open Markets</Button></section>
   <section className="panel pro-card"><h2>◇ Upgrade to PRO</h2><p>Unlock advanced analytics, real-time alerts, and exclusive research.</p><Button onClick={()=>router.push("/pro")}>Upgrade Now →</Button></section>
  </aside>
 </main><ShareModal open={shareOpen} onOpenChange={setShareOpen} url="https://rwa.ms/home" onShare={()=>setShareOpen(false)}/><JoinRewardsModal open={rewardsOpen} onOpenChange={setRewardsOpen} onJoin={()=>router.push("/rewards")}/></AppShell>
}
